### ISSUE TITLE
Convert "Surge manual.odt" to markdown and either bake it into a file while publishing, or ..?

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#100]
@jsakkine hi, @kurasu just posted `Surge manual.odt` a couple of minutes ago, and I'm wondering what the best method for distributing this would be. I'm edging towards markdown, but since you're a bit more knowledgeable about opensource projects, I'd value your opinion.

Is there some way of using a markdown file to bake it into a PDF.. or maybe using a markdown file to deploy the documentation online?

**Comment by esaruoho** [comment]
i guess the first step is to load the manual (PDF) and the original file (ODT) onto a splitscreen and see if they are even the same. here's the results:
![surge_manual_odt_and_surge_pdf__page_2_of_38__and_everything_ _ssh_esaruoho_kapsi_fi_-i____ssh_id_rsa_-t_screen_-rd__bash_--login_ _150x50_and_gnu_general_public_license](https://user-images.githubusercontent.com/4966687/50646494-e0017a80-0f7e-11e9-9957-f2a275c5ba13.jpg)

waaaiitt.. the .ODT is newer than the .PDF!

**Comment by esaruoho** [comment]
results: by exporting PDF via libreoffice, the fonts are the wrong sizes and overall there will be pages like this:
![surge_manual_1_6_pdf__page_7_of_36__and_surge_pdf__page_7_of_38__and_surge_manual_odt](https://user-images.githubusercontent.com/4966687/50646783-a2e9b800-0f7f-11e9-8494-4334242eaf15.jpg)

like, pages with only one or two lines of text, as opposed to the others. i'll try and see what openoffice churns out with .ODT

**Comment by baconpaul** [comment]
Why not use pandoc yo go to markdown and then we can maintain the document forever more in a text format and render it as web pages?

**Comment by baconpaul** [comment]
OK so a bit of noodling.

If you `brew install pandoc` or otherwise get pandoc however you want you can do this

```
paul:~/dev/music/surge/doc$ pandoc --extract-media ./images Surge\ manual.odt --to=gfm -o Surge.md
```

and then you get a markdown file and a directory of images.

If you then use something like https://github.com/joeyespo/grip or any other markdown viewing tool you can see Surge.md rendered. It is pretty close.

<img width="1104" alt="screen shot 2019-01-03 at 3 38 31 pm" src="https://user-images.githubusercontent.com/13387561/50660395-a2e0bc80-0f6d-11e9-8eff-6b1cd2987f77.png">

<img width="997" alt="screen shot 2019-01-03 at 3 38 48 pm" src="https://user-images.githubusercontent.com/13387561/50660410-ac6a2480-0f6d-11e9-8c8a-84a5260009e7.png">

and editing could then proceed in markdown. The page would be displayable by GitHub with a link.

The only problem is some of the images in the ODT file are "SVM" files (which are kind of like vector files for LIbreOffice) so those need to be resnapped or converted to PNGs and edited.

Of course you don't have to go this route, but it seems both super web friendly, super easy to edit, and most of the wya there.

**Comment by esaruoho** [comment]
yeah, i could probably try and do this, as long as noone expects it to look like the PDF manual does (kinda print-y look)

**Comment by baconpaul** [comment]
yeah it's 2018 I think folks are used to online documentation. Plus also with it being online in markdown we can link to particular sections of the doc from the ui in some future version.

**Comment by baconpaul** [comment]
heck it's 2019 even! How'd that happen? Chuckle.

**Comment by baconpaul** [comment]
Just tagging @kzantow and @itsmedavep to this issue. If kzantow sets up the static web repo we could sweep the manual assets into there rather than the source repo and then do this markdown conversion quite easily.

**Comment by esaruoho** [comment]
as per what @baconpaul did elsewhere (at `surge-synthesizer/surge-synthesizer.github.io`) i guess we can close this ticket.

**Comment by baconpaul** [comment]
This is done, in the other repo

https://surge-synthesizer.github.io/surge-manual/Surge.html
