### ISSUE TITLE
Flexible feedback in Osc FM2, FM3 modes

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1029]
Another FR in regards to FM discussion in the slack channel:
Gaining the ability to route the "feedback" in  FM2 or FM3 to the modulators instead of just the carrier would make some more of the DX100 front panel configurations possible in Surge.

**Implementation**
No idea about the if it's doable to add this to the oscillator code, but in terms of visually this could be added to the interface like this:
Right click menu option for FM2/FM3 Feedback slider with 3 options:
- feedback to carrier (default)
- feedback to modulator 1
- feedback to modulator 2
- feedback to modulator 3 (FM3 only)

**Comment by baconpaul** [comment]
Hmm I like this idea
Maybe 163 is the “fm” release?

**Comment by mkruselj** [comment]
@baconpaul This one doesn't necessarily need param list change, since the feedback options would be in the dropdown menu, hence not host automatable? As such this one might potentially happen sooner than 1.8?

**Comment by baconpaul** [comment]
True kinda, especially if you don't want to modulate it.

**Comment by mkruselj** [comment]
I can't see why anyone would really want to modulate where feedback is in the operator algorithm, honestly... sounds like a recipe for blown speakers!

**Comment by mkruselj** [comment]
@baconpaul I'd like to extend the reach of this feature request.

1. For FM3, we should make M3 have its Absolute mode togglable. Right now it's always absolute, whereas for 1.8 we added Absolute mode for M1 and M2. For consistency it'd make sense to make M3 the same. Using streaming handler we can make sure old patches load correctly of course, so it'd still be in Absolute mode by default.

2. Since we're expanding parameters in 1.9, including how many params oscs can have, we should add an Algorithm integer slider, so that we can add all the DX100/TX81Z algorithms, and maybe a few more! These are DX100 algs:

https://www.keithmcmillen.com/wp-content/uploads/2015/07/4-op-Chipset1.jpg

These are algs from 4-OP FM oscillator in Falcon:

![image](https://user-images.githubusercontent.com/2393720/104370724-96f64080-551f-11eb-9fa3-13aa25fadbe4.png)

A few more than DX100.

**Comment by baconpaul** [comment]
You know maybe we should just add a 4 op fm oscillator as a new oscillator .... would be easier from both a code layout and comparability perspective

**Comment by mkruselj** [comment]
FM4? Ha I guess we could heheh. So keep FM3 and FM2 as legacy, but have FM4 be the "TX81z+" thing? Sure.

But can you agree that M3 in FM3 should also get Absolute toggle?

**Comment by PopeKehoeIII** [comment]
I think toggling M3 in FM3 would be nice as a shorter term improvement before making FM4 become a full TX81z+ (would that include multiple waveforms per operator?)

**Comment by mkruselj** [comment]
> (would that include multiple waveforms per operator?)

But of course! We will have more than 7 params possible per operator 🙂

**Comment by magnetophon** [comment]
My [CZ oscs](https://github.com/surge-synthesizer/surge/issues/3273#issuecomment-748304590) also sound great when FM-ed, just saying. :)
[Here](https://github.com/magnetophon/DigiDrie), you can play with a full synth using them.
Full FM matric and mod matrix provided.

So maybe the CZ ones can just be extra waveforms in FM4, instead of a separate thing?

**Comment by mkruselj** [comment]
I'd would personally like them to be a separate thing. NHF! 🙂

**Comment by mkruselj** [comment]
Closing this issue in favor of #3619.
