### ISSUE TITLE
Tuning: Choose different stable notes

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1043]
Right now the stable note (unchanged by tuning) is fixed in the synth. With 1.6.3 we may want to move the midi note and frequency which is stable (although this may come better through kbm files - lets see)

But so I don’t forget to think about it add this issue as I closes #828

**Comment by SeanArchibald** [comment]
Kbm files specify the "stable" MIDI note and frequency - so if full kbm support happens then you could close both issues in one go. :)

The benefit of kbm support is that it doesn't lock the user in to using linear mappings only - users could specify their own custom key mappings. I can think of a few use cases where custom key mappings are useful, including:

- Making fingerings more easy for standard keyboard controllers (e.g. the user has an 11-note scale, but their standard MIDI keyboard repeats every 12 notes, so they could make a mapping that skips every 'E' key so the 11-note scale repeats every 12 keys, thereby keeping fingerings more regular)
- Added flexibility for isomorphic keyboard controllers (e.g. the user has a Linnstrument or AXiS and wants to change the mappings so that certain intervals line up along certain directions)
- One mapping can be used for multiple scales (e.g. the user has hundreds of 7-note scl scales, and would only require a single kbm file to map any of those scl scales to the white keys)

The above examples are just for illustration. Kbm support means the user has the power to come up with their own solutions to all the above!

**Comment by baconpaul** [comment]
I agree. KBM (#1041) is the way to go so I’ll close this issue (but link it to 1041 so your useful comments carry over there).
