### ISSUE TITLE
Expand Unison Voice Count in Wavetable and Window OSC Modes

### ISSUE THREAD

**Issue by theofficialajyoung** [surge-synthesizer/surge#1046]
There are currently 3 Oscillator modes that support Unison: Classic, Wavetable, and Window.

Classic supports up to 16 Unison Voices, which is a good amount, but Wavetable and Window only support up to 7.

I propose raising the number of voices in those two modes to 16 to match with Classic. 

As far as I can see there's no real reason for the lower number of voices available. Increasing to 16 will allow many kinds of wide, detuned patches to be made with wavetables and user-imported waveforms.

**Comment by baconpaul** [comment]
From reading the code it seems this is a very conscious choice in the parameter but I don't see a place in the actual dsp code where it matters vs MAX_UNISON of 16).

I'm going to tag the 1.6.3 since I think I want to leave it until after our upcoming release but if I convince myself it was just CPU savings I could put it in 1.6.2 also.

On and let me link it to #1034 also

**Comment by mkruselj** [comment]
Well, we have it done now for 1.7. :)
