### ISSUE TITLE
Move the "Timbre" mod tab up

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1083]
![image](https://user-images.githubusercontent.com/2393720/63974995-41e29780-caae-11e9-8254-88c4cd68d4b2.png)

Reasoning: the first row would have all the external modulators then, the other two rows would then have all the internal modulators. It makes a lot of sense IMHO :)

**Comment by baconpaul** [comment]
Here's the diff to do this.  I would apply it now since it works it seems but I want to test a couple fo things before I do

1. Hook up my Roll and make sure Timbre still maps (I checked Amp and Filt EG did)
2. Just make sure a patch saved with nightly puts routing in right spot

Seems like it all should but test before I push.

Will def sweep this one into 1.6.3

```
diff --git a/src/common/ModulationSource.h b/src/common/ModulationSource.h
index b9d6732f..95c9880d 100644
--- a/src/common/ModulationSource.h
+++ b/src/common/ModulationSource.h
@@ -102,10 +102,10 @@ const char modsource_abberations_short[n_modsources][32] = {
 const int modsource_grid_xy[n_modsources][2] = {
     {0, 0}, {0, 0}, {1, 0}, {2, 0},  {3, 0}, {4, 0}, {5, 0},          // vel -> mw
     {7, 0}, {8, 0}, {9, 0}, {10, 0}, {7, 3}, {8, 3}, {9, 3}, {10, 3}, // ctrl 1-8
-    {6, 0}, {6, 2},                                                   // EGs
+    {6, 2}, {6, 4},                                                   // EGs
     {0, 2}, {1, 2}, {2, 2}, {3, 2},  {4, 2}, {5, 2},                  // LFO
     {0, 4}, {1, 4}, {2, 4}, {3, 4},  {4, 4}, {5, 4},                  // SLFO
-    {6, 4}                                                            // Timbre
+    {6, 0}                                                            // Timbre
 };
 
 inline bool isScenelevel(modsources ms)
```
