### ISSUE TITLE
Linux LV2 Audio Incorrect

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1135]
As reported by @rghvdberg in Surge IRC, Tagging @jpcima. Here's how I reproduce it

1. Open the Surge VS2 in Carla Linux. Click the mode from "poly" to "latch" and you get low output sawtooth wave

2. Open the Surge LV2 in Carla Linux. Click the mode from "poly" to "latch" and you get the VU meters going red and something wrong coming out of the audio pipe.

Running with 44.1k jack. I actually don't have my VM audio routing properly to my speakers so don't know quite the sound right now. but clearly the behavior is different.

**Comment by baconpaul** [comment]
As reported further:

The problem is just the init patch; loading a patch works fine.

So something in the startup path.

**Comment by baconpaul** [comment]
Yup - confirmed. This is a release blocker for sure; @jpcima can you look and @tank-trax do you confirm the same behavior?

**Comment by jpcima** [comment]
It's because I didn't load the init patch. These parameters are probably default ones.
I will check it, a bit later today evening.

**Comment by rghvdberg** [comment]
well, it makes sense then :-)

**Comment by baconpaul** [comment]
The init patch is loaded by constructing a surge storage in the correct order. The surge patch constructor runs. You don’t need to load a patch.  Just FYI.

**Comment by baconpaul** [comment]
Basically the init patch isn’t a patch. It is the result of constructing a storage and patch pair

**Comment by baconpaul** [comment]
https://pastebin.com/yfThshey

Crystal math on irc says that fixes it. I’ll test at home and then apply if so.

**Comment by jpcima** [comment]
Hi, I examined the problem now, experimented, and also viewed the patch suggested.

One simple way to fix it, that would be to set the init patch as defaults into the lv2 manifest (instead of parametermeta defaults).
https://gist.github.com/jpcima/a5d4047d78f1d3ab0e66236f792573e9

The patch which is linked in the pastebin is not appropriate, because if lv2 specification is strictly followed, it's said that the plugin must not rewrite the control values from the host.
(ie. don't write into the data location pointed area)

At startup, the plugin respects the initial values which are sent by the host.
It's why, it will override whatever patch is initially in there.
To set initial values as desired, it can be coded into the defaults. I don't know if there is a solution which preserves defaults like parametermeta has them, I can research it if necessary.

**Comment by baconpaul** [comment]
OK well I will not apply that patch then!

So what we change the exporter to set the same values as a blank patch?

**Comment by baconpaul** [comment]
Confirmed your patch works; also confirmed that pMeta.fdefault was not the right thing! So I like your diff. Can you send it over as a PR and I'll merge it?

Thank you!

**Comment by jpcima** [comment]
Alright ! :+1:
I was not sure what's your difference between a "init" and "blank" patch from reading your first post above. If this solution is considered fine regardless, I'm happy to implement it.

**Comment by baconpaul** [comment]
So there's three separate things

1. The result of every parameter getting set to "fDefault". That's not anything other than noise. But it results from foreach(param) param->setValuef01(param->fDefault);

2. The result of constructing a SurgePatch(). That's the "init" patch and uses the non-default settings for a single sawtooth as described in SurgePatch.cpp. That comes up as "init" even though it is not streamed

3. A patch from a .fxp, some of which are named init. Those are not loaded for the init

I'm just sharing this for information really. It's odd. I would love one day to have the init patch be a patch which was configurable. But not today!
