### ISSUE TITLE
Fast LFO speeds cause graphical slow down (older machines?)

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1167]
This is something I've noticed on my Macbook, it's only come up a couple times because i don't need super fast LFO's that often but it is kind of big issue for usability/stability on this system.
I've also noticed this slowdown on my linux machine as well in #1103 , wondering if they are related. 

My partner has a newer macbook (2013 13inch with intel HD4000 macos Mojave) and the the issue DOES NOT occur. It also doesn't happen on my Windows machine.

**TESTED ON:**
mac os sierra, 2013 13 inch macbook
i7, 8gb ram, intel HD 3000

**Problem**
Taking the LFO above around 10hz (into audio rate) causes EXTREME graphical slow down on all plugin platforms (VST2, VST3 AU ) and all tested DAWS (REAPER, Logic X, Renoise, Ableton Live). It appears to be because of the drawing of the LFO, once the LFO graphic draws, the slowdown stops and the LFO sounds as expected.

**What it's like**
When the LFO is slowing down the interface locks, and you get a the spinning beach ball graphic. Audio is completely unaffected as far I can tell, sounds keep playing as they should. Takes up to 5 seconds to be able to change parameters.

**The big issues with this:**
A: it causes big slowdowns and is graphically weird
B: it's actually impossible to accurately set fast lfo times, because the interface locks up.

**Possible Solutions and Concerns**
I'm wondering if this is just because this computer has an older integrated graphics card and my Windows computer has a more modern, dedicated GPU.... It makes sense that drawing 1000's of indivdual lfo cycles would slow down an old GPU.... Maybe this isn't so much a bug as something that isn't as optimized as it could be? 

Is this particular graphic really necessary? It just looks like a bunch of scribbles at high speed anyway? Is it possible to have high LFO speeds be represented in a different way visually?

I don't have more machines to test but if this slow down is indeed just effecting older computers/gpu's but if that IS the case I'm concerned.  I think a sizable section of people who will be using Surge will be on older/cheaper machines and this slow down effects the usability.

**Comment by baconpaul** [comment]
Yeah at high frequencies I can put in a different approximation than drawing everything - let me test it.

I can also increase the averaging rate out of the gate which will just help everything.

**Comment by mortfell** [comment]
awesome! Thanks for checking this out @baconpaul !

**Comment by baconpaul** [comment]
So there's a couple of solutions

I have one which increases the averaging rate some and compensates for having a small window which uses about 1/4 the resources to make the scribbles

If that doesn't work on your old machine I also have the old bitmap code available since we need it on Linux so I could do something like "if a draw cycle takes > 1/30th of a second fall back to the old display forever" or something. or make it a user preference.

But let me push my immediate improvement which doesn't result in that much quality degradation on my machine and see if that fixes it for you.  If that fixes it great. If not I will back out the change and add another approach.

Please be on the lookout for a nightly in about an hour. Thanks!

**Comment by mortfell** [comment]
Will definitely check it out! Have a day off today and working on the Wavetable wikis 🤓

**Comment by baconpaul** [comment]
Cool. Just merged the optimization so new nightly probably within 30 minutes or so. Thanks

**Comment by mortfell** [comment]
Ok so the scaling you did, on my machine anyway, does improve the drawing speed but not much.
It no longer gets a beachball, but it's still slow enough that usability is hindered substantially, have to wait 1.5 seconds instead of 5.

**Comment by baconpaul** [comment]
Whoa 1.5 seconds!!!!! That’s insane

It takes 12ms on my computer literally 

Let me think of a plan b. I’ll back out this diff and try a different one!

**Comment by mortfell** [comment]
Yea, well that is just an estimate, but I don' think I'm being that hyperbolic haha.... it's long.

**Comment by baconpaul** [comment]
Right. That’s bad

I’m going to make it a user option but also I’m going to time the draw and if the draw ever takes more than 50ms or so toggle the option for that session is my current olan

**Comment by mortfell** [comment]
nice, sounds like an elegant solution.

**Comment by mortfell** [comment]
Yeah this is perfect thanks so much @baconpaul !!

**Comment by baconpaul** [comment]
OK great.

To finish it off, I’ll change it to 3 states. (1) auto detect [default mac/windows]; (2) always vector and (3) always bitmap [default linux] then implement and push. I’ll add a manual update while at it and close this issue when i have

thanks for the report!

**Comment by baconpaul** [comment]
OK here's what I ended up doing

1. The menu is still there so you can pick a default except on linux where bitmap only
2. If you are in vector mode, and a draw takes > 0.1 seconds, then the rest of that instance and that session defaults to bitmap mode.

Pushing the code now. Did a test on all platforms of this one since it is a bit of a tweak. Works fine.
