### ISSUE TITLE
Please make 'cmake' install files

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#1200]
--deleted--

**Comment by baconpaul** [comment]
Happy to review and merge a pull request which does this and builds the plugin all flavors Mac windows and Linux. 

Build Linux definitely installs things though. I use it to install the synth all the time! Use the install option.

**Comment by yurivict** [comment]
> Happy to review and merge a pull request which does this and builds the plugin all flavors Mac windows and Linux.

Why do you expect others to do development for you? I am only a package maintainer on FreeBSD, I identify software that might benefit some users, port it and then maintain the ports. I personally don't need most packages, including surge.

You should be happy that somebody identified a weakness in your code, and pointed out that this weakness would cause a lot of users to never even see your software because package creators and maintainers on various systems wouldn't be able to figure out how to even create a package for your software. Instead, you ask the person who identified the weakness to also fix it for you. This is totally unreasonable.

----------------------

> Build Linux definitely installs things though.

No it doesn't.

1. It assumes that the installation path is /usr when ```make install``` should install into ```$DESTDIR$PREFIX```.
2. It expects the ```premake5``` executable when it is really called ```premake```.
3. Even after correcting the above issues it still fails:
```
cd /usr/ports/audio/surge-synthesizer-lv2/work/surge-e1997c8 && ./build-linux.sh -p lv2 install
./build-linux.sh: missing operand
```

---------------------

The above issue only attests that writing custom shell scripts to do what cmake already does very well only decreases the quality of your software. Just look at the time I've spent typing the problem description above. With cmake installation would have been seamless.

**Comment by baconpaul** [comment]
@jpcima @falkTX let me tag this and introduce you to a member of the linux/freebsd community who has a variety of opinions on how surge build system works there.

@yurivict best of luck in meeting your goals! Hope you enjoy surge.

**Comment by mkruselj** [comment]
> Why do you expect others to do development for you?

It's called "open source software". Duh.

> You should be happy that somebody identified a weakness in your code, and pointed out that this weakness would cause a lot of users to never even see your software because package creators and maintainers on various systems wouldn't be able to figure out how to even create a package for your software.

A little less asshattery and a more diplomatic approach in your statements would be welcome.

**Comment by falkTX** [comment]
I know almost nothing of cmake, so I am afraid I cannot help much here

**Comment by yurivict** [comment]
> It's called "open source software". Duh.

Open source doesn't mean that you would be comfortably watching movies, and other would do work for you.

> A little less asshattery ...

I just pointed out the attitude problem, no asshattery there.

**Comment by falkTX** [comment]
> > A little less asshattery ...
> 
> I just pointed out the attitude problem, no asshattery there.

It is not the first time I see this happening, and I can tell you for sure your attitude is a problem.
Might be cultural differences, I do not know.
But next time try to think more of *asking* instead of *demanding*.
Your current approach often ends up sounding like demands

**Comment by yurivict** [comment]
Yes, this is a cultural problem of project authors fishing for help vs. fixing things themselves.

I am tired hearing project authors saying "could you please also fix this for us?"

I maintain 920 packages. With each update there is ~50% chance of some sort of breakage. Imagine if every time I report such issue I also had to fix it. This would have been not even one, but more like 10 full time jobs. And why would people assume that I need their package?

**Comment by baconpaul** [comment]
Your comments, especially considering your lack of context with the project, are fascinating. But I wish you the best. I don't think this issue is going to end up being the one we tag with the cmake build - perhaps one of the other ones where folks discussed it will. 

So I'm going to close this issue. I hope you enjoy using surge!

**Comment by yurivict** [comment]
It's fascinating when people write a cmake file that builds the project, and then find it necessary to write a custom shell script to install it, unlike thousands of other projects. And then, when somebody points out the problem, they ask the reporter to also fix that issue, and eventually close the bug report about this obvious issue without fixing it.

**Comment by baconpaul** [comment]
I wish you peace and happiness. If you make music I hope you enjoy using surge.

**Comment by kzantow** [comment]
@yurivict I suggest you try another approach to this. If you want something done to the cmake files (which are not and have never been complete), you're welcome to submit a pull request with the appropriate changes or outline what you'd like done in a civil manner. But please understand that it is no one's responsibility to do this for you. If you don't like the project, feel free not to use it.

**Comment by yurivict** [comment]
I never said that I needed this project.  I assumed that the authors wanted more people to see it and suggested an easy way to do this. But this was a wrong assumption, sorry.

**Comment by esaruoho** [comment]
@yurivict it is not our problem that you maintain 920 packages. if you find it so stressful, i'd suggest dropping the maintaining of 920 packages and do something that you actually like.

**Comment by esaruoho** [comment]
from @yurivict 
>Yes, this is a cultural problem of project authors fishing for help vs. fixing things themselves. 
>I am tired hearing project authors saying "could you please also fix this for us?"

Hi `yuri@FreeBSD`. considering you just dropped here and then deleted all your messages, i'd suggest figuring out what the state of this project is, before attacking it. @baconpaul and many others have spent enormous amounts of hours making Surge compile for Windows, macOS, Linux in various formats, and on improving the plugin after it was made opensource by @kurasu. 

This project has been, from the start, a "if you know how to help, please do". And people do. Because that's how it progresses.

You are the _second_ person to come in here saying "do this, do that", without contributing a single thing. When you get called out on it, you profess ignorance, claim a 920 package workload makes it impossible, and clarify your statements with a "i don't need this software" and go and delete your messages. 

Is this really the way you want to conduct yourself in the opensource community?

**Comment by yurivict** [comment]
@esaruoho It's you who professes ignorance. I pointed out a valid problem in your code. Every responsible engineer would try to fix the problem in their code, and your attitude is "You fix it yourslf if you need it." You are either irresponsible, or incompetent, or both. Probably incompetent, because you don't seem to understand the issue at all.

I have also spent infinite amount of hours on various projects, just not on this one.

**Comment by falkTX** [comment]
jeez, dont act like a douche; now name-calling?

this is not exactly "our code", as mentioned before this project exists out of kindness.
the author released the source and a few developers now maintain it, with the help of the community.
community that you could be part of, but somehow proudly want to piss on.

we are working on stuff to get it working for each of us.
you pointed out an issue *for your own usecase*, so it seems fair to say that a PR is welcome.

there are many issues reported by users, are they all going to start insult developers when we say "makes sense, PR welcome"?
can't you see that what you are asking, how you are behaving, is totally unprofessional and childish?

**Comment by tank-trax** [comment]
we've reached out to Bitwig and Reaper to get things worked on, on their end and not once did we come in guns blazing and start criticizing their project, we asked to help, contribute and collaborate and the response has been great

your tact is lacking to say the least

so maybe back up and accept that although you may be right, it doesn't make how you approached the situation right, you're putting everyone off, so in this case... you are the one who should reconsider their approach

if there is something you feel you can contribute to assist and get this synth to the FreeBSD audio community.... all 13 of them.... we will gladly help (that all 13 of them was a joke BTW)

so lighten up a bit and apologize

from there we can move forward

**Comment by yurivict** [comment]
You talk like you have a high moral ground. I have a different set of principles. From my standpoint, your attitude is outrageous, unbecoming of an engineer. You can't outsource changing your code to random visitors or bug reporters. I stated that I am just a package maintainer. I offered to create a package, notified you of a bug. Instead of being grateful, you asked me to also fix your code. You imply that I need it. But I don't need it, it's for the ease of users. You shlould be interested in your software to be seen by as many users as possible, not me, a random visitor.

**Comment by falkTX** [comment]
we appreciate that of course. but we do not appreciate being insulted, that should be common-sense, no?
it is not unusual to ask for a PR when someone reports an issue. packagers are not regular users, often times they understand a bit of code too. this request is not as outlandish as you make it out to be.
if you are tired (which seems really to be the case) please consider taking a rest, you do not have to do so much

**Comment by tank-trax** [comment]
if you had simply offered to create a package and notified us of a bug we wouldn't be here... that's not how it went down

**Comment by yurivict** [comment]
Sorry that I didn't mention my original intent.

**Comment by esaruoho** [comment]
> Sorry that I didn't mention my original intent.

your original intent was apparently

```
--deleted--
```

so apparently you had no intent?

**Comment by baconpaul** [comment]
You're all bumming me out. Can you please stop? Clearly the OP has strong opinions, clearly my invitation to him to help solve the problem he raised was not one that worked for him. But I don't think you all really need to keep with the same back and forth.

Surge is the way it is today because people solved problems most important to them; I made it work on the mac when it didn't; I made MPE work when it didn't; jjs and I made the engine compile linux and falk made the plugin work; esa and oddly you guys found a scullion bugs; kzantow set up the pipelines. A million people found bugs and contributed content. And we all set our priorities based on our personal interests and the users we interact with. 

For me cmake has not made it to the top of my list - which is long.  I wish we were using it instead of make, but not enough to move to it instead of fixing the problems in the engine. I still invite anyone to whose list it does make it to the top to contribute a pull request which me and others here will gladly review, merge if appropriate, deploy, and if they are willing to be civil and inclusive, welcome them to the community.

**Comment by yurivict** [comment]
I couldn't get the upstream to accept the issue, instead it turned into a request to help fix the project and into an unproductive conversation, instead of a constructive resolution, so I deleted the conversation.

But I really don't like being asked by random people to fix issues in their code. This happened an infinite amount of time. I could have spent a lifetime fixing others' code.

**Comment by esaruoho** [comment]
@yurivict if you read carefully what @baconpaul said, he'll get to it when he gets to it, but anyone that wants to help, can help. no help? he'll get to it when he gets to it. 

simple, huh?

**Comment by tank-trax** [comment]
I haven't used FreeBSD since FreeBSD 4. I wasn't even aware that there was a FreeBSD community.

I am a Linux user though. When I came into the project it was with the hopes that it would work in Linux. Well.... it does.

Apart from that, and from my experience with this project is that I want to see it succeed and on as many platforms as possible. There are a few people using Arch and their contributions have been not just well received but also critical to Surge's portability to Arch based distributions. Getting it over to Arch would not have been possible without their contributions and bug reports. It's going to have to be the same thing for FreeBSD. None of us use it, so to get it moved over would take FreeBSD users to get involved.

If you noticed something in the code that could use fixing we are all open to hearing it. The original comment has been deleted and I am not into scouring the history to get the gist of it.

If you can reword it and offer some suggestions and/or solutions it would be appreciated.

**Comment by yurivict** [comment]
Re-wording my original suggestion:

Please make the cmake script install ```surge-synthesizer```. The shell script that is currently doing it fails for a variety of reasons:
1. It assumes the the installation root is ```/usr```, instead of ```$DESTDIR$PREFIX``` as it should be.
2. The executable name for ```premake``` is ```premake```, not ```premake5```
3. It fails with
```
./build-linux.sh: missing operand
```

**Comment by baconpaul** [comment]
As an FYI On #2: The executable name for premake 4 is premake; the executable name for premake5 is premake 5. We require premake5 right now and, alas, they are different incompatible versions. I wonder if that is causing your problem #3.

**Comment by baconpaul** [comment]
I am reclosing this ticket since I consolidated the cmake discussions and the measures of success for a move over in a new clean #1206 

Thanks

**Comment by mkruselj** [comment]
> 
> 
> Re-wording my original suggestion:
> 
> Please make the cmake script install `surge-synthesizer`. The shell script that is currently doing it fails for a variety of reasons:
> 
>     1. It assumes the the installation root is `/usr`, instead of `$DESTDIR$PREFIX` as it should be.
> 
>     2. The executable name for `premake` is `premake`, not `premake5`
> 
>     3. It fails with
> 
> 
> ```
> ./build-linux.sh: missing operand
> ```

This is exactly how your original post should have looked like, without later resorting to being a massive douche.

**Comment by tank-trax** [comment]
@yurivict FYI Surge is moving from premake to cmake
