### ISSUE TITLE
Surge's plugin wrapper in FL Studio is re-sizable

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1212]
**Bug description**
Surge's plugin Wrapper in FL Studio is re-sizable, where it should probably not be.

**Surge Version**
1.6.2 , VST3, 64 bits.

**To Reproduce**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/50145178/65452546-7298c100-de0f-11e9-8168-8bd5ce1bdb8f.gif)

**Expected behavior**
There shouldn't be the re-size triangle on the bottom right of the Wrapper for Surge, so that we use the integrated zoom options in the plugin instead. (or we could re-size the GUI dynamically, although this is probably much more complicated to do and for another day)

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/50145178/65452892-13877c00-de10-11e9-904f-eae254c5e915.png)

**Desktop config:**
 - OS: Windows 10 x64
 - Host: FL Studio 20.5.1 x64

**Additional context**
This isn't a major issue, but it's been there since the beginning and I've dragged it by mistake a couple of times in the past. I don't know if it's easy (or possible) to tell the Wrapper that Surge is "not re-sizable" and still be able to use the zoom options, but I've seen other plugins that either have a re-size triangle integrated in their GUIs, or zooming options similar to Surge's zoom options, while the wrapper itself doesn't have that triangle. Also don't know if this is present in other DAWs.

**Comment by baconpaul** [comment]
Yeah so I know why but the fix is slightly tricky

Vst3 sets property “can resize” to true because surge can resize and that lets me process the resize events that the zoom control sends. But it also means hosts can if they want try and resize 

That will send me a message which I ignore because I have an assumption that the only person resizing is me. That assumption is wrong of course but until now I didn’t know a host which broke it as cleanly as fl seems to. So that’s great!

The solution is for me to more properly implement onsize and sizeconstraints in the surgeguieditor so that when you drag it calculates and sets the zoom properly. And also retains the aspect ratio

I think I’ll end up doing a 1.6.3 release when I get access to Cubase around fixing the vst3 - I can include this issue in that too. It’s too big a change for the point release this week tho.

Thanks as always for the clean report!

**Comment by baconpaul** [comment]
Link this with #1219

**Comment by VincyZed** [comment]
So after implementing the new dynamic zooming feature (which is awesome by the way), I saw this bug:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/50145178/66053297-106f4880-e500-11e9-8b85-6a1d86045d1b.gif)

Closing the wrapper and reopening it gets rid of the empty black area on the right and allows to shrink down again.

Windows 10, FL Studio.

**Comment by baconpaul** [comment]
Ok the new nightly should have fixed this problem. Can you confirm and if so we can close this issue! Thanks

**Comment by VincyZed** [comment]
So I tested, and yes it doesn't constrain the wrapper re-sizing, which is a great improvement. When extending past the max (which would be blocked before), it just fills the additional blank with black. (I don't know if it's intended that way or not but in case it isn't here you go). Also, I don't know if you have control over the wrapper size itself, but it's possible to put it where (I guess between 2 percentage values or something?) there is still a black outline when re-sizing the wrapper, as seen below.

![image](https://user-images.githubusercontent.com/50145178/66168159-6defbc00-e60a-11e9-862b-84eb302de736.png)

Of course, I'm super happy that this feature works now, the rest is just basically nitpicking at this point! Great job!

**Comment by baconpaul** [comment]
The black beyond is intentional yeah. 

The little border is because I am being conservative about resize. I can be less conservative pretty easily. I'll look before I close it

Thanks for testing!

**Comment by baconpaul** [comment]
Link to #1219
