### ISSUE TITLE
Expose parameters as LV2 CV?

### ISSUE THREAD

**Issue by mxmilkiib** [surge-synthesizer/surge#1321]
LV2 (and JACK) have a "CV" port feature allowing audio rate data to be patched between plugins (and apps) for parameter control. More information [here](https://linuxmusicians.com/viewtopic.php?f=1&t=20701).

Could Surge optionally expose the input and output of some of it's parameters in this manner?

**Comment by baconpaul** [comment]
Hi again! @jpcima and @falkTX wrote the LV2 so mechanics of the actual LV2 I have almost no idea about. So tagging them.

But... Surge snaps its control parameters every block_size (8 samples) and then either holds them constant or linearly interpolates them from prior value at start of block to current value at end of block. Controlling parameters on a resolution higher than that is impossible. This leads to some things - like super efficient execution - but other things too - like having the VCVRack adaptation be a little less analog than other modules. HTH!

**Comment by jpcima** [comment]
Hi,
@mxmilkb I don't know yet much about the CV ports of LV2.
Are we able to transform a ControlPort into CVPort, without breaking the compatibility?

**Comment by hems** [comment]
> - like super efficient execution 

This is very overlooked nowadays, i feel like everytime Native Instruments releases a new version of Reaktor i need to have a 10.000 USD computer in order to play live and make music with it.

It's just not sustainable.

One of the most special things on surge is how low CPU it consumes and how many instances you ca run at the same time.

We should have that as paramount or we will end up like those "business vst plugins" that are more worried about lush GUI but lack of sound character!

**Comment by hems** [comment]
> LV2 (and JACK) have a "CV" port feature allowing audio rate data to be patched between plugins (and apps) for parameter control. More information [here](https://linuxmusicians.com/viewtopic.php?f=1&t=20701).
> 
> Could Surge optionally expose the input and output of some of it's parameters in this manner?

This is amazing, thanks for sharing.

We were thinking today about this while working on some Surge patches.

In an ideal world there would be some more modulations on the bottom so you could have "envelope follower" for instance following the amplitude of some part of the signal path or external source.

Another thing would be to use very slow OSCillators as triggers for envelopes like you can do with the step sequencer on the first LFO.

Another idea is instead of "KeyTrig" envelopes to have "Audio Trig" so waveform cycles could re-trig the envelopes when you're in "latch" mode..

just a few ideas.. 🤓

**Comment by baconpaul** [comment]
> We should have that as paramount or we will end up like those "business vst plugins" that are more worried about lush GUI but lack of sound character!

Yup I profileit if I make changes to the dsp and make sure we keep the sse2 instruction set running along internally. Not gonna break this feature!

**Comment by baconpaul** [comment]
> In an ideal world there would be some more modulations on the bottom so you could have "envelope follower" for instance following the amplitude of some part of the signal path or external source.
> 
> Another thing would be to use very slow OSCillators as triggers for envelopes like you can do with the step sequencer on the first LFO.
> 
> Another idea is instead of "KeyTrig" envelopes to have "Audio Trig" so waveform cycles could re-trig the envelopes when you're in "latch" mode..
> 
> just a few ideas.. 🤓

I like each of these ideas. We should make them separate issues though. I know @mkruselj has also thought about them (and I thought had even written up a feature idea for using lfo crosses as envelope triggers but I can't find it). I think #982 is also super relevant for a lot of these ideas.

**Comment by mkruselj** [comment]
> (and I thought had even written up a feature idea for using lfo crosses as envelope triggers but I can't find it)

#1383

**Comment by baconpaul** [comment]
Closing this issue, since #4030 is the place we are investing in LV2 going forward. If the JUCE/LV2 port works, it works, and the problems in our hand-port will be gone (or replaced with problems in the JUCE/LV2 port).
