### ISSUE TITLE
CC- offsets are off in the VST3 for automation

### ISSUE THREAD

**Issue by AlexMirMir** [surge-synthesizer/surge#1347]
only way to do it is assigning midi cc controller

**Comment by baconpaul** [comment]
Hi. Can you give us some more details please?

Which os, which version of the plugin, which version of bitwig? 

Thanks!

**Comment by baconpaul** [comment]
![bitwig](https://user-images.githubusercontent.com/13387561/69722127-530a6700-10e4-11ea-917b-732ba063899e.gif)

Here's me using Bitwig 3 on macOS with the 1.6.4 VST3. The param control automation seems to work no problem.

So definitely need some more details to understand your problem. Thanks so much!

**Comment by AlexMirMir** [comment]
Thank you for the reply, it's only with control sliders...
Windows, Surge 1.6.4, this issue appears  in 1.6.3 before was working

https://www.youtube.com/watch?v=ZQ6esdcqxUM

ср, 27 нояб. 2019 г. в 20:06, Paul <notifications@github.com>:

**Comment by baconpaul** [comment]
Thank you. That made it very clear.
My guess is that this will work fine in 162 and not in 163 or later; and the rest of vst3 midi will work fine in 163 or later and not 162

I have an idea what would cause this. Let me add it to the December list

Appreciate the clear bug report

**Comment by AlexMirMir** [comment]
Awesome, love the synth since the very first version, keep up the good
work!

чт, 28 нояб. 2019 г. в 20:46, Paul <notifications@github.com>:

**Comment by baconpaul** [comment]
So just a note to myself.  This is one of the last 1.6.5 issues left.

This happens because CC0 and the remapping code and stuff in beginEdit and so forth in the VST3 is all a bit confusing and confused. I just need to document who calls what and with which ID and then make sure I do the right transformations. I got close but it is too late.

Most importantly though it doesn't seem to require us to adjust the metaparam offset. But more testing and debugging required.

**Comment by AlexMirMir** [comment]
Hey Paul,

Surge Xt 1.1.2 Clap format has the same issue as we talk before, the vst3
version has no issues with automation,

you guys a doing amazing work, thank you!

пт, 24 янв. 2020 г. в 12:30, Paul ***@***.***>:

**Comment by AlexMirMir** [comment]
It's all good, sorry, my bad

ср, 9 нояб. 2022 г. в 22:02, Paul ***@***.***>:
