### ISSUE TITLE
LFO waveform ruler: Support a beat ruler when tempo sync'd

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1388]
When I temp sync rate on and LFO, my mind works in trying to place modulations at a given beat increment since I have now chosen that for the slider. Since the slider is conforming to that, I want to see the waveform display that way as well. 

So for example I want things to happen at "2 and" which is tough to visualize currently.

**Comment by baconpaul** [comment]
I like this idea - a couple of questions 

1. Several of the lfo sliders can Temposync. We just want to use rate Temposync to switch the axis right? Like imagine you Temposync the envelope delay but not the rate - show seconds. And Temposync the rate but not the delay - show beats

2. As that question shows the display is dependent on bpm. I need to see if we detect bpm changes in a way that triggers a repaint. More a note to myself

3. During playback if bpm changes would you expect the display to change? The modulator would so I think the answer is yes but this could be an expensive repaint 

4. Label the beat axis 123456... and don’t assume a time signature? Should we highlight 4 8 etc or not? I should also check if daws send us a time signature in the transport block. I think au does but am not at my computer

**Comment by mkruselj** [comment]
1. Yes, rate is the one to go by.

2. I don't think you should follow BPM at all, that might be potentially problematic with gradual tempo changes and GUI open? Should just render it taking 120 BPM as base.

4. Just take 4/4 and run with it. It's the most often used. I didn't see time signature taken into account for tempo synced time rules in (m)any plugins.

**Comment by baconpaul** [comment]
We have to use bpm since the attack etc will be in seconds and we want to draw the truth!

**Comment by mkruselj** [comment]
Argh, well I suppose let's see how that works in practice. It's probably not gonna be helpful at all after a certain point (curve gets too dense).

**Comment by baconpaul** [comment]
Yeah it’s actually harder to use 120; the question is when do we repaint

also the number of bits of music I’ve written which are 4/4 120 in the last 5 years is I think 0 :)

**Comment by baconpaul** [comment]
Actually the repaint question on bpm change is a question now too! Even if we don’t change the axis we have the same question

**Comment by itsmedavep** [comment]
Upon further consideration I think all I need is the ability to switch the time display to beats and measures. The additional ability to make beats and measures the default would be extra nice. 

I dont really need anything "smart" or auto switching the ruler. 

![beat-grid](https://user-images.githubusercontent.com/11078351/69997360-9f590b00-1519-11ea-91a5-e531bc06a93b.gif)

This is behind a right click. Id prefer it be a toggle button. 

For your question 3:
Ideally yes.

For your question 4:
Indicate the measure and then quavers. Ideally, the ruler would change based on time signature.

**Comment by itsmedavep** [comment]
![changing-time-sig](https://user-images.githubusercontent.com/11078351/69998001-04613080-151b-11ea-9c79-66b55412c13d.gif)

Here is changing the time signature.

**Comment by baconpaul** [comment]
OK so right now none of the engines give us a time signature. In the au there is a 'CallHostMusicalTimeLocation' which I could call (but don't) which would give me the signature and then I could plumb it through but I would need to do the same for VST2 and VST3 using those bespoke APIs and test it in the various hosts. I think bars and measures are probably beyond what's super easy.

But right now we already have a 'doesn't repaint on BPM change' bug. Look here. Changing the LFO envelope forces a repaint (as we know). But changing BPM doesn't. So when we change BPM in temposync mode and then jog the envelope later, the waveform jumps to the new BPM.

This is not because the BPM isn't coming through. Surge sees every change. It is because the LFO isn't repainting when BPM changes. I think it probably should, or at least should if any of the current modulation source parameters are temposynced.

Once I've fixed that, and I know if any parameters are temposynced, I can also easily change the axis. That's not hard at all. I'll just do it to beats and for now will make every 4th beat emphasized but will also explore the APIs in VST2 and 3 for gathering time signature.

![TempoSyncLFORefresh](https://user-images.githubusercontent.com/13387561/69998623-ba7d4800-1524-11ea-9b9c-296196ba821f.gif)

**Comment by itsmedavep** [comment]
This seems like it contains some relevant information on this topic. VST2 may be problematic.

https://forum.cockos.com/showthread.php?t=214003

**Comment by baconpaul** [comment]
![Fix](https://user-images.githubusercontent.com/13387561/70000101-417fef80-1528-11ea-8f66-6ef2883d611c.gif)

Getting a lot closer

But we need to also invalidate the LFOGUI when any of the parameters toggle their temposync which is really painful.

**Comment by baconpaul** [comment]
![Fix](https://user-images.githubusercontent.com/13387561/70000176-768c4200-1528-11ea-8b67-3ec1ac975c20.gif)

Getting close. But need to also invalidate if any of the LFO parameters toggle their temposync. Which is a bummer.

**Comment by baconpaul** [comment]
VST2 time sig is impossible; that and the LV2 will just get 4/4. The VST3 and AU have time sig coming through shortly.

**Comment by baconpaul** [comment]
![WithTS](https://user-images.githubusercontent.com/13387561/70013674-700cc300-1546-11ea-99ad-ae872573d6a7.gif)

Yeah entirely doable.

**Comment by baconpaul** [comment]
OK this is headed into the nightlies looking like this:

![FinalChoice](https://user-images.githubusercontent.com/13387561/70088154-b6fcc600-15e3-11ea-8c8b-0ca21210ea87.gif)
