### ISSUE TITLE
Blue half-tint slider indication does not appear when modulating LFO parameters by other modulation sources

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1424]
**Bug description**
The blue half tint indicators on sliders (meaning that the parameter is modulated, but not by the currently selected mod source) do not appear in the LFO editor section when modulated by another LFO or any other modulation source.

**Surge version**

* Latest nightly
* VST3
* 64bit

**To Reproduce**
1. Open Init Saw patch for instance.
2. Select LFO 1.
3. Engage routing mode.
4. Click LFO 2's magic arrow, for instance.
5. Modulate rate, magnitude, or any other LFO or envelope parameter in the LFO editor. It will have a full blue tint (that's normal, since you're now editing LFO 2's modulated parameter by LFO 1, and LFO 1 is selected as the mod source).
6. Select LFO 2 as the mod source now.
7. See bug.

**Also, when going back in routing mode, the blue slider does not appear at all, unless the original modsource is selected.**

**Expected behavior**
The modulated parameter should now be half-blue tinted to indicate that it is being modulated but not by the currently selected mod source, instead of being gray as if it was not modulated at all.

**Demo**

![Demo](https://user-images.githubusercontent.com/50145178/70958895-93f0fe00-2048-11ea-8dfa-fa432ecb1477.gif)

**Desktop config**
 - OS: Windows 10 x64
 - Host FL Studio 20.6 

**Additional context**

This has been happening for a while now, maybe a month (or longer, don't remember when is the last time that it worked). It really confused me when doing lots of complicated cross-modsource modulation stuff, as visual feedback is missing.

**Comment by VincyZed** [comment]
Just discovered that right after that, when selecting another voice property modsource (like Poly AT), the half-blue tint appears. When selecting back LFO 2 as mod source, it disappears again.

![image](https://user-images.githubusercontent.com/50145178/70959833-3d38f380-204b-11ea-8cec-aaced60895e3.png)

**Comment by baconpaul** [comment]
It's not just the tint.

Do this

Select Channel AT and modulate an LFO then click it again and you will find that the blue handle doesn't show up when re-activated. It does with some other things like velocity. So clearly some weird state bug with the sliders here getting it wrong.

**Comment by baconpaul** [comment]
OK so here's what's happening, although I don't know a fix yet

The blue color is set up in SurgeGuiEditor in the default: of openOrCreateEditor with the

```
if( symt->isValidModulation )
```

block around line 1350. Basically it is asking if a modulation is valid before turning stuff blue.

Now lets take a look at SurgeSynthesizer::isValidModulation. That has a case

```
   if ((p->ctrlgroup == cg_LFO) && (p->ctrlgroup_entry == modsource))
      return false;
```

which makes perfect sense. An LFO can't modulate itself.

But therein lies the problem. We are using 'isValidModulation' to mean can A modulate B; and also therefore should A display modulation. But it doesn't mean the second. Because when we select LFO1 then the mod source is LFO1 and the target is LFO1 so obviously it is not a valid modulation. But there may be external modulations onto LFO1 we want to display.

I think we need to call isModDestUsed in the not-valid branch. That's what I'm going to test next. That is independent of mod source.

**Comment by baconpaul** [comment]
Oh yeah that was easy. That's exactly the fix.
