### ISSUE TITLE
Scrolling through buttons is not consistent

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1440]
**Description:**
Scrolling through orange buttons such as **Scene Mode, FX Bypass/Character, OSC FM Routing, Filter Configuration, Octave switches, Filter algorithms, Waveshaper Shape,** etc. is inconsistent.
Sometimes it takes **two scroll** steps for it to switch to the next / previous option, when it should only take one.

**Version:**
Latest nightly, VST3, 64 bits.

**Desktop (please complete the following information):**
 - Windows 10 x64
 - FL Studio 20.6

Seems like a small bug, probably valid for #1390 ?

**Comment by baconpaul** [comment]
The mouse wheel tries to normalize the rate based on the number of rows and columns, but I bet that isn’t working quite right.

Code is here https://github.com/surge-synthesizer/surge/blob/a64f93570111bc13da0d159d45d54c7d4974ae60/src/common/gui/CHSwitch2.cpp#L114

It’s a bit hard for me to test this (I don’t have any device with a physical scroll wheel just trackpads with swipe gestures) but here’s some things I would look for

1. Does getRange() return correct values? (Presumably 0/1)
2. Is that calculation of rate correct?
3. You know just generally look at and debug that code branch to make sure normalization is correct!

I’ll look at this when I’m back but since you can now build and do PRs figure I would point you at the code in case you wanted to. It’s a pretty straight forward chunk of code and the solution is definitely in that block somewhere!

**Comment by VincyZed** [comment]
So after some testing, getRange() seems to always return 1.0.
After trial and error, I managed to kind of get it working right by adding +0.13 offset to Range before the calculations. This is clearly not the best way to do it, but that shows that the issue is indeed somewhere here.

**Comment by VincyZed** [comment]
Ah I just figured it out. We simply had to do subtract 1 to the number of columns and number of rows because here we want the number of **"scroll steps"** or **"dividers between the buttons"** instead of the number of buttons for the calculation!

**Comment by baconpaul** [comment]
Oh yeah!

**Comment by baconpaul** [comment]
If you put that in a pr I can merge it in the morning! Awesome!
