### ISSUE TITLE
Crash: FL Studio crashes as soon as playing this patch

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#1514]
**Describe the bug**
Surge makes FL Studio crash when playing this patch:

**To Reproduce**
Here's an example patch with **only the last step needing to be done (step 6)** to make the crash happen:

[SURGE_CRASH.zip](https://github.com/surge-synthesizer/surge/files/4113119/SURGE_CRASH.zip)

Steps made to create this patch:
1. Extend Scene Pitch parameter.
2. Set LFO1 to Envelope mode.
3. Route LFO1 with maximum extended value (168) for the Scene Pitch.
4. In LFO1. set all 6 LFO EG parameters to 0.
5. Route Keytrack to LFO1 Magnitude to the highest value possible (1.00). At this point, you should still be able to play a note without any issues.
6. While spamming a note (I spammed C5 on my MIDI keyboard), slowly increase the Decay parameter of LFO 1. I found that past 0.060 (sometimes a bit more), FL Studio will crash.

**Please let us know your surge version**
Latest nightly, VST3 x64

**Desktop (please complete the following information):**
Windows 10 x64, FL Studio 20.6.1 x64.

**Additional details**
FL Studio will freeze, and a single CPU thread will be maxed out 100%. It will then show the "Stopped Responding" window.

**Comment by baconpaul** [comment]
I look forward to debugging this.

Without running or looking at the code or any other such thing, I bet that we are overrunning the pitch table because the note after modulation is longer and we aren’t checking for an upper bound properly. That is we are effectively playing note 2000 or something and running off the end of the array. But that’s just a guess I”m putting on the github here as a record keeper, in case I’m right, in which case, it will seem super smart. If I’m wrong I promise I won’t edit this comment out. Chuckle.

**Comment by VincyZed** [comment]
:D Reading your guess, that would make sense!

**Comment by baconpaul** [comment]
OK in Hosting AU it doesn't crash but it does go super overloaded click mad when I hit decay above that point. Probably an internal NAN crashes FL. let me find out why.

**Comment by baconpaul** [comment]
Alright I was wrong but I don't quite know what it is yet

Something is making a massive DC offset and pushing the onset of the sound out further, just resulting in a click.

Here's the left and right waveform (I think - this is hacked together in the regrets) at delay 0, delay 0.049 and 0.131 or so. As you can see the saw is riding some sort of big DC offset when it starts which does decay away.

I'm not sure why FL crashes when Hosting AU just pops. I'll try in logic and it would be great if some other folks could test too.

But not exactly sure what to do with this one yet. I may leave it be for 1.6.5 since I'm starting to think it may be a 'bigger problem' and I would like to keep the current codebase stabilized. For the next release we may solve this with the [doctor joke](https://www.goodreads.com/quotes/7570350-the-patient-says-doctor-it-hurts-when-i-do-this)

Will see...

<img width="732" alt="Screen Shot 2020-01-26 at 10 00 09 AM" src="https://user-images.githubusercontent.com/13387561/73137143-2c54a800-4023-11ea-9d68-8f0f5b1b403c.png">

<img width="724" alt="Screen Shot 2020-01-26 at 10 00 20 AM" src="https://user-images.githubusercontent.com/13387561/73137145-2c54a800-4023-11ea-98ee-080768ed45d0.png">

<img width="624" alt="Screen Shot 2020-01-26 at 10 00 28 AM" src="https://user-images.githubusercontent.com/13387561/73137144-2c54a800-4023-11ea-8dcc-1e67248a4fe5.png">

**Comment by baconpaul** [comment]
Oh those graphs are wrong by the way ... the delay of the left channel is just an i/o bug (the blue lines are correct).

**Comment by baconpaul** [comment]
OK this patch clearly blows up when the delay gets too high - and that blowup seems to crash FL and glitch out Hosting. Here's the picture on my mac of the waveforms as I go around 0.073 second delay. You can see the sawtooth pushes out and you just end up with a nasty click, at least in the headless simulator. Not sure why i get such awful noise.

But I think there's something pathological about the patch which isn't an internal memory error but is a DSP error. I'm going to push this one out of 1.6.5 for now since I think it's going to be too destabilizing to find whatever limit we are over. Hope that's OK.

![nanPatch_0](https://user-images.githubusercontent.com/13387561/73144029-efae9e00-406e-11ea-9625-cdeaf90b9c41.png)
![nanPatch_1](https://user-images.githubusercontent.com/13387561/73144030-efae9e00-406e-11ea-99cb-ce2a6e03e400.png)
![nanPatch_2](https://user-images.githubusercontent.com/13387561/73144031-efae9e00-406e-11ea-8b2c-c587d7884766.png)
![nanPatch_3](https://user-images.githubusercontent.com/13387561/73144032-efae9e00-406e-11ea-94bf-869df1dc4122.png)
![nanPatch_4](https://user-images.githubusercontent.com/13387561/73144033-efae9e00-406e-11ea-95cc-7d9617abe686.png)

**Comment by VincyZed** [comment]
No worries, this scenario is probably not encountered often anyways.

**Comment by baconpaul** [comment]
Cool. I pushed my regrets stuff with the plotter into master so I can tackle it and not forget it; but I'm gonna leave it alone for the release in 2 weeks.

**Comment by K0rrid0r** [comment]
I'm also encountering something like this now.
![24](https://user-images.githubusercontent.com/56724286/83465953-e185e980-a475-11ea-9289-a9bd9163c741.gif)

here is the preset. just drag up FM depth to max and CPU should max out.
[fm depth fail.zip](https://github.com/surge-synthesizer/surge/files/4714010/fm.depth.fail.zip)

**Comment by baconpaul** [comment]
<img width="868" alt="Screen Shot 2020-06-02 at 8 28 52 AM" src="https://user-images.githubusercontent.com/13387561/83520158-36902280-a4ab-11ea-8bbd-a05b72ecc3b6.png">

So I ran @K0rrid0r 's patch under the profiler on mac and all the time is in osc_sine::process and none of its subs

Something is blowing up there. I'll peek

**Comment by baconpaul** [comment]
I think the Vincey and Korridor things are different but hav ea fix I think to the Korridor one which I will push now.

**Comment by baconpaul** [comment]
<img width="621" alt="Screen Shot 2020-06-02 at 8 44 39 AM" src="https://user-images.githubusercontent.com/13387561/83522898-4f023c00-a4af-11ea-8e0e-d53bbaaf4550.png">

but maybe look there

**Comment by baconpaul** [comment]
That fix was wrong but I think the snap-in-bounds-with-while is the problem

**Comment by VincyZed** [comment]
Fixed by #2017
