### ISSUE TITLE
Audio input cannot be an FM carrier

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge#1530]
**Describe the bug**
We can use VST3 to have a Surge as a proper audio effect in REAPER now Yay!
With this I've noticed a couple things.... First:

Audio Input can be used as modulator but NOT a carrier in the FM routing.
Maybe there is a technical reason for this, but seems like it should be possible?

Testing on:
Surge VST3, Jan27 nightly, REAPER 6.03
Same deal with VST2, and VST3

**To Reproduce**
If Osc 1 is set to audio in, and switch  FM mode 2>1 on. 
FM Depth doesn't effect... anything

If Osc 1 is set to another oscillator (such as sine) Osc 2 is set to audio input, we get modulation of Osc 1 by Osc 2. Change FM mode to 3 > 2 > 1 ... no change, Osc 3  is not effecting Osc 2

**Comment by baconpaul** [comment]
Yeah that’s right. The audio oscillator is a strict pass through right now. I actually found the same thing when using the audio in in my latest disquiet (and also ended up using the audio as a modulator to cool effect)

Fixing this is “hard” because essentially you have to hold the audio input in a buffer then read back the buffer based on the modulator. But definitely on my mind for the future!

**Comment by mortfell** [comment]
Oh ok great. I thought I remembered being able to do this before, but I guess I was confusing it with using Audio input as a modulator.

Having Surge VST3 as a proper audio effect in REAPER is so good!
Thanks for getting around to that.

**Comment by baconpaul** [comment]
You are welcome! We had to change Surge and Reaper both to make it easy!! Pretty neat eh? (There's a way to do it without the change to Reaper but it is a bit clumsy)

**Comment by mortfell** [comment]
yeah very neat!
