### ISSUE TITLE
In non-sandboxed hosts the file selector can be weird on Mac

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1556]
In non-sandboxed hosts the file selector sometimes exhibits problems like not keeping selection or not registering buttons, all of which seem consistent with it running on the wrong thread. Sigh.

I probably need some variant on "performSelectorOnMainThread" placed into UserInteractionsMac

Test is that the SCL dialog in Hosting AU or bitwig single process or what not never ever flakes out when you select the directory dropdown.

**Comment by Jurek-Raben** [comment]
Hi,

this problem appears to be much more massive as I assumed:  If you use the Surge VST2 in Renoise 3.21 macos, disabled the plugin sandboxing, Surge currently can mess up your whole song project, because it might open on a completely wrong fx slot instead. 

<img width="874" alt="Bildschirmfoto 2020-02-29 um 13 25 31" src="https://user-images.githubusercontent.com/239679/75607524-53a60580-5af8-11ea-8413-fea984d743f3.PNG">
Above you see Surge in the very last instrument slot of a song. If I now click "open external editor" of the reverb vst below, the surge GUI actually will appear instead:
<img width="880" alt="Bildschirmfoto 2020-02-29 um 13 25 40" src="https://user-images.githubusercontent.com/239679/75607539-77694b80-5af8-11ea-8548-58d1efeea4ab.PNG">

So now your reverb is jammed by Surge, and the whole track is not outputting anything anymore, because a VSTi does not belong into a VSTfx slot.

**Comment by Jurek-Raben** [comment]
Seems to be caused by the VST2 version only, and not the VST3 one. But I have no proof for this assumption.

**Comment by mkruselj** [comment]
@baconpaul Is this still a thing in XT?

**Comment by baconpaul** [comment]
Nope
