### ISSUE TITLE
Negative and Extended Feedback on Sine and FM2/3 oscs

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1661]
Here's a very neat trick Yamaha did with their FM implementation on Reface DX: the feedback parameter can go negative. What this does is feed back the squared output of the operator back to itself, which creates a square wave-like waveform, instead of the usual sawtooth. @baconpaul Maybe that trick could be retrofitted to FM2 and FM3 and Sine oscs in Surge?

**Comment by baconpaul** [comment]
As mentioned on slack
- clever idea I like it
- requires a streaming change since floats stream as [0,1] so need to do the version trick
- while we are at it, we should make feedback extendible also so you can drive into noise

**Comment by baconpaul** [comment]
Update from slack: If we keep the non extended in [0,1] and make extended something like [-3,3] then no streaming change required.
Would have to think about using the bipolar tray when extended but you know.

**Comment by mkruselj** [comment]
I think [-2,2] should be plenty enough, but lemme test this a bit.

**Comment by baconpaul** [comment]
OK so we decided -4,4 was a good extended range. Here's what you do

1. In Parameter.h in the list of types (ct_blah) add a new type at the end, "ct_oscillatorfeedback"
2. In Parameter.cpp find out where we set up ct_percent( look for the case around line 594) and set up c_osccilatorfeedback similarly
3. Make it extendible. Add ct_oscillatorfeedback to Parameter::can_extend_range in Parameter.cpo
4. Make it string convertible. basically around like 11062 see how ct_percent is converted to string? Do that just use get_extended( f ) instead of f
5. in Parametre:;get_extended(f) make it return -4,4 in extend range (so case ct_oscfeedback return 8 * f - 4
6. In Oscillator.cpp in osc_sine::init_ctrtyles change the Feedback control type from ct_percent to ct_oscfeedback and do so in FM2 and FM3 also

at this point if you compile you should be able to rm extend the feedback slider just fine but the extension will change the stringification but not the actual feedback. So

7. In Oscillator.cpp where the feedback is set (so the FB.newValue around line 8) replace it with something like

FB.newValue( oscdata->p[1].get_extended(local copy[id_fb].v) )

and do similar in FM2/3 where [1] is replaced with index of feedback param

8. Test some manually
9. Extra credit is think about a regtest we could automate but that's pretty hard

**Comment by mkruselj** [comment]
That's line 1062 not line 11062, and line 87 not line 8 :) But yep - great instructions, I have this built locally now!

**Comment by mkruselj** [comment]
By the way, with the extend parameter there is one thing that I noticed - the oscillator waveform doesn't redraw, which is pretty important since differences between the same slider value in normal and extended mode can be quite drastic!

**Comment by baconpaul** [comment]
Find the extend menu operator in surgeguieditor 
In there set the refresh thingy Which is set in other spots
That will force a ui redraw

**Comment by baconpaul** [comment]
Specifically around line 2564 change

```
               addCallbackMenu(contextMenu, Surge::UI::toOSCaseForMenu("Extend Range"),
                               [this, p]() { p->extend_range = !p->extend_range; });
```

to

```
               addCallbackMenu(contextMenu, Surge::UI::toOSCaseForMenu("Extend Range"),
                               [this, p]() { p->extend_range = !p->extend_range; 
                                                  this->synth->refresh_editor=true;});
```

**Comment by mkruselj** [comment]
That worked!

**Comment by baconpaul** [comment]
Great
