### ISSUE TITLE
Pitch Bend Smoothing leads to odd behavior such as Oscillator out of tune after pitch bend

### ISSUE THREAD

**Issue by janifr** [surge-synthesizer/surge#1673]
Oscillators don't always return to neutral pitch after pitch bend. This is more noticeable with higher bend ranges.

Surge version 1.6.6, VST3i 64bit on Windows 10 home 64bit.

I've verified that my controller's bend wheel returns in the middle positon. When pitch error happens last event is  E0 00 40 [Pitch Wheel] chan 1 LSB 0 MSB 64

**Comment by janifr** [comment]
I noticed same kind of behaviour with channel aftertouch. If I release key fast from aftertouch zone some of the AT, which I've routed to OSC 2 tuning, keeps affecting the oscillator frequency.

**Comment by baconpaul** [comment]
Just out of curiosity: is MPE enabled or disabled when you see this?
I don’t suppose you happened to run a session which recorded a midi file that shows the problem did you?
And finally: I wonder (thinking out loud and not trying it since I’m not at my keyboard) if this is because the note off comes before the midi event. I wonder if we are ignoring Pb and at after note off.

**Comment by baconpaul** [comment]
So I just gave it a whirl. Here's a patch which has two sin oscillators and maps the pitchbend modulation source to the pitch of one.

This means when you bend all the way up they are way out of tune. When you release though you head something interesting. The PB slowly returns, in this case resulting in the sin going exactly out of phase for a moment (so dropping to zero signal) before ending up back in tune.

Here's the patch to try

[pbfxp.zip](https://github.com/surge-synthesizer/surge/files/4399603/pbfxp.zip)

Now the reason for this is because pitchbend is attached to a ControllerModulationSource which basically smooths midi controllers over time. When you move your pitch wheel it calls "set_target" on the modulator (in ModulationSource.h)

Then with every block that edges up towards the target

```
 virtual void process_block() override
   {
      float b = fabs(target - output);
      float a = 0.4f * b;
      output = (1 - a) * output + a * target;
   }
```

which means exactly what you say - namely that big bends stay out of tune longer - is exactly what is happening.

Hmm. Now with my sample patch, if I change that code above to just say 'output = target' (which means, basically, that the controller is 'immediate') then the problem goes away, no phase and sound drop. 

@mkruselj also noticed these lags. They exist to smooth things like filter changes bound to midi but I wonder if we want to (somehow) make the optional in a patch.

Lemme change the title here and ponder. Thank you for the bug report.

**Comment by baconpaul** [comment]
(Note there are other lags inside surge which are harder to get to; the mapping of midi controllers to things is easier to fix.)

**Comment by janifr** [comment]
[test_pb.zip](https://github.com/surge-synthesizer/surge/files/4400635/test_pb.zip)

Wow, thank you for very fast responce, I wan'st expecting that.

MPE was not enabled. I've attached results from testing the patch you posted.

**Comment by janifr** [comment]
Is it possible that `virtual bool process_block_until_close(float sigma)` affects this? As bend stays out of tune for a very long time.

I'm just installing Visual studio to see if I can get compiled on my own. I only have experience of Linux tools.

**Comment by baconpaul** [comment]
Nah its just the exponential back off in the process which does it. If you look at the original code, it moves 40% closer every step.

I was actually thinking about this overnight and we probably want the midi controllers to move more in a straight line (so they don’t jump immediately but they do reach their target). I think a formula somewhere between ‘output = target’ and ‘output sneaks up on target’ is the right answer. Probably ‘output linearly approaches target and dOutput changes if you reset target’

So something like

1. Add a `enum Mode` to the ControllerModulationSource of ‘original, linear, direct’
2. When we construct the pitchbend ControllerModulationSource in SurgeSynth set the mode to linear
3. In the ControllerModulationSource setTarget set a dOutput if mode == linear
4. In the ControllerModulationSource process_block do a switch on mode for origina, linear, or direct
5. Add a regtests for ControllerModulationSource in src/headless/UnitTestsMOD.cpp

And then the problem should be fixed.

I put this level of detail in, by the way, since you are installing visual studio. If you wanted to do the above I would love to have you as a contributor to the source! If you get stuck on any steps just let us know here or on our slack.

Oh and the synth works just fine on linux if you prefer that as a development environment. You can run it in Carla, Reaper, Bitwig, etc... (but if you don’t have the VST2SDK you will probably want to run the VST3 in Reaper, which is the best of the VST3 hosts).

**Comment by janifr** [comment]
I think this can be closed.

**Comment by baconpaul** [comment]
Agree. Thanks for your help
