### ISSUE TITLE
FX Presets: Ability to cycle through FX presets on the GUI would be stellar

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#1740]
It would be nice to be able to get at the FX presets some way without having to click on the FX name and then navigate the menu to find the next preset in the list.

Im not sure how you would do that exactly. Increment and Decrement buttons next to the droplist would imply cycling through the FX. AKA next FX in list/previous FX in list.

BUT what I do know is that as Im messing around today with Surge and a project Im finding I want to cycle through FX presets to see if there is one that I really like as a jumping off point.

So Im currently having to pick a preset, listen, then click on the drop list navigate the menu with my mouse to find the same FX and hover to expose that FX’s preset menu.

Nope dont like that one. Rinse and repeat.

**Comment by itsmedavep** [comment]
Per Evil:

> I agree we need prev-next buttons for FX presets!
2:12
alternatively mousewheel above the menu also scrolls through FX presets

**Comment by baconpaul** [comment]
This is a great idea. Easy to do also.

**Comment by baconpaul** [comment]
So turns out the code to jog forward and backwards is pretty easy. I have most of it put together. And the code to respond to a jog button ala patch is also pretty easy. 

But... where to put the jog button

<img width="310" alt="Screen Shot 2020-04-19 at 8 04 37 PM" src="https://user-images.githubusercontent.com/13387561/79703331-1bf64700-8279-11ea-89f5-3d3659e43639.png">

can you take this and put the +/- button in the right place? Then I can code it up really easily. (Irritatingly, mouse wheel is a bit harder but maybe not impossible).

**Comment by itsmedavep** [comment]
Man I figured this would be the hardest part.  Im not sure Im particularly in love with this but here it is. 
![Slice 1](https://user-images.githubusercontent.com/11078351/79707313-b35f9800-8281-11ea-9425-f704a11e6b95.png)

**Comment by tank-trax** [comment]
What about under the presets to the left of Menu?

**Comment by baconpaul** [comment]
OK so a first version of this is headed to the nightly. It has jog buttons but critically it has no label

I'm thinking of putting a tiny label with the preset name right next to the jog buttons. Haven't done that yet so will leave this open.
