### ISSUE TITLE
A Compressor Effect

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#1742]
Generally viewed as helpful.

Here’s our slack conversation just pasted in

![B206D81B-BEB3-4F37-91CC-622F4A6F13F5](https://user-images.githubusercontent.com/13387561/79692962-188d9c00-8236-11ea-9412-e89763b87245.jpeg)

![7869C826-27B4-4FEB-A964-879FB31371E4](https://user-images.githubusercontent.com/13387561/79692958-16c3d880-8236-11ea-99a7-fc49285c0fd7.jpeg)

**Comment by mkruselj** [comment]
Closing this one since we have Airwindows in. :)

**Comment by check-m4te** [comment]
Sorry, but, what's the compressor effect in Airwindows, most similar I could find is the Buttercomp, but it only has this "compress" slider, 
![image](https://github.com/surge-synthesizer/surge/assets/132251469/ee1f4a2d-7d01-4785-a3c4-e38db04cc0db)
is there any compressor with the usual threshold, ratio, etc?

**Comment by Andreya-Autumn** [comment]
No there isn't actually. The Conditioner and the Airwindows comps are all good for their respective niches, but there is no general-purpose compressor in our FX set right now. Which is indeed a weakness. 

We're very swamped with things to do right now. But if someone shows up and wants to do the coding to add a more straightforward comp to Surge, we'd be all for it. Otherwise I wouldn't say it's high on our list right now, since every DAW has a good compressor of this kind nowadays.

**Comment by mkruselj** [comment]
Majority of effects in Airwindows->Dynamics section are compressors.

**Comment by check-m4te** [comment]
> No there isn't actually. The Conditioner and the Airwindows comps are all good for their respective niches, but there is no general-purpose compressor in our FX set right now. Which is indeed a weakness.
> 
> We're very swamped with things to do right now. But if someone shows up and wants to do the coding to add a more straightforward comp to Surge, we'd be all for it. Otherwise I wouldn't say it's high on our todo list, since every DAW has a good compressor of this kind nowadays.

Oh, well. Thanks for the quick reply! I'm really surprised about the support of this great synth. Even tho it's free, and opensource, support is really fast, faster than a lot of paid software. This made my day.
