### ISSUE TITLE
Surge AU not loading Logic 9.1.8 macOS 10.10.5

### ISSUE THREAD

**Issue by paulgreenmusic** [surge-synthesizer/surge#1744]
**Describe the bug**
Does not show up after install in Apple Logic 9.1.8 (64bit). 10.10.5 Yosemite.

Effects are there.

**Please let us know your surge version**
Latest version I downloaded today, I'm new here.

* Surge Version: 
1.6.6 - 2020-02-27 macOS

**Comment by baconpaul** [comment]
Hi!

Woo that's an old version of logic and macOS. In theory we build a plugin which should work with 10.9 but I haven't tested it ever. Happy to offer a few thoughts though

1. When you installed did Logic rebuild the plugin cache? If not would you like to try to get it to do that? I know how to do it in LPX but don't remember in 9 (although I've been a logic user since 7 also!)

2. Can you run commands from the terminal? If so perhaps there's a validation command which might help?

If the effects are there it means something is making surge not load - some library we use which isn't in 10.10 or some such - but I am not quite sure how to debug it.

**Comment by baconpaul** [comment]
Closing - we can’t debug and didn’t hear back from op
