### ISSUE TITLE
Oscillator shows selected wave type for Classic.. 

### ISSUE THREAD

**Issue by sense-amr** [surge-synthesizer/surge#1753]
Not sure if this has been addressed before or infact implemented in the latest versions .. 
but i would wonder if its possible and easy to just add the name of the type of Classic wave selected when using Classic waveform..

eg, Sin / Square .. instead of just "classic" 
also to have a tick .. showing which is selected.. 

This seems to be present for every other waveform selection type other than Classic.. 

![classiclabelandtickplease](https://user-images.githubusercontent.com/1504019/80057267-79381400-8569-11ea-868a-58b829b8b417.jpg)

**Comment by baconpaul** [comment]
The reason it works this way is because Square and Sawtooth aren't waveforms; they are classic presets. So the oscillator is the same for both. 

A checkmark would be great but it's super annoying in CSNapshotMenu. But its on the list so I'm going to close this one as a dup of #726 

I was just in that code recently so let me see if the changes I made to add an FX preset jog make the check mark easier.

**Comment by sense-amr** [comment]
having it show SOMEWHERE which you have selected between square and sawtooth .. would be nice.. instead of having to write it down on a piece of paper and sticky tape it to your wall .. in order to remember which you used..

**Comment by baconpaul** [comment]
yeah i understand. there's all sorts of super tricky, tedious, and annoying problems doing it though, which is why it's been open for a year.
