### ISSUE TITLE
"MIDI learn Parameter ..." not stored

### ISSUE THREAD

**Issue by spurkopf** [surge-synthesizer/surge#1774]
CC-controller can be learned and used, but when the song ist re-opened this settings are gone.
Also impossible to store the learned parameters within a patch.

* Surge Version: Nightliy from 30.04. but didn´t work here with previous versions too
* Plugin type (VST2, 3 or AU) VST2
* Bits (32/64) 64

**Desktop (please complete the following information):**
 - OS: linux - opensuse tumbleweed
 - Host: tracktion waveform
 - Version: 10

**Comment by mkruselj** [comment]
MIDI learn in Surge is global, not per patch.

**Comment by spurkopf** [comment]
Thanks for the information. But it doesn't work globally here either, only temporally. The function in the free 8 controller slots is also overwritten when saving.

**Comment by baconpaul** [comment]
I will look; we do now have daw extra state where we could save this and should indeed do so

**Comment by spurkopf** [comment]
If "Midi learn parameter ..." is global, maybe it should be stored in the settings too.

**Comment by spurkopf** [comment]
Also related: Remember/Save CC mappings #1678

**Comment by baconpaul** [comment]
Not quite sure what evil meant by global but the data structures are pretty clear. I’ll write up the correct solution this morning and add it to the list

Thanks for tagging that other issue - helpful!

**Comment by baconpaul** [comment]
OK now I see what he means.

So all the learn is on the Synth not the SynthUI class, pushed onto storage and the parameters. Parameter has a midictrl which is set around line 1100 of SurgeSynthesizer.cpp in the learn_custom section. Fine.

But it then calls ".save_midi_controllers()". What this does is it writes into the 'snapshot loader' which is basically configuration.xml. When i test with my local build it actually does modify configuration.xml since I am storing it in a writable directory. But that's the wrong place for the data.

On linux default install when configuration.xml is with the factory data in /usr/share the write will silently fail. And on windows using %PROGRAMDATA% rather than %LOCALAPPDATA% it will also fail. Plus a fresh install will blow away your settings. Plus it's the wrong place anyway.

So what we want to do, really, is

1: modify the save and load through snapshot (snapshot == configuration.xml) to also have local-configuration.xml in ~/Documents/Surge as you mentioned spurkopf (with that directory using the OS appropriate user path from the storage obj of course)
2: Add the mappings to the DAW extra storage and have the DAW extra win. This means if you set up routings and save in reaper, when you reload it will work even if the default global settings have changed
3: Allow you to save and restore mappings other than the global default by naming them

Clearly needs addressing before 1.7

The code that does this will also let us save and restore FX presets (or be so close to letting us that it is all the same issue) so let me link up #378 also.

**Comment by baconpaul** [comment]
btw I think this is very similar to #1678 so let me link them.

**Comment by baconpaul** [comment]
I have just pushed a patch to fix this (I am cleaning up all the midi mapping as part of our late summer Surge 1.7 release). The nightly should at least consistently save midi mappings for params and controllers to and from a DAW once the next nightly arrives. When this issue auto-closes the patch is merged. Thanks.
