### ISSUE TITLE
Send latch automation event to host for LFO shape

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1801]
I would like to see it being possible to send host automation signals to change the LFO shapes.
This would lead to --extremly-- advanced signal flow and modulation happening! Very intereting and wanted by me and some friends.

At the moment the change of an LFO shape is not registered by the DAW (in my case FL Studio)

**Describe alternatives you've considered**
Also an alternative and probably also a new issue for itself is to be able to modulate the shape buttoms with internal LFO signals and envelopes but maybe more specifically the Step Seq LFO or the S&H LFO. 

To be able to do that maybe a small buttom needs to be added next to the shapes on the left side, this needs to be discussed if its possible or not and how that would be implemented wisely.

The goal result of this for me is manily -more chaotic and interesting signal flow-

**Comment by mkruselj** [comment]
While this might be useful in certain cases, it would also create lots of trouble down the road if want to add additional modes for the LFO (for example a multisegment envelope, for which we do have a feature request). Adding a new entry to the listbox would throw off any previously written automation because the number of possible states changed.

**Comment by baconpaul** [comment]
nah if you make it an integer parameter you'll be fine Evil. That advertises limits and converts internally. Need to be a wee bit careful but you can do it. (If you made it a float and scaled you would be correct).

**Comment by mkruselj** [comment]
But host automation is _always_ a 0.0 ... 1.0 float, no matter which host you use or how you stringify the parameter value. So yeah you can have your integer parameter, say we have 5 values, and you automate it in your host, when envelope is at 100% you have the 5th value selected. Then at some point down the road you add 5 more values, now that same automation lane is going to select the 10th value because it's still at 100%.

I've seen this happen a number of times in a number of plugins. Doesn't matter if a parameter is represented as float or int on the GUI, when internally it's just a 0...1 32-bit float. Correct me if I'm wrong, but from experience I think I'm right :)

**Comment by baconpaul** [comment]
well au and lv2 have a more reasonable API than that, vst2 does not, vst3 does but i am not sure we using it properly.

So: you are wrong but not completely wrong.

**Comment by mkruselj** [comment]
Ha, ok :)

So you're saying in AU, if you have an integer parameter and you create host automation envelope in Logic, it rescales the envelope if the parameter got a larger range in an update?

**Comment by baconpaul** [comment]
it stores the automation as ints

**Comment by baconpaul** [comment]
(I think; I know for a fact that ardour lv2 does because we have bugs there!)

**Comment by K0rrid0r** [comment]
So i just realized this is actually possible, the option does exist in the parameter automation list, but i didn't know.
![162](https://user-images.githubusercontent.com/56724286/86537406-21b20f00-beef-11ea-9848-54528b5fa357.gif)

The only thing is that it is not fetched by the "Last tweaked parameter" in FL. If we only figure that out this issue can be solved.
Is there some code not being sent to SurgePatch.cpp perhaps?

**Comment by baconpaul** [comment]
This will be the lfo widget not raising the event 

Lemme look but probably not for 170

**Comment by baconpaul** [comment]
Jeez it is 2 lines to raise the event. Merging for 1.7.0

**Comment by baconpaul** [comment]
[p.txt](https://github.com/surge-synthesizer/surge/files/4875650/p.txt)

Here's the patch that's as far as I got but it has problems, Backing out for 170

**Comment by mkruselj** [comment]
> I would like to see it being possible to send host automation signals to change the LFO shapes.
> This would lead to --extremly-- advanced signal flow and modulation happening! Very intereting and wanted by me and some friends.
> 
> At the moment the change of an LFO shape is not registered by the DAW (in my case FL Studio)

By the way @K0rrid0r, host automation of LFO type is definitely already possible, but you need to set it up manually - not by wiggling the parameter on the  GUI, but by picking it from the list of automatable parameters.

So, renaming this issue to be more exact - this issue is about sending a latch event to host when tweaking LFO type on the GUI, so that host automatically creates an automation lane.

**Comment by K0rrid0r** [comment]
i know its possible by finding it in the list of automation options. @baconpaul did try beginedit code to make this list appear in last tweaked menu but it didn't work in FL for some reason, spending more time on this issue would solve it i believe.

that fix showed up in reaper though.

**Comment by baconpaul** [comment]
The reason was it did a rebuild and that blew up mouse drags if I recall
