### ISSUE TITLE
OBS/Xsplit wont show Surge 1.6.6 or nighly build, surge 1.5.2 is visible.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1802]
OBS Studio (version 25.0.4)
https://obsproject.com/sv

It cant record Surge 1.6.6 or the nightly build only the old pre open source Surge 1.5.2

I reckon the problem lies in surge and not OBS, but i might be wrong.

**To Reproduce**
Try to record surge with OBS

**Screenshots**
![strange](https://user-images.githubusercontent.com/56724286/81140425-90afcd80-8f69-11ea-80be-84ba33640136.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - Host [e.g. FL Studio 10]

EDIT: VST3 instance cant be seen either.

**Comment by baconpaul** [comment]
So this is impossible for me to debug because I don't have win 8.1 and everything seems to work ok on mac but...

I think the problem is with surge 1.6 we upgraded to vstgui4 which uses directx / direct2d and I think obs in your config isn't capturing it

https://obsproject.com/mantis/view.php?id=342

that thread seems related.

Hope that helps!

**Comment by K0rrid0r** [comment]
@baconpaul OBS problem solved! I was selecting 'window' instead (which would be easier ofc) of 'capture display'. Now I'm up and running and surge is captured. wierd problem..

**Comment by baconpaul** [comment]
OK great! Thanks.
