### ISSUE TITLE
Adjustable slope for the scene highpass filter

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#1807]
I think it would be good and usefull to add more db slope choices just like in FabFilter-Pro Q 2 or other more advanced eqs.

That is something i usually find myself needing to add in the signalflow after surge in the DAW to do "better mixing" or when i dont need the lowest frequencies because it physically limits the volyme i can have on my speakers, i mean it's super that it goes down to very low hertz, that is let's say "correct". But, mixing and mastering wise it would be wise to have some slopes to choose from in that HP filter already from beginning like:

12 db, 24 db, 48 db, 72 db

The HP is as of now set at 12 db slope and is not good enough for this very purpose, it needs a more hard slopes as a feature to choose from.

**Additional context**
Example from FabFilter Pro-Q 2
![96dbslope](https://user-images.githubusercontent.com/56724286/81222582-c80f9000-8fe4-11ea-8fed-979fa11b66f9.jpg)

Example from EQ 2 in FL studio that will do the same things as fab filter in this setting.
![96dbslope 2](https://user-images.githubusercontent.com/56724286/81222714-04db8700-8fe5-11ea-83af-f95e7b9287fc.jpg)

**Comment by baconpaul** [comment]
Good idea still but gonna knock this out of 1.7

**Comment by mkruselj** [comment]
I did a very quick test by adding new BiquadFilter members to SurgeSynthesizer, it does work. I assume this would be better served with std::vector?

![image](https://user-images.githubusercontent.com/2393720/147709035-988e7ae8-9f1a-469b-b133-b803ff0127e7.png)

![image](https://user-images.githubusercontent.com/2393720/147709041-f4244352-3cc8-441e-90a5-24639aebde81.png)

(This was done only on scene B in order to compare the slope vs regular single HP implementation in scene A.)


Then in order to change the slope I bet we just use deform. 🙂

**Comment by baconpaul** [comment]
there may be a more efficient way but sure good that it works!

**Comment by mkruselj** [comment]
Hence I moved it to XT 1.1 milestone, since it seems quite simple to add without any big restructuring.

**Comment by baconpaul** [comment]
where do we put the slope?

**Comment by mkruselj** [comment]
Right-click menu, below Deactivate option. We could reuse Deform to provide slope options.

**Comment by baconpaul** [comment]
oh yeah cool. then pretty easy indeed!

**Comment by baconpaul** [comment]
so in the 'notes' category

data structure in header is

```
static constexpr int n_hpBQ = 4;
std::array<BiquadFilter, n_hpBQ> hpA, hpB;
```

modify the constructor so rather than `hpA(&storage)` it has `hpA{&storage,&storage,&storage,&storage}` and it should construct just fine

then add the deform using standard param magic and read it

the

```
for (int i=0; i<defvalue; ++i)
{
   hpA[i].process()
}
```

and make sure deform is between 1 and n_hp-1

**Comment by mkruselj** [comment]
That makes it much tidier, thanks!
