### ISSUE TITLE
Retrigger option for step sequencer shift buttons

### ISSUE THREAD

**Issue by ghost** [surge-synthesizer/surge#1821]
Following the discussion this week on Slack regarding host-automation of the LFO-Sequencer grid-position buttons, it occurs too, that a third re-trigger pane option in the sequencer to de/increment those buttons, might also be an interesting option. 

That way moving the grid-position could be self-contained within Surge for creating generative patches. 

Obviously though, host automation would also provide another kind of control. Take or leave as needed.

**Comment by mkruselj** [comment]
This should be a separate lane in the sequencer, where we could have options like: forward, backward, random, first, last.

A great example of this are arpeggiators in certain Waldorf synths, i.e. [Largo](https://waldorfmusic.com/en/104-largo/version-15/309-arpeggiator-8824). The "Chord" option is of no consequence here, but the idea should be clear.

**Comment by baconpaul** [comment]
One thing I was thinking on this

If we are adding DAW automation for the gray buttons (so that is if the gray buttons have names like "Sc A LFO 3 SS Jog Fwd" and "Sc A LFO 3 SS Jog Backwards") as discussed over in #1798 then we don't quite need the feature as @JackyLigon laid out. Rather we can just make the gray buttons *internal modulation targets* using the same rule.

So you go to LFO1 set up a sin wave, go to LFO 2 set up a step sequence, go back to LFO 1, arm it for modulation, click the LFO2 orange arrow and not just the rate and envelope are modulatable bu so are the gray buttons.

Then this isn't 'special'. you can job your step sequence with key tracking if you want.

It's some work - probably more work than I'll do for 1.7beta1 - but wanted to write down the thought;

**Comment by mkruselj** [comment]
Closing this issue in favor of #1798.
