### ISSUE TITLE
LV2 falls back to zoom 100% size when reopening UI

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#1918]
**Describe the bug**
When setting UI zoom scale to over 100% LV2 Surge does fall back to 100% when reopening the UI.

**Please let us know your surge version**
Version: 1.7.nightly.7ac5e76
Built from git 2020-05-21 fetch including submodules

* Surge Version: LV2
* Bits: 64

**To Reproduce**
1. open host
2. add Surge LV2 instrument
3. open Surge LV2 instrument UI
4. set zoom scale to 150%
5. close Surge LV2 instrument UI
6. open Surge LV2 instrument again

**Expected behavior**
Surge LV2 instrument is opened with 150% UI scale

**Screenshots**
Surge LV2 opens with 100% zoom scale.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Host: Carla
 - Version: 2.1.0

**Additional context**
Also tested on Qtractor and the behavior is same but I'm using Carla here as it's quicker to setup for testing. Also nightly VST2 version does not have this issue while LV2 does.

I can compile the LV2 version of the plugin and plot debug print output on demand if needed in case this cannot be reproduced easily.

**Comment by baconpaul** [comment]
This bug is almost definitely going to be the lv2 not saving or restoring the daw extra editor state structure. Another likely in the set Lv2 persistence and streaming problems

Carla has vst3 support I understand. Can you use that? We’ve been working hard to get that working on Linux. There’s a long list of known lv2 bugs and I know that the lv2 guys are working on them - but appreciate the clear report on this one also!

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/7ac5e76ca0479f8066e7ce72ffe9c722db0cf3b1/src/lv2/SurgeLv2Wrapper.cpp#L373

Yeah I looked at the code and the lv2 ignores all the editor state at persistence time. That code just needs to be written! So not even a bug as much as incomplete implementation 

That said some of our lv2 problems are because the lv2 spec is not naturally compatible with surge. The biggest of these is the param change stuff in the other issues but I do wonder if there will be an editor reference issue here.

**Comment by xard-dev** [comment]
For unknown reason Carla currently does not find VST3 instruments even though the UI gives an impression that it supports them.

**Comment by baconpaul** [comment]
I know @tank-trax has made it work - maybe he can shed light?

**Comment by xard-dev** [comment]
However skin changes are persisting as expected in LV2.

**Comment by xard-dev** [comment]
I wouldn't mind having shared zoom level between all instances of Surge stored in shared settings though. This is just my take on this and there might be good use cases to store zoom in instance data.

**Comment by baconpaul** [comment]
We didn't store zoom this way because we have people who set up multi-surge systems with specific zooms.

We do, though, store "default" zoom this way. If you do menu/zoom/set default zoom then your zoom when you make a new surge is set. This will also be the zoom you always get in LV2 because, as I noted above, LV2 doesn't support the editor-extension DAW persistence.

So set your default to 150 and all your surges will be 150. If you then make a session with 6 Lv2s and set them all to 100, when you reopen it then will be 150 again.

(On linux, because of a bug in VSTGUI, the smallest surge is 100%; this is not true in mac and windows).

**Comment by tank-trax** [comment]
Carla's latest build using JUCE6 can detect and load VST3 instruments and effects. You still have to add the paths to VST3 locations and scan those folders.

**Comment by tank-trax** [comment]
@xard-dev you would want to get this version 2.2.0

![Screenshot_20200521_102025](https://user-images.githubusercontent.com/41337033/82568755-4c1d5800-9b4d-11ea-9a51-10c326f7dac1.png)

Add the paths

![Screenshot_20200521_102106](https://user-images.githubusercontent.com/41337033/82568863-6fe09e00-9b4d-11ea-968b-4f3fe8585137.png)

Scan for VST3's

![Screenshot_20200521_102633](https://user-images.githubusercontent.com/41337033/82568952-90105d00-9b4d-11ea-8e69-c5b225299aaa.png)

And then should see something like this...

![Screenshot_20200521_102927](https://user-images.githubusercontent.com/41337033/82569291-07de8780-9b4e-11ea-889e-fbcde53a0f86.png)

![Screenshot_20200521_102402](https://user-images.githubusercontent.com/41337033/82569059-b59d6680-9b4d-11ea-9050-eaf00848795b.png)

**Comment by xard-dev** [comment]
So Carla  2.1.0 was the issue then?
Uh oh... that means Carla sideloading / compilation business then.

**Comment by tank-trax** [comment]
I have experienced this issue with LV2 also using all hosts that support LV2 notably jalv.select

**Comment by baconpaul** [comment]
Closing this issue, since #4030 is the place we are investing in LV2 going forward. If the JUCE/LV2 port works, it works, and the problems in our hand-port will be gone (or replaced with problems in the JUCE/LV2 port).
