### ISSUE TITLE
Phantom hover on mod tabs

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1922]
![image](https://user-images.githubusercontent.com/2393720/82603927-bff24b80-9bb3-11ea-9cfd-e0c51fc30c98.png)

You right click on osc Sync (classic oscillator), LFO 4 gets hovered. Also happens on other sliders close to mod tabs area, different mod tabs get phantom hovered as you right-click on sliders.

**Comment by baconpaul** [comment]
So looking this doesn’t happen on Mac. Will peek when next doing some windows dev

**Comment by baconpaul** [comment]
I bet - bet - this is the same as #2020. That is, after a redraw you get a hover event at the wrong spot.

**Comment by baconpaul** [comment]
Yeah it is. The phantom hover only happens on a rebuild. And it's because we get hover events at bad coordinates, which is what lights up the lfo. To see it you need your menu item to trigger a rebuild (so make a modulation on sync and then clear it and 2 or 3 lights up; and if you change your zoom to 100% it doesn't happen).

If I can fix #2020 it will get this one too. I will leave them both open now but good to know it's just one issue.
