### ISSUE TITLE
MIDI Mappings inconsistently stored when presets swap

### ISSUE THREAD

**Issue by ContemporaryInsanity** [surge-synthesizer/surge#1929]
**Describe the bug**
Flute 2 preset, map Overblow to modwheel using set macro to cc1, works as expected, store, reload (by switching to another preset and back again), mapping gone.
Flute 2 preset, map Overblow to modwheel using midi learn, when modwheel returns to default reverb disappears as modwheel is now also mapped to send fx 1 return.  This then persists without storing after switching to another preset and back again, have to manually unmap cc1 from send fx 1 ret or restart surge to correct.

**Please let us know your surge version**
1.7.nightly.a0bf0b9

**Expected behavior**
Modwheel mapping to persist when switch from and back to patch.
Send fx ret 1 not also mapped when mapping Overblow to modwheel via midi learn.

**Desktop (please complete the following information):**
Linux Mint xfce

**Comment by baconpaul** [comment]
Thanks! This is basically a dup of #1774 and #574 

I just need to fix it properly which means

1. if you set up a mapping it stores with your DAW session
2. if you have a particular mapping you can make it a global default for all patches

Right now #1 doesn't exist and #2 sort of exists in some windows configurations but not really

Those issues were on the 1.7 milestone so let me add this one to that milestone also and then I can close em all at once.

**Comment by baconpaul** [comment]
oh and a bit off topic: if you are playing with flute2 I made a short video on roughly how it works

https://www.youtube.com/watch?v=u7u49V3Loxw

even though I didn't patch it (Claes did) i spent a while reverse engineering it :)

**Comment by baconpaul** [comment]
Oh the FX on midi learn thing is fixed in master. The persistence of the mod is all that's left here. Changing the subject. Thanks!

**Comment by baconpaul** [comment]
I just tested this and think it is all fixed in the nightlies now so will close it. Here is the test I did

1. Start a fresh surge
2. Load Flute2
3. Do RMB on overblow and choose CC1/ModWheel
    (wiggle mod wheel and it moves)
3. Click the patch forward button (to LOW) and the mod wheel still moves control 0
4. Click the patch backward button (back to F2) and the modwheen still moves control 0
5. Open another patch with the menu and the mw still moves c0

So clearly the control mapping sticks with the various changes I made in the nightly.

The second one (learn maps the wrong thing) was fixed last week and was a real bug indeed!

And finally these mapings will all save in your DAW session when you save your track; and these mappings are all exportable as user presets.

So closing. If you find problems with these feature sin the nightly please reopen.

And thans for the clear report.
