### ISSUE TITLE
Phase Management in sin and RM

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2021]
fasten needs -PI < x < PI
so in sin and rm I do things like

```
while( p > PI )
  p -= 2 * PI
```

which works but gets slow in big FM

so bang head against table and do proper mod thing.

**Comment by K0rrid0r** [comment]
So, legacy FM mode still glitches very loud and sounds wrong in latest builds since 'sin -> fastsin' was implemented on May 30. This exist in Both 32/64 bit and is happening at max FM depth, it lags out the CPU so sound cant even be recorded. Legacy FM mode also crashed both FL and MAX/MSP 8 when turned on in certain combinations.

Here is a picture of what the latest build looks like in the waveform when FM Depth is dragged up to max slowly compared to older 'nightly 0c8b7c9' 
![dc](https://user-images.githubusercontent.com/56724286/83652337-ca044900-a5ba-11ea-9116-8023a7567c30.jpg)

I think this change needs to be completely reverted and thought over again if it cant be tweaked to sound right.

The presets above can't even be recorded by Edison in FL because of the nature of CPU lag. Remember to latch them to listen.

In the preset above just drag up FM Depth to max and CPU will lag out
[sin 1+2+3, drag up fm depth to max - CPU test.zip](https://github.com/surge-synthesizer/surge/files/4724149/sin.1%2B2%2B3.drag.up.fm.depth.to.max.-.CPU.test.zip)

In the preset above just drag up FM Depth to max and CPU will lag out, Legacy FM
[sin 1+2+3, drag up fm depth to max - CPU test Legacy Mode.zip](https://github.com/surge-synthesizer/surge/files/4724173/sin.1%2B2%2B3.drag.up.fm.depth.to.max.-.CPU.test.Legacy.Mode.zip)

This preset will CPU lag and probbaly even start with CPU lag when put on and possibly crash the daw even on low FM depth range because the Osc's are in:
Osc 1 is Legacy mode
Osc 2 is Consistent mode
Osc 3 is Consistent mode
[sin 1+2+3 fm depth test x.zip](https://github.com/surge-synthesizer/surge/files/4724269/sin.1%2B2%2B3.fm.depth.test.x.zip)

This is the thing is use surge most for and also appreciate it most for, to do crazy FM stuff that sounds cool!

**Comment by K0rrid0r** [comment]
works! you can close this now!
