### ISSUE TITLE
Typein range issue when assigning modulation sources to Sine oscillator Feedback

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2084]
Surge-NIGHTLY-2020-06-09-47a55f0 | Win-10, VST3i
Typein range issue when assigning modulation sources to Sine oscillator Feedback

The Feedback control without any modulation assignments has a range of from -100 to 100.

When assigning a modulation-source to Feedback, manually adjusting the feedback control shows the slider control to have a range of -2 to 2.

When typing in values, entering 1 will set the modulation range to full, and likewise, typing in 2 sets the range to full.

![LICEcap](https://user-images.githubusercontent.com/66483816/84161029-d2d2a000-aa3c-11ea-8f6d-5dcc388deadf.gif)

**Comment by baconpaul** [comment]
So there's two issues here

1. The scaling (why is it -2/2 rather than -200/200). That's issue #1991. The infrastructure is in place and @mkruselj has said he will do the same here. So then you would RMB and do "132 points" rather than "1.32". (In this case "points" is the unit not "percent" because the modulation is the number of percentage points you are changing by).

2. The value. Why is it -2/2 rather than -1/1. This is because the max modulation range is |max-min| which for a bidirectional percentage is |1 - -1| = 2. This allows a unipolar modulator to span the entire range if you are set at the bottom and isn't a bug (but is a weird thing about the mod sliders where you can drag beyond end in some cases).

![whythetwo](https://user-images.githubusercontent.com/13387561/84169010-1978c800-aa46-11ea-93bd-f57b103ad497.gif)

So since 1 is a dup and 2 is expected, I'm going to close this issue if that's OK.

Thanks!
