### ISSUE TITLE
Activating Unipolar draws the end waveform to positive amplitude instead to zero crossing

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2086]
**Reason?**
It's been like this since 1.5.2, i just checked.

Activating Unipolar draws the end waveform to positive amplitude instead to zero crossing and also puts the waveform in a lower hertz. It should just stay at the same hertz and draw to zero crossing. It's most logical.

Example is at 1.000 Hz.
![53](https://user-images.githubusercontent.com/56724286/84164440-cd904800-aa72-11ea-8db4-2200e2cffc1e.gif)

**Comment by baconpaul** [comment]
the display is showing what the oscillator actually does.  But we could draw it [0,1] rather than [-1,1] I suppose. Worry it would be a bit deceptive.

The frequency looks exactly the same to me. Why do you say it is different hz? It is clearly a different phase (looks like the phase shifts by -PI/2, which makes sense, so the LFO still starts at 0 still) but I still see 6 maxima in the range. Same frequency.

So not sure there's actually anything we want to change here?

**Comment by mkruselj** [comment]
Yeah this is correct display really. Nothing to change.

**Comment by K0rrid0r** [comment]
Really? maybe i don't understand the math involved then. i was wrong about the Hz. ok.

but this is correct?
![correctornot](https://user-images.githubusercontent.com/56724286/84169834-632ed600-aa79-11ea-92bf-4370b55966ec.jpg)

**Comment by baconpaul** [comment]
yeah. those two signals have the same frequency. The second has a phase shift of -PI/2 and an amplitude difference of 2x.

**Comment by K0rrid0r** [comment]
and the reason for the phase shift is?

**Comment by baconpaul** [comment]
so the value of the oscillator starts at 0.

**Comment by baconpaul** [comment]
```
   case ls_sine:
   {
      if (lfo->unipolar.val.b)
      {
         phase += 0.75;
         if (phase > 1.f)
            phase -= 1.f;
      }
   }
```

yeah explicit. (+.75 == -.25 obvs)

**Comment by baconpaul** [comment]
and note in your screenshot, the bipolar doesn't end in the same place it begins. (It starts at 0/increasing and ends at 0/decreasing) so that display is showing 5.5 periods. That means if unipolar starts at 0 / no derivative it will end at 1 / no derivative. Which it does.
So I'm going to close this - don't think there's anything to change here.
