### ISSUE TITLE
Coupled slider deactivation

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2089]
Book of work:

- [x] Phaser: if Count parameter == 1, show Spread as semitransparent (it shouldn't have a Deactivate option, just show as semitransparent because it's non-functional in this case)
- [x] Tape: Deactivate the whole Hysteresis section if right-click on Drive deactivate option is toggled
- [x] Tape: Deactivate the whole Loss section if right-click on Speed deactivate option is toggled
- [x] Tape: Deactivate the whole Degrade section (when it's implemented) if right-click on Amount deactivate option is toggled
- [x] EQ: Deactivating one band should deactivate all 3 sliders pertaining to it

__________

Related mostly to the new parameters in the rotary speaker, but could be useful elsewhere, who knows.

It would be great to have a way to deactivate multiple parameters, while the activate/deactivate toggle is only on one slider. Basically a linked relationship.

This would mean that both Amp related sliders in rotary speaker effect would be semitransparent when drive is deactivated.

**Comment by mkruselj** [comment]
Just adding a related note here based on what @baconpaul said on Discord - the mechanism that is going to be implemented to support this feature request can be reused to do other things, like renaming parameters on the fly based on certain other parameter values (i.e. LFO Phase / Shuffle becomes only Phase or only Shuffle based on LFO type being Step Seq or not).

**Comment by baconpaul** [comment]
Turns out what I said on discord was wrong and we should be a bit more tactical and just do activation as one step.

**Comment by baconpaul** [comment]
So the three use cases to solve here right now are

1: When drive is deactivated in the rotary, so is waveshape
2: When phaser stages != 4 then deactivate some other stuff
3. Pattern to make that at least not tedious

**Comment by mkruselj** [comment]
5. Deactivate LFO rate and phase sliders when in Envelope mode.

**Comment by baconpaul** [comment]
sigh this one is so tricky. I don't know a good way to structure it. Like: I just don't know where to put the logic.

here's the problem. When we deactivate something we set the deactivated to true and rebuild. Fine. 

So at that point we have a param. We need to know the other params to deactivate. How do we know that? Well clearly you would want some data structure adjacent to the parameter where you can ask for 'deactivation buddies'. 

But where do you put that code? That is, where do you put the 'if lfo type == envelope then i have deactivation buddies'? That's a function. There's nowhere natural to put it because that function changes. Like phaser stages != 4 means your deactivation buddies on your FX are different by FX type. But we only know the param not the instance of the FX when we deactivate, and we are on the UI thread, so we can't even safely call methods on the FX necessarily.

So each time I try it I come to the conclusion that this is hard to structure or really hideously hacky and non-local (like you just have a big pile of if statements in SurgeGUIEditor).

Not to mention that you have to add new deactivatable types for all the buddies. 

Harumph. I need to ponder. But again every time I set out to do this one I get stuck, over complicated, or over hacky. Thats why it isn't done yet.

**Comment by baconpaul** [comment]
Oh and:

You can't put that buddies function on param because param doesn't know about other params. It has to be at least at the patch level. But we don't want the patch to know about innards of individual FX etc....

**Comment by mkruselj** [comment]
Can't we abstract the list of deactivation buddies and trigger condition to a separate file like SkinModel or SkinColors that then get referred in SGE?

**Comment by baconpaul** [comment]
It's not static
Parameter 342 has a deactivation buddy if parameter 317 has value phaser but not if value 317 has value delay
where to put those ifs is the question
i will continue to ponder.

**Comment by baconpaul** [comment]
OK so there's loads of pain and complexity here. Basically we want to use something like the automation refresh idle queue to do this from the synth and then do it properly, including gutting all the filter and width deactivation stuff which is a mess in SGE, consolidating all that logic into SurgeSynthesizer, toggling the internal state on the right thread appropriately, and then updating the UI on idle.

**Comment by mkruselj** [comment]
Things that should deactivate jointly:

- [ ] Phaser: if Count parameter == 1, show Spread as semitransparent (it shouldn't have a Deactivate option, just show as semitransparent because it's non-functional in this case)
- [ ] Tape: Deactivate the whole Hysteresis section if right-click on Drive deactivate option is toggled
- [ ] Tape: Deactivate the whole Loss section if right-click on Speed deactivate option is toggled
- [ ] Tape: Deactivate the whole Degrade section (when it's implemented) if right-click on Amount deactivate option is toggled
