### ISSUE TITLE
Modulation Routing Labels Issue

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2111]
Right-clicking on a modulation source, shows the routings to modulation targets.

In the attached GIF, SEQ 1, SEQ 2 and SEQ 3, are modulating each other's parameters, but right-clicking on the modulation slots, shows that the modulation-sources are modulating LFOs rather than SEQs.

Q: For consistency, since a "SEQ" modulation-source indicates a Step-Sequencer, shouldn't the modulation-target label also reflect the actual type of modulator as well?

Likewise in this GIF, S-LFO 1, 2 and 3, modulation sources are are similarly routed to SEQ 1, SEQ 2 and SEQ 3, and right-clicking to see the overview of modulation routings, shows them routed to LFO 1, LFO 2 and LFO 3.

Q: Same as above, for consistency in practical use, shouldn't here also, the modulation-target label also reflect the actual type of modulator as well?
![LICEcap](https://user-images.githubusercontent.com/66483816/84537580-0bcd7780-acbe-11ea-9e6e-b04459e3163c.gif)

**Comment by baconpaul** [comment]
Oh good catch thank you!!

**Comment by baconpaul** [comment]
This is a wee bit tricky because we do this by calling p->get_full_name() which internally gives the VST3 name. So the best plan of attack is 'get_full_name' gets a bool adjust_mod which is false, we set it to true, if its true etc.... you know the drill. So a bit more than a one line change but one we should do for 1.7.0

**Comment by baconpaul** [comment]
Have a fix to this coming in.
