### ISSUE TITLE
Add cents values to Bend Depth ranges in extended mode

### ISSUE THREAD

**Issue by ghost** [surge-synthesizer/surge#2192]
Excerpted from Slack discussion:

Jacky  
Is it possible to make Bend Depth ranges support floating point values?

Negative/positive implications of doing such?

If it were actually possible, and wouldn't interfere with the tuning library implementation, then, instantly, the first part of #2125 could be checked off the list.

![image](https://user-images.githubusercontent.com/66483816/85616719-255eaf80-b62c-11ea-97e3-1172abaf616b.png)

Fantasy implementation of the above, might include Shift + LMB scrolling to specify precise semicents values... 
And or typeins.

baconpaul  
Where they are applied yes; where they are stored i would have to look

And yeah shift to scroll etc....

Don’t want to do it for 170 since I’m really trying to freeze new features but would be happy to look once we are stabilized. From my understanding of the code there is nothing that makes it fundamentally an int inside the synth engine. Can you add an issue?

**Comment by mkruselj** [comment]
Here's a proposal for implementation for @baconpaul (because I tried it in #3073 and failed spectacularly):

Add extended mode for pitch bend range, which would enable both wider range (+/-96 semitones?), AND typing in floats instead of ints.

**Comment by baconpaul** [comment]
gonna knock this one out

**Comment by baconpaul** [comment]
Key insight here
The int vs float is a pain in the butt
But let’s keep it an int and have extended mode
Mean that pitch bend is in cents not keys

so you can’t set sub cent bends

but I also don’t have to rewrite the entire code to do an if on whether you are flost or int stored and fix all the streaming and stuff

I just have ine if and a mul by 0.01

then make the ui have drag edit keys and shift drag edit cents for that mode 

probably still keep it our of xt1 especially since you can just use a formula modulator to do the same thing if you want more or less but will ponder that insight so knock it back in just in case

my primary concern now is the ui and whether we have space to show 13.57 as a bend

**Comment by mkruselj** [comment]
We do have the room to show 13.57. But -13.57 might be a bit tricky, but considering we redesign GUI for XT2 anyways it will be accounted for.

**Comment by baconpaul** [comment]
We don’t actually need to show the - since it is labeled dn 

I can also reduce the font for the decimal part 

So now maybe this does make xt1 or maybe not

want to look at code to decide

**Comment by baconpaul** [comment]
Just took a second to look at the code
Keep it an int and extend it to mean cents is a really easy change I think. Some edge cases with Max and min but totally doable so let me keep this one in xt1 for now.
With this and midi channel and if I finish up the tws port xt1 could accidentally be a pretty good microtonal release as well as everything else!
