### ISSUE TITLE
Abbreviated ModRange for typeins and menus

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2219]
the b < v > b format that @mkruselj is great in the infobox but not in the menus and typein. So add a brief mode and so on.

**Comment by baconpaul** [comment]
So the API is now there. Now to crank through. Said cranking also does a lot of #2141 at the same time, basically

**Comment by Jacky-Ligon** [comment]
**Surge-NIGHTLY-2020-06-27-4ec1fc6 | Windows-10, VST3i | Typein Issues**

**Velocity Modulation to Sine Osc Feedback**
Map Velocity to Sine-osc Feedback; range is 0-100% as expected.
Right-click and typein any value in the range of 0-100% shows Invalid Entry.
Right-click again and Edit Velocity, typein 50, result shows range from 50 to 150%

**Velocity Modulation to Sine Osc Low Cut**
Map Velocity to Sine-Osc Low Cut
Set range to approximately 500 Hz, right-click, typein 500 Hz
Value displayed is 513.750 Hz

**Velocity Modulation to Sine Osc High Cut**
Map Velocity to Sine-Osc High Cut
Set range to approximately 500 Hz, right-click, typein 500 Hz
Value displayed is 25087.711 Hz

**[Q: 25087.711 Hz appears to be the default cutoff frequency for High Cut. Should this be host sample-rate aware, and actually return ½ Nyquist at 48k SR = 24 kHz, and 22,050 Hz at 44.1 SR?]** 



**Keytrack Modulation to Sine Osc Feedback**
Set Feedback to 50%, and set range to approximately 25 – 75%
Right-Click, typein 25, shows Invalid Entry

**Keytrack Modulation to Sine Osc High Cut**
Assign Keytrack to High Cut
Drag slider down to where the rightmost value is approximately 500 Hz.
Right-Click, type in 500, value returned is 25087.711 Hz


**LFO Modulation to Sine Osc Feedback**
Begin with slider at 50%
Assign LFO to Feedback and adjust to approximately 25 – 75%
Right-click, typein 25, returns Invalid Entry

**LFO Modulation to Sine Osc Low Cut**
Assign LFO to modulate Low Cut
Move slider to approximately 500 Hz
RC and typein 500
Value returned is 513.750 Hz

**LFO to Sine Osc High Cut**
Assign LFO to High Cut
Drag slider down to where the rightmost value is approximately 500 Hz.
Right-Click, type in 500, value returned is 25087.711 Hz

Note: SLFO to all of the above, produce the same result.

**Comment by Jacky-Ligon** [comment]
**Surge-NIGHTLY-2020-06-27-4ec1fc6 | Windows-10, VST3i | Typein Issues**

**Modulation Of Mixer Levels Typein Issue**
Pull down Mixer Channel 1 to -inf dB.

Assign a Velocity, ENV, LFO, or SLFO modulation-source to positively modulate the Mixer Channel in from -INF to 0 dB.

As one moves the Mixer channel slider up, the leftmost value shows -INF, and the rightmost 0 dB.

RC on the blue handle and try to type in a new value for the rightmost value shown when setting the modulation initial range, and one will see that it is actually the leftmost value that is displayed for editing, rather than the right.

Try a type in value of -24 dB, and one will observe that the blue handle of the Mixer channel, rather than being set to -24 dB, is rather set to -INF.

In this scenario, it appears that the typein values are inverted, and is not possible to typein a value less than 0 dB without setting the control to -INF.

**Comment by Jacky-Ligon** [comment]
**Surge-NIGHTLY-2020-06-27-4ec1fc6 | Windows-10, VST3i | Typein Issues**

**Filter Modulation Typein Issues**

RC on a Filter handle, type in 500 Hz for the cutoff frequency.

Assign Velocity to positively modulate the cutoff frequency with a range of 500 Hz, to 5000 Hz.

RC on the blue handle, and typein 5000, then RC again to check the value...

Rather than the expected 5000 Hz, 5500 Hz is displayed instead. 

This seems to manifest with all of the other modulation-sources as well.

**Comment by Jacky-Ligon** [comment]
**Surge-NIGHTLY-2020-06-27-4ec1fc6 | Windows-10, VST3i | Typein Issues**

**Send FX and Return FX Modulation Typein Issues**

RC on any Send or Return FX slider, and typein -12 dB to set the initial center value of the control.

Assign a S-LFO to the control for bipolar modulation.

RC on the blue modulation range handle, typein -6 dB, and observe that the blue handle swaps sides of the control center.

RC on the blue modulation range control, and notice that the displayed values show -7.12 ... -18 dB, rather than the expected and specified -18 to -6 dB range.

**Comment by Jacky-Ligon** [comment]
Surge-NIGHTLY-2020-06-27-4ec1fc6 | Windows-10, VST3i | Typein Issues

Output Volume Modulation Typein Issues

RC on Output/Volume control and typein -24 dB to set the center value of the control.

Assign an LFO to the Output/Volume control for bipolar modulation.

RC on the blue modulation range control, and type in -6 dB.

Observe that the blue modulation range handle has swapped sides of the center value control.

RC on the blue modulation range handle, and notice the values are -19.12 ... -30 dB, rather than the expected -30 to -6 dB range.

![image](https://user-images.githubusercontent.com/66483816/85936614-6ffd5780-b8ca-11ea-9b16-0d3e7741cc86.png)

**Comment by mkruselj** [comment]
That one is actually correct, Jacky. You have -24 dB, adding -6 makes it go to -30, but this parameter has non-linear scaling so it cannot be -6 dB range in both directions. So that works as intended.

**Comment by Jacky-Ligon** [comment]
But should probably ask for clarity, if, when dragging the blue modulation handle to the right to set the initial modulation range, then typing in a value, if the blue handle swapping sides of the center value is normal behavior?

**Comment by baconpaul** [comment]
Close in favor of #2229
