### ISSUE TITLE
Modulation not cleared when changing osc type

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2224]
I noticed that modulation is not cleared when you change osc type. You can end up with stuff that doesn't make sense, like slider background gets blue for integer sliders in sine osc which aren't modulatable. 

Maybe in cases when the parameter name is the same when switching from osc type A to osc type B, it should be retained (WT/window morph, skew horizontal or vertical, not sure off-hand if there are any others).

**Comment by Jacky-Ligon** [comment]
Confirmed during beta-testing with:

**Surge-NIGHTLY-2020-06-29-9c42bd3 | Win-10, VST3i**

![LICEcap](https://user-images.githubusercontent.com/66483816/86043434-bfe93500-ba16-11ea-86ac-ebd484f3e21b.gif)

**Comment by baconpaul** [comment]
Oh man this has been there forever, and the fix is deep in a scary bit of code. I may push it out to 1.7.1.

**Comment by baconpaul** [comment]
OK so this is tricky because of one thing. Notes to self.

the switch happens in SurgeSynthesizer::loadOscAlgos and only if queue_type is != -1
queue_type is *not* set on patch load so we could in theory clobber modulation there

it is set by parameter automation - unclear if we want to blow away then
it is set by the snapshot menu - char we do want to blow away then
but also sneakily it set every time you drag and drop a wavetable in.
The first time you drop a wavetable in (so you are in sine and you go to wavetable) you want to reset
but the second time you drag one in it also re-spawns.
So that's where we need to be careful.

**Comment by baconpaul** [comment]
Here's the logic which would mean param automation and menu resets, and wave drop does the right thing

```
bool SurgeSynthesizer::loadOscalgos()
{
   for (int s = 0; s < 2; s++)
   {
      for (int i = 0; i < n_oscs; i++)
      {
         bool resend = false;
         if (storage.getPatch().scene[s].osc[i].queue_type > -1)
         {
            bool reloadMod = true;
            if( storage.getPatch().scene[s].osc[i].type.val.i ==
                storage.getPatch().scene[s].osc[i].queue_type )
            {
               reloadMod = false;
            }
```

**Comment by baconpaul** [comment]
Group decision was to not clear when you daw automate, to avoid breaking saved tracks, even though you can daw automate into a weird state.

**Comment by baconpaul** [comment]
Pushing this to 1.7.n since it is a rare-ish case and a bit tricky to get this late in.
