### ISSUE TITLE
Scene B S-LFO 1-6 can still modulate Scene A/B effect parameters even if it's not suppose to work.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2285]
**Describe the bug**
Scene B S-LFO 1-6 can still modulate Scene A/B effect parameters even if it's not suppose to work according to the manual.

**To Reproduce**
![161](https://user-images.githubusercontent.com/56724286/86521831-fe875100-be55-11ea-86e3-1c2761e3b1bf.gif)
These LFO links wont do anything, still it is possible to do them. Very confusing.

**Expected behavior**
https://surge-synthesizer.github.io/manual/#modulation-routing-in-depth

VST3 hash 75f7bc1

**Comment by baconpaul** [comment]
Oh very good find.

**Comment by K0rrid0r** [comment]
It would be good if we later on could make it work this way though, this seems like a strange limitation. But it is probably deeper then that.

**Comment by baconpaul** [comment]
Yeah
or maybe we don't even fix depending on how deep it is.
Still need to look.

**Comment by mkruselj** [comment]
So wait only scene A SLFOs can modulate FX? Hmmm. Bit of an arbitrary limitation, no?

**Comment by baconpaul** [comment]
Well I think @K0rrid0r 's request is: make the manual, the synth, and the UI do the same thing for 1.7.0; and then we can think about what it is

I think A SLFO should be able to modulate AFX and MasterFX; BSLFO for BFX and MasterFX, myself.

I don't know what the synth actually does

I may ship 1.7.0 with this break in place though, since it feels like it could be a bigger fix

**Comment by baconpaul** [comment]
In my test I was able to modulate A and B fx with both A and B SLFO.
So I'm not sure what's up here?
Gonna push out of 1.7.0 though until I understand it better. If we do need a change from looking at the code it would be a bigger one. But not entirely sure we do.

**Comment by K0rrid0r** [comment]
Let me double check!

**Comment by baconpaul** [comment]
No you are right
The reason is

SurgeSynthesizer::setModulation

uses the parameter->scene as the scene param for the source list

For FX there is no scene so it uses the modlist_global

but the modlist is keyed uniquely on mod source, not on mod source and scene

so mod source 23 gets collapsed in the global routings

and blammo. there's only one LFO.

What we need to do, alas, is key the mod source routings including the source scene

which is painful.

**Comment by K0rrid0r** [comment]
Great find and explanation of the inner working of this!

**Comment by baconpaul** [comment]
yeah it's definitely something fixable. but it's quite a bit of surgery on the innards.

we can fix it for 1.7.1

**Comment by mkruselj** [comment]
@baconpaul ...or 1.7.2? 🙂

**Comment by baconpaul** [comment]
Oh this issue is very similar to the index work I did. If we are mucking with mod internals we should do it in one go

**Comment by mkruselj** [comment]
Oh it will be lovely to see this one fixed!
