### ISSUE TITLE
Unexpected typein behavior when Keytrack modulating the FM3 oscillator M3 Frequency control

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2290]
**Surge-NIGHTLY-2020-07-03-75f7bc1 | Win-10, VST3i**

Unexpected typein behavior when **Keytrack** modulating the **FM3** oscillator **M3** Frequency control

In the attached GIF, observe the typein behavior when setting discrete values for **Edit Value**, and **Edit Keytrack -> M3 Frequency**.

After typing-in the **Edit Keytrack -> M3 Frequency** of 440 Hz, then typing-in the **Edit Value** of 146.667 Hz, the pitch of **Edit Keytrack -> M3 Frequency** is also lowered from its initial setting of 440 Hz to 146.667 Hz, requiring the user to have to type in the **Edit Keytrack -> M3 Frequency** of 440 Hz anew.

Next, for another example, after typing-in the **Edit Keytrack -> M3 Frequency** of 440 Hz, then typing-in the **Edit Value** of 110.000 Hz, the pitch of **Edit Keytrack -> M3 Frequency** is similarly lowered from 440 Hz to 330.000 Hz, again requiring the user to have to type in the **Edit Keytrack -> M3 Frequency** of 440 Hz anew.

The expected, ideal and optimal behavior for configuring Keytrack ranges and frequency offsets, is that typeins of discrete Hz values for **Edit Value** and **Edit Keytrack -> M3 Frequency** should be possible, without changing the initially configured Hz value of **Edit Keytrack -> M3 Frequency**.

![LICEcap](https://user-images.githubusercontent.com/66483816/86540683-28338d00-bed5-11ea-8c31-7620fad80dc8.gif)

**Comment by mkruselj** [comment]
This is not a bug, if I'm understanding correctly. You are editing modulation amounts, not the base value. So you're changing the modulation amount from 440 Hz to 110 Hz or whatever. This is how it should be.

**Comment by baconpaul** [comment]
Right so I am not sure if this is the desired behavior but I’ll explain why it happens

Basically all the frequency sliders are displayed / interpreted in 2^x space but are stored in x space. That is, as you slide from 1 -> 50 you go from 2 -> 2^50

Modulation is the same. When you set a modulation depth if is “x” space. So for the non-linear parameters if you set a modulation to 440 at 440 that is the distance to get to 880, or +1.0. This +1.0 is what is stored

So when you set the value back to 147 the modulation value is still +1.0 which, in this case, stretches you up by 147

Lets assume for a moment that behavior is wrong (I can make both cases of course). Changing this is tricky. It means value changes constantly update modulation depth changes. So if you had +440 at 440 == +1 and you set to 110, then +440 would be +2 (since you need to do 2^x). And as you slide in between the modulation calculation would be constantly changing to keep that constant displayed distance. (It gets even uglier for the dB sliders).

Now that’s not solving your immediate problem. And to be clear the current behavior requires too much “inside the machine” mental model. 

But with that information, curious what folks think the solution is.

That solution won’t be part of 1.7.0 by the way. To do the modulation-changes-as-value-changes would be at least an option and would also be far ranging. The primary reason that we even notice this now is the typeins and displays. Remember it used to just say “440hz” with modulation of “1.0” without units!

**Comment by baconpaul** [comment]
I tagged this “feature request” and “1.7.n” since the answer to this problem (an ‘absolute modulation mode’) is a feature request which I can’t get into 1.7.0.

I think it is good idea also. Just not sure how hard it is

**Comment by Jacky-Ligon** [comment]
By way of explanation and the need for the above:

Surge FM3 Oscillator | M3 Keytrack Ratios

While the M3 modulator is typically used as an absolute frequency modulator with a range of 14 Hz to 25 kHz, it is actually possible to use the Keytrack feature of Surge to specify precise ratios for M3, which can be useful for creating a wide variety of complex FM synthesis timbres.

There are two parameters to configure after assigning the Keytrack modulator to M3 Frequency:

Edit Value: This is the ratio offset value expressed in Hz.

Edit Keytrack -> M3 Frequency: Specifies how the M3 modulator will track the pitch across the MIDI range.


![image](https://user-images.githubusercontent.com/66483816/86541485-5916c080-bedb-11ea-94ec-3bef845200cf.png)

Since the M3 modulator of the Surge FM3 oscillator has a reference frequency of 440 Hz, setting both Edit Value and Edit Keytrack -> M3 Frequency to 440 Hz, will cause M3 to track the pitch at unison with the Carrier.

Use the table below to specify other harmonic or subharmonic offset ratios in Hz for the Edit Value parameter, and set Edit Keytrack to 440 Hz to track the pitch in tune with the carrier.


Harmonic-Subharmonic | Harmonics 			Hz | Subharmonics 			Hz
-- | -- | --
1 | 440.000 | 440.000
2 | 880.000 | 220.000
3 | 1320.000 | 146.667
4 | 1760.000 | 110.000
5 | 2200.000 | 88.000
6 | 2640.000 | 73.333
7 | 3080.000 | 62.857
8 | 3520.000 | 55.000
9 | 3960.000 | 48.889
10 | 4400.000 | 44.000
11 | 4840.000 | 40.000
12 | 5280.000 | 36.667
13 | 5720.000 | 33.846
14 | 6160.000 | 31.429
15 | 6600.000 | 29.333
16 | 7040.000 | 27.500

**Comment by baconpaul** [comment]
yeah interesting - in this specific case you actually want to specify in some (not precisely clear in my head but I’m sure it is clarifiable) concept of ‘harmonics’ not in ‘hz’ it seems.

**Comment by Jacky-Ligon** [comment]
Thanks for the feedback, and don't go to any big trouble about this, as I personally have no problem typing in the values needed to make these offsets, since it is such a powerful synthesis technique, and especially considering that, without this method, none of the Surge FM oscillators can use subharmonic modulators.

Discovering this recently has been like getting a new oscillator in Surge that makes some complete unique new timbre possible.
