### ISSUE TITLE
Hurricane hover effect on buttons

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#2305]
On Linux the new button hover feature looks like

![buton-bad](https://user-images.githubusercontent.com/41337033/86614172-98e3b380-bf80-11ea-8b9a-9d6570d9cc54.png)

whereas it should look like

![button-good](https://user-images.githubusercontent.com/41337033/86614177-9aad7700-bf80-11ea-8266-d452799b351b.png)

Slight variation for vertical sliders

![image](https://user-images.githubusercontent.com/41337033/86614985-d09f2b00-bf81-11ea-992b-311ef9546bd9.png)

**Comment by baconpaul** [comment]
The problem is that dave is drawing around the outer circles with a stroke and my svgs renderer is not capping the stroke path properly

<img width="181" alt="Screen Shot 2020-07-06 at 2 51 44 PM" src="https://user-images.githubusercontent.com/13387561/86628743-5201b800-bf98-11ea-9ad4-d32f4b6675c4.png">

so now I know what to fix.
