### ISSUE TITLE
Global keytrack modulators (lowest/highest/latest note)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2352]
Keyboard tracking is a per-voice thing, however it could very well be extrapolated into a global modulator by offering variations that only track lowest, highest or latest note played from the keyboard. This way, key position (at least in this rudimentary manner) can be used to modulate effects parameters.

The way it could be implemented is similar to release velocity - through a RMB context menu on the mod tab for keytrack.

![keystuff](https://user-images.githubusercontent.com/2393720/87467422-36418600-c618-11ea-97cd-70d934dc04b6.gif)

**Comment by baconpaul** [comment]
So there's two parts to this

Part one is adding that menu and the property. Really easy

Part two is swapping something from a voice modulator to a scene modulator. That is something we don't do anywhere else. The data structures for the modulation are separate and the place in which they are evaluated is separate. In a way you want this to be a 'different modulator' and that modulator is a scene modulator, which is some pretty substantial surgery which is why i've left this here.

but if you follow the way release velocity works, generalize it to more than 'one alternate', have that alternate set of modulators be scene not voice modulators in the Modulator info, it will all work. That's the plan of attack, basically. Don't make keytrack have 4 modes, but have 4 separate modulators ("vkeytrack, skeytrack low, skeytrackhigh, and skeytracklatest") then treat that menu as a modulator swapper and build those modulators properly.

Also you would have to do the work of updating those modulators on keypress and also handle release events. Probably best to just scan the voices when you get a noteon or off but remember to do that in a scene aware way. basically if voice->gate == true are the voices you want.

Also you would need to decide what value the modulator keeps when all notes are off.

So a bit of a tricky one but those are the hints. Lemme know if you need more to start.

**Comment by baconpaul** [comment]
OK so the implementation of the modulators in your branch is correct but the implementation of the alternate state causes all sorts of problems. The reason it causes problems is because SurgeGUIEditor has a member 'mod source' which is used both to indicate the current modulator and also to index into the gui_modsources array so it has to be only for mod sources with buttons. If you naively set mod source to ms_keytracklow then you get a core dump looking at the GUI object; if you leave it set as keytrack you get scene/voice confusion.

So what we need to do is move the 'has an alternate' out of the CModulationSourceButton object (which is transient) and put it as a permanent feature of SurgeGUIEditor (which is long lived). Then go and fix up things. Here's what I would do

1. Remove the alternate stuff from CModulationSource pretty much completely.
2. Add to SurgeGUIEditor the following methods: `hasAlternatesForRootModulationSource( mod source )` `countAlternatesForRootModulationSource( mod source )` `addAlternateForRootModulationSource( mod source, additional mod source, name )`, `selectAlternateForRootModulationSource( mod source, newmodsource )` and `getAlternateForRootModulationSource( ms )` and have the last one return the root modulation source if there are no alternates (so if size of alternates is zero etc...). The data structure you probably want for this is `std::map<int, std::vector<int>>`.
3. Then you go ahead and in the SurgeGUIEditor constructor do things like
    `addAlternateForRootModulationSource( ms_velocity, ms_releasevelocity, "Release Velocity" )`. Do that once there.
4. Then everywhere you were doing cms->hasALternate use these new APIs instead.
5. Then critically in the openOrRecreateEditor everywhere we call synth->isValidModulation( p, ms ) replace that with synth->isValidModulation( p, getAlternateForRootModulationSource( ms ) )

**Comment by mkruselj** [comment]
Current state of feature is at mkruselj/surge-synthesizer/ed-keytrack-mods.

**Comment by mkruselj** [comment]
This is now implemented without modulator alternates, by PR #2674.
