### ISSUE TITLE
Open Sound Control (OSC) support

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2355]
https://en.wikipedia.org/wiki/Open_Sound_Control

This could be a neat thing to add to Surge at whatever point in time... Basically it's a bidirectional network-based protocol with higher parameter resolution (and hierarchically sorted parameter list accessible through URIs rather than integers like in VST...). A number of plugins use it for remote control (see [TouchOSC](https://hexler.net/products/touchosc)), and in Surge it could be used for that as well, but also for controlling the headless (if at any point headless gets live connection to audio/MIDI I/O.

This would enable people to make standalone hardware devices running Surge with a custom control panel and UI/UX, for example. Certainly niche and low priority, but maybe somebody else can also provide some thoughts on how supporting OSC would be useful for them.

**Comment by turian** [comment]
I would like this as it would simplify programming Surge.

**Comment by baconpaul** [comment]
Are you a C++ programmer @turian - if so I can give you hints as to how I would go about it.

**Comment by baconpaul** [comment]
So anyway some comments on this issue finally

1. There's plenty of C++ libraries to be an OSC server. Obviously we want to use one agree.
2. I really wish OSC had taken off. It kinda hasn't (except funnily in logic where it is how the control surface works, and of course in max/pd land and associated live land). I did a bunch of work with OpenFrameworks and OSC a while back and nothing really spoke to it that well.
3. Integrating an OSC server is "easy" - the big questions are what to integrate it with and what the messages are.
4. I don't think you are proposing having a VST3 spin up an independent OSC thread and socket are you @mkruselj? That sounds like a bad idea for a variety of reasons (including getting your DAW very confused when you change a parameter by OSC or having to do the engineering of having OSC send the right begin/end edit message; but also, sockets, threads, network, etc...) so I am reading this as some sort of standalone OSC driven surge renderer.
5. Assuming that's the case then it's 'not that hard'. 

Here's the plan for a standalone OSC renderer which could work

1. Basically you would be "another" headless. So make src/osc-standalone and whack the Cmake and stuff. Just like the JUCE plugins compile with TARGET_JUCE and TARGET_HEADLESS you would compile with TARGET_OSC_STANDALONE and TARGET_HEADLESS

2. Grab a library for cross platform audio out. The right choice is https://github.com/thestk/rtaudio. Submodule it, do the cmake, make it so that your headless spins up and writes to that. First step I would do is copy the midi player code from headless into OSC and make it so `surge-osc-standalone --midi ~/x.mid --audio "PreSonus FireStudio"` or whatever played that midi file with the init patch. We have almost all of this code now - it's just the rtaudio engineering

3. Then pick the right OSC server library. Some research there. It will be one of these four. http://opensoundcontrol.org/guide-osc-libraries. Pick the one that is license and OS compatible. submodulify, cmakeify, spin up the server. So now `surge-osc-standalone --osc-port 23414 --audio "PreSonus FireStudio"` will listen on localhost:23414 for the OSC UDP message

Now you need the messages you are going to receive; and you need something to send them. Thinking about surge I think you want to set up your OSC message hierarchy like this (for clarity I am not expanding the type strings and values, just candidate addresses)

*Playing and Transport*
/surge/transport/set/bpm value  # Needed so temposync works for instance
/surge/transport/get/bpm
/surge/transport/noteon channel note velocity
/surge/transport/noteoff and CC and PitchBend and so on

Fine now you can send OSC notes like midi. Next is parameters

*Setting parameters*

Base all of these off of the streaming name like `a_lfo2_rate` rather than an index.

/surge/param/get-all-params   # returns a list of streaming param names
/surge/param/set/(streaming-name) value  # streaming name like a_lfo2_rate just 
/surge/param/get/(streaming-name)
/surge/param/get-display-name/(streaming-name)
/surge/param/get-display-value/(streaming-name)

*Setting and Getting Modulation*
/surge/modulation/set/source/target value
/surge/modulation/get/source/target 

*Other Mechanics*
/surge/misc/load_patch_by_path
/surge/misc/load_scl_tuning_by_path
and some others I'm sure

That's kinda what you are talking about. Quite a bit of work but not impossible. The callbacks for each of these are really small if you set up the right OSC responding data structures. The trick will be to make your threading correct (like don't handle messages on the audio thread and so on) but that's really a pretty simple 2 thread model also.

Pretty big project in any case.

Finally, even if you are thinking that the plugin should have a separate out-of-DAW OSC attachment (which seems weird) the same address hierarchy as above seems right.

Hope that helps someone!

**Comment by mkruselj** [comment]
>     4. I don't think you are proposing having a VST3 spin up an independent OSC thread and socket are you @mkruselj? That sounds like a bad idea for a variety of reasons (including getting your DAW very confused when you change a parameter by OSC or having to do the engineering of having OSC send the right begin/end edit message; but also, sockets, threads, network, etc...) so I am reading this as some sort of standalone OSC driven surge renderer.

If I'm reading you correctly, you're asking if OSC should work in VST3 flavor. I think it should - Reaktor and Falcon are both examples of plugins where it works. But if this tremendously increases the scale/complexity of the implementation, hmmm...

Maybe it could be done in segments? Get the standalone first, then VST3/AU? Disable it for VST2/LV2 because meh.

**Comment by baconpaul** [comment]
Well what would it do in a plugin? You would have surge bind a socket inside the DAW and listen for messages independent of the DAW? So you can have random other network software change the state of your DAW playback?

That seems .... odd.

**Comment by baconpaul** [comment]
it's not technically that hard. it's just conceptually weird

**Comment by mkruselj** [comment]
That's what those mentioned plugins allow - yes it's separate from host automation and MIDI learn. Just another means of controlling the plugin. Reaktor even allows being receiver only or sender only, or both.

**Comment by baconpaul** [comment]
Huh and that’s usable? Can reaper record so along with midi or some s7ch?

**Comment by mkruselj** [comment]
Yeah sure, OSC sets the parameter externally and you can record the parameter changes into host automation envelopes if you're in touch/latch/write mode.

**Comment by mkruselj** [comment]
Implemented in #6938!!!
