### ISSUE TITLE
UI: Adjust Oscillator Display Alignment

### ISSUE THREAD

**Issue by cyanit** [surge-synthesizer/surge#236]
Im not shure if I brought this up yet, but currently the oscillator display is positioned a few pixels too high (and therefore covering up some of the header). 

I caused this (and can fix this again, if its too hard to do in the code) by changing the graphics, but I think it would look way better if all “cards“ have a uniform header size/style. This may be just me and my “organize everything“ drive, but I think it would be important to tackle bedore using the new UI.

**Comment by baconpaul** [comment]
The reason it is tough to fix in the code is because we want to be able to work with "either" skin for a while and there is no compile time knowledge (and not enough runtime knowledge either) of which skin is on right now. What adjustment needs to happen in the graphics? I would sooner have the new skinning exercise not make code changes about positioning.

**Comment by esaruoho** [comment]
@cyanit @baconpaul @itsmedavep overall, can this ticket be closed? has this been fixed?

**Comment by baconpaul** [comment]
I think for now we could close it and run 1.6.0 with daves vector skin or at least tag it future release but @itsmedavep and @cyanit should discuss. It's a trivial change but I don't want to break the current zooming skin.

I don't think I'll get to dual skin before we print 1.6.

https://github.com/surge-synthesizer/surge/issues/240

that issue is how we would fix it in some imagined 1.7 release.

**Comment by cyanit** [comment]
Abolutly, a stable 1.6 is the goal.

**Comment by itsmedavep** [comment]
@cyanit Thank you!
