### ISSUE TITLE
1.7.0 VST 3 Surge Instrument Does Not Appear in DAW but SurgeEffectsBank Does

### ISSUE THREAD

**Issue by smilinggoat** [surge-synthesizer/surge#2395]
**Describe the bug**
In macOS Mojave the VST 3 Surge instrument does not appear in DAW hosts even though the file exists in /Library/Audio/Plug-Ins/VST3/Surge.vst3 and the SurgeEffectsBank.vst3 does appear and load in hosts.

Tested with both Ableton Live 10 and Adobe Audition 2020.

I initially installed with brew, experienced the issue, then installed via the download DMG but the problem persisted. I attempted restarting after experiencing the issue.

**Please let us know your surge version**
1.7.0

* Surge Version: 1.7.0
* Plugin type: VST 3
* Bits: 64

**To Reproduce**
1. Install normally via brew or DMG
2. Attempt to load plugin in host
3. VST3 version does not show up in plugin list
4. AU version does show up in plugin list
5. VST3 SurgeEffectsBank does show up in plugin list

**Expected behavior**
The instrument should appear in the plugin menu

**Screenshots**
![Screen Shot 2020-07-29 at 17 41 16](https://user-images.githubusercontent.com/569236/88867580-b80de380-d1c2-11ea-8e43-a52c358601b4.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Host: Ableton Live 10, Adobe Audition 2020

**Comment by baconpaul** [comment]
Hi

I fixed this in the nightly install yesterday after other users reported it. The fix for live will be in Surge 1.7.1. Until then your options are use the AU; or install the nightly (https://surge-synthesizer.github.io/nightly).

Turns out Live places an extra signing constraint on your vst3 that no other host does; and our move to cmake and screwed up our no-op signing. But it's fixed in the nightly now. I'll close this but if the nightly doesn't work for you please do re-open it.

Thanks for the clear report!
