### ISSUE TITLE
Expand FX engine with more slots

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2446]
Once the parameter list ordeal is hopefully resolved, we could think about adding more FX slots, like so:

![image](https://user-images.githubusercontent.com/2393720/109390734-a5ec5300-7913-11eb-8000-6e9ac2e4b3e5.png)

I doubt we need more than 2 send FX, but that can be open for discussion.

**Comment by magnetophon** [comment]
Yes, this is great!
4 sends would also be very welcome!

**Comment by mkruselj** [comment]
That creates some UI layout issues, I would much rather keep sends at 2. We need the UI space for other more important params - more filter and osc params, more FX params...)

**Comment by baconpaul** [comment]
So @mkruselj reading this issue: Seems like we are discussing putting 4 new sliders (2 more send levels and 2 more return levels) here. I know how to code those but before I do: Considering we aren't resizing the UI in XT 1.0 where would you put them?

Note if we develop a knob we could answer this question pretty easily. Happy to do so also.

**Comment by mkruselj** [comment]
Same thing as waveshapers. Keep 2 sends for now then add 2 more after XT 1.0?

**Comment by baconpaul** [comment]
yeah i keep running out of sends but i suppose that's the answer.

**Comment by baconpaul** [comment]
I want to take a shot at this one pretty soon. Remind me: Did we want to stay at 2 sends in XT or are we going to split/mouse the sliders or squeeze in a bit more UI space?

We could also go with 4 knobs (and then use knobs for the filters also) as an approach. The knob UI itself is pretty easy the way I have the code set up.

**Comment by mkruselj** [comment]
I'm down with 4 sends, if sliders related to sends 3/4 swap places with 1/2 when you select send FX slot 3 or 4. Should be fine for the time being, let's do any medium to major skin overhauls in XT 2.0?

**Comment by baconpaul** [comment]
OK so merged all the slots but the back 2 sends don't work. Here's my rough plan based on chatting on discord with @mkruselj 

1. Update SceneStorage so that sends goes from [2] to [n_sends] or some such
2. Assign them in surge patch but have 3 and 4 have a special property called 'togglableWith({other-control}).toggleState(false)' or some such and have 1 and 2 have .togglableWith({}).toggleState(true)'
3. Do the same for the return sliders (although we don't need params for them since each return is a param on the FX we may need to assign the params since I think the sends are specially assigned in surge patch)
4. at this point we should be able to load a delay into send 3 and use the automation path to increase the send and return and have it work. If so...
5. Modify SGE to allow
      a. a menu to toggle things in toggle groups and
      b. to have the effect selector do the toggle if you press send 3 and 4 but
      c. have that feature behind a user pref in case you don't want it, but default the pref to true


In XT2.0 have these always displayed as a set of knobs instead. but thats XT2.0
