### ISSUE TITLE
Define font in skin XML

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2464]
Request from KvR. Would be nice to be able to choose different font (+weights, sizes) through skin.xml.

Bonus points for portability by looking for font files within the skin bundle.

**Comment by baconpaul** [comment]
So basically we want a CFont::loadFromTTF( stream &s ) or ( file &) type api
If you look inside CFont there’s an IPlatformFont which is an interface then implemented in platform/(linux|mac|win) so you implement the underside of this 3x.
For windows here’s a start on D2D from a TTF file https://stackoverflow.com/questions/37572961/c-directwrite-load-font-from-file-at-runtime
Don’t know the free type equivalent.

**Comment by baconpaul** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-idwritefactory-createfontfilereference

**Comment by baconpaul** [comment]
https://www.freetype.org/freetype2/docs/tutorial/step1.html

let fontURL = URL(fileURLWithPath: "path/to/font.otf")
let fd = CTFontManagerCreateFontDescriptorsFromURL(fontURL as CFURL) as! [CTFontDescriptor]
let theCTFont = CTFontCreateWithFontDescriptor(fd[0], 12.0, nil)

there's some lin and mac doc.

Maybe I'll take a swing at this.

Would solve many a problem.

**Comment by mvf** [comment]
This issue is independent from TTF loading, so I opened #3002 to track the latter (for Windows only since it blocks portable installs). There should be nothing blocking the implementation on skin engine side. The only caveat is that skins won't be able to rely on a particular font being present or looking a particular way on platforms that don't yet implement TTF file loading.

**Comment by baconpaul** [comment]
So the skin engine would say something like <font I’d=“blah” file=“fonts/blah.ttf”> in the skin xml then resolve that font relative to the skin root. This means basically the skin engine will have a full path to the ttf file and apply it to controls and labels which have a font=“blah” property

The skin property stuff is easy as is setting a font object on a control. The question is given a ttf file how do I make a cfont. Without that I’m stuck.

**Comment by mvf** [comment]
> So the skin engine would say something like <font I’d=“blah” file=“fonts/blah.ttf”>

Why would it do that when VSTGUI already abstracts fonts? Just put `<font family="MyFont">` into `skin.xml` and pass that name straight into `VSTGUI::CFontDesc`. It's then up to the platform-specific backend to provide that font, either from the Surge data path or from the system fonts.

**Comment by baconpaul** [comment]
Well, the reason we want to do that is so a skin author can include a TTF file in their skin directory.

**Comment by baconpaul** [comment]
(and then distribute the skin to people and have it work of course, but figure that part was clear :) )

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/97623934-a7217800-1a26-11eb-96f0-e567d794acd0.png)

**Comment by mvf** [comment]
> [...] it's not the case that we know directories or layouts well or that they have any relation to the location of the dll [...]

Aah, so skins should be loadable from **outside** `SurgeData` or `SurgeUserData`? Okay, that explains where this file based API approach is coming from. We shouldn't resort to this lightly though. If a search path based approach can do it, that seems preferable. Otherwise we could end up having to reimplement parts of each platform's font handling, such as matching fonts within files.

**Comment by baconpaul** [comment]
Right now it will come from data or userdata but those folders can live in a wide variety of locations. And in the future drag n drop skins make a lot of sense too so yeah skins from anywhere is the idea 

I think the thing to do is to check if a skin has a fonts subdir when it is loaded and if so add that to the search path then use system resolution yes. On mac that is super easy to code (its the same code already in runtimefontmac basically just with different path resolution). On windows I guess it is reimplementing a font enumerator and using that. On linux I think it is just modifying that vstgui internal map. 

But lets now make the api the mix of the ones you and I considered which is 

1. A skin can have a subdir fonts/ which is flat and contains ttf files 
2. Those files are loaded and added to font resolution when you load a skin
3. So the family names of those fonts are available to your skin assets 

Then if I put that ugly ttf in fonts I could do <label font=“UgkyTuoist”> and if that family name matches the ttf in skin fonts Dir ttf family we resolve otherwise we fall back

And reload skin should re add ttf and it should be process lifetime only etc 

Agree?

**Comment by baconpaul** [comment]
Oh and if you agree with that api I can code it up on mac and make a font tutorial skin which we can use to test win and lin. If we don’t get the feature done we can just disable it before release but that might help with testing and avoid you having to muck with skin code? Lemme know, super easy to do

**Comment by mkruselj** [comment]
IMHO DnD skins should just copy the file to SurgeUserData and open it from there.

**Comment by baconpaul** [comment]
Why would you do that? We don't do that with DnD anything else?

**Comment by baconpaul** [comment]
But that point doesn't matter. SurgeUserData can live anywhere a user wants and can have skins at any level so we need to deal with relatively arbitrary paths.

**Comment by mvf** [comment]
> Agree?

Yes, this sounds great. Basically an implicit search path Skin→Surge→System. The `skin.xml` part could already be implemented since it won't change anymore. Loading system fonts is a complete, well-defined feature by itself.

As for the API between Surge and VSTGUI, it might be best to postpone committing to that until we have a clear picture how to best cover all platforms. The Windows portable font loading could bring some insight here because it already deals with font paths in the VSTGUI context.

I agree with @mkruselj that skins should be copied to `SurgeUserData` on DnD. At least that would by my expectation coming from browser addons and the likes. But of course this is an independent topic.

**Comment by baconpaul** [comment]
Cool
Alright so why don't I do this

1. Write a tutorial 09 on fonts
2. Add a font directory with some ttf files
3. Make that skin actually use those fonts in a way which references the family name
4. Add a function (somewhere) called "addSearchPathToForFonts". I'll probably add that in SkinFonts.cpp or some such for now but we can always move it.
5. Implement it on macOS and make it std::cerr a warning on win and lin
6. Push

Then the skin.xml will simply say `<label font="WhatNot">` where WhatNot is the family name. And that will render fine when we have implemented the function in #4.

**Comment by baconpaul** [comment]
OK PR #3021 implements exactly this spec on mac

1. It adds a Tutorial 09 skin which has a fonts/ directory containing two distinctive OFL fonts
2. It uses that skin.xml to set the font family on sliders
3. It adds the ability for Sliders to read font family from skin (the other controls will need a similar change)
4. When the fonts/ directory is found it called the newly added addFontSearchPathToSystem in SkinFontLoader.cpp
5. It implements that for mac bu traversing the file and using CoreText to add the font to the process font table

That results in the first two sliders in the oscillator section having a weird font. Here's a screenshot.

On mac and linux it will use default font resolution for the two typefaces and (my guess) come back with Sans Serif or some such.

<img width="238" alt="Screen Shot 2020-10-31 at 3 31 50 PM" src="https://user-images.githubusercontent.com/13387561/97788309-76f4e900-1b8e-11eb-8d14-dc519612cdea.png">

**Comment by baconpaul** [comment]
OK that's merged!

We should decide in the next couple of weeks if it is practical to make the tutorial also work on lin and win. If it is I can add the rest of the family support to the other components and we can go into 18 with it; if it isn't I can back out the tutorial from the 18 release and we can regroup.

**Comment by baconpaul** [comment]
OK per discussion with @mvf I am rolling this to 1.9

I have removed the 'font demo' tutorial skin from the main branch. You can get it back any time by just reverting git transaction 0018f76

**Comment by baconpaul** [comment]
Juce actually makes this super duper easy so pushing back into xt milestone

**Comment by baconpaul** [comment]
Oh I just pushed tutorial skin 10 last night which does this. Closing.
