### ISSUE TITLE
Phaser FX: new Phase control for deterministic output

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/surge#2465]
**Is your feature request related to a problem? Please describe.**
Currently (bleeding edge 2020-08-08 main build), the phaser's internal LFO is continuously progressing, regardless of the position in the performance. This means the output is not deterministic, and consistency might be critical for performance takes.

**Describe the solution you'd like**
A means of controlling the phaser's LFO phase, to be consistent. This can happen by:
(1) Setting an LFO frequency of 0
(2) Having a new **Phase offset** parameter in the phaser, which can be externally modulated by a (preferably _unipolar_) LFO.
(3) Consider implementing this feature also in the flanger FX - [from EvilDragon - Slack](https://surgesynth.slack.com/archives/CF6NVE4RW/p1596921838149300).

**Describe alternatives you've considered**
.

**Additional context**
An observation that might result in this issue being ignorable:
* If I restart a live performance in my DAW, the phase is not reset and continues. This is the situation that led me to create this FR issue.
* If I export the performance from the DAW, the phase is reset (screenshot shows three exports, which all start with the same phaser LFO phase).

![image](https://user-images.githubusercontent.com/13245475/89720211-b795f980-d9c7-11ea-8707-f0a9c512479a.png)

**Comment by baconpaul** [comment]
So this one is slightly tricky because the ringout can continue after transport. But it's not impossible at all. The LFOModulationSource already does it (but the LFOModulationSource has far cleaner trigger semantics).

SurgeStorage contains a songpos variable which is the transport position in ppq. So we could, when we start an effect, calculate the song position and phase based on that.

The trick is gonna be with continuing to accumulate phase. We obviously need to do it in ringouts which may occur absent transport. 

The phaser has a short ringout so probably restarts a lot. Other effects not so much (for instance the flanger has a very long ringout since feedback can make it self-oscillate).

**Comment by j5v** [comment]
**Phase offset** is perhaps a poor choice of name. If this goes ahead, we should review of the UI label.

**Comment by j5v** [comment]
> (but the LFOModulationSource has far cleaner trigger semantics)
That's part of my reasoning behind choosing an LFO to manually drive the phaser's LFO, but is **trigger mode: freerun** inviting the original problem? Is there a new LFO **trigger mode** waiting to be implemented?

**Comment by baconpaul** [comment]
Free run on an SLFO will follow the song transport (or should)

**Comment by mkruselj** [comment]
So with a bit of coding magic this is now possible, @j5v (after the above PR is merged)! Happy days! 🙂
