### ISSUE TITLE
MSEG book of work

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#2474]
**PSA: This issue is now locked for conversation, due to the friendly reason of us using it as a book of work. For suggestions please open a new issue, or better - hop on our Discord if you want to discuss MSEG-related things!**

- [ ] Outright bugs
   - [x] We can still drag+extend a node past the current zoom/pan limit of 128 phase units. Restrict that to 128 phase units
   - [x] Actions / DoubleSize can go well beyond 128 phase units also
   - [x] hidden drags in the axis area (loop markers, pans, etc...) when the mouse 'moves' into the draw area triggers hovers
   - [x] Dragging loop start past loop end (and vice versa) is still buggy when reaching the first or last segment of MSEG
   - [x] Dragging loop end past MSEG end wraps around weirdly
   - [x] Start marker can be dragged past start
   - [x] This hover segment is drawn weirdly:

![image](https://user-images.githubusercontent.com/2393720/102557031-8d1d2100-40ca-11eb-8c82-98bb8d1f4443.png)

- [ ] Editor Features
   - [x] Movement mode should be global for all MSEGs
   - [x] Currently in Draw mode, LMB and button3 drag all do the same thing. We should make it so that LMB does what it does now ("draw"), but button3 drag should do the 4D zoom/pan. (BP Note: I will do this for shift button and code it for button 3 but will need a windows user to test button3)

**Comment by K0rrid0r** [comment]
here comes the first preset to analyze.
something if blowing up my CPU to 99% when mseg on S-LFO 3 is turned on. 

[mseg S-LFO 3 CPU overload.zip](https://github.com/surge-synthesizer/surge/files/5066532/mseg.S-LFO.3.CPU.overload.zip)

**Comment by K0rrid0r** [comment]
other things ive found so far.

Mseg cant be copied from an LFO to another LFO.
Mseg goes beyond -1 1 in LFO draw.
Mseg nodes can be dragged way outside of the edit spectrum in the mseg and cant be brought back if needed.
Only LFO1 is showing the init mseg sequence. (Clever solution needs to be discussed/is needed here).

**Comment by mkruselj** [comment]
- add nodes via double-click and remove via right click on the node
- adjustable vertical and horizontal grid snapping (adjustable number of steps)
- zoomable and scrollable viewport
- ruler showing seconds or beats
- editing modes for moving nodes: ripple (moving a node moves all nodes after it), lock (constrains node movement between left and right neighbor), freehand (fixed node timing, mouse drag over nodes adjusts their amplitude only)
- adjusting loop start/end
- disabling loop
- editing in the main LFO view: should be able to move, add and remove nodes, change curve and curve type, change loop points and disable loop (RMB context), at the very least
- MSEG preset save/load

**Comment by mkruselj** [comment]
Bug: right node of a segment can be moved past the left node of a segment, making the segment go away.

**Comment by Jacky-Ligon** [comment]
Really looking forward to this enhancement, and have little to offer beyond what everyone has collectively stated as the primary features.

For what it may be worth, among the better implementations of MSEGs in virtual-instruments used here, are in U-He's Zebra-2 and Zebra-HZ, the Xfer's Serum.

Of these two developers, in many ways, the Z/ZHZ MSEGs offer many deeper options, such as being able to set arbitrary metrical lengths, but with Serum, there is the recent enhancement of being able to assign modulation-sources to the nodes for creating some quite complex modulations overall. 

I see that Korridor has suggested that, and I'll add my voice to that issue as well, since it seems to be in general accord with the ability to modulate modulation sources.

One thing I really liked in reading through the above feature suggestions, is the ability to save modulation-source presets. Surge really needs this for all modulation-source types, and in agreement, this will be particularly useful for the MSEGs, and as above, with Z/ZHZ and Serum, it is a matter of routine to archive these modulation-source presets for later use as starting points to speed-up sound-design tasks.

All to preface asking about modulation-source presets, is where in the user data is it proposed they will be stored?

One small suggestion I might offer, is to write all of the presets into modulation-source specific directories to clearly delineate them in the data directories.

LFO: Sine, Triangle, Square, Saw, Noise S&H
Envelope
Step Sequencer
MSEGs

Saving them into modulation-specific directories, according to modulation type, would make them easier to save, load and manage from these directories, as opposed to just writing everything into one modulation-source directory.

[Related aside, is that I really wish we could do the same for FX settings: a separate directory for each FX type.]

**Comment by K0rrid0r** [comment]
Just putting this one here as i dont know if this has been worked out yet or not.

Edited MSEG dont copy edited MSEG state to next LFO in the edited way, it's only copying init state.

![edited MSEG dont copy edited MSEG state to next LFO](https://user-images.githubusercontent.com/56724286/90542134-f2e0b700-e183-11ea-9ab8-fe65aae722e6.gif)

**Comment by K0rrid0r** [comment]
Edit button text increases when you only click on a slider and decreases back to normal size when you drag a slider

![Edit button text increases when you only click on a slider and decreases when you drag a slider](https://user-images.githubusercontent.com/56724286/90543357-db0a3280-e185-11ea-84ed-3e295638ff9a.gif)

**Comment by K0rrid0r** [comment]
Initializing "Edit Both" and draging last node to beginning of Mseg crashes daw (in this case FL)

![draging last node to begining of mseg crashes at least FL](https://user-images.githubusercontent.com/56724286/90543869-8b783680-e186-11ea-8f36-af8e65592d1a.gif)

**Comment by mkruselj** [comment]
- [ ] Duplicate Rate, Phase, Amplitude and Deform sliders in the big popup to speed up editing.

**Comment by K0rrid0r** [comment]
![getting SnH like brezier curve by draging mouse off screen](https://user-images.githubusercontent.com/56724286/91782063-61019100-ebfc-11ea-8153-78798e20dda2.gif)

Got S&H like curve by draging mouse way outside MSEG while still holding down mouse button.

**Comment by baconpaul** [comment]
Wow can you trap one in that state and save it as a patch for me? Wonder where I’m accidentally truncating!

**Comment by baconpaul** [comment]
Also when it gets in that state, if you close the editor does the LFO show the steps?

I can't for the life of me see where it would truncate and it doesn't on my mac so a patch trapped at that point would be super helpful.

**Comment by K0rrid0r** [comment]
[MSEG cool rounding brezier bug.zip](https://github.com/surge-synthesizer/surge/files/5153517/MSEG.cool.rounding.brezier.bug.zip)

here you go!

**Comment by baconpaul** [comment]
Oh thanks. That craps out differently on mac but definitely craps out. lemme look.

**Comment by baconpaul** [comment]
Found it. Doing a push along with scurves now.

**Comment by K0rrid0r** [comment]
![repaint bug](https://user-images.githubusercontent.com/56724286/92012074-44746e80-ed4c-11ea-9ba8-0da363c55e6f.gif)

baconpaul 18:39
we are invalidating part of the UI when we repaint
even if it is covered

**Comment by Jacky-Ligon** [comment]
@baconpaul 

Will there eventually be both x and y grid snapping, and if so, will the vertical snapping of nodes - when routed to Oscillator and Scene Pitch - be 'SCL-aware' in the manner of the Step Sequencers, or is this sort of implementation completely outside of the initial concept?

Testing it a little just now with: **Surge-NIGHTLY-2020-09-02-d02262f, Win-10 Pro, x64, VST3i**, and unless missing a detail, vertical snapping doesn't appear to be possible as of yet.

**Comment by mkruselj** [comment]
Snapping is in the list in the first post of the issue. 🙂 It will happen and it will also have custom number of steps (like in Massive X).

**Comment by Jacky-Ligon** [comment]
Is there any limit to the number of custom vertical steps?

Where already Surge has gone beyond Serum in the SEQ/MSEG area, is that Serum is limited to only 16 vertical steps, which severely limits its capabilities with using it for pitch-sequencing.

**Comment by K0rrid0r** [comment]
MSEG 2 clips MSEG 1 deform
[MSEG 2 clips MSEG 1 deform.zip](https://github.com/surge-synthesizer/surge/files/5164963/MSEG.2.clips.MSEG.1.deform.zip)

hint: setting the amplitude on MSEG to 20% will not clip. setting it to 21% will start the clipping

**Comment by mkruselj** [comment]
> Is there any limit to the number of custom vertical steps in Massive X?

24.

**Comment by mkruselj** [comment]
Moved checkboxes from #2563:

- [ ] Defaulting the control point value should be done with Ctrl+click on the control point. Although Ctrl+click anywhere in the valid segment would also work, but we should save it in case we need Ctrl+drag on segment for something later on.
- [ ] Add Deformable toggle in RMB context (enabled by default for all segments), which allows any segment to stay free from being affected by the Deform slider. The non-deformable segments should have a different curve color. We should also have a keyboard shortcut for this, say Alt+click anywhere in the segment to do that.
- [x] Double click on a node removes it
- [ ] Nudge the MSEG Editor down so that it doesn't cover category/patch prev-next buttons (in fact the MSEG Editor header could also be thinner in height)
- [ ] Reduce the height of MSEG editor (now that we made it modeless so we won't repeat all those sliders and buttons etc.) so that rows 2 and 3 of modbuttons can always be seen, enabling switching between different MSEGs easily and swiftly
- [ ] Related to above, if we switch from one LFO to another and that new LFO isn't of MSEG type, close MSEG editor, otherwise update MSEG with that LFO's data
- [ ] Mousewheel on V/H snap numberfields (maximum value 100 steps)
- [ ] Changing the number of snap levels should update the grid
- [ ] Thinning of gridlines and axis labels needs to be done when there's too many of them
- [ ] The node still behaves as two separate points w.r.t. RMB context menu. If you click on the left side of the node and change curve type, preceeding segment changes, if you click on the right side of the node and change curve type, following segment changes. It would be great if, when right-clicking the node, all changes apply to the _following_ segment always
- [ ] The actual window of MSEG should be styled the same as miniedit - Surge logo in top left, same titlebar height, same roundrect radius for Close button (and skin colors for all that)

**Comment by mkruselj** [comment]
Bug: if MSEG editor is opened, clicking on Edit button again makes it uncloseable (until you choose another LFO, that is).

**Comment by VincyZed** [comment]
- [ ] Ctrl + Left-click on a point would delete it, like double-clicking does. Ctrl + Left-click-Drag could delete other points you drag over in one motion. Exactly how it works in the Step Sequencer, actually.

**Comment by mkruselj** [comment]
- [ ] Bug: Double clicking outside of MSEG area (axis ruler etc.) actually generates a node out of bounds.

**Comment by mkruselj** [comment]
- [ ] Let's change MSEG snapping text edit fields to CNumberFields! Later on we can add typein functionality to CNF.

**Comment by mkruselj** [comment]
Here's assets for classic and dark skin for MSEG edit button (off-on states and hovers):

[LFO MSEG Edit assets.zip](https://github.com/surge-synthesizer/surge/files/5379173/LFO.MSEG.Edit.assets.zip)

**Comment by mkruselj** [comment]
Path drawing bug with neighbouring Beziers:

![path draw bug mseg](https://user-images.githubusercontent.com/2393720/98020752-b710d180-1e03-11eb-806f-cec36b46421e.gif)

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/98451581-5e18a480-2147-11eb-9c48-822f14b7996b.png)

When panning, gridlines shouldn't be visible beyond the vertical axis.

**Comment by mkruselj** [comment]
- [ ] The longer the MSEG is, the slower panning becomes. It should probably scale with the length of the MSEG so that the speed of panning is constant.

![panspeed](https://user-images.githubusercontent.com/2393720/98790775-779a4480-2404-11eb-8253-25681e5a9b64.gif)
