### ISSUE TITLE
Patch Changes with no Audio Engine silently do nothing. Warn instead.

### ISSUE THREAD

**Issue by MichaelH60** [surge-synthesizer/surge#2479]
Hello, I have a new Laptop with WIN 10, Ableton Live 10 Lite (10.1.18).

I installed the latest version of Surge 64 Bit for Windows in the given folder. Then I started Live an the Surge. klicked on the Patch Browser. All the categories showed up. But when I choose a patch, nothing happend,

So I (tried to) uninstall it, but got a error message about Surge.VST3. I looked for this data and deleted it manually. After that I made a new installation. Same problem,

Any idea?

**Comment by baconpaul** [comment]
On possible cause is that you don't have audio engine running in your DAW. The patch change requires a process block and a process block requires an audio engine.

If when you open surge and you click 'latch' do you get sound? If not then that's the problem and you'll need to do (whatever you do in live on windows to start the audio engine).

If, though, clicking latch gives you a sound and patches still don't change it is something else.

**Comment by MichaelH60** [comment]
Hi Paul, you are right. Ich tried without my audio interface. 

Now it works. Thanks a lot.

**Comment by baconpaul** [comment]
Great.

I'm going to repurpose this issue with a new title so I can remember to show some sort of warning if you are in this situation (like if the audio block isn't running and you change a patch it shows something in the UI). We can add that in 1.7 family sometime. You aren't the first person to hit this!

Thanks!

**Comment by j5v** [comment]
This explains a strange behaviour I made note of last week. I frequently have to switch off the DAW's audio engine, because ASIO greedily takes exclusive control of my sound hardware, and I need to release it to hear any refs outside my DAW.

**Comment by mkruselj** [comment]
You wouldn't need to do that if you had an audio interface with a proper multi-client ASIO driver. 🙂

**Comment by baconpaul** [comment]
@mkruselj you should try CoreAudio! You don't even have to worry about drivers :)

But the point is: this bug has hit us enough that we should detect if we are in that state and change the UI somehow.

**Comment by mkruselj** [comment]
My suggestion would be just an 80% opaque black rectangle covering the whole UI with a message that audio engine isn't running and that Surge is in limbo as a consequence. :)

**Comment by K0rrid0r** [comment]
@j5v after i installed FL 20 i got another asio instance running together with my ASIO4ALL 

it has literally saved my life.... if you understand what i mean. no more switching on and off.

**Comment by baconpaul** [comment]
How do I turn off the engine in windows reaper?

**Comment by j5v** [comment]
> My suggestion would be just an 80% opaque black rectangle covering the whole UI with a message that audio engine isn't running and that Surge is in limbo as a consequence. :)

1. Maybe only do that if the engine has been unavailable for a few seconds.

If we don't allow a little time, it might be annoying for a user, to be actively doing something with the UI, then it blacks out, and causes glitchy behaviour, all because of short downtime that might not have caused any trouble in the first place.

Your mileage may vary, but I've found that when the audio engine reconnects, the messages were buffered and were sent when the interface was available again. So it might not be necessary to freeze out the interface entirely. Might be better to light up an amber light near the menu/logo.

Also, being too ready to switch in-out of blackout would put more strain on a resource-starved system (which is the likely scenario).

2. Consider whether UI interactions would be broken, e.g. would the plugin receive a mouse-down (before blackout), but never receive the corresponding mouse-up, because of the blackout?

**Comment by baconpaul** [comment]
Sure easy to require it to be off for 250 idles or some such. That’s a good idea

**Comment by baconpaul** [comment]
But to test this I need to know how to turn the engine off in reaper on windows

**Comment by mkruselj** [comment]
In Preferences>Audio>Playback there's an option to run FX when stopped which is usually enabled, try disabling it.

**Comment by baconpaul** [comment]
sigh of course reaper still processes my samples on mac when i set my output device to none because core audio is running. Similarly on linux reaper has a dummy output if jack is off and bitwig sends to jack even if there's no endpoint.

So I guess I need to understand how windows reaper can end up without a audio driver or something? Or I could just wing it. But this seems like a problem that will only occur on windows systems without an audio setup, which i can't produce on mac or linux.

Evil - can you come up with a windows configuration which demonstrates problem? If so I can use that to dev a fix.

**Comment by baconpaul** [comment]
Oh I don't need to turn off the audio system. I can just hack a 'return' into process on my mac and it makes it like windows.

So have a fix for this. Basically if you load a patch with the menu and it hasn't loaded within 30 idles, you pop an error saying turn on your audio system.
