### ISSUE TITLE
Oscillator FM Routing | Configuring, Saving and Restoring Oscillator Frequency Ratios

### ISSUE THREAD

**Issue by Jacky-Ligon** [surge-synthesizer/surge#2506]
**Surge-NIGHTLY-2020-08-21-4988da1 | Win-10 Pro x64, VST3i**

What follows is a broader reframing of FM concepts proposed in the closed issue #2051, which are also tangentially related to the open #2363, and extrapolating them here to be applied for all oscillator types.

**Parallel Routing of Oscillator FM Routing and Oscillator Mixer Signals**
Among the interesting possibilities for sound-design with Surge 1.7.1, are using the basic algorithms in the **Oscillator FM Routing** section and the **FM Depth** control to create a **_blend_** of an FM timbral layer that can be routed in parallel with signals from the **Oscillator Mixer**. 

**The interaction of the Oscillator Edit Value Pitch Offsets with SCL Scale Size**
Usually in the Surge sound-designs here, patches are designed initially to be played in **12-tone-equal-temperament**, and user selected microtunings of arbitrary size can be freely loaded to change to other intonation systems as required of the musical scenario at hand.

With 12-tone-equal-temperament as the starting point for patch sound-designs, one can, using **semicents** (semitones and cents floats) typeins, easily configure the three Surge oscillators in a Scene and routed to the Oscillator FM Routing section (one Carrier and two Modulators), to arbitrary offset intervals such as (quasi) sub/harmonic ratios.

However, there is an unfortunate showstopping rub whenever new SCL-KBM microtuning combinations are loaded that feature scale sizes other than 12, where the carefully configured ratio offsets are rescaled and displaced to other intervals according to the SCL scale size.

**A proposed solution for Oscillator Pitch Edit Value Offsets in FM configurations**
So that **Edit Value** configured semicents FM ratios are not displaced when loading other SCL-KBM microtuning combinations with scale sizes that are < or > 12, it is proposed here to add an **Oscillator Pitch Edit Value** context menu option to **‘Edit Value - Ignore SCL Size’**.

Adding this simple Oscillator Pitch context menu **‘Edit Value - Ignore SCL Size’** feature would immediately make it possible to create a vast range of new FM timbres with Surge, and would completely remove the complexity of having to recalculate new FM ratio typein values for arbitrary SCL scale sizes.

![image](https://user-images.githubusercontent.com/66483816/90956400-4721ba80-e454-11ea-8182-71439bb3ace9.png)

**A Related FM Issue: Oscillator FM Routing and independent FM Depth modulation**
Stating the obvious, in addition to the above feature-request, is that at some point in the future, it would also be extremely useful to evolve the **Oscillator FM Routing** section such that users could independently modulate the index, or C and M ‘Amount/Depth’.

As we know, currently ‘FM Depth’ modulates them all at once, which can be used, as above, for a basic FM timbre layer, but for more deeply refined and expressive FM timbres to be possible, being able to route modulation-sources to C-Amount/Depth, M1-Amount/Depth and M2-Amount/Depth would be a powerful enhancement.

Already aware here that there is an existing issue on this topic (with a unique perspective), and that an FM matrix design has been considered, and with the latter matrix concept, FM synthesis in Surge could move far beyond the basic algorithms that are currently available. 

Consolidating everything in this issue here for consideration and discussion.

**Sub/Harmonic pitch offset units for Sine oscillators #2051**

**FM2 and FM3 Oscillators | Subharmonic and Harmonic Ratio Input #2363**

**"FM mode" for mixer section #1031**

**Comment by Jacky-Ligon** [comment]
To better understand this somewhat complex pitch-transposition and musical intonation issue, what follows are some observations and Surge presets to illustrate and illuminate the topic. 

Here though, for simplicity of discussion, let's completely remove FM synthesis from the equation, and focus singularly on:

1. The behaviors of **_the two_** typical methods for configuring oscillator pitch-transpositions.
2. The interactions of these two pitch transposition methods when SCL-KBM microtuning table files of arbitrary size are loaded.
3. And finally, **the implications of the above for all presets in the Surge patch library that feature oscillator pitch offsets**.

**Part 1 | The interaction of oscillator octave transpositions with SCL-KBM microtunings**

Attached here is a ZIP archive containing a Surge preset labeled, **3-Sine Oscillators - Octave Transposition.fxp**, which features:

1. Three Sine Oscillators routed to the Oscillator Mixer.
2. Only the Oscillator Mixer Channel for Oscillator 2 is active.
3. Using the Oscillator's Octave Transposition switches, Oscillator 2 is transposed up +1 (one 'octave', AKA, the pitch is multiplied by harmonic 2).

[3-Sine Oscillators - Octave Transposition.zip](https://github.com/surge-synthesizer/surge/files/5114591/3-Sine.Oscillators.-.Octave.Transposition.zip)

![image](https://user-images.githubusercontent.com/66483816/90985090-91d02f00-e547-11ea-803a-22e9b8e8caa8.png)

To observe the behavior and interaction of loading different SCL microtuning table files with this +1 Oscillator Octave Transposition:

1. First load the above preset, **3-Sine Oscillators - Octave Transposition.fxp**, into Surge 
2. Next, place a **musical instrument tuner** after Surge and put the tuner in its **Hz** readout mode to make pitch measurements in terms of frequencies. 
3. Open the **Surge Tuning-Library** directory: Right-Click on the **TUNE** button (top right of UI), choose, **Factory Tuning Library**, the access the **SCL files** in the **SCL directory**.
4. Once the Factory Tuning Library SCL directory is open, hold **MIDI Note 69.A**, and starting with SCL file ED2-05, start drag-and-dropping the SCL files, one at a time onto the TUNE button, and observe that...

The pitch of Oscillator 2 remains at all times fixed at 880 Hz, no matter what SCL file is loaded, which illustrates that with the octave-transpositions made with the Oscillator's Octave Transposition switches, that the octave interval between the oscillators remains consistent no matter which SCL file is loaded.

![image](https://user-images.githubusercontent.com/66483816/90985720-b8906480-e54b-11ea-9633-464c26a96589.png)


**Part 2 | The interaction of Oscillator Context Menu, Edit Value, oscillator octave transpositions with SCL-KBM microtunings**

![image](https://user-images.githubusercontent.com/66483816/90985884-c09cd400-e54c-11ea-8413-1304092622d3.png)

To illustrate the interaction of Oscillator 2 Context Menu, Edit Value, pitch-transpositions when SCL microtuning table files are loaded, attached is another Surge preset, **3-Sine Oscs - Edit Value Octave Transposition.fxp**, which features:

1. Oscillator 2 Octave Switch is set to "0", indicating there is no octave transposition applied here.
2. Oscillator 2, however, has its (right-click) context-menu, **Edit Value**, set to **12.00 Keys**, which, in **12-tone-equal-temperament**, equates with multiplying the pitch of the oscillator by 2 (transposition by harmonic 2), and when the tuning is in 12-tone-equal-temperament, this is indistinguishable from the scenario detailed in Part-1 above.

[3-Sine Oscs - Edit Value Octave Transposition.zip](https://github.com/surge-synthesizer/surge/files/5114661/3-Sine.Oscs.-.Edit.Value.Octave.Transposition.zip)

Here, as we will see, the behavior and interaction with SCL microtuning table files, it quite different from Part-1 above when the octave transposition is applied with the right-click context-menu Edit Value of 12.00 Keys. To observe this difference:

1. First load the preset, **3-Sine Oscs - Edit Value Octave Transposition.fxp** into Surge.
2. Next, place a **musical instrument tuner** after Surge and put the tuner in its **Hz** readout mode to make pitch measurements in terms of frequencies. 
3. Open the **Surge Tuning-Library** directory: Right-Click on the **TUNE** button (top right of UI), choose, **Factory Tuning Library**, the access the **SCL files** in the **SCL directory**.
4. Once the Factory Tuning Library SCL directory is open, drag-and-drop the **ED2-12.scl** file onto the **TUNE button** to initially tune Surge to **12-tone-equal-temperament**.
5. Next, hold **MIDI Note 69.A**, and notice in the tuner readout that the initial frequency is 880 Hz, here transposed one octave above the fundamental.
6. Now, while still holding **MIDI Note 69.A**, begin drag-and-dropping SCL microtunings that have a scale size <12, starting with ED2-11 down through ED2-05, and here one will notice that with each newly loaded SCL microtuning, the pitch of **MIDI Note 69.A** grows increasingly higher. 
7. Conversely, as one drag-and-drops the SCL microtuning table files that are >12, starting with ED2-13 and above, one will notice that the pitch of **MIDI Note 69.A** is progressively decreased according to the size of the loaded SCL file.

Part-2 here, is to illustrate that any pitch-transpositions made with the Oscillator's right-click context-menu Edit Value feature, are accurate in 12-tone-equal-temperament, but with any SCL files having scale sizes < or > 12, the intervals configured with Edit Value will be distorted and detuned from the intended intervals.

![image](https://user-images.githubusercontent.com/66483816/90986758-3e63de00-e553-11ea-9bd4-499fb3992bb1.png)


**The Implications For Factory Preset Content**
To conclude this analysis, the implications for factory preset, or any user presets, where any intervals are configured using the oscillator context-menu Edit Value feature, will be rendered accurately when the intonation is in 12-tone-equal-temperament, but will be rendered completely detuned away from the intended intervals, when any SCL microtuning table files are loaded with scale sizes that are < or > 12.

So, this is an issue that impacts not only the way FM synthesis works when using Edit Value ratios with the features of the Oscillator FM Routing section, but also, globally with any presets that feature oscillator pitch transpositions of any size configured with Edit Value, when loading SCL microtunings with scale sizes that are < or > 12.

@baconpaul @mkruselj

**Comment by mkruselj** [comment]
That's simply because the pitch control works in key space, not semicent/frequency space. As Paul said once "you have to go out of your way in Surge not to have everything follow SCL now".

**Comment by Jacky-Ligon** [comment]
Does an "Edit Value - Ignore SCL Size" enhancement sound like a plausible solution?

TBH - Making these kinds of oscillator pitch offsets in other virtual-instruments is an easy matter of routine, and here discussing these details in the hope and effort that we might find some solution to make it easier for Surge as well. 

If an "Edit Value - Ignore SCL Size" enhancement does not sound like a plausible solution, then what might be a better idea?

As it stands now, I'm sampling Surge in 12-equal so that I can play these kinds of FM patches in other microtonal tunings, but am hoping that eventually, we can find a way to use the Edit Value feature for FM synthesis when using any kind of SCL-KBM combination.

Thoughts or possible solutions?

**Comment by Jacky-Ligon** [comment]
@baconpaul @mkruselj 

Being that **_"it's just code"_**, one might wonder if there might be an opportunity and solution here in adding a right-click menu option for the oscillator octave transpose switches that would enable semicents typeins of arbitrary interval sizes?

![image](https://user-images.githubusercontent.com/66483816/90987903-99e69980-e55c-11ea-923d-a70036eb124a.png)

Adding such a feature to the oscillator octave transpose switches would:

1. Enable free-transposition of the three oscillators in FM routing sound-design scenarios.
2. Preserve the current Edit Value functionality.
3. Leave all factory and user presets unaffected by the change.

One might imagine that the code behind those oscillator octave transposition switches is merely dividing or multiplying by factors of 2, and might be accessible for such a context-menu typein application and enhancement.

Sound plausible?

**Comment by mkruselj** [comment]
I'd rather not clutter the slider RMB context menu, if anything this option should be in the Tuning menu.

**Comment by Jacky-Ligon** [comment]
Perhaps approaching these issues from the skewed and biased perspective of having programmed and made music with myriad FM synths for the better part of four decades, I would hardly qualify being able to configure frequency ratios in FM synthesizer algorithms as _"niche usage things"_, but to each there own experiences and perspectives.

If, in the end, none of these ideas are of interest for enhancing the the current octave-based FM paradigm of Surge, it's trivial to sample it in 12-equal using the Edit Value options, where arbitrary frequency ratios can be configured, then load the SFZ into a microtonal sampler. 

But as I'm certain most anyone would agree, the natural preference is being able to somehow achieve these basic - and almost universal - FM synthesis functions in the virtual-instrument, then write and playback parts from the actual generating instrument, rather than having to hassle with sampling, which, as we know, tends to lose a degree of detail and expression in that process.

Whatever the final outcome of this discussion, I'm happy to use Surge the way it is, and can tap into the many other virtual-instrument options available in the system here, where deeper FM sound-design possibilities are required, although, personally speaking, I would love to see Surge evolve on this important detail.

**Comment by baconpaul** [comment]
Sorry I'm super behind on my GitHub. Lot going on.

So the current behavior is: The pitch slider moves you by (N) keys, the octave selector moves you by (scale.length) keys, and the oscillator sounds at frequency( scale( key ) ) which if you are in 12TET is basically 440 * 2^((key-69)/12)) but if you have an SCL loaded is different. And the real concern is that we always send keys to the oscillators so things like 'octave is a frequency multiple' are hard because by the time we make waveforms, we don't know whether we pressed note 60 with octave 1 or note 72 with octave 0. More on this below though.

So there's a few thoughts though on what maybe we can do

1. We can configure individual oscillators to not use tuning. Like seriously. "Oscillator 2 is always in 12TET no matter what". This is moderately easy to accomplish. It could be super interesting in an FM context.

2. We can configure oscillators so that a pitch slider *offsets* are always 12-TET and only base frequency is from the scale. So lets say you play note 42 and you have pitch set at +3. Rather than playing `frequency( note 45 )` you would play `frequency( note 42 ) * 2^3/12` - so pitches are tuned but pitch shifts are 12TET.  This is moderately difficult to accomplish mostly because the pitch is externalized from the oscillator (or: the oscillator gets the same thing when you press note 45 with pitch at 0 as it does when you press note 42 with pitch at 3).

3. We can configure surge such that the octave button has a different behavior either per-oscillator or per-scene or per-instance. Whether this is easy to do or not depends on the behavior but has a similar difficulty as my second item.

Of course you would save whichever setting in the patch etc....

Where we put the UI is secondary. The thing I'm trying to figure out from this fascinating thread (and thank you for all the detail) is what do we actually want the behavior to be.

Our biggest constraint is the oscillator knows the pitch in key space which is requested of it; but it does not know which key was pressed to trigger that. Things like modulation, pitch shift, pitch bend wheel, octave button are baked in before we go and start making waveforms. So the 2 and 3 options could be a bit more surgery - namely making sure each oscillator knew not only the pitch but also the key. We have the data available though so we could plumb it through and it seems like it may be useful in a variety of settings. But that leads to some things being more extensive fixes.

Finally: Alternate tuning is hard! What an interesting conversation.

**Comment by baconpaul** [comment]
Note if we did my idea 2 above it would mean we lose a constraint I've tried to keep which is: Set pitch bend to 2. Press C. Bend all the way up. Listen. Release key and pitch bend. Press D. Hear the same note.

In idea 2, C bent 2 up would not be the same as D if D was tuned to non-12TET-interval

**Comment by mkruselj** [comment]
> Perhaps approaching these issues from the skewed and biased perspective of having programmed and made music with myriad FM synths for the better part of four decades, I would hardly qualify being able to configure frequency ratios in FM synthesizer algorithms as _"niche usage things"_, but to each there own experiences and perspectives.

Maybe you misunderstood me, or I didn't explain very well, or a bit of both. 🙂  All I wanted to say is if there is to be an option to bypass scale length from SCL, it should not be in each individual pitch-related slider's RMB context menu - scale length is an SCL feature, so it is better suited to be on a global level, grouped with all other microtuning options that we already have. I did not mean to say anything about FM ratios etc., just purely entered my "product designer" mode on the feature that you proposed in your issue title ("Ignore SCL scale size"). All good? 🙂 


I think this discussion is an important one (even though, as you know, I am not really using microtunings myself). This is also why I think it shouldn't be bodged, we need to find a satisfying solution for everyone, while keeping the workflow clean. Hence me putting my "product designer" hat here.

I would suggest to try dissecting how some other synths deal with this situation. For example a good study here could be u-he ACE - it allows the oscillators to be adjusted in semicents, partials (0-24, 0 being the fundamental), subharmonics (0-24 again), Hertz (0-24 Hz), and sync (because oscillator can also be used as an LFO, so this gives you tempo synced divisions - not very useful as an audio rate oscillator). Then ACE has another knob to adjust offset from this pitch value, and it can be in cents, +/- 5 Hz offset, beats (to be used with "sync" mode), and multiply (which is where the sauce lies). The modulation is always applied in cents regardless. @baconpaul Does this breakdown spark some thoughts?


Really, @Jacky-Ligon, you should have ACE in your arsenal. These options are right up your alley. 😉

**Comment by Jacky-Ligon** [comment]
@mkruselj @baconpaul 

Actually have ACE since we last discussed it on Slack sometime ago.

Yes, the subharmonic/partials (with floats) controls are a really elegant solution, and something to consider emulating in Surge for its FM frequency ratios.

There is, with ACE and Bazille, from this humble perspective, a rather annoying niggle though, is that the control readout shows the value sub/harmonics in a n-1 format...

U-He should really just call them what they are for precision: 1 = 1/1, 2 = 2/1, 3 = 3/1 ...

Rather than: 0 = 1/1, 1 = 2/1, 2 = 3/1 ...

That is seriously like fingernails scratching blackboards. Just don't understand why they designed it that way, but I can deal with it.

For Surge though, if we do something like ACE/Bazille sub/harmonics controls, please call harmonics and subharmonic numbers what they actually are - i.e. - the integers these ratios actually represent, rather than in the form of n-1, and thanks in advance for preserving sanity here and avoiding the cognitive dissonance of the way U-He's is designed.  

Having said that, otherwise, ACE is quite an amazing microtonal (TUN based) synth. Can't recall if we've discussed it in the past, but one of the central features of the old XA IVOR2 virtual-instrument, was its ability to do audio-rate modulation of PWM, as well as, audio-rate modulation of the PWM bounds - potentially at different rates, at the same time - but with ACE, I've not yet found a way to achieve the latter, while the former is easy to configure and sounds amazing.

**Comment by Jacky-Ligon** [comment]
Wanted to add that while I have no problem with an exclusively typein driven method for setting FM frequency ratios for the three oscillators in Surge, one might easily predict that many users would prefer some sort of knob or slider control (like the n-1 sub/harmonic knob in ACE for example), so where another control would reside on the UI of Surge, is a question.

@baconpaul @mkruselj

**Comment by mkruselj** [comment]
> Just don't understand why they designed it that way, but I can deal with it.

It's because the knob shares the same parameter range for multiple modes, so they conflated them all.

**Comment by Jacky-Ligon** [comment]
Closed for consideration at some future time.
