### ISSUE TITLE
Adding a "Show Presets Folder" option in the right click menu of the presets!

### ISSUE THREAD

**Issue by viceverser** [surge-synthesizer/surge#2514]

**Comment by mkruselj** [comment]
The main problem here is that all we can show is the whole data folder, because we have presets split in two folders - factory and 3rd party.

**Comment by baconpaul** [comment]
@viceverser meant 'user presets folder' so really 'open user data folder' on the coscillatormenu

**Comment by mkruselj** [comment]
I mean sure we can have all 3 options - open factory, open 3rd party, open user.

Ideally though we would move factory and 3rd party folders in one overarching presets folder, though, this makes it cleaner?

**Comment by baconpaul** [comment]
You'll need to change the C++ code though in a couple of places, and the installers on mac and linux and windows if you do that since the internal data structures have the third party concepts. Mostly in SurgeStorage.

I think the easy immediate request of "open user data folder" on the oscillator menu is separate from that though.

**Comment by mkruselj** [comment]
Ha sure, I guess, but I thought if we're doing one we should do the other properly too. Must say it always felt weird that we don't have an overarching folder for factory presets...

**Comment by baconpaul** [comment]
This will be in an upcoming nightly.
