### ISSUE TITLE
MSEG Design

### ISSUE THREAD

**Issue by ThyHG** [surge-synthesizer/surge#2563]
### Segments and points

- Every part of the envelope is a segment.
- Segments can be added between two other segments as well as before the first and after the last segment.
- Each segment has a line type (line / constant / bezier, etc).
  - The line type can be changed at all times.
- Each line has a start and end point
- The start point of segment 2 can be ‘unlocked’ from the end point of segment 1 and be tied together again.
- Some lines have control points (curve for bezier, etc).
- Each start and end point has an XY value - duration and amplitude
- Each point can be adjusted in both X and Y
- If a point is adjusted on the X (duration) it can either ripple through to other nodes behind it OR just adjust the duration between it and the point before and after it.
- The editor also has a mode to ONLY adjust Y (amplitude) values.
  - (Maybe this mode could be - drag points for amplitude and drag segment lines for duration??)
- When dragging a point it shows a Y value as a hover text next to the point - the X value can be read on the X-axis. (Or both as hover next to point)
- Segment should have a toggle that makes deform applied to it or not (ON by default)

### Grid
- The envelope is created on a grid.
  - The segments should be visually differentiated from the grid.
- The grid can be tempo synced (following beats) or not.
- The X-axis can be based on the units: 1. Absolute seconds, 2. tempo or 3. phase (?)
- The grid can be zoomed in and panned around
- The values of the points can be snapped to a grid (on X and Y values - independently).

### Other
- The envelope can be looped by setting a loop start and loop end segment
- The nodes can be quantised to grid
- The nodes can be distributed equally for the entire envelope duration
- There is a setting for unlocking start/end point locking.

### Interaction possibilities
- The aim is that all (or most, especially the standard tasks) can be done with only the mouse (no keyboard modifiers).
- Stuff that can be clicked should have an hover effect for discoverability

- The start and end points have mouse events
  - Click and hold to drag based on the mode (X - Y field)
  - Right click - set start/end loop
- The control point has a mouse event
  - Click and hold to drag to change the shape
  - Right click (??)
- The segment has a mouse event
  - Right click for options (delete - change shape of line - quantize to grid - distribute evenly).
  - Double click the line to create another segment in between
- The editor has events
  - Scroll wheel for zooming
  - left click and hold to pan (! - this makes a marquee tool (if ever) only available in yet another mode or right click and drag).
  - Double click for zoom to fit 

	

### Menu options (show a bar to left, right or bottom of the grid).

- The sliders from the modulation window (Rate / phase / amplitude / deform)
- Settings for duration snap and amplitude snap
  - Should these be preset values in a dropdown or completely user selectable?
  - Can be toggled on or off per axis
- Settings for which movement mode for points (ripple, lock, amplitude only)
- X-axis unit selection
- Lock or unlock points from each other

### Designs WIP
Screen without much going on
<img width="939" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/92037777-962fef80-ed72-11ea-9e59-4cf8767f3503.png">

Right click segment:
<img width="941" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/92037915-d2fbe680-ed72-11ea-988b-ce3157e16cb5.png">

Moving a node option #1
<img width="944" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/92037942-e1e29900-ed72-11ea-83e2-025b07d66887.png">

Moving a node option #2
<img width="942" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/92037966-ec9d2e00-ed72-11ea-8a29-497f7e1b6393.png">

Sketch of points unlocked mode (two half ovals or two circles)
<img width="1049" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/92038021-08083900-ed73-11ea-8f2c-54ce75f51f47.png">

**Comment by mkruselj** [comment]
Here's my comments:

- Snapping should be separately togglable for horizontal and vertical I'd say.
- User allowed to type any value for snap level? Even decimal numbers? Not sure how useful. But let's say maximum snap level should be 100 subdivisions.
- Not sure if we really need add/remove segment options in RMB context menu for segment, when we can just double-click to insert a new node, creating a new segment.
- ONLY the starting node of a segment (in case of segment editing mode, rather than simpler node editing mode) should have the options for picking out loop start/end.
- In the case of eventual marquee select tool, while left drag is being used to scroll left-right, we should have the ruler do the node selection instead.
- One crucial detail: dragging the last node out of range should extend the envelope of course, but not in an epileptic manner as it does now (jumps in zoom level are pretty erratic). Instead it should be smooth like in Zebra:

![zeebsextendmseg](https://user-images.githubusercontent.com/2393720/92039912-26236880-ed76-11ea-9f88-ca1d9e0b510b.gif)

**Comment by ornithologistnightmare** [comment]
Seeing this feature proposed for a free synth has caught my attention since whatever MSEGs get put here might become popular. Here's some comments on what features would be nice:

* The structure of the MSEG should be attack (note on), loop/sustain and release (note off) as discussed above, but there could be two options (I recommend adding both for user configurability) as to how to handle the loop/sustain part:

   1. either the loop start and end points should be markers which are independent of any of the MSEG points (with snapping to MSEG points as an option), or...

   2. the MSEG graph should be a double graph (two lines on top of each other) with a single sustain marker for both parts of the graph (not one each). A switch would allow a user to control one line or the other. The first line would control the usual level of the MSEG, while the second line controls the dry/wet of a custom-shaped LFO (using another separate graph) which replaces the looping. It would be like letting the looping part in the first case have a custom fade-in and fade-out setting. This option is more complicated but might be the most complete MSEG ever made.

- Multiple range modes would be good. Given three parameters `t`, `X%` and `Y%`, we could have multiple modes for how that's interpreted (`X% + t*(Y%-X%)` (interpolation); `X%+Y%*2*(t-0.5)` (bipolar range)...)

- In addition to the range modes, a unipolar/bipolar switch for the whole envelope.

- Retriggering options (e.g. instant retriggering even if another note is held down, retriggering only after a certain part of the envelope has been reached...)

- Text editing for point X, Y and bend values

- Each bend should have two parameters for more flexibility.

**Comment by ThyHG** [comment]
Three segments with two drawn in hover effects (both the segment and the point).
<img width="737" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93004568-71910000-f548-11ea-9571-d2b01c96666f.png">

Right mouse on a segment.
<img width="1060" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93004595-af8e2400-f548-11ea-9434-c9dc06ff9ffa.png">

Right mouse on a point.
<img width="1062" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93004603-bddc4000-f548-11ea-959a-9e54fe77f468.png">

Dragging a point.
<img width="729" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93004668-583c8380-f549-11ea-836a-211817817ed6.png">

TODO.
1. Exact style for 'advanced segment editing' mode. 
2. Decision for placement of controls. Left or bottom.

**Comment by ThyHG** [comment]
Small update on the controls:
<img width="595" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93029058-c308c000-f618-11ea-96ad-8d488a86affe.png">

**Comment by mkruselj** [comment]
If we have Show DAHDSR button... wouldn't it also make sense to duplicate DAHDSR sliders here, too?

In fact I'm proposing for the whole envelope part of the LFO to be separately togglable on/off (then we could have just a small circular power button for it, instead of chunky Show DAHDSR button), which would make things more consistent between LFO types then, too...

**Comment by mkruselj** [comment]
- [ ] Close button of MSEG editor should be just an X, also on the left side for macOS, and right side for WIndows, maybe? That might be problematic for skin developers, since they could just force the positioning of that button, though?

**Comment by ThyHG** [comment]
We forgot to include design for the loop functionality (oops). Below are some screens for that, which include some alterations to earlier design as well.

Loop button is added to the controls (and controls have been aligned - evenly sized)
<img width="635" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93665561-b1d80d00-fa77-11ea-9ce3-5898432cd3f9.png">

When activating loop in the controls - the loop start and loop end get drawn in. The user can drag the flags on the ruler to adjust the place of the loop start and end (it snaps to the points).
<img width="712" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93665722-219ac780-fa79-11ea-93ac-04f6773fdd01.png">


Because of this, the right click menu on points does no longer need to include set loop start and end.
<img width="637" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93665624-20b56600-fa78-11ea-98c7-25256ecebd05.png">

**Comment by ThyHG** [comment]
When having drawn points in bipolar mode and moving to unipolar - the point should clip to 0 and show a dashed line for the part that is clipped.
Example:
<img width="710" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93671257-c7622c80-faa1-11ea-987e-1cd5db6682db.png">
<img width="715" alt="afbeelding" src="https://user-images.githubusercontent.com/10957304/93671261-cfba6780-faa1-11ea-9e0c-0abab6732645.png">

**Comment by mkruselj** [comment]
- [ ] Defaulting the control point value should be done with Ctrl+click on the control point. Although Ctrl+click anywhere in the valid segment would also work, but we should save it in case we need Ctrl+drag on segmetn for something later on.
- [ ] Add Deformable toggle in RMB context (enabled by default for all segments), which allows any segment to stay free from being affected by the Deform slider. The non-deformable segments should have a different curve color. We should also have a keyboard shortcut for this, say Alt+click anywhere in the segment to do that.

**Comment by mkruselj** [comment]
- [ ] Nudge the MSEG Editor down so that it doesn't cover category/patch prev-next buttons (in fact the MSEG Editor header could also be thinner in height)
- [ ] Reduce the height of MSEG editor (now that we made it modal so we won't repeat all those sliders and buttons etc.) so that rows 2 and 3 of modbuttons can always be seen, enabling switching between different MSEGs easily and swiftly
- [ ] Related to above, if we switch from one LFO to another and that new LFO isn't of MSEG type, close MSEG editor, otherwise update MSEG with that LFO's data

**Comment by mkruselj** [comment]
- [ ] Mousewheel on V/H snap numberfields (maximum value 100 steps)
- [ ] The node still behaves as two separate points w.r.t. RMB context menu. If you click on the left side of the node and change curve type, preceeding segment changes, if you click on the right side of the node and change curve type, following segment changes. It would be great if, when right-clicking the node, all changes apply to the _following_ segment always
- [ ] The actual window of MSEG should be styled the same as miniedit - Surge logo in top left, same titlebar height, same roundrect radius for Close button (and skin colors for all that)

**Comment by mkruselj** [comment]
Closing this issue since MSEG design is pretty much in place now.
