### ISSUE TITLE
Airwindows effect "Loud" is clipping loudly when initialized.

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#2620]
So opening the "Loud" effect from airwindows menu is making a loud clipping sound that is coming so abruptly its scary.
And that clipping is different everytime when initializing the effect. urge can also end up in a state like this when "Loud" is opened.

![airwindows fx - Loud bug](https://user-images.githubusercontent.com/56724286/93047842-acd12300-f65d-11ea-9dc2-6728485c1622.gif)

This kind of clipping is also bad for the speakers since it has very low frequencies and comes all of a sudden.

**Comment by mkruselj** [comment]
Can you try saving a preset with dry/wet set to 0%, then load that and see if it pops?

Will be easy to change the default value if it doesn't pop in that case.

**Comment by baconpaul** [comment]
Did you do anything other than load it? On mac it doesn't clip for me. (I can try win too of course but want to be sure I'm not missing how to repro)

**Comment by K0rrid0r** [comment]
@mkruselj Making a present with dry/wet set to 0% makes no clipping sound.

@baconpaul You have scroll by it sometimes several times until it clipps. Sometime it doesn't and sometimes it does.
It's clipping like on the picture about 85% of the times when you initialize it.

Anyway just tried now again ended up like on my posted GIF.

**Comment by baconpaul** [comment]
So I think what is happening here is the "A" parameter is out of bounds in Loud because you had a prior FX set up and it doesn't properly re-initialize. Loud isn't stable under A being outside of range.

So there's a couple of fixes

1: Put a limit_range in Loud. That's easy but wrong-is
2: Deal with the lifecycle problem which is having values drag over from prior AW properly. That' the FX Lifecycle problems

Loud has code which does "boost = pow( A + 1, 5 )" where A is 0-1 range supposedly. But if you set that to 1e34 accidentally because of a bad init path it would blow up. That's the primary thing I can see here.

And I know the AirWindow init lifecycle is messed up so it makes sense that the soccurs when switching back and forth.

I'll leave this open of course until I fix the other lifecycle things but I think this is not 'special 'problem with Loud it is just 'very sensitive' problem that Loud sees more than others.
