### ISSUE TITLE
Audio glitching out when turning off "Activate extra scene outputs" if a sound was playing

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2639]
Description:
The audio glitches out continuously when turning off "Activate extra scene outputs" if a sound was playing at the same time.

Here's an example audio file when playing the default saw patch: 
[glitch.zip](https://github.com/surge-synthesizer/surge/files/5250254/glitch.zip)

**Comment by baconpaul** [comment]
So this doesn't happen reliably on the mac but I think the solution is in SurgeVST3Processor if numoutputs ==3 && activated we fill; if numputputs == 3 and not activated, though, we need to zero out the buffer. So that's the code to add (and symmetrically in the VST2). 

I'll add that code shortly and then ask you to re-test OK?

**Comment by baconpaul** [comment]
@VincyZed at your convenience, can you check out branch `baconpaul/deactivate-2639` which should fix this problem?

Thanks!

**Comment by VincyZed** [comment]
@baconpaul Confirmed, it's fixed! Thanks :)

**Comment by baconpaul** [comment]
Great

**Comment by baconpaul** [comment]
Merged. Thanks for the test!
