### ISSUE TITLE
Using SURGE as "CV source" on Ableton

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#2701]
**Is your feature request related to a problem? Please describe.**

After watching this (very inspiring) [video on youtube](https://www.youtube.com/watch?v=VPSeNM2mZoI) named `Mod ANYTHING With Serum's LFOs` i could not hold myself from trying to do the same with Surge.

The problem here is that I don't know exactly how I could edit the wavetable file on Surge to look like what he did with the wavetable on the tutorial?

![image](https://user-images.githubusercontent.com/27327/94326087-ce090c00-ff99-11ea-96a8-11392c44f12e.png)

I guess it's just a "frame" filled with constant "1s", but to be honest I don't know to create it without using Serum's editor.

Is there an easier way than doing it on Serum then sampling it and importing to Surge, I supposed that would work?

**Describe the solution you'd like**
Is there a simple way of generating that wavetable file for Serum, for instance with a command-line tool or achieve that waveshape in some other interesting way using Surge?

Shall such basic wavetable be included as default on the Wavetable library so neat things like that could be created?

**Comment by baconpaul** [comment]
1: Surge can import serum wavetables directly. Just drag the .wav file onto surge and it reads the serum metadata
2: If you want to make your own we have a bunch of tools which let you do it, but right now they are command line / python tools mostly
3: We're all ears for ideas to make this better but there's some code to write and it's not in our immediate queue
4. I like the idea of making some constant tables I think but I do wonder about dc offset. 
5: I didn't watch the video but was the idea "have a 50 frame wavetable where the entire period values are -1, -0.95, ... 0.95, 1" and then modulate that with the LFO to generate a waveform? If so you'll alias like hell in surge since the LFO control rate is BLOCK_RATE and linear interpolates over the block. That aliasing may be entertaining but we don't have audio rate modulation in surge.

Here's the wiki on making waves

https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki

**Comment by mkruselj** [comment]
In the latest nigthlies there is now an option to deactivate the highpass filter in Surge (right-click the HP slider next to waveshaper). This should allow you to do the same thing as in Serum.

**Comment by hems** [comment]
> waveform needed to be -12 dB gain).

I guess this can be compensated by adding +12db on the Surge preset

**Comment by mkruselj** [comment]
Sure, or by loading EQ in an effect slot etc

**Comment by mkruselj** [comment]
OK so basically this issue could now pretty much be considered solved, right? We have highpass that can be disabled, and you have the rectangle window from the Window oscillator you could load in the regular WT oscillator to do your bidding. This counds as a resolved/closed issue in my book.

**Comment by hems** [comment]
> OK so basically this issue could now pretty much be considered solved, right? We have highpass that can be disabled, and you have the rectangle window from the Window oscillator you could load in the regular WT oscillator to do your bidding. This counds as a resolved/closed issue in my book.

awesome, thank you, I'll check on my end asap and report back
