### ISSUE TITLE
Moving the OSC Sync parameter from 0% after hitting a note will often make a clicking noise

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#2737]
**Description:**
Moving the OSC Sync parameter from 0% after hitting a note will often make a slight clicking noise.

**Surge version:**
Latest Nightly (007c08d)
VST3 x64 in FL Studio x64

**To Reproduce:**
1. Load an init instance of Surge.
2. Press down a note
3. Move the Sync parameter in the OSC section slightly. As soon as you move it, you will often hear that slight clicking noise.

**Expected behavior**
It should increase smoothly.

Here's a video demonstrating the issue:
[Video.zip](https://github.com/surge-synthesizer/surge/files/5301957/Video.zip)

**Comment by baconpaul** [comment]
So the reason for this is because the sync state isn't updated when the sync is zero so when you set the sync off of non-zero, the sync state kicks in and you skip a big chunk of the wave (the sync state is the basically time pointer in sync mode).

I'm looking at all the places it is updated to see if we just want to always update it even if sync is 0 and then only use it if... etc... 

but this is a real problem yeah. Basically you skip between 0 and 1 phases when you jog the sync state off of zero

**Comment by selenologist** [comment]
It seems this is now an issue again (@VincyZed is still hearing it) after #3534 reverted the change as per #3529. Reopening.

**Comment by mkruselj** [comment]
Yes, no way around it from what I can tell. If we change how sync is calculated, this will also affect certain patches using S&h3 Noise at low correlation.
