### ISSUE TITLE
Remove runtime.xml feature as it is too fragile!

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#2740]
Try exporting components to runtime.xml with Classic skin. Works nicely.

Now try doing it with dark skin. All bg_resource names are now bmp00000.svg!

**Comment by baconpaul** [comment]
There's a technical reason for this which is hard to fix. We've lost contact with the id by the time we are at the runtime in the non-default skin. You could do a super nasty hack but this is only a dev feature.

So the solution I propose is: if you do a runtime.xml generation from something other than the default skin it gives you a user message saying you can only generate runtime.xml from the default skin. Since other things may not reverse out properly in non-default-skin this seems to me like the wisest choice.

**Comment by mkruselj** [comment]
But don't we already HAVE the info in the skin, if it uses i.e. renamed assets? Or if it doesn't use any custom assets, could just write out default bmp names as they are in the Classic skin? No? 🙁

**Comment by baconpaul** [comment]
the least useful word in all of computer science is "should".

why "should" the runtime inspection of a widget dynamically from the ui hierarchy be able to trace all the way back to the dynamic creation parameters?

The code will explain to you why it "doesn't" and what the solutions are!

But the solutions are all painful so #2 is a good option. Or just remove the feature altogether! It's hard to maintain and keep correct. (which is why it is always not correct!)
