### ISSUE TITLE
Rename "show cursor while editing" to "pen mode"

### ISSUE THREAD

**Issue by MartyLake** [surge-synthesizer/surge#2775]
**Is your feature request related to a problem? Please describe.**
When I use my pen-tablet, mouse stealing when dragging a slider means I cannot adjust any setting in Surge UI.

**Describe the solution you'd like**
A là Ableton Live, introduce a pen-mode that does not steal the mouse.

**Describe alternatives you've considered**
I tried the different options in menu > user settings > mouse mode.
OMG there is an option for pen-mode, it's called "show cursor while editing"

**Comment by mkruselj** [comment]
Yep, that option only works under Windows currently, too. We feel this name is more appropriate, since it's also very valid for regular mouse usage as well.

Also, it's not perfect in a number of ways (including the fact that it's not an infinite drag, the mouse cursor still travels the same distance through the screen, it's just hidden, so you can still "hit" the boundaries of the screen area, which would mean that the control would stop moving), so it's still considered a work-in-progress (as you can see there is a draft pull request that deals with mouse cursor appearing at the position where you let it go, but quantized to the area of the control you dragged, which is in its current state quite inconsistent and has a number of edge cases where it just doesn't work correctly)...

**Comment by MartyLake** [comment]
thanks for your swift answer @mkruselj 
I went to your draft PR, it looks hard to reason about and prone to tons of errors indeed =/

I don't fully understand the problem space there, maybe everything I say is inappropriate, sorry in advance for that. I am also not (yet) a hardcore Surge user, but I have a "learning" goal in my backlog so I will get there eventually =)

what if the mouse is never hidden, does it make the issue easier ? there is no infinite space on a desk to move the mouse up anyway, so if the user sees the mouse, maybe the user can reason about what's happening ?

**Comment by baconpaul** [comment]
Our life would be so much easier if the cursor was never hidden, except for the complaints from all the users who expect the cursor to be hidden on windows.

On mac and linux we have not implemented cursor hiding.

Glad you found the option! Good to know how Ableton calls it. Wonder if we should name it "Show Cursor Always (pen mode)" instead? wdyt @mkruselj

**Comment by mkruselj** [comment]
It's not nearly a consistent name. For example, NI calls it "touchscreen mode". I'd rather keep current name then explain more about it in the manual.

And yeah. we cannot have the cursor just always show by default, because that would be breaking Surge's default behavior on Windows at least. But I'm fairly certain there's plugins that also hide cursor or Mac too, @baconpaul. So we should bind the APIs for Mac and Linux too...

**Comment by baconpaul** [comment]
Sure! I would merge that. 

OK lets just tag @VincyZed here and link to #2413 To remember to put the alias names in the manual and close this. don’t think there’s anything left to be done here.

@MartyLake hope you have fun making music with surge!!
