### ISSUE TITLE
Mapping a CC to macro freezes Live when MIDI message stream is too dense

### ISSUE THREAD

**Issue by MartyLake** [surge-synthesizer/surge#2778]
**Describe the bug**
Mapping a CC parameter to Surge macro freeze Live when the amount of message is too high.
I suspect that it's because Surge macros are generating some kind of Gesture/Edit.

**Please let us know your surge version**

* Surge Version: 1.7.1.5270cfb
* Plugin type (VST3)
* Bits (64)

**To Reproduce**
1. Start Ableton Live
1. Load Surge in a midi track
1. Live: Create a midi clip containing midi data on CC18
1. Surge: map CC18 to macro 1
2. Live: Create an audio track, open the EDIT menu to see that the undo text is about the created audio track
3. Live: Launch clip
4. Live: open the EDIT menu, see that the undo text has changed to "macro 1..."

**Expected behavior**
Last step:
Live: open the EDIT menu to see that the undo text is about the created audio track (aka not a macro change due to midi mapping)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Host Live
 - Version 10.1.13

**Additional context**
Using Ableton Live 10.1.13 on Windows, any VST that declares a gesture/edit have its parameter changes recorded in the undo stack, thus completely flooding the Live's undo when moving a parameter from a midi mapped parameter. When using high resolution midi devices (like Touché from Expressivee), this flood of parameter changes can overwhelm Live to the point of freezing.

One main interest I have for Surge is the ability to midi map, in order to bypass Ableton Midi mapping mecanism that suffers from the same behavior. Unfortunately, this bug is no go to me =(

I can provide dev hours if it can help fixing this. I have tried grepping https://github.com/surge-synthesizer/surge/search?p=2&q=beginEdit but only found gui-related code. I also tried grepping https://github.com/surge-synthesizer/surge/search?p=9&q=midi but found nothing related to midi mapping.

**Comment by baconpaul** [comment]
Does this happen if the UI is closed? I bet it does not.

If not: my guess is

1. The midi application in SurgetSynthesizer and subsequent smoothing in ControllerMOdulationSource is updating the value
2. The updated value is forcing the display of the controller to re-render raising an event
3; you hit the sendParameterAutomation in SurgeGUIEditor in the valueChanged callback for tag_mod_source block. My version of SGE is undergoing some surgery but that's around like 3896 for me.

If it does happen with the editor closed then: I would put prints or debug breakpoints in SurgeVST3Processor::getParamNormalized 

But I expect it does not because, here on my mac, I built the VST3, mapped macro1 to a knob on my keyboard, opened reaper, and did a track latch, did a playmate latch, and mapped the control to pitch.

With the UI open I get the pitch changing as I wiggle and play but also get VST3 events.

With the UI closed I get the pitch changing as I wiggle and play, but do not get the VST3 events.

That's clearly a bug.

This leads me to believe that my "requires the UI open" case is true, this is a real bug, and it is the call to sendParameterAutomation in SGE which is doing it. Fixing that would be interesting. You want to send the automation event if you drag the slider, but not if you wiggle the midi. Separating those cases would be some work but not impossible.

My very first step would be to comment out this line

```
        synth->sendParameterAutomation(t + metaparam_offset - ms_ctrl1, control->getValue());
```

and see if that fixes the problem. That fix is not mergeable but it is diagnosable.

Also you may want to consider hopping on the #surge-development channel on discord, but if you don't want to, GitHub is also fine!

**Comment by baconpaul** [comment]
I bet it is the edit_drag state on the CModulationSource object being in the wrong state when midi resets it, now I peek at the code. Not 100% sure but that's where I'd look first, if you see the same UI open / UI closed action in windows live.

Thanks for offering to dive in. Glad to help as you navigate the code.

**Comment by baconpaul** [comment]
Some more interesting things

1. This isn't just macros. Learning filter cutoff does the same thing. So it's not CMS/edit_drag related
2. In reaper, which admittedly polls values a lot from a vst3, in latch mode with the UI open wiggling midi changes the daw automation value but also the string display value; with UI closed it changes the string display value but not the automation value.

So yeah having the UI open is sending an event that having the UI closed does not.

It is almost definitely sendParameterAutomation though. Start there for sure I think!

And good luck!

**Comment by baconpaul** [comment]
Oh and I tagged this for 1.8.0. I don't have time to look in depth next week or so but if you end up stymied and I can't help, I can debug it before the next release (which we are scheduling for Jan21)
