### ISSUE TITLE
MSEG open state survives transitions

### ISSUE THREAD

**Issue by viceverser** [surge-synthesizer/surge#2791]
**Describe the bug**
When I use the MSEG (in Reaper) and close the plugin window then reopen, I have to reselect the LFO I was using, then reopen the MSEG editor each time... Basically close open forgets where I was in the LFO's

ALSO effects... Selected oscillator, selected LFO editor, MSEG editor open state, selected FX in the FX grid, Store dialog, miniedits.
Maybe more???

**Please let us know your surge version**
This information is all in the menu/about screen

* Surge Version: 1.8 NIGHTLY-2020-10-05-2f73cd0
* Plugin type (VST2, 3 or AU) ALL
* Bits (32/64) x64

**Expected behavior**
Should remember closed state.

**Desktop (please complete the following information):**
 - OS:WIN 10
 - Host: Reaper
 - Version: 6.14

**Comment by baconpaul** [comment]
The reason for this is, I think, because Reaper (as is its right) destroys and recreates and editor object when you open and close. And the editor object stores all this state.

I'm reluctant to put editor state on the synth (for obvious reasons) so this one may be a bit tricky. Def not a 1.8 if my theory is correct

You can validate my theory by seeing if the SGE constructor and destructor run on open/close. I am pretty sure they do though.

**Comment by mkruselj** [comment]
Yeah they probably do run... but the expectation here is to be able to continue where you left off even if you close the plugin GUI. Which is a rather important workflow thing.

**Comment by baconpaul** [comment]
Sure. but if our state object is destroyed... we need to figure out where to put that state.

**Comment by mkruselj** [comment]
Right. So DAW state is the perfect location for that. Any particular reason why not to use that?

**Comment by baconpaul** [comment]
Yes exactly, except no because (1) this isn't DAW state (like are you in MPE mode or are you tuned) this is UI state and (2) DAW state is only populated when you stream

So need to make something like 'lastEditorState' on the synth which is used to initialize an editor and which gets snapped when you close/destroy basically. 

So "same idea; different data; different point in the code" basically

**Comment by mkruselj** [comment]
Gotcha!

As long as it can be done 🙂

**Comment by baconpaul** [comment]
@mkruselj as discussed tonight I'll hang diffs and stuff here

**Comment by baconpaul** [comment]
OK did current scene and current osc

Left is

modulator by scene
selected fx
other bits i'm sure

mseg open state is more ambitious but doable i think but perhaps push that one into a separate issue?

**Comment by mkruselj** [comment]
PR #2971 addresses most of these!

**Comment by baconpaul** [comment]
Unclear what’s left to do here. @mkruselj i think we are all done with your merge above yeah? Should we close this?
