### ISSUE TITLE
Catch SurgeError in the corresponding plugins (VST2, VST3, AU)

### ISSUE THREAD

**Issue by jsakkine** [surge-synthesizer/surge#280]
In order to get eventually rid of GUI code inside SurgeStorage.cpp, display error dialog in the plugin level by catching SurgeError exception.

**Comment by jsakkine** [comment]
Probably more than one PR. I'm working in the VST2 side now.

**Comment by baconpaul** [comment]
See #217 also for a comment in what to do when you do catch

**Comment by baconpaul** [comment]
Just letting you know: I'm coding up #217 now and will sweep this in along with it. Will have a chunk of code for you to review in the next day or two.

**Comment by baconpaul** [comment]
So turns out that having the constructor throw in the audio unit is "relatively painful" if I don't want to segfault with the way the allayed is for now. So while I agree this is a great aspiration, I'm going to special case audio unit in surge storage for now to pop the dialog and complete the constructor. Just FYI.

Although I did learn something interesting about how AU hosts deal with mis initialitialization... but I'm going to hold on debugging and just wrap #217 for now.

**Comment by baconpaul** [comment]
OK actually this works pretty badly on VST2 Mac also. If the configuration.xml isn't there you get the message but then (say) bitwig forgets the plugin. I think this throw from the constructor is going to be generally unpleasant to handle on the mac hosts (from my sample size of 2 hosts and 2 plugin types). Something to discuss but I think this isn't easy to handle throwing constructor of the main type.

**Comment by jsakkine** [comment]
I think things are now in sustainable state. Better to do smaller scale issues if need arises.
