### ISSUE TITLE
User can save an unnamed (empty) preset and it will be saved to Category/.fxp

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#282]
currently user is able to save an unnamed preset and if it is saved into a new category, the category-folder will get created, and then there'll be a `.fxp` file in there.

user can then load the preset, too.
<img width="268" alt="fullscreen_12_01_2019__18_43" src="https://user-images.githubusercontent.com/4966687/51075860-fce23000-1699-11e9-986a-2098417737d1.png">

**Comment by baconpaul** [comment]
Well at least you can load it!

**Comment by baconpaul** [comment]
This one needs #217 resolved first. My plan is to pop an error box saying "patch not saved since name was blank" or some such. But I would love that API to show an error box to user modally in code. (This is not a case where we can throw).

@jsakkine just flagging your attention to this also since I know you are working on the show-message stuff on linux.

Leaving this sit for a bit.

**Comment by baconpaul** [comment]
This is now fixed.
