### ISSUE TITLE
Renaming a Macro breaks the GUI

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge#2933]
**Bug Description:**
After right-clicking on a macro and selecting "Rename" the GUI glitches out and becomes unresponsive.
Closing and re-opening the GUI doesn't help. The DAW is responsive and the synth produces sounds, but no GUI interactions is possible.

**Surge Version**
1.7.1 VST3 Linux64-bit

**Reproduction Steps:**
Assign macro 1 to filter cutoff 
Right click on the macro and select "rename"
Watch the GUI break.

**Screenshots:**
![image](https://user-images.githubusercontent.com/491704/96737870-7013ec80-13be-11eb-9fd2-fd70279120c2.png)

**Computer Information (please complete the following information):**
 - OS: Manjaro Linux
 - Host: Ardour 6.3

**Comment by baconpaul** [comment]
Hi!

With 1.7.1 to rename a macro you need zenity installed and in your path. Moreover, as you see, we recover gracelessly from its absence.

With the nightly and the upcoming 1.8.0 release this is no longer the case, although other functions do require zenity.

For now, can you `apt-get install zenity` (or equivalent for your distro) and try again?

Thank you!

**Comment by baconpaul** [comment]
Oh also (now I remember) even if you have zenity in your path it won't load because of the Ardour LD_LIBRARY_PATH hacks they use to do gtk2 and so on.

So really for now: Don't rename a macro in ardour or use the nightly. (There are some other functions around file system which won't work in ardour but shouldn't crash so horrifically).

So I'm going to close this issue as resolved in 1.8 even though it is indeed real in 1.7.1.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/issues/2455 There's the history if you are interested!
