### ISSUE TITLE
Feedback and FM Depth sliders stay grayed out

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#2991]
**Bug Description:**
After changing to a routing which has feedback, the feedback slider stays "grayed out" until you change the routing again. The same happens with FM routing and FM Depth.

**Surge Version**
Version 1.8.nightly.86f3af6 (Intel 64-bit Windows VST3 in Ableton Live 10.1. Built 2020-10-27 at 20:52:13 on pipeline host 'WIN-FUUP911EET4')

**Reproduction Steps:**
1. Load a fresh instance of Surge
2. Click on a routing that has feedback
3. Notice how the feedback slider stays grayed out

Funnily enough, this is 100% reproducible in Live and Fruity, but it does not happen in Bitwig, as far as I can tell.

**Comment by baconpaul** [comment]
Question

In a situation where it is grayed out if you swap the modulator (like toggle lfo1 to lfo2) does it reactivate?

The fact that it is daw dependent makes me think that there’s an automation loop and we are confusing 1/7 without rounding properly somewhere in a get value when we toggle the activation state maybe. Especially since I made more things (correctly) generate automation messages. If this theory is true then (1) the toggle above won’t fix it but (2) if your daw is in parameter latch mode you should see a value for routing which is rounded by a smidge differently in live etc rathe than bitwig and (3) we need to be more careful reading this state!

Finally just to check - when you toggle the filter mode the filter tooology actually changes right? Like if you play a note?

Thanks!

**Comment by TheNerdyMusicGuy** [comment]
That did it! Changing to another LFO seems to "update" the slider.
Filters change just fine.

**Comment by baconpaul** [comment]
Ok so this is just me missing a call to rebuild somewhere. I’ll look. Thanks!

**Comment by baconpaul** [comment]
So @TheNerdyMusicGuy can you try a nightly later tonight?

**Comment by baconpaul** [comment]
@TheNerdyMusicGuy I was able to repro this live10 / macOS and have a fix coming in (PR 3001). Should be in a nightly within an hour or so.
