### ISSUE TITLE
Freerun LFOs retrigger when no notes are playing and the transport is running

### ISSUE THREAD

**Issue by selenologist** [surge-synthesizer/surge#2998]
**Bug Description:**
A basic patch (as attached) with an SLFO modulating pitch in freerun mode should continue the LFO regardless of whether notes are held. Playing staccato should merely gate the amplitude. When Ardour's transport is stopped, Surge behaves as expected, but when the transport is running, the LFO resets when there are no notes held. Playing staccato causes the LFO to retrigger each time.

**Surge Version**
1.8.lv2-timefix.89398381 (...I'd changed branches to do a change Paul suggested but it happens with or without that change, so this is basically main.89398381)

* Version:
Both LV2 and VST3 under 64bit Linux

**Reproduction Steps:**
1. Load the attached patch.
2. Repeatedly tap a key and observe that the LFO continues as it should
3. Start your DAW transport
4. Now the LFO resets for each key

**Expected Behavior:**
Whether the transport is running, and whether notes are held, should not matter

**Computer Information:**
 - Linux 64-bit
 - Ardour 6.3-258-gb90f057e6e

[slfo-retrigger.zip](https://github.com/surge-synthesizer/surge/files/5455792/slfo-retrigger.zip)
n.b. oops, you can ignore `CausesRetrigger.mid`, this turns out not to be special

**Comment by mkruselj** [comment]
LV2 is borked in general, but I wonder if Ardour maybe implements VST3 transport handling incorrectly in some way...

**Comment by baconpaul** [comment]
I just tried the AU in LPX and it works correctly also. I do wonder if Ardour is doing the wrong thing indeed. @selenologist I'll share some debug code with you to try.

**Comment by baconpaul** [comment]
So yeah can't break this in AU / LPX nor seems can I do so in reaper / VST3 so I bet that Ardour is setting the songpos wrong

LfoModulationSource.cpp you can see there's a `double time Passed = storage->songpos * ... ` and that's the mechanism we use to shift phase away from 0 point. Obviously if storage->songpos is 0, then you will see what you are seeing.

Now the VST3, if transport isn't running, automatically advances songpos. So what you see without transport makes sense. It runs a little fake clock to make freerun work.

Songpos is updated through the following

1. In `SurgeVst3Processor.cpp` at line 451 or so we do surgeInstance->time_data.ppqPos = ... so that's the first thing to check. Is ardour setting the data.processContext flags properly (it seems it must be since we zero out the ppqPos) and is it setting projectTimeMusic properly (my guess is it is setting it to zero).

2. If those ifs trigger and projectTimeMusic is set to non-zero then there's a small chance that something is going wrong in SurgeSynthesizer:;resetStateFromTimeData, but that's really unlikely. That's a super simple function

so my guess (not being able to run ardour vst3) is that: in transport mode, Ardour is setting the playing flags on the VST3 data structure and not setting `projectTimeMusic` which is (basically) telling Surge that every block starts at frame 0. That means the catch-up code in the voice lfo won't work.

**Comment by selenologist** [comment]
Added `printf("pTM %f\n", data.processContext->projectTimeMusic);` to line 451 of `SurgeVst3Processor.cpp` and yup sure enough, I just get `pTM 0.000000` forever.

I also tried `printf("tPB %f\n", self->_timePositionBeat);` on line 142 of `SurgeLv2Wrapper.cpp` to see what happens with LV2 and yuuup, `tPB 0.000000` forever there too.

So yeah, it's Ardour's fault, this can be closed :smile_cat:

Thanks for the help diagnosing this.
