### ISSUE TITLE
Some Adjustments to VST3 Menu Rendering

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3090]
![image](https://user-images.githubusercontent.com/2393720/98521765-29563b80-2274-11eb-9669-8696295b2052.png)

As you can see, it's showing Macro 3 instead of Global Volume there. It's similar for some other parameters, like Return 1/2, Scene Mode, Split Point, Max Poly.

@baconpaul said he knows exactly what and where this is. 🙂

**Comment by baconpaul** [comment]
This is a savi bug. The VST3 spec is on parameter ID not parameter index, and we pass the right thing. Savi uses the wrong one internally to make the menu clearly (since the ID for global volume is 642 and the index is 0; but the index for macro0 os 0 but the id is 20480)

Tested in reaper and bitwig and no problem.

But it did make me realize that I forgot to turn on the macro host menus when I added indirection so doing a small PR for that.

**Comment by Arakula** [comment]
Yes, there was a SAVIHost bug; I've uploaded a new SAVIHost beta to https://www.hermannseib.com/programs/beta that shouldn't exhibit this problem any more.

_But:_ your menu handling also isn't clean.

**Problem 1:**

There's a problem in SurgeGUIEditor.cpp in SurgeGUIEditor::addVst3MenuForParams().
If you look closely at the f***ing Steinberg VST3 specification, **kIsGroupEnd** is defined as **1 << 4 | kIsSeparator** - and that is a problem, since in your code, you check for **kIsSeparator** first, and only if it is _not_ set, kIsGroupEnd is handled in the general else().
Thus, if a nested PlugIn menu is created by the host (which is perfectly valid if you pass in paramId 0), your editor ruins the layout.

**Problem 2:**

If the default menu created by the host contains strings with non-ASCII characters (as, for example, umlaut characters in a German text), these get mangled somewhere. I guess this is an unfortunate effect of using
  Steinberg::UString128(item.name, 128).toAscii(nm, 1024);
but I'd have to debug _your_ code to be sure :-) which would require quite a lot of installations (starting with VS17). So I'll leave that to you.

You should be able to test this with by current development version of VSTHost, which you can also download from https://www.hermannseib.com/programs/beta (use vsthostx64_beta.zip).

**Comment by baconpaul** [comment]
Oh that grouped thing is such a nightmare and yes that grouped is also separator thing has hurt me. In Reaper we get the right thing but appreciate the pointer.

Thanks for the other pointer. Unicode is hard. VSTGUI + unicode + cross platform is .....

**Comment by mkruselj** [comment]
@Arakula Thanks for chiming in! 🙂

**Comment by baconpaul** [comment]
I addressed both of these and tested Reaper and Bitwig (I'm still unable to install the runtime needed for me to run savi so can't actually test that.). I don't have german characters but I went form .toAscii to a codecvt_utf8_utf16 to map between the encoding that vst3sdk uses and vstgui uses. 

Thanks for the pointers @Arakula and thanks for making savi. Many of our users love it :)

@mkruselj if you wanna give it a whirl tomorrow after I merge that'd be great. Like I said tested bw and reaper lin/mac/win.

**Comment by baconpaul** [comment]
Oh FFS MSVC < 2019 doesn't properly define codecvt in a linkable fashion

https://stackoverflow.com/questions/32055357/visual-studio-c-2015-stdcodecvt-with-char16-t-or-char32-t

so I'll try something different for that code branch I guess.

**Comment by mkruselj** [comment]
OK so that latest SAVIhost beta doesn't show the VST3 host-side context menus at all anymore. Which is fine, I guess, since there are no automation facilities in it.

**Comment by Arakula** [comment]
Yes, that's precisely what should be expected. All it did, by the way, was to initialize the menu with a header line (name of the parameter + ':', greyed out) ... and it used the parameter ID as an index, as @baconpaul correctly pointed out.

I corrected that, but ... well, your PlugIn _prepends_ its own menu items instead of appending them, so apart from not really contributing anything from a functional point of view, the "header" appears at the bottom, which doesn't make much sense either. So I just removed it.

**Comment by Arakula** [comment]
I tried the current nightly build, and while it looks much better regarding nested submenus, the problem has now shifted a bit ... separator lines are obviously not treated correctly now. Look at that:
![Surge3149](https://user-images.githubusercontent.com/1124609/99253337-ddc20580-2810-11eb-8a37-39bd7315847f.jpg)
all separator lines are blank text lines now. At least they cannot be selected, which is good.
The Umlauts are OK now.

**Comment by mkruselj** [comment]
Reopening issue... @baconpaul bac

**Comment by baconpaul** [comment]
```
   enum Flags {
                kIsSeparator    = 1 << 0,                                       ///< Item is a separator
                kIsDisabled             = 1 << 1,                                       ///< Item is disabled
                kIsChecked              = 1 << 2,                                       ///< Item is checked
                kIsGroupStart   = 1 << 3 | kIsDisabled,         ///< Item is a group start (like sub folder)
                kIsGroupEnd             = 1 << 4 | kIsSeparator,        ///< Item is a group end
        };
```

it's like the one feature in VST3 I like, they still manage to make awful.

I'll take a look.

**Comment by mkruselj** [comment]
@arakula, which specificl VST3 SAVIhost should I get? I tried savihost3x64_beta.zip | 2020-11-11 23:08, but when I right click any parameter in Surge opened in SAVI, I don't see the VST3 menu at all, like you're showing in your screenshot?

**Comment by Arakula** [comment]
That's from VSTHost. Here's a direct link: https://www.hermannseib.com/programs/beta/vsthostx64_beta.zip
No installation necessary; just expand it to a new directory, run vsthost.exe (ignore the plea for donations :-) ), drag your surge.vst3 into it. Then open the editor (menu PlugIn/Window/Editor) and right-click on any item that opens a menu.

**Comment by Arakula** [comment]
If you're convinced that your code does the right thing, let me know what you think _I'm_ doing wrong. This VST3 stuff is extremely underspecified, as all Steinberg APIs since the dawn of time are (well ... at least since ~2000, when I started playing with VST hosting).

**Comment by baconpaul** [comment]
I am not convinced we are right!

**Comment by mkruselj** [comment]
> That's from VSTHost. Here's a direct link: https://www.hermannseib.com/programs/beta/vsthostx64_beta.zip
> No installation necessary; just expand it to a new directory, run vsthost.exe (ignore the plea for donations :-) ), drag your surge.vst3 into it. Then open the editor (menu PlugIn/Window/Editor) and right-click on any item that opens a menu.

Ahh! That was stupid of me, could've just tried VSThost myself. Yep, I can confirm exactly what you showcased there.


> This VST3 stuff is extremely underspecified, as all Steinberg APIs since the dawn of time are (well ... at least since ~2000, when I started playing with VST hosting).

Man, that makes me so sad... why can't they write nice, readable, usable code?!

**Comment by baconpaul** [comment]
I’ll put together a test branch for you later @mkruselj

**Comment by baconpaul** [comment]
Hey I can't get savi to run in my VM but I can get vsthost to run here. And I see the same. Lemme see if I can figure it out in the next few minutes.

**Comment by baconpaul** [comment]
<img width="820" alt="Screen Shot 2020-11-17 at 5 58 16 PM" src="https://user-images.githubusercontent.com/13387561/99460800-8601c800-28fe-11eb-997b-337a247c20b8.png">

Anyway there you go
There is no way to write that code correctly unless you know the values of the constants.
But once you know the values you can figure out the ordering of the if cascade
What a terrible API
Thanks for all your help @Arakula

**Comment by mkruselj** [comment]
@Arakula Just FYI it seems that the change you did in SAVIhost beta broke how Surge's macros work for some reason.

https://cdn.discordapp.com/attachments/744324663383031821/778571188099481600/macrosborked.gif

The index of the macros is 0,1,2,3. The ID of the macros is 20480, 20481, ... the ID of master volume is 0 1 2 the index of the macros is 689, 690, 681. I suppose there's a mixup somewhere there, because this does not happen with the version available on your website.

**Comment by Arakula** [comment]
I'll look into it.

**Comment by baconpaul** [comment]
Surge avails ourself of the VST3 option to have the int param ID != the index of the parameter when enumerated at construction into the paraminfo array. So it’s not the case that paraminfo[i].id == i. Problems like the one @mkruselj sees come when we blow it. Usually it has been me getting this wrong but we have it pretty well tested now. Hope that helps!
