### ISSUE TITLE
Next/Previous Patch could "transcend" category limits (across categories, not within category)

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#314]
currently if you are on `Bass` category preset name `WTBass` (last one in Bass category) and press `+` You will go back to `Attacky` (first `Bass` category preset).

Proposal: Pressing `+` at the last preset of a category, takes you automatically to the first preset of the next category.

Also, when in the last preset of the last category, pressing `+` will take you to the first preset of the first category. And the other way around with `-` (first preset of first category, press `-`, you are in the last preset of the last category).

@jsakkine maybe you'd like to the honours on this one?

**Comment by baconpaul** [comment]
I think this is the incorrect feature. 

The reason I think it is the incorrect feature is because patches have distinct category and patch toggles. So the patch +/- is inside the category and the category +/- is for category switches.

I think @jsakkine fix for wavetables in current form is correct, but as I mentioned on the issue, I could also imagine a future fix where we have both a < and a << under the name which change patch or category and change the display to show category

So I do not think we should do this! Sorry.

**Comment by baconpaul** [comment]
So I’m going to close this; I think with the distinct controls current behavior is correct 

If we want we can open a distinct issue to have a category display and jog on wavetables like we have in patches then make both work the same.
