### ISSUE TITLE
Turning on Tempo sync on rate slider with step seq makes all sliders within that LFO move extremely slow

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#3156]
**Bug Description:**
Turning on Tempo sync on rate slider with step seq makes sliders within that LFO move extremely slow.

Between the range  64 whole notes - whole note  its really visible and felt when moving the slider but actually this goes on on all divisions just in smaller and smaller steps as one move more to the right on the rate.

**Surge Version**
Version:	1.8.HEAD.6957460a
Build Info:	Built on 2020-11-14 at 23:56:20, using local host 'KORRIDOR'
System:	Intel CPU, Windows VST2 (unsupported), 32-bit and VST3
Plugin Host:	Image-Line Fruity Wrapper

**Reproduction Steps:**
choose any LFO
choose step seq
click on tempo sync for the rate sliders
drag rate slider around this area 64 whole notes - whole note
now drag any slider in this LFO, everything moves -very very- slow.

![66666](https://user-images.githubusercontent.com/56724286/99160470-10241380-26e8-11eb-9e35-99a1751fe0c1.gif)
(this gif is an exact representation of how it looks, its not slow fps)

Go to another shape in the same LFO only to find there is no issue with the same procedure and tempo sync on.

**Comment by baconpaul** [comment]
Oh fantastic report thanks

**Comment by baconpaul** [comment]
I bet I know what it is. At that super low rate the lfo has to evaluate for a long time to draw the white line.

**Comment by K0rrid0r** [comment]
right but i can feel its happening on all divisions when in step seq, after whole note and more to the right divisions are getting so small it feels smooth, but the same bug is actually still there. but i guess you got that!

**Comment by baconpaul** [comment]
Yeah we have to generate the white line for 16 phases. So at longer rate etc...

I bet if yo set tempo to 400bpm it also gets better but not perfect

**Comment by K0rrid0r** [comment]
yeah i just tried 999 bpm, you are right. feels smoother, but only a bit less ofc.

**Comment by baconpaul** [comment]
yeah the fix will be to ignore rate in the rendering copy

**Comment by baconpaul** [comment]
Hmm the reason we run so long is because we show the envelope on the white line in the step sequencer. Let me think of a way to scale that down so we can basically make this faster.

But from looking at it: a chunk fo this delay is just 'your computer and graphics system aren't very fast". It's just raw refresh rate and calculation of frame. On my MBP it's not a problem visually although I can indeed trap the increased time in my debug state. So a fix may still be slow. The other option, of course, is just to not show the white line at all for slow systems (have some sort of backoff: if it takes > 1/10th second to calculate the white line suppress it going forward or some such).

**Comment by K0rrid0r** [comment]
now i understand what's going on even more.. i had dragged down the project bpm to 15 bpm only to hear everything evolving really slow together with the surge modulations. 

now i notice that this issue ive posted becomes apparent on very slow bpms. i never noticed that before. so this is not really a bug. still a bit to slow and wierd behavior from the slider i think, could maybe be rendering a bit faster even if tempo sync is on and bpm is very low. what do you think?

**Comment by baconpaul** [comment]
Yeah I have a few thoughts and will put together a test branch for you this week. I already have some
Optimizations in place for non temposync so carrying them over and giving you a branch to test makes sense

**Comment by baconpaul** [comment]
oh i can mac my mac explode also if I just set things a few tens times larger than the cutoff and set my bpm super low. And the code is flooring out rate before temposync not after. so this is clearly the problem. Will fix this week. Nice find.

**Comment by baconpaul** [comment]
(The problem, by the way, is that to draw the white line we need to run the step sequencer for 16 steps. If your temposync is on 4 measures and your bmp is 10bpm or whatever, then 4 measures * 16 / 10 = 5 and a half minutes of LFO run time for each repaint. So that's why it lags. LOL. Obviously put in a cap and then your envelope will render incorrectly but your LFO won't drag).
