### ISSUE TITLE
High pass and Low pass filters in the oscillators needs limit_range

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#3238]
**Bug Description:**
modulating them too much will lead to loud -1, 1 clipping sound.

here is a preset that exhibits that specific sound, just deactivate the active low pass and it' gone.
[needs a limit range in OSC 1 Low Cut.zip](https://github.com/surge-synthesizer/surge/files/5603153/needs.a.limit.range.in.OSC.1.Low.Cut.zip)

the team knows what to do.

**Comment by baconpaul** [comment]
Just a note on how to do this (since I'm not doing it this morning)
there's an `applyFilter` in Sin, Window SampleAndHold and AudioOscillator

Has code like this

```
if (!oscdata->p[sin_lowcut].deactivated)
      hp.coeff_HP(hp.calc_omega(localcopy[oscdata->p[sin_lowcut].param_id_in_scene].f / 12.0) / OSC_OVERSAMPLING, 0.707);
```

that code should change to something like this (which i have typed into GitHub not a compiler)

```
if (!oscdata->p[sin_lowcut].deactivated) {
      auto par = &(oscdata->p[sin_lowcut]);
      auto pv = limit_range( localcopy[par->param_id_in_scene).f,  par->val_min.f, par->val_max.f );
      hp.coeff_HP(hp.calc_omega( pv / 12.0) / OSC_OVERSAMPLING, 0.707);
}
```  

for high pass and lowpass for the four oscillators with the param ids appropriately changed

Then give it a whirl with the test patch and you should be good.
