### ISSUE TITLE
Only the first word of LFO presets can be capitalized

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3285]
When saving LFO presets, only the first word can be capitalized.

1: Save a preset with the name "Thurston Waffles".
2: Try to load the preset.
3: Notice how it's now called "Thurston waffles", with a non-capitalized "waffles".

Version: 1.8.nightly.186fab3
Build Info: Built on 2020-11-29 at 00:21:03, using pipeline host 'WIN-NSSBUUS6UC1'
System: Intel CPU, Windows VST3, 64-bit
Plugin Host: Ableton Live 10.1

**Comment by baconpaul** [comment]
Ha the reason for this is because we make the menus OS case specific and on windows the guidelines say "This is a menu cap". 

@mkruselj think since this is showing files we should take out the toOsCase at line 4862 of SGE? I kinda think we should (and that would immediately fix @TheNerdyMusicGuy 's problem).

**Comment by mkruselj** [comment]
Yes preset names should respect original letter cases. But toOSCaseForMenu should still apply to all other menu entries.
