### ISSUE TITLE
confusing differences between windows and osx building re: where the actual plugins are placed.

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#331]
Situation:
You are a Windows builder and the `Surge.dll` and `Surge.vst3` builds "have always" built to

```
C:\Users\usernamehere\repo\target\vst2\Release
C:\Users\usernamehere\repo\target\vst3\Release
```

Then you go and compile on macOS for the first time, and turns these folders are full of dylibs, and the `Surge.component`, `Surge.vst` and `Surge.vst3` are actually in

`/Users/usernamehere/repo/products`

For the sake of making documentation easier, would it be possible to fix both or either so that they are always in the right places?

Or is there some operating system-specific reason why they are in different places?

**Comment by baconpaul** [comment]
There is some operating system specific reason why they are in different places.

**Comment by baconpaul** [comment]
(the reason is that target\... is the end of the build process of the dynamic library; for mac to package into a compent there is an additional step; we could if we wanted have windows make a product directory and just do a copy but have not yet; if you would like to add that as a post stage in premake go for it! I get around this by having my windows build script copy the right assets and others have made installers which use the right location)
