### ISSUE TITLE
Ableton Live Lite User cannot open VST3 on Windows

### ISSUE THREAD

**Issue by Tinkymon** [surge-synthesizer/surge#3354]
Hi,

Not sure where to ask or find information regarding this. I downloaded the installer for Windows 64-bit VST3. When i ran the installer I could not select the file to save it to - it automatically put it in programme data instead?  Because of this I cannot find it from my Ableton Live 10 Lite programme. Any suggestions?

**Comment by baconpaul** [comment]
**Q:  Where is Surge synthesizer installed on Windows?**
A: Surge is installed to the default VST3 plugin path, which means:

32-bit path - C:\Program Files (x86)\Common Files\VST3\Surge Synth Team
64-bit path - C:\Program Files\Common Files\VST3\Surge Synth Team

We advise you to NOT move the plugin to any other folder on your system. We also advise you not to move the C:\ProgramData\Surge\ folder anywhere else, or bad things will happen!


**Q: Surge doesn't show up in Ableton Live!**
A: First, make sure you are running at least Live 10.1 in order to be able to load VST3 plugins. Live didn't support VST3 plugins prior to this version. Second, make sure you have Preferences->Plug-ins->Use VST3 Plug-In System Folders option set to ON.


Does that help?

**Comment by Tinkymon** [comment]
AMAZING! I was looking all over for it :) Thanks so much :+1:

**Comment by Tinkymon** [comment]
> **Q: Where is Surge synthesizer installed on Windows?**
> A: Surge is installed to the default VST3 plugin path, which means:
> 
> 32-bit path - C:\Program Files (x86)\Common Files\VST3\Surge Synth Team
> 64-bit path - C:\Program Files\Common Files\VST3\Surge Synth Team
> 
> We advise you to NOT move the plugin to any other folder on your system. We also advise you not to move the C:\ProgramData\Surge\ folder anywhere else, or bad things will happen!
> 
> **Q: Surge doesn't show up in Ableton Live!**
> A: First, make sure you are running at least Live 10.1 in order to be able to load VST3 plugins. Live didn't support VST3 plugins prior to this version. Second, make sure you have Preferences->Plug-ins->Use VST3 Plug-In System Folders option set to ON.
> 
> Does that help?


I thought it did, but for some reason my Ableton cannot see the VST3 file still, though you showed me the correct path?

**Comment by baconpaul** [comment]
Yeah and to be sure: You are running live 10.1 or later? And you have loaded other VST3 plugins into your live session successfully?

**Comment by baconpaul** [comment]
Here’s the abelton doc: https://help.ableton.com/hc/en-us/articles/209071729-Using-VST-plug-ins-on-Windows

**Comment by baconpaul** [comment]
Hi I'm going to assume this helped you solve your problem. If not please reopen the issue.
