### ISSUE TITLE
Manual updates

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#3456]
Just a place for everyone to report new features / changes that need to be added in the manual that aren't in the nightly changelog, or things that would need clarification, so we can keep track of it :)

**Comment by VincyZed** [comment]
We should mention in the manual that modulation of attack, portamento, and other trigger times when they are exactly zero can fail, as the attack, portamento, etc... will complete before the modulation takes effect, and to set them to a very small value instead.

**Comment by mkruselj** [comment]
@VincyZed We should explain the relevance of LFO EG for scene LFOs better in the manual. This is especially important for MSEGs, because with MSEG looping disabled, the envelope will only really start at the beginning of the project and never retrigger - Paul says this is ok and consistent, so reducing the LFO EG Release from "infinite" to a lower value is the remedy apparently.

Discord chat reference: https://discord.com/channels/744319641211633774/744320274714984518/798891108242423838
