### ISSUE TITLE
Modulation of portamento not working when portamento set to zero

### ISSUE THREAD

**Issue by williamfields** [surge-synthesizer/surge#3476]
When portamento is set to zero, modulation of portamento has no effect. Set portamento to a very small value, and it works again.

Version:	1.8.nightly.6b81fcb
Build Info:	Built on 2020-12-17 at 15:51:10, using pipeline host 'WIN-9R6KBPQ9SKP'
System:	Intel CPU, Windows VST3, 64-bit
Plugin Host:	REAPER

**Comment by TheNerdyMusicGuy** [comment]
Possibly related to https://github.com/surge-synthesizer/surge/issues/2650?

**Comment by mkruselj** [comment]
Very likely related to that issue, yeah.

**Comment by baconpaul** [comment]
Yeah looking at the code I think it is exactly the same thing.

Let me tag this into 19. I couldn't figure out a good fix for #2560 and don't know a fix to this, and there's a workaround.

@VincyZed we should mention in the manual that modulation of attack, portamento, and other trigger times when they are exactly zero can fail, as the attack, portamento, etc... will complete before the modulation takes effect, and to set them to a very small value instead.

Should fix this in 19. The fix isn't easy since you have to topologically sort the modulators and deal with cycles (what if AEG modulates portamento etc...)

**Comment by VincyZed** [comment]
OK!

**Comment by djtuBIG-MaliceX** [comment]
> will complete before the modulation takes effect, and to set them to a very small value instead.

I seem to recall other synths such as audjoo Helix took this approach as well, where it locked minimum portamento time to like 0.0001 instead of 0 (perhaps to disguise a bug?).

**Comment by mkruselj** [comment]
I don't think we can make that change due to patch support.

**Comment by mkruselj** [comment]
Closing this one in favor of #2650.
