### ISSUE TITLE
Wavetable needs a new Format for .wav files.

### ISSUE THREAD

**Issue by artyfunk** [surge-synthesizer/surge#3583]
I want to create a Wavetable Package but Surge uses the same old Wavetable engine like in the past.
Iam Arty who created the old Wavetable Package and the FX Presets for Reverb and some others.

I thinking for the new Wavetable engine it would be nice to go on 32Bit FLOAT and 2048 Samples for Loop Function and complete Samplelength should be 4096 Samples.

and maybe you can set the Frequency rate: 48000Hz.

This is the most important feature i think what surge need right now! Because the Wavetables create the sound. And this make THE difference.

I noticed that surge is distortiing the wav files. Maybe you can fix that too.

tell me if this is possible ? i think yes when you look at other Synthesizers like Arturia Pigments 2.

Please, tell me what the Develeopers think of this big improvement / idea?

**Comment by baconpaul** [comment]
Thank you for your contributions to surge!

So: We agree because we've already done many of these things! With a wav file and I think with a wt file you can go up to 8096 long tables now. With wav you need to give it proper tags but it does work.

SampleRate is kind of irrelevant I think since you have 'one cycle per table' and the sample rate is ignored. Surge runs fine at 96k and 2x oversampled anyway and will select and generate a bit stream from the table in a SR appropriate way.

There's a couple of types of distortion. The first is the DAC emulation (which isn't distortion; its a feature; but for very low count wavetables adds lots of noise). The second is truncating to i15 internally in some cases BUT for the wavetable oscillator in the source now, it uses F32 (just if you give it i16 it expands in a slightly distortive way). So a 8092 F32 wavetable should work fine and be full 32bit (in the Wavetable oscillator; the Window oscillator uses the I16 representation).

**Comment by mkruselj** [comment]
Yeah, Surge already supports 32-bit floating point wavetables and frame sizes up to 8192.

Do note that such wavetables, especially if they have a large number of frames, will greatly increase the size of the resulting patch (because wavetables are stored inside the FXP file).
