### ISSUE TITLE
./build-linux.sh

### ISSUE THREAD

**Issue by jarkkojs** [surge-synthesizer/surge#360]
Implement ./build-linux.sh that compiles Surge and copies configuration.xml, presets and wavetables to their locations.

**Comment by baconpaul** [comment]
Oh hey @jsakkine when you do the final sweep with your last step, can you also update README.md. @esaruoho did a first pass but getting it all ship shape for linux would be lovely. Thanks!

**Comment by jsakkine** [comment]
@baconpaul, sure

**Comment by falkTX** [comment]
For the linux builds, I really recommend updating vstgui to the latest version (which means your own vst3sdk repo, because vstgui is a submodule of this submodule..)

Current "stable" vstgui uses gtk3 for window and event management on Linux, which is pretty terrible.
It brings an entire big system toolkit for a plugin UI, which is supposed to be self-contained in the first place. (there are far too many reasons why gtk, or similar system/generic toolkits are bad ideas for plugins)
As it is, the plugin will fail to load (I mean, crash the host) when loaded in a few Linux hosts.

vstgui on its develop branch is going in the right direction, now using just cairo and xcb.

I got it built myself locally by using a slightly older git commit of vstgui (absolute latest has some API changes regarding menus that I did not look into).

**Comment by jsakkine** [comment]
Switching to a newer VSTGUI is not an issue associated now we do Linux builds, or how we package. Lets not associate orthogonal problems with each other. I agree that getting rid of GTK would be nice, though.

**Comment by falkTX** [comment]
I understand that this specific ticket is about the packaging.
It is still related a bit, because we will have to switch libraries used for linking.
I created the other ticket so we can leave updated-vstgui stuff there anyway.

Please note, if we do linux builds with the current state, it will be dangerous for users that try it.
Packaging as-is will result in a broken plugin.

**Comment by jsakkine** [comment]
This not really a packaging issue, just a build script, and missing still presets and wavetables. Can you define what you mean by user? There is nothing too dangerous in that script, and it is not meant for end users.

**Comment by esaruoho** [comment]
is the packaging finished or still under way? just wondering if this ticket can be closed or still under works? @jsakkine
