### ISSUE TITLE
Link left/right times in delay FX

### ISSUE THREAD

**Issue by artyfunk** [surge-synthesizer/surge#3613]
Problem is: everytime when using the delay-time and change the Frequency or Temposynced Steps the Left and Right Channel needs to be moved individually. It would be a great when there would be and Link Button for the Left & Right Channel. Then it could be moved simultaneously.

The advantage: easy to use and very quick to setup or change.

**Comment by mkruselj** [comment]
It's probably easier to add this as a right-click option.

**Comment by artyfunk** [comment]
its okay right click will work for me

**Comment by mkruselj** [comment]
Note to @baconpaul: I envision this working exactly the same way as Resonance 2 Link button works (except we would have it under right click option rather than a physical button). So, we toggle the link, delay time right slider goes semitransparent (it still reacts to any mouse interaction, but the value is not applied in the delay per se), and in delay FX code delay time left value is used for both L and R. Should be an easy early 1.9 addition?

**Comment by baconpaul** [comment]
If it was exactly like Resonance 2 link, the slider would stay active and become bipolar an be offset. That would also be cool it seems to me!

**Comment by mkruselj** [comment]
That's Cutoff 2 Offset, not Resonance 2 Link 😉

**Comment by artyfunk** [comment]
version 1.9 will be interessting !
