### ISSUE TITLE
Ubuntu snap packaging

### ISSUE THREAD

**Issue by jsakkine** [surge-synthesizer/surge#365]
I think in 1.6.0 timeline we should prioritize packaging for Ubuntu with snap: https://tutorials.ubuntu.com/tutorial/basic-snap-usage. After 1.6.0 we can also implement FlatPak, which is used by other distributions, but I think it would be a good compromise to make Surge work great on one popular operating system first.

**Comment by jsakkine** [comment]
https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0

**Comment by baconpaul** [comment]
Yeah! If people complain we should have used flatpak we can always point them at the pr page! I think “make a choice” is the right choice.

**Comment by jsakkine** [comment]
https://docs.snapcraft.io/snap-documentation/3781

**Comment by jsakkine** [comment]
I use Ubuntu in all my Linux machines, and I don't get paid for this work, so that's how it kind of goes :)

**Comment by jsakkine** [comment]
And this is how we can invoke premake5: https://forum.snapcraft.io/t/scriptlets/4892

**Comment by baconpaul** [comment]
ExCtly! That’s how I feel about 32 bit Mac too.

**Comment by jsakkine** [comment]
And just found out that you can build snap packages also on macOS: https://forum.snapcraft.io/t/building-the-snap-on-mac/6751

**Comment by jsakkine-intel** [comment]
Snap's are similar to macOS package e.g. they contain the environment to run the app. The way the package is built is either inside VM or Docker. The macOS version uses a Docker image to build the package AFAIK. That's how it can build Linux package inside macOS. Kind of handy because you can develop the packaging recipe inside host, and do not have work on it inside a VM. VM is needed just for testing.

I'm now converging to a Linux build for a while from a different direction. I'll finalize the build script and create packaging so that we have a deployment process. Only after that I focus on code level issues. This should also help @whydoubt to look at Linux things (and anyone else who is interested).

**Comment by jsakkine** [comment]
Closing this because Ubuntu is managed with .deb. Good enough. Will open later FlatPak issue (when I actually start doing something).
