### ISSUE TITLE
Non-Unicode author names stored in FXPs

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3672]
See attached example.

[Unicode author name in patch.zip](https://github.com/surge-synthesizer/surge/files/5836007/Unicode.author.name.in.patch.zip)

![image](https://user-images.githubusercontent.com/2393720/105038180-49b62980-5a5f-11eb-874b-d103be4fce03.png)

**Comment by baconpaul** [comment]
So this is not a unicode problem. You can totally store unicode author names in FXPs

![Screen Shot 2021-02-10 at 11 42 14 AM](https://user-images.githubusercontent.com/13387561/107541347-09952300-6b95-11eb-882c-276e6e681de0.png)

I think this particular problem is that the user used UTF-16 although when I load that patch it has no author at all.

So I'm going to close this since

(1) it works now with UTF-8
(2) the port to JUCE will give us better UTF-8 protection everywhere
