### ISSUE TITLE
Sound sometimes cuts out when switching to Wide mode

### ISSUE THREAD

**Issue by TheNerdyMusicGuy** [surge-synthesizer/surge#3683]
When switching to the "Wide" filter routing, the sound sometimes cuts out with a loud burst of noise.

1. Load the preset
2. Switch back and forth between the S2 and wide filter routings a couple of times while playing some notes
3. Notice the bug happening

The sound seems to come back after some time.

I'll try to pin this down further, if I find the time, but I just wanted to report things for now before I forget again.

[Wide Bug.zip](https://github.com/surge-synthesizer/surge/files/5847335/Wide.Bug.zip)

Surge Synthesizer
Plugin Host: Ableton Live 10.1
System: x86 CPU, Windows VST3, 64-bit
Build Info: Built on 2021-01-21 at 01:31:57, using pipeline host 'fv-az95-512'
Version: 1.8.nightly.b7c72a6

**Comment by baconpaul** [comment]
So here's what I think is happening

When you run in wide mode it uses twice as many filters obviously (one per channel)
When you switch to S1 those other-side filters are unused
so when you switch back those filters have the state from their last activation; you give them some new signal; that discontinuity looks like 'uninitialized' state; the filters crash out for a bit

The fix for this is: when switching into a stereo mode from a mono mode, re-init the stereo side voice filters at 0.

We don't really have a hook in the code where we can do that surgery easily now though so I think this one will have to roll to 1.9. it's a moderately big change to find and re-initialize those filters (and make sure we get the right ones).

**Comment by TheNerdyMusicGuy** [comment]
Sounds good to me. This seems to be relatively rare. It only seems to happen with that specific patch, it never happened the many, many times I performed that action before.

I tried to make it happen with a simpler patch, but I couldn't quite figure it out yet.

**Comment by mkruselj** [comment]
Linking this to #4355.

**Comment by mkruselj** [comment]
Right so in XT2 this will be a non issue since we're moving to nodal filter routing and all filters are gonna be stereo all the time.

**Comment by mkruselj** [comment]
OK so I am going to close this one since we know we're gonna be all stereo all the time in XT2.
