### ISSUE TITLE
Windows protected your PC warning?

### ISSUE THREAD

**Issue by hems** [surge-synthesizer/surge#3692]
**Bug Description:**
just downloaded latest binary and got this message, is it expected?

![image](https://user-images.githubusercontent.com/27327/105454223-6a59cb80-5c79-11eb-9925-e97fa11c19e0.png)

**Computer Information (please complete the following information):**
 - OS: Windows 10

**Comment by mkruselj** [comment]
False positive, just Run anyway.

**Comment by papernoise** [comment]
I'm getting this as well on WIndows 11 (with Surge XT 1.3.2, but I think also with previous versions).
It's a bit annoying but I think this is because the installer is not signed, isn't it? That's why the developer is shown as "unknown". Having some checksums (eg. sha256) to check if the downloaded files are actually what you think they are would be really handy btw. you can't really trust anything anymore nowadays.

**Comment by baconpaul** [comment]
Yeah our build is a day old so hasn’t built any trust with the virus scanners 

as to trust - our whole build pipeline is available for record (but yeah checksums would be a good idea to add) but if you don’t want to trust our binaries you can build from source easily on all platforms 

Microsoft is in process of making windows signing as easy as macOS so there’s a chance we might sign windows this year but right now we can’t indeed

**Comment by papernoise** [comment]
Thanks a lot for your reply and for clearing this up! That's good news about the signing on Windows!
The virus scanner thing makes sense. Windows can be really opaque when it comes to these security things, sometimes making them more of an annoyance than a help to be honest.
