### ISSUE TITLE
MSEG hover path drawing bug when scrolling

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#3697]
![mseg scrolling hover path bug](https://user-images.githubusercontent.com/2393720/105574574-d9ace980-5d65-11eb-8af4-e4d5cf97ec73.gif)

**Comment by baconpaul** [comment]
The reason this happens FYI is because of the thing where the hover segment misses ‘point 0’ when you have very steep curves. the trick will be to know whether i am scrolled off screen before adding that extra phantom point. pretty easy change should be able to get to tomorrow. Just an if at the start and end of hoverpath looking at axis bounds.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/4f7fddc7a55e39b0bfd96f211fa9657990750e95/src/common/gui/MSEGEditor.cpp#L1134

That’s the line that needs to be zoom aware basically.

**Comment by baconpaul** [comment]
And the end line above it also. Should give a similar bug when scrolling off the other side
