### ISSUE TITLE
retain zoom settings in plugin configuration across multiple plugin instances

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#374]
Suggestion:
When you have set your plugin to 200% and are happy with that zoom, the next time you load an instance of Surge, it could also default to 200%.

So some sort of cookie or a cache or a configuration flag that defines it to be  zoom type X

path to #305

**Comment by sense-amr** [comment]
why wouldnt you just set it each time ? i mean i could understand it being "saved" in a song as a "setting".. or as part of a patch used in a song, but i dont really understand why you would want to force a zoom each time you load Surge ..

**Comment by esaruoho** [comment]
If Logic worked like this, where you'd have to re-create screensets every time you load the logic song template, people would go "hey, why do i have to re-create my screensets even though i load this logic song template?" Surge could also stash some settings, easily, surely? @baconpaul

**Comment by baconpaul** [comment]
Funny on my handwritten notes about all the steps to zoom being done, I have "User Defaults" as a step because I was thinking users would want a default. (I also have "integrate with logic positional and size saving" as one too which we don't do now).

So let me add that overall "User Defaults" issue now and link this one too it and tag them both path to zoom and the other one design required.

**Comment by esaruoho** [comment]
the good bit about user defaults is, if you don't want it changed, don't change the default.
if, however, you do want it changed and retained.. it's there.

so i mean, yeah.

**Comment by baconpaul** [comment]
Yeah checkout #375 for my thinking.

I guess I should get the rest of my thoughts into issues one day soon.
