### ISSUE TITLE
Ardour can’t spawn zenity

### ISSUE THREAD

**Issue by unfa** [surge-synthesizer/surge#3790]
**Bug Description:**

Following controls do nothing:

* Wavetable → Load From File...
* Menu → Open User Data Folder...

Any pretty much anything else regarding interacting with an OS's file manager or file selection dialog.

**Surge Version**

* Version: 1.8.1.9de9336
* Plugin Type: VST3
* Bitness:  64-bit

**Reproduction Steps:**
1. Change an oscillator to WT
2. Select "Load from File..."
3. See that nothing happened.

**Expected Behavior:**
A file selection dialog should open (and used to do that in an older version)

**Computer Information (please complete the following information):**
 - OS: Manjaro Linux KDE edition
 - Host: Ardour
 - Version: 6.5

**Comment by mkruselj** [comment]
Do you have Zenity instealled. File browsing operations in Surge for Linux require Zenity.

**Comment by unfa** [comment]
I do have Zenity:

```
$ zenity --version

(zenity:75323): Gtk-WARNING **: 13:09:21.984: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
3.32.0
```

**Comment by baconpaul** [comment]
Yeah this is incredibly frustrating. Ardour uses gtk2 and modifies the runtime environment in a way which makes zenity non launchable. The Ardour devs suggest first of all not launching external programs at all but since linux isn’t a desktop so there is no consistent way to pop a file open dialog so we have no choice. So then suggest special casing a script for Ardour if we want to launch sub programs but surge has no place to install that script. So we need our c++ layer to push the plugin layer out of the plugin into the open and then set a path but only for Ardour etc...

I keep hoping someone in the linux community will actually help us fix this issue! But that hope ends up with open issues but no prs. So let me tag this into 182 and see if I can do something acceptable

**Comment by unfa** [comment]
Maybe Ardour could intercept and translate such calls to make them work?

**Comment by baconpaul** [comment]
nah. They've told me multiple times that they won't.

I have to hack hackety hack hack inside surge to provide ardour users a file open dialog.

I'll do so though. It's just frustrating how pointlessly hard it is to give linux users the same experience that we can give mac and windows users.

**Comment by baconpaul** [comment]
sigh and even better of course, in self built ardour it works because the environment and paths are different. What a pain.

**Comment by baconpaul** [comment]
and to download the built one the ardour team needs me to type my email into a website or pay.

**Comment by baconpaul** [comment]
Anyway I've now done that. @unfa if you look in your stdout you will see a message like this

```
zenity: symbol lookup error: /lib/x86_64-linux-gnu/libsecret-1.so.0: undefined symbol: g_input_stream_read_all_finish
```

which is what happens when you run zenity (a gtk3 app) in an environment which has been hacked to run gtk2 (which is what ardour does). That's the bug that needs fixing.

**Comment by baconpaul** [comment]
OK PR #3792 puts a bunch of 'if Ardour' into the codebase so now I can open a file.

Will merge once it passes CI and it will be included in 1.8.2.

**Comment by jpcima** [comment]
This is fixed in upstream Vstgui, I pushed the fix there that addresses zenity in Ardour.
one has to unset `LD_LIBRARY_PATH`, which makes zenity load the bundled Ardour Gtk instead of the system one.

**Comment by baconpaul** [comment]
Yeah I did exactly that in our loader. 

We are moving off VSTGUI as fast as possible though. Our JUCE port is underway. So I just stuck it into our direct zenity calls.
