### ISSUE TITLE
No sound make latch patches in factory or 3rd part library please!

### ISSUE THREAD

**Issue by itsmedavep** [surge-synthesizer/surge#3816]
So, I was just switching patches testing stuff. 

Then I came across a patch that had latch turned on. Which then emitted a very loud sound out of my speakers because I was not expecting to make noise and had forgotten how much the volume was turned up. 

Regardless, you could probably save some speakers and some hearing by moving these over to their own category. Then a user would know to expect auto sound creation for those patches.

Just a thought.

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/106968413-0dfead80-6749-11eb-980e-4bc1916a2bf0.png)

Actually we only have very few patches that have "hidden surprises" in store, and others require latch for purposes of audio input, so we will just resave those patches using regular Mono instead of Latch play mode. Easy peasy!
