### ISSUE TITLE
UI zoom level problems in REAPER

### ISSUE THREAD

**Issue by williamfields** [surge-synthesizer/surge#3834]
**Bug Description:**
UI zoom is not behaving properly in REAPER. My default zoom level is set to 150%, and I would like it to be fixed at that level, but the zoom jumps around when I change presets or resize the parent FX window. See the video below for an example.

**Surge Version**
Surge Synthesizer
Plugin Host:	REAPER
System:	x86 CPU, Windows VST3, 64-bit
Build Info:	Built on 2021-01-27 at 12:54:59, using pipeline host 'WIN-T8F93AN0SJV'
Version:	1.8.1.9de9336

**Reproduction Steps:**
1. Set default zoom level to 150%.
2. Change presets and/or window size.

**Expected Behavior:**
Zoom level should always stay at 150%.

**Screenshots:**
![zoom problems](https://user-images.githubusercontent.com/9380730/107121585-42fe2380-6861-11eb-902b-0369d85e7016.gif)

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: REAPER
 - Version: 6.21

**Comment by baconpaul** [comment]
So VST3 provides a drag-to-resize handler which we implement. This is kind of the expected behavior 

You want a mode where you resize the window and surge *doesn't* resize?

**Comment by baconpaul** [comment]
the preset is weird though

**Comment by williamfields** [comment]
Hmm... I just want Surge to stay at the same zoom level (150%), regardless if I load a preset or adjust the FX window size. (Note that the FX window is shared with other plugins, so I may need to adjust the size.) 

Maybe there could be an option in the zoom settings for "Zoom level automatic based on parent window size"? And otherwise always follow the fixed percentage setting?

**Comment by mkruselj** [comment]
> 
> 
> the preset is weird though - oh that's because of the zoom state having to live in the editor to remember it and getting streamed. Sigh. That's hard to fix.

I have an easy fix, we've talked about this already. We shouldn't save zoom in DAW state anymore, but to user config XML instead. All instances on a perticular system should have the same zoom level, and loading a DAW-saved preset shouldn't change zoom levels as a consequence.

This shouldn't be too hard? Just disregard zoom level when loading DAW state, and only refer to the default zoom level as stored to user config XML?

**Comment by baconpaul** [comment]
Yeah a “default no matter what dagnabbitt” zoom setting which ignores all other attempts to set the zoom other than to the user default. That’s basically what you want right?

**Comment by baconpaul** [comment]
> > the preset is weird though - oh that's because of the zoom state having to live in the editor to remember it and getting streamed. Sigh. That's hard to fix.
> 
> I have an easy fix, we've talked about this already. We shouldn't save zoom in DAW state anymore, but to user config XML instead. All instances on a perticular system should have the same zoom level, and loading a DAW-saved preset shouldn't change zoom levels as a consequence.
> 
> This shouldn't be too hard? Just disregard zoom level when loading DAW state, and only refer to the default zoom level as stored to user config XML?

So we need to save it someplace so that when you open and close your editor the zoom state stays.

But I think what we really want is the “default no matter what” zoom setting which no matter what you do always sets the zoom to the default. Either zoom is system-wide or it is instance-wide. It can’t be a mix and match. We could also have an instance wide option to not save it in the streamed state. That means some open/close operations would change your zoom back to the default.

**Comment by mkruselj** [comment]
We already store default zoom level to user config XML, though? That's the only one that should ever be used, really.

**Comment by baconpaul** [comment]
One of the biggest complaints we got about the first zoom implementation by the way was “i set up this session with these zooms and when I restart my session the zooms are all gone”. So we should definitely make this a user behavior option. 

But sure we can just have that bug come back and use the user config XML! I’m fine with that.

Or we can add a user option to choose what to do.

**Comment by baconpaul** [comment]
> We already store default zoom level to user config XML, though? That's the only one that should ever be used, really.
> 
> This is also how any other plugin that has zooming works, that I know of. Which also means, if you drag the edge to resize, that should also update the zoom level in user config XML. This is also how other plugins work (i.e Valhalla, TAL...)

If you want to do this then

1: Modify the stream / unstream of DAWExtraState to not push or pop from the XML
2: LEAVE the zoom in the DAWExtraState memory though otherwise open/close the window operations will reset you to default zoom in reaper.

That will solve the defaulting. 

The next thing you want to do to solve this issue is to add an option to ‘ignore resize on window drag’ which would stop calling setZoomFactor in the VST3 onResize operator. That should be a user option.

**Comment by mkruselj** [comment]
Yeah so I just tried TAL and Valhalla, setting different instances to different zooms. This worked while the session was active, but when I saved it then reopened, only last set zoom level was used. These are both JUCE plugins, so we're heading in that direction. Might as well just do the same thing they are doing.

**Comment by baconpaul** [comment]
OK well I outlined how to do it! Basically write dont read. And make a user option in the onResize.

I always thought drag to resize kinda sucked anyway myself! But I use the AU which doesn’t have it :)

**Comment by mkruselj** [comment]
@williamfields As you can see, this issue is in the process of being resolved. One of incoming nightlies will have the issue fixed - zoom level will not change anymore when loading different patches. Only the zoom level stored in userconfig.xml will be used for all instances of Surge (except when you manually change them, but they will all fall in line to the stored zoom level on next project load, or an undo operation).

**Comment by williamfields** [comment]
@mkruselj Thank you!
