### ISSUE TITLE
Cannot move window after selecting preset

### ISSUE THREAD

**Issue by sagantech** [surge-synthesizer/surge#394]
Select a preset from the popup menu (windows) and then mouse capture prevents the window from being moved.

**To Reproduce**
1. Go to surge
2. Click on preset and select one
3. Now click on surge title bar and try to move it.
4. Fails because of bug in VSTGUI and can be fixed by the following code:

win32frame.cpp line 945:
 { // js: this is wrong for track popup menu, in surge after selecting preset cannot move window via title bar
         if (GetAsyncKeyState(VK_LBUTTON) < 0)
            SetCapture(getPlatformWindow());
      }

**Expected behavior**
You should be able to move the window.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Host: Metro
 - Version: 7.3

**Comment by sagantech** [comment]
Did you try it?

**Comment by esaruoho** [comment]
@sagantech i don't have access to 32bit windows. but maybe you do? :)

**Comment by sagantech** [comment]
Sorry but now that debugging is so slow it is unlikely that I will be working with this version. See here: https://github.com/surge-synthesizer/surge/issues/505

**Comment by baconpaul** [comment]
I just tried this with 64 bit surge vst2 in bitwig. The behavior I see is

1. I can move the window normally
2. I chose a patch with the menu
3. I then click on the window decoration bar to move the window and I cannot move the window
4. I then click on the window decoration bar again to move the window and I can move the window

So the problem is real and still there @esaruoho 

At least in the bitwig host it somehow cures itself after the first mis-eaten click. I didn't try other hosts.
