### ISSUE TITLE
AU Preset Names

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#405]
currently, for instance, Logic or Live do not show the "currently selected surge preset name" in the daw.

**Comment by baconpaul** [comment]
From slack

```
baconpaul [2:33 PM]
We need to raise a PropertyChanged(kAudioUnitPropert_CurrentPreset, kAudioUnitScop_Global, 0 )

Sagantech [2:33 PM]
Yes
UpdateDisplay should do that no?

baconpaul [2:34 PM]
Right now update display does less than you would think in AU…

esaruoho [2:34 PM]
i gotta get back to playtesting for shekels-> (edited) 

baconpaul [2:35 PM]
But there’s no mechanism by which that is raised in the AU updateDisplay path
basically
```

**Comment by baconpaul** [comment]
OK so this is a bit more complicated than PropertyChanged; the way the AU implements the preset handling is incomplete in our current aulayer. If I fire the property change (with PresentPreset which is the new name) I get all my logic tracks go to "untitled" because I don't handle the setting of preset into aulayer state properly. This one is a bit trickier than thought.

**Comment by baconpaul** [comment]
Alright in AU right now and latest logic pro we see the presets

but it still doesn't reflect in track name when you change it in logic. So we are close but not quite there.

**Comment by baconpaul** [comment]
Current status:
- works
- has a lag in logic if you use the internal preset browse buttons and I don't know why
- needs to sort and name the presets better - don't use preset order list; only use factory
