### ISSUE TITLE
FX drop downlist does not scroll 

### ISSUE THREAD

**Issue by muziker** [surge-synthesizer/surge#4062]
**Bug Description:**
In the drop down list for FX additions, the drop down list doesn't create a scrollbar or scroll downwards when the last item is highlighted. The user has to manually scroll down with the arrow key

**Surge Version**
1.9main.251000e4
 
* Plugin Type: VST3
* Bitness: 64Bit

**Reproduction Steps:**
1. Click a global fx box
2. Scroll to select an fx in the drop down menu
3. The menu does not scroll to the end, or indicate there are further selections
4. Use arrow keys to scroll further the selection list
5. The selection randomly elects to go a menu selection deeper even when using keyboard arrows

**Computer Information (please complete the following information):**
linux, carla

**Comment by baconpaul** [comment]
@tank-trax do you see the same? I thought we had mostly cleaned up the vstgui menus to a point of being  'basically acceptable' but this sounds like maybe we missed some.

**Comment by tank-trax** [comment]
will test this and get back in a bit

**Comment by tank-trax** [comment]
same thing here and only on the FX menus, scroll works but left and right arrow are dead when going to a sub-menu... can't use the arrows to get back to the top level, arrows only work on the submenu

Ahhh I see the issue... the mouse actions are inverted

pressing left arrow does what right should do and vice versa

so actually it works... just not as intuitively as humans may like

@muziker 

when the menu is active up and down arrow will move around the elements

to use arrows to expand sub-menus, using right or left will expand, once expanded use up and down to highlight elements in the sub-menu

on the menus that hug right, as they expand left... the Arrows in the Menu are still on the right side of the Menu so they still behave that way. Try using the left to go right and vice versa.... 

@baconpaul In my opinion the Menus are OK (in a Linux way) no issue here

*still would like to see those arrows at the top and/or bottom of menu* :-)

Surge Synthesizer
Plugin Host:	AudioPluginHost
System:	Linux 64-bit VST3 on  Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Build Info:	Built on 2021-03-11 at 11:55:56, using local host 'LinuxDAW' with 'GNU-8.3.0'
Version:	1.9.main.93c86600

also scroll mouse is working and can get to the bottom of the FX that way also

One odd thing I notice though is when FX are expanded Neuron is default. Likely because the Mouse is there. That being said when scrolling off the Menu the highlighted element jumps to Neuron whereas I would think it would be better if it stopped scrolling and remained at either the top or bottom element depending on which way the arrow is moving.

This behaviour can be stopped by using the scroll mouse. However with the arrow going past the end will bring you back to the top, In my opinion it would be better if it would stop rather than cycle around to the other end of the spectrum without going back through the elements. Also when not jumping from zero to infinity it will, when passing below the bottom or over the top shoot back to the last highlighted effect. 

Two questions. Can we get it to hold at the end of the menu when using the arrows? Can the arrow behaviour be inverted when the menus expand left (to avoid the left goes right and right goes left behaviour)?

**Comment by tank-trax** [comment]
Hmmm. maybe it is an issue... using arrows the menu will not expand beyond Surge's GUI outline. The highlighted element jumps back top. This _is_ and issue in my opinion.

I would think the solution would be to:

a) get the arrows to be able to push the hidden elements into view
b) have the scrolling stop at the top or bottom once reached, rather than jump around
c) have the arrows flip vertically their behaviour when hugging right and sub-menus expand left

**Comment by tank-trax** [comment]
just add this to _it's another moving to JUCE will fix_ thing

**Comment by mkruselj** [comment]
Already did (see labels) 😉

**Comment by baconpaul** [comment]
Yeah the surge xt menus should be fine 

This is vstgui not using system menus because Linux doesn’t have system menus etc ...

I think we should close this. It’s a wontfix with vstgui and an already fixed with juce. If you disagree open it again though!
