### ISSUE TITLE
The Sonic Transformation Soundset by HO for the Vember Audio - Surge 

### ISSUE THREAD

**Issue by Sonic13564** [surge-synthesizer/surge#4246]
I have make a Soundset for the Surge ( but it'Äs in the " User Patches " becuase the Soundbank a bit older) 
https://www.kvraudio.com/product/the-sonic-transformation-by-sonic-sirius

I have now assigned all 152 presets to a category (FX - Leads - Pads - Sequences ) and uploaded them to download! 
https://www.mediafire.com/file/ha2r8n0166as0yh/-+Send+to+Vember+Audio+Surge+Team.rar/file

Inside the Download is the " Wavetable Pack by Arty " i use the Wavetables in my Soundbank ! 31,8 MB 

Please put this Soundbank in the " Third Party Patches " and dont forget the Wavetables from Arty,
I have make some Screenshots - it's all in the Download 

This is my Webpage: http://ohlenbostelhelge.magix.net/public/

Thanks

**Comment by mkruselj** [comment]
We will likely just point to that pack in here: https://github.com/surge-synthesizer/surge-synthesizer.github.io/wiki/Additional-Content

Because it would considerably increase the size of the installer with all those wavetables. But also - wavetables you use in patches are stored in the patch, they don't need to be installed alongside.

**Comment by mkruselj** [comment]
Oh, we already link to that soundset (Content from KvR section). Alright then, we can close this issue.

**Comment by Sonic13564** [comment]
Thanks for the valuable information.

Am Sa., 3. Apr. 2021 um 11:42 Uhr schrieb EvilDragon <
***@***.***>:
