### ISSUE TITLE
Custom installation folder !!!!!!!

### ISSUE THREAD

**Issue by 2blackbar** [surge-synthesizer/surge#4266]
I keep all my vstis on D drive not on C, cant install surge in my folder, theres just one default path, its strange, please change it.

**Comment by baconpaul** [comment]
Hi!

The VST3 Spec is perfectly clear that it belongs in the C:. Some DAWs - most notably FL - don't work with VST3s outside the C:. 

If your DAW supports it you can move it after install. 

Thanks

**Comment by mkruselj** [comment]
> If your DAW supports it you can move it after install.

But DON'T do this because once you update Surge some time down the road it won't update the .vst3 if you move it manually elsewhere.

What you should do is move C:\Program Files\Common Files\VST3 folder to your D: drive, then create a symlink back at C:\Program Files\Common Files\VST3 that points to the moved location at D:.

That does what you want - you will have your VST3s on D:, but all DAWs will still scan for them using the default C: drive path. I have it like this, works like a charm!

**Comment by K0rrid0r** [comment]
symlink is the answer
