### ISSUE TITLE
Pitch bend range and semitones in hertz

### ISSUE THREAD

**Issue by muziker** [surge-synthesizer/surge#4289]
Just a request for info,

For 12tet, each frequency is f(n)=F*2**((n - a)/12), where F is the reference frequency, a is the number assigned to the reference pitch and n is the number of the desired pitch, where n & a are from a set of monotonically increasing numbers. 

And so for an mpe pitch bend of 48 semitones, does it entail: 
1. -48 semitones ~= -8192 & +48 semitones ~= 8192 pitch bend units
2. ==> or each increase in pitch bend unit is: 48 semitones/8192 pitch bend units 
3. And is the division of the pitch bend range linearly defined and not similar to how the 12tet freq is derived, ie. log based 

The other thing is: 
Does the mpe implementation mean channels 2-15 are the only midi channels that can be used for mpe pitch bends, limiting the polyphony to 14 if using mpe pitch bends assist with microtonal pitches?

**Comment by baconpaul** [comment]
Sort of. Well yes but not for quite the reason you give And in tuning modes it is more complicated and MPE is different.

So non MPE case (the pb range on the UI)
Internally surge maps to frequency very “late” and does almost everything in keyboard space. So the pitch bend range is really the number of keys to move. That is, if you press middle C (midi note 60) with Pb range 4, if you bend all the way up you will send midi note 64 through the system. The oscillators will see this and then do whatever they want with midi note 64. When you apply micro tuning you get two choices. You can either map note 60 to whatever the tuning equivalent is (this is called ‘tune at keyboard’) and then add 4 to it, in which case the pb range is 400 cents, or you can push 64 to the oscillator and ask for the frequency (tune after modulation). There’s scenarios when you want both, but the first is the default. So except in some of the microtonal case, the PB on the UI relates to a cents move.

The MPE pitch bend is treated differently. In MPE mode there’s a control channel (0) and then note channels (1-15) [using 0 based indexing for channels here] so you are correct you can only play 15 MPE notes active at once which is, alas, a deficiency in the MPE spec. What surge does then is make the MPE pitch bend range the number of steps between keys. This is a parameter that devices will send. We always apply MPE pitch bend before tuning - even in modulation case - since it preserves slides.  And yes your math is right, with an MPE Pitch Bend Range of X, the X/8192 is the width of a full key distance.

MPE pitch bend and PB range are different things and applied differently. Although there is currently (as far as I know) no single device which is an MPE controller with a global pitchbend wheel, Surge would support that, and it works if you play your roli and wiggle the pitch Bend wheel on another device properly midi mapped. Then the MPE pitch bend responds to finger position and the global pitch bend moves the entire sound scape. 

Does that help?

**Comment by muziker** [comment]
Yes that's helpful. 

So lets say I need to move 170.66 pitch bend units to advance one semitone ( 48 semitones per 8192 pitch bend units).  Going upwards 100 pitch bend units, the frequency is an interpolation, freq = s * 100/170.66, where s is a semitone. For instance with A=440 as a reference at midi note number 69. One semitone would be midi note 70 at 466.16, so with a pitch bend unit of 100, the resulting frequency would be, freq=( (466.16-440) * (100/170.66) ) + 440. Is that right?

**Comment by baconpaul** [comment]
Assuming you are running surge untuned and sending pitch bends in, then if the frequency will be interpolated in 2^n space.

https://github.com/surge-synthesizer/surge/blob/c4a7ea3456ad1be31f2fe4c8d31f55959f1887b4/src/common/SurgeStorage.cpp#L1610

there's the code but basically if you press note 69, have MPE pitch bend range of 48, and send a 50, you will get note 70 + 2/48 and that will convert using the 440 * 2^((70+2/48-69)/12)

we do table lookups to make it quicker. The table_pitch_ignoring_tuning is basically log_2(frequency/MIDI_NOTE_0_FREQ) which is freq / 8.162etc. The 2^x table is the 2^ in between so we interpolate in log2 space properly.

**Comment by muziker** [comment]
Out of curiousity, why is the incoming x, the midi note, added with 256, and why is the code using a bitmask [ e & 0x1ff ] when the max e will ever be is 0x1fe?

**Comment by baconpaul** [comment]
1. The midi keyboard notes have range 0 -> 127 before modulation but modulation and non-midi input can range frequencies inside surge from the frequency space of -256 -> 256 validly. This function isn't just used for notes from keyboard its also used for cutoffs and in some cases very low frequency activities. We store this recalculated data in a table of 0...512 hence the +256. You can see in SurgeStorage where it is created

2. oh beacause this code has moved around a lot and until you asked I didn't read the whole thing as 20 lines - so used to be one clamp wasn't there and another was and then this version came here and so on and so forth. Definitely the case that we redundantly clamp. I'll add an issue and we can clean it up after the 1.9 release to be a bit more pars ominous

**Comment by muziker** [comment]
The other thing i found in this version of surge that i have, 1.9.main.251000e4 on linux, 
1. <pitch bend, channel 1> is always 2 semitones range up
2. <pitch bend, channel 2> uses the correct mpe pitch bend range

channel 1& channel 0 seems to be global pitch bend and can affect the midi notes pitch bends in other channels, and channels 2-15 are for mpe midi notes and pitch bends, which means polyphony is 14 notes. I'm testing this using pure data to send the midi notes/ pitch bend data to surge.

**Comment by mkruselj** [comment]
Yes, that is normal behavior, global pitch bend is handled by the up/down range parameters on the GUI, and MPE pitch bend has a separate setting. This is according to the MPE spec.

**Comment by muziker** [comment]
yes you are right 2-16 channels

**Comment by baconpaul** [comment]
Yeah it’s confusing since the code is 0 based and our tools are 1 based.

**Comment by baconpaul** [comment]
Oh also channel 1 pitch bend is controlled by the pb up pb dn value in the ui and drives the pitch bend modulator also

**Comment by mkruselj** [comment]
@muziker if you've got all the relevant info on the topic that you need, I'd like to close this issue (since it's more of a discussion really, and this can happen even in closed issues - or on our Discord!). Let me know, please.

**Comment by muziker** [comment]
i'll close it. Yes it's been very enlightening

**Comment by baconpaul** [comment]
Great - let us know if you have any other questions of course!

**Comment by muziker** [comment]
Not implying that it should be changed, because it works. But I was looking at the tuning code and how it uses the fractional portion to interpolate between 2 points. Isn't it a linear interpolation between 2 points that are pow2 instead of a pow2 interpolation? At 1000 fractional points it's probably not very obvious

**Comment by baconpaul** [comment]
So there’s three cases. 

Untuned: Then we end up doing the interpolation into the 1000 fractional point array and that array is initialized with 2^x for x in 0,1. So using the identity 2^(a+D) = 2^a * 2^D we get an exact representation of 2^a and then linearly interpolate the table for 2^D. This means there is a linear interpolation error in the representation of 2^D indeed, but it is still way way better than d * 2^a + (d-1) * 2^(a+1) or what not (which is what to code did in 1.8).

Tuned with tuning at midi keyboard: In this case the mapping happens before the interpolation and so internally we look untuned. This is (now) the default case and also the ODDSound case and also the case you would get with MPE simulating pitch bend. The *primary* reason we changed to the interpolated lookup described above is to handle the case where a single note press lands between 12-TET and this got us several cents more accurate tuning.

Tuned with tuning at modulation. This is the case where we are least accurate between notes since we have to interpolate linearly between pitches (we don’t actually know the functional form of a given scale). There’s also a bug like feature with keyboard mappings which disable notes in this case that I’ll fix in XT. 

Hope that helps!
