### ISSUE TITLE
Factory FX presets in a folder structure, in the binary

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4356]
Rather than having all of our factory FX presets converted from .srgfx files into one-liner entries in configuration.xml, it would be better if we just had .srgfx files directly in a folder structure that is being read out and snapshots menu created from it. Much easier to ingest new FX presets this way, too.

Linking to #3434.

**Comment by baconpaul** [comment]
So this is going to add a bucket of code and startup and compile time complexity if we want to keep surge running even without a factory directory (which it does now). I would sooner not do it. But doing it would amount to adding those files to the binary and then running over them in a c++ loop. I think we are better to just edit config.xml since it changes infrequently and am of a mind to close this as a “wont do”

**Comment by mkruselj** [comment]
Ha let's then also move the default skin out of the binary? That's also a lot of files that are iterated over...

**Comment by baconpaul** [comment]
Because then surge won’t start

**Comment by baconpaul** [comment]
But you want a folder structure in the binary
A folder structure in the data directory is easy enough and then you can shrink the binary
But a folder structure in the binary is really hard

**Comment by baconpaul** [comment]
Talked with @mkruselj and config xml will stay
