### ISSUE TITLE
Window oscillator is glitchy in continuous mode over wavetable frames

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4429]
@mkruselj reports window in continuous mode glitches over frames
@baconpaul bets he got the interpolation sign wrong 
The way he would debug it is

1. Make a 3 wave wavetable which is obvious 
2. Load it and see what happens as you run in continuous mode

**Comment by baconpaul** [comment]
I have no idea why this is happening. Sigh.

**Comment by mkruselj** [comment]
@jatinchowdhury18 Do you perhaps have some bandwidth to check this one out? No rush.

**Comment by baconpaul** [comment]
yeah so the fractions are correct but when they toggle over so you go from idx=n, frac=0.99 to idx=n+1, frac = 0.01 you get a click 

i couldn't see why when i read the algo

i am not sure, though, the mipmaps will interpolate cleanly - i suspect the problem may be there somewhere - but wasn't able to find it

**Comment by mkruselj** [comment]
Oh BTW here's an easy wavetable to check this one with.

[08 Roughmath I.zip](https://github.com/surge-synthesizer/surge/files/6443581/08.Roughmath.I.zip)

**Comment by jatinchowdhury18** [comment]
@mkruselj Yeah, I can take a look at this on Sunday!

**Comment by baconpaul** [comment]
Awesome. All the 'fractable' stuff is the new stuff I added which works except it doesn't work when you cross. Should be pretty clear. 

Here's a test wt I made to test also which just alternates between squares and sines so you can make sure the right thing is happening

[sinesquarealt.wt.zip](https://github.com/surge-synthesizer/surge/files/6444228/sinesquarealt.wt.zip)

**Comment by jatinchowdhury18** [comment]
Okay, so I've gotten to the "bottom" of this, but I'm not 100% sure what the right fix is. Just gonna try my best to explain it here, in the goriest of detail:

Starting at [`WindowOscillator::ProcessWindowOscs()`](https://github.com/surge-synthesizer/surge/blob/main/src/common/dsp/oscillators/WindowOscillator.cpp#L181), near the top, we set `Table` (index of the current table), `TablePlueOne` (index of the table we're morphing with), and `FTable` (the interpolation fraction). Then we have a nested unison loop and sample loop:

```cpp
for (int so = 0; so < NumUnison; so++)
{
    ...
    if (Window.Table[0][so] >= oscdata->wt.n_tables)
        Window.Table[0][so] = Table;
    if (Window.Table[1][so] >= oscdata->wt.n_tables)
        Window.Table[1][so] = TablePlusOne;
    ...
    short *WaveAdr = oscdata->wt.TableI16WeakPointers[MipMapB][Window.Table[0][so]];
    short *WaveAdrP1 = oscdata->wt.TableI16WeakPointers[MipMapB][Window.Table[1][so]];
    short *WinAdr = storage->WindowWT.TableI16WeakPointers[MipMapA][SelWindow];
    ...
    for (int i = 0; i < BLOCK_SIZE_OS; i++)
    {
        ...
        if (Pos & ~SizeMaskWin)
        {
            Window.FormantMul[so] = FormantMul;
            Window.Table[0][so] = Table;
            Window.Table[1][so] = TablePlusOne;
            WaveAdr = oscdata->wt.TableI16WeakPointers[MipMapB][Table];
            WaveAdrP1 = oscdata->wt.TableI16WeakPointers[MipMapB][TablePlusOne];
            Pos = Pos & SizeMaskWin;
        }
        ...
    }
}
```
Basically since `Window.Table[i][so]` is not updated every sample, if the tables have shifted (and the fraction along with it), then the first few iterations of the sample loop will have the wrong tables (until the if statement is true, then the addresses reset, and then we're back on track).

Now there is the code in the unison loop to set those values, but they're stuck behind  `if (Window.Table[0][so] >= oscdata->wt.n_tables)`. I found that if I removed those if statements, then it fixes the issue, and the continuous morphing sounds correct:
```cpp
for (int so = 0; so < NumUnison; so++)
{
    // if (Window.Table[0][so] >= oscdata->wt.n_tables)
    Window.Table[0][so] = Table;
    // if (Window.Table[1][so] >= oscdata->wt.n_tables)
    Window.Table[1][so] = TablePlusOne;
    ...
```
Is there something specific those if statements are supposed to be doing? Otherswise, I don't see the problem with removing them altogether. Anyway, hopefully this helps!

**Comment by mkruselj** [comment]
Yeah it doesn't help that it's also written in an entirely different style from the rest of the codebase...

**Comment by jatinchowdhury18** [comment]
Haha, yeah I was wondering about the lack of camelCase.

I think removing the if statements and just setting `Window.Table[0][so] = Table` every time is the right thing to do, since the "fallback" case of the if statement does that anyway. Like it doesn't cost us anything extra, and might actually be faster :). I'll make a little PR for it.

**Comment by baconpaul** [comment]
That definitely fixes it. Thanks @jatinchowdhury18 !! Closing this.

**Comment by mkruselj** [comment]
Removing the ifs brought (way) more clicks in non-continuous mode. I think the if needs to stay but be more elaborate. Sadly adding || extend_range to the >= condition doesn't help it.

**Comment by baconpaul** [comment]
Well bummer. Let’s do a pr to put the ifs back for now then

**Comment by baconpaul** [comment]
Is the clicking you are hearing in continuous mode with the slider or with a modulator?

**Comment by mkruselj** [comment]
Ha true, with modulation it's fine... but why not via slider then? And it's fine with WT osc?

**Comment by baconpaul** [comment]
Answer is a lag<float> on morph basically

**Comment by jatinchowdhury18** [comment]
Ah, that makes sense actually. I was testing on a patch that used modulation on the morph parameter, since that made it easier to debug.

**Comment by jatinchowdhury18** [comment]
Ah, that makes sense actually. I was testing on a patch that used modulation on the morph parameter, since that made it easier to debug.

**Comment by baconpaul** [comment]
yeah we just need to add a lag<float> and use the to process the morph. but the morph is only once per block so you need that faster lag trick so that process is still smooth enough
