### ISSUE TITLE
XT Mousewheel is all over the place

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4432]
All the nice things we did with mousewheel with VSTGUI, proper rounded steps and so on, all are broken now in JUCE, things are jumping in super arbitrary steps.

A number of other JUCE-based plugins have an issue with this. One of rare JUCE-based plugins that does things sensically with mousewheel is Pianoteq, so maybe they know what to do (I reckon subclassing mousewheel handling is the solution, but unsure).

Putting this as its own issue rather than pedantikon because it's a far more complicated one to solve (from what I'm aware at least). But it has to be solved!

**Comment by baconpaul** [comment]
We already subclass the mouse wheel handling, otherwise it would do nothing. So we are already in a good spot.

The place to start tracking this is escape_from_vstgui.h in the method juceCViewConnector<T>::mouseWheelMove around line 1738

What that does is take a juce mouseWheelMove and sends it to the VSTGUI proxy class. You will notice some obviously dumb things I did in there

1. I try X then Y then both in an arbitrary order. We should look in the event data
2. I multiply stuff by 3 for some reason
3. And so on

So the way to start is basically start putting prints in there, reading the juce doc on mouseWheelMove, and seeing what we get, and comparing that to the values we sent in vstgui land, and making them the same, then we will get the same behavior.

Other than hooking it up, i made no effort to scale this properly by the way. So unsurprised it doesn't work.

https://docs.juce.com/master/structMouseWheelDetails.html

that's everything we know when we get the event.

**Comment by baconpaul** [comment]
oh and: since we got everything inter-calibrated properly in 1.9 and that code is all the same, this will get uniformly fixed if we fix the juce - to - fake - vstgui bridge in that one function. in theory.

**Comment by mkruselj** [comment]
OK, will take a gander. Thanks for the info!

**Comment by mkruselj** [comment]
Also direction of mousewheel is inverted to how it was in VSTGUI. At least that one is an easy fix.

**Comment by baconpaul** [comment]
So one thought here

We are taking the (nice) JUCE mouse wheel API and trying to map it into the (less nice) VSTGUI api so we can call our existing mousweheel handlers

We don't have to do that. I could make a new API on our VSTGUI 'fake' base class which was exactly the juce API and then we could go one by one and redo the mouse handlers in the new API where the compat layer isn't up to snuff. Since we are never going back that's fine with me. 

Your thoughts welcome. If you are interested I could do it on something easy like the hswitch as an example.

**Comment by mkruselj** [comment]
Probably a good idea to do that. The less we have to lean on EFVG the better, no?

**Comment by baconpaul** [comment]
Yup
Lemme see if I can bang it out quickly this AM so you can get to work.

**Comment by baconpaul** [comment]
OK onc I merge #4558 you have an option of adding two functions to a CControl

```
 virtual bool supportsJuceNativeWheel() override { return true; }
    virtual void mouseWheelMove(const juce::MouseEvent &e,
                                const juce::MouseWheelDetails &wheel) override;
```

the first can just return true. it just tells efvg that this control uses native juce mouse api. The second the implements the wheel handler. You can see in CHSwitch2 how I did it.

**Comment by baconpaul** [comment]
so we don't want to do it that way because #4587 will move us all to juce native. As such I'm going to close this issue and we can fix wheel on a case-by-case as we jucify (especially since the first couple I did came out just fine).
