### ISSUE TITLE
JUCE SVG and UI issues

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#4438]
- [x] Here's 1.9 on the left, and XT on the right:

![image](https://user-images.githubusercontent.com/50145178/116331728-5e146b80-a79e-11eb-9a95-73501d3e8ac7.png)

- [ ] Left - 1.9, right - XT. Slider groove is darker/more opaque and there's no semitransparent triangle.
![image](https://user-images.githubusercontent.com/2393720/124323709-0b7e7380-db82-11eb-8cf5-9240b88113d5.png)

- [ ] Unsure why the modbutton arrow is a different color here. Makes no sense, SVG shows brown and yellow states over here. Red is nowhere to be found?

![image](https://user-images.githubusercontent.com/2393720/124323754-1d601680-db82-11eb-932d-32f3c3d2b6d7.png)

- [ ] Different colored MSEG nodes and FX jog:

![image](https://user-images.githubusercontent.com/2393720/137403694-3b257362-0540-4b59-9fab-4eeb4e0f1918.png)

- [ ] From issue #4377: These things are back at 175% zoom (non-HiDPI):

![image](https://user-images.githubusercontent.com/2393720/115920845-082c8480-a47b-11eb-928a-53ef979b088a.png)

- [x] Issue with hoverOn00166.svg in Classic and Dark skins:

![image](https://user-images.githubusercontent.com/2393720/136414595-d8193a1e-5b2b-43e2-83b1-80d6c6329f98.png)

Chromium and Figma render it fine. Seems to be caused by the stroke in the last `<path>`:

![image](https://user-images.githubusercontent.com/2393720/136414642-7704db0e-547b-46ed-a650-dcecc6f1b6f4.png)

**Comment by baconpaul** [comment]
Since I asked:

> So on XT the colors are flatter (and darker)
> It's the blue-gray ish gradient (lighter in the middle than on the sides) that we added in 1.8 iirc. This doesn't show up in XT, where it's all the same dark color everywhere, basically the "old 1.7" dark skin.
> You can especially see it if you compare the FM routing and filter config area.

**Comment by mkruselj** [comment]
Hmmm SVG parser in JUCE not working with our specific type of gradient (or the way it's outlined in the SVG)?

**Comment by mkruselj** [comment]
![image](https://user-images.githubusercontent.com/2393720/124323709-0b7e7380-db82-11eb-8cf5-9240b88113d5.png)

Left - 1.9, right - XT. Slider groove is darker/more opaque and there's no semitransparent triangle.

![image](https://user-images.githubusercontent.com/2393720/124323754-1d601680-db82-11eb-932d-32f3c3d2b6d7.png)

Unsure why the modbutton arrow is a different color here. Makes no sense, SVG shows brown and yellow states over here. Red is nowhere to be found?


@baconpaul These might all be related to the OP issue, so renaming the issue to "JUCE SVG issues".

**Comment by mkruselj** [comment]
From issue #4377:

These things are back at 175% zoom (non-HiDPI):

![image](https://user-images.githubusercontent.com/2393720/115920845-082c8480-a47b-11eb-928a-53ef979b088a.png)

**Comment by mkruselj** [comment]
@baconpaul Please investigate why we cannot nicely center text vertically AND horizontally in the tempo block (VKB area).

**Comment by baconpaul** [comment]
I remember now
If your text editor is small or your font is high the indents "win"
here's the line from TypeinParamEditor I used to fix this

```
  textEd->setIndents(4, (textEd->getHeight() - textEd->getTextHeight()) / 2);
 ```

**Comment by baconpaul** [comment]
which you should call in `::resized`

**Comment by mkruselj** [comment]
OK fixed that, but now the colors aren't being shown correctly when starting up Surge, they only sort themselves out when typing in something and pressing Enter.

![colors](https://user-images.githubusercontent.com/2393720/132763691-95be13f8-2e49-41ba-b3da-f8375540ac47.gif)

**Comment by baconpaul** [comment]
The dar skin radial gradient thing is actually an XT bug

Making the SVG more pronounced in that gradient here/s XT vs 19

<img width="2275" alt="Screen Shot 2021-09-15 at 8 53 29 AM" src="https://user-images.githubusercontent.com/13387561/133437292-1ab15f87-dcd2-40d6-bfac-0a01ccb1e6df.png">

and here's XT vs Boxy (chromium)

<img width="2158" alt="Screen Shot 2021-09-15 at 8 54 39 AM" src="https://user-images.githubusercontent.com/13387561/133437322-07af8a2f-0563-4a42-a5af-f84bfa8f7c86.png">

So the fix for dark skin fade is to adjust the SVG to work with a spec compliant renderer!

**Comment by baconpaul** [comment]
basically change this line

> gradientTransform="translate(451) rotate(90) scale(451 451)"

in the SVG from 131.45 to 270.5 and you will get something closer to what 19 did

Seems 1.9 was not dealing with non-uniform scales on gradient transforms properly.

**Comment by mkruselj** [comment]
Aaaaand that's fixed. JUCE is still not rendering the raster texture that's part of that gradient but I guess that's up to them to implement?


Which then only leaves the Royal Surge issues.

**Comment by baconpaul** [comment]
The reason for the different colors in royal surge are because royal surge has odd svg. It might be standards OK but juce doesn't like it.

```
<path
     d="m 7.0500183,26.500023 -2.5,-3 h 5 z"
     id="path7164"
     fill="#f92a69"
     fill-rule="evenodd"
     stroke="none"
     style="fill:#f6d537;fill-opacity:1" />
```

here's the SVG for a chunk of the LFO arrow. 

That's saying the fill is `#f92a69`  which is this color. This is the color juce renders.

<img width="136" alt="Screen Shot 2021-11-17 at 5 57 59 PM" src="https://user-images.githubusercontent.com/13387561/142295834-3147e066-f266-45cc-8897-003905dbe7c6.png">

But it is *also* saying there's a style with a fill. That fill is #f6d537 

<img width="143" alt="Screen Shot 2021-11-17 at 5 58 55 PM" src="https://user-images.githubusercontent.com/13387561/142295930-155cd65d-1363-4f6d-b96c-9692bcb1dad0.png">

which is the desired color, and also the color chromium selects.

So the answer on these odd royal skin colors is: Royal gives two conflicting colors for the fill in their svgs. Chromium and VSTGUI pick one, juce picks the other. Juce may be wrong but the easy fix is to find all the places with a fill and a style and make them coherent.

I think, other than new assets and new colors, that's the only remaining svg issue correct?

**Comment by mkruselj** [comment]
@baconpaul There's also the issue where the slider grooves render completely differently in JUCE vs 1.9. Is that the same conflicting color thing?

**Comment by baconpaul** [comment]
I'm assuming it is yes. Here's a fragment from bmp00154

```
 <path
     d="m 144,35 h 113 v 2 H 144 Z"
     id="path50926"
     fill="#070403"
     fill-rule="evenodd"
     stroke="none"
     style="opacity:0.08;fill:#fffefe;fill-opacity:1" />
```

same problem

**Comment by mkruselj** [comment]
Gosh darn it! Oh well, gotta manually tweak.

**Comment by baconpaul** [comment]
wonder if i can write a script to find em
there's probably a few.
or just remove those fills and check also - that may be easiest.

**Comment by baconpaul** [comment]
yeah i you just remove the conflicting fill and fill-rule the style gets used properly
so "if there's a style with a fill and a fill, remove the fill to work in juce" seems to be the rpescription

**Comment by baconpaul** [comment]
by the way, do we know if we will have royal updated for xt1? If so I need to update the pipelines.

**Comment by mkruselj** [comment]
I gotta talk to Nick. I think the problem will be the temporary coded multibutton you coded, all of them look a bit different style wise in Royal, so the coded ones would stick out like a sore thumb.

**Comment by baconpaul** [comment]
Right so we would need backgrounds blank for some since they change their label as we undertake actions if we went with svgs, or we would need to change the drawing code with more options

**Comment by baconpaul** [comment]
Alldone except for the goobits moved to #5437
