### ISSUE TITLE
Lanczos read index error

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#4465]
@jatinchowdhury18 reports:

> By the way @baconpaul, I was studying the Lanczos resampling code today, and might have found a weird edge case: basically at this line (https://github.com/surge-synthesizer/surge/blob/main/src/common/dsp/LanczosResampler.h#L132) tidx can end up being equal to LanczosResampler::tableObs which means that all of the table accesses further down in that function are uninitialized. I noticed the issue when the input and output sample rates are the same, but I could imagine getting the same bug (but less often) if the sample rates are an integer multiple.

and I think he's right (even though it would only blow up twist when running at 24k sample rate I think). Write a test and check and fix for sure.

**Comment by jatinchowdhury18** [comment]
Yeah, the solution I came up with was to make the tables longer by 1 entry
```cpp
float lanczosTable[tableObs+1][filterSize];
```

But a better option might be to wrap (but _after_ setting `fidx`):
```cpp
int tidx = (int)(off0byto);
double fidx = (off0byto - tidx);
tidx = (idx0 + tableObs) & (tableObs - 1);
```

Another weird behaviour I found was that if you `push()` more samples than the `BUFFER_SZ` in between calls to `populateNext()` then the buffer will overflow, and weird stuff starts to happen. It probably doesn't matter for our purposes since the block sizes are small, and I'm not sure if there's anything we can do about it anyway, but it might be worth putting a comment in case we try to re-use that code elsewhere.

Anyway, just wanted to write down the stuff I was thinking last night before I forget it all :). I can help with writing test cases and so on later today or tomorrow.

**Comment by baconpaul** [comment]
I was thinking fo the extend-by-one fix this morning and I think it is the right one.
The wrap goes to the wrong "side" - basically we need to be up-to-and-including one not up-to one.

**Comment by baconpaul** [comment]
yeah the buffer overflow is real but practically not a problem. I thought about making the buffer size a template.

I'll push a little +1 fix in a minute.

**Comment by baconpaul** [comment]
Anyway put in a fix and tested twist - which is still fine at 44.1 and 48 
let me know if it fixes things for your test case also?
