### ISSUE TITLE
Add option to choose default patch

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4502]
On the heels of #1824, we will finally gonna have properly loaded Init Saw by default.

Add an option to User Settings > Patch Defaults > Set current patch as default. Also add it to CPatchBrowser context menu (both LMB and RMB variants), right after "Initialize patch".

**Comment by baconpaul** [comment]
We should add a single function like "int SurgeStorage::idForDefaultPatch" which does

```
int id = -1;
int defPatchname=getUserDefault
int defPatchcat = getUserDefault
foreach( p in patch )
   if( name && cat )
      id = this id
if( id == -1 )
   // not found
   foreach( p ) if name is "init saw" and cat is "templates" id = this id
return id
```  

then call that from the two spots. this way if you delete your default patch you startup. Then have the clients be resilient to a -1 return value.

**Comment by baconpaul** [comment]
So in the PR above I added a initPatchName and initPatchCategory variable to SurgeStorage which is consistently used.
So an easy way to close this issue is

1. Add a menu item to the PatchBorwser which is "Make this my Init Patch"
2. When you call that do a userDefaultSet for initPatch and initPatchCategory
3. In the surge storage constructor at the end set the variables to the getDefault with a default of "Init Saw" and "Template"

and bobs your uncle.

**Comment by baconpaul** [comment]
Actually I'm just gonna add that to the PR and close this issue along with the other one

**Comment by baconpaul** [comment]
And done
