### ISSUE TITLE
Linux automated builds for releasepage

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#452]
Another one - it would be great to be able to prepare for Linux automated builds for the releasepage - eventually Linux will work pretty close to 100% so we're going to need this ticket i guess.

**Comment by baconpaul** [comment]
Hey @jsakkine @falkTX and @rghvdberg - is it hard to package linux up as a deb with build-linux? If so this is easy to close and do, but we need a command which makes the .deb file from the current builds. Thanks!

**Comment by rghvdberg** [comment]
https://makeself.io/ maybe ?

**Comment by baconpaul** [comment]
No idea! I just know that if `./build-linux package VERSION` made a file with the VERSION set up and an appropriate name we could put it on the website. Seems Carla and several other linux tools have a .deb file download as one of their distorted methods so that looked reasonable but I don’t know anything about linux packaging.

From reading in the googles making a deb file seems to amount to (1) setting up the directory structure in a tmp directory; (2) adding some xml or something to epxplain what you are and (3) running a command which turns that structure into a deb

But again I haven’t done this. I just think it would be cool if the website had a link to download the nightly just like mac and windows do! And don’t know what’s the way to do that on linux which won’t have people all upset that you didn’t do it the other way (or if such a way even exist)

**Comment by rghvdberg** [comment]
deb file is debian specific, which will make arch, fedora users grumble ..
And there's the fact that Surge has some external dependencies, so maybe makeself.io isn't the right solution.
Let's concentrate on making debian packages first. Which is basically a tar ball, we can use @falkTX surge deb as a template maybe ?

**Comment by baconpaul** [comment]
Sure. Maybe step one is to get the scripts that make that .deb file into scripts/linux in the repo? If they exist that sounds like a very good starting point.

**Comment by jsakkine** [comment]
Reminder to myself: look if FlatPak is feasible or not. I'm getting more active with Surge again soon. Have been overloaded with work lately  :)

**Comment by baconpaul** [comment]
Good luck with work!

@rghvdberg made some progress with a .deb file construction this afternoon on slack also so I’m confident we can crack this shortly!

**Comment by falkTX** [comment]
Input from a Linux packager.
The all-in-one package types we got recently (FlatPak, snap, etc) are not to be used for plugins, they are made for applications which ship specific versions of shared libraries.
A plugin, by design, should not be using shared libraries to begin with, it should be self-contained.
(Otherwise it can easily get into issues regarding conflicting library versions)

For a generic package, we should try to have build the more esoteric dependencies statically, and everything else (cairo, x11, pthread, libc) we can leave as shared libraries, as pretty much all distros will have it installed - they are quite common dependencies from other software.

I am attaching here the debian folder I use to build packages in the kxstudio repos.
[debian.tar.gz](https://github.com/surge-synthesizer/surge/files/2878579/debian.tar.gz)

**Comment by rghvdberg** [comment]
thanks @falkTX 
do you see any potential problematic libs here?
```
~/git/surge/target/vst2/Release $ ldd Surge.so 
	linux-vdso.so.1 =>  (0x00007fff689a4000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f3333628000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f33333e5000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f333313b000)
	libxkbcommon-x11.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 (0x00007f3332f33000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f3332cf4000)
	libxcb-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-cursor.so.0 (0x00007f3332aee000)
	libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007f33328d3000)
	libxcb-util.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 (0x00007f33326cd000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f33324ab000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f3332171000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3331f54000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3331d3e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3331b3a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f33317b8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f33314af000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f33310e5000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f3330e3d000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f3330c18000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f3330a14000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f333080a000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f3330600000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f33303ee000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f33301d4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f332ffcc000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f332fda3000)
	libxcb-render-util.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0 (0x00007f332fb9f000)
	libxcb-image.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-image.so.0 (0x00007f332f99a000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f332f796000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f332f590000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f33345ca000)
```

**Comment by falkTX** [comment]
the libxcb stuff is not always installed on all distros.
I am not sure if we should build it as statically though. perhaps we can ask @wrl as his latest synth had to deal with exactly the same issue.
@wrl any insights? do you still ship your linux binary with libxcb stuff as shared lib?

**Comment by falkTX** [comment]
hmm libpng might be a problem, there are many versions of those and the soname even changes.
We should build that one statically (on CI I guess, for release builds) and also get an old enough distro to build things on.
I just tested on 14.04, I am able to build surge here with the gcc8 from the r-test repo (need to add libxcb-xkb-dev to package list to install).
This should provide a build that works for most people.
Since travis runs on 14.04 by default, we can just use that directly for the builds and make them automatic.

**Comment by falkTX** [comment]
Patch against the readme for build-deps in 14.04:
```
diff --git a/README.md b/README.md
index 68aa3a1..3bde85e 100644
--- a/README.md
+++ b/README.md
@@ -212,7 +212,8 @@ You will need to install a set of dependencies.
 - libxkbcommon-dev
 - libxcb-cursor-dev
 - libxcb-keysyms1-dev
-- libxcb-util-dev
+- libxcb-util-dev | libxcb-util0-dev
+- libxcb-xkb-dev
 
 Then `git clone` surge and update the submodules:
 
```
(sorry, just about to leave, might be useful to take this and apply to master branch)

**Comment by wrl** [comment]
I don't see any problems. I've been shipping with all of the XCB libs linked dynamically and even though most of my users have to install a few extra dependencies, it hasn't been an issue otherwise.

I've been told that everything except `libxcb.so` itself can be linked statically, but I've not investigated this.

**Comment by tank-trax** [comment]
I tried to install the build from my Debian 9 computer on another computer that has Mint 19.1 and it did not run as it was not recognized
ldd Sur ge.so showed one missing library

libxcb-util.so.0 => not found

I downloaded and installed libxcb-util0_0.3.8-3+b2_amd64.deb and the VST now loads on Mint 19.1

==============

On another system using UbuntuStudio 
ldd Sur ge.so showed another missing library

libxcb-cursor.so.0 => not found

installing libxcb-cursor0_0.1.1-4ubuntu1_amd64.deb resolved the issue

**Comment by jsakkine** [comment]
@falkTX, At least based on what I came across your statement about FlatPak is not exactly correct. FlatPak does provide the extension mechanism even in the form that you can specify a directory from where the plugins are mounted to the applications sandbox.

However, I do agree that right now tar ball is a better solution because the FlatPak would require the DAW's also shipped with FlatPak.

Not really an expert on the subject so might have some details wrong no feasibility though: https://github.com/flatpak/flatpak/wiki/Extensions

**Comment by jsakkine** [comment]
To summarize the above rant it is not looking too feasible :)

VST plugins are usually such that you want to manually organize them  to directory hierarchies of your choice and they have fixed ABI so probably also in long-term this will be the case. At least this is how I use them on macOS and probably would be the case also on Linux.

FlatPak type of thing works great for stuff like a video codec where you just want one thing and do not have much creative needs above that.

**Comment by baconpaul** [comment]
Ok so it sounds like we want to make two assets

* a deb like discussed in slack
* a tar.gz of binaries and assets with a readme on how to install if you want to local install

And as always a source tarball

Yeah?

**Comment by jsakkine** [comment]
My proposal is after some discussion in Slack:

1. Have a Debian package as one download option.
2. Have a .tar.bz2 with README containing instructions as 2nd option.

I can add package command to `build-linux.sh` to implement the 2nd option.

**Comment by baconpaul** [comment]
I Comoletely agree. Plus fix up the Linux paths issue and voila
