### ISSUE TITLE
Pocket Verbs 100% CPU on M1 in Rosetta 2

### ISSUE THREAD

**Issue by mhetrick** [surge-synthesizer/surge#4521]
**Bug Description:**
When loading "Pocket Verbs" effect, CPU spikes to 100% on my M1 machine.

**Surge Version**
Surge Synthesizer
Plugin Host:	Ableton Live 11.0.2
System:	macOS 64-bit VST3 on Apple M1
Build Info:	Built on 2021-04-21 at 11:26:22, using pipeline host 'Mac-1619004058536.local' with 'AppleClang-12.0.0.12000032'
Version:	1.9.0.91069f8

**Reproduction Steps:**
1. Load the Airwindows effect.
2. Select "Pocket Verbs"
3. CPU meter immediately spikes to 100%. Playing any note leads to breakups.

**Expected Behavior:**
CPU hit should be similar to other Airwindows effects.

**Comment by baconpaul** [comment]
Thank you very much for the report.

The AU on Intel Mac doesn't do this.

I need to get my hands on an M1 box somehow. Thank you for reporting this. Unfortunately my recommended fix for now is "don't use pocket verbs on an M1" but i'll tag this into our next cycle and try and find an M1 box for some dev work before we ship.

**Comment by mkruselj** [comment]
Seems there is some pathology between Live and Rosetta 2. We have reports that PocketVerbs works perfectly fine in FL20.9, for example.

**Comment by baconpaul** [comment]
So I finally got an M1
It's pretty awesome
But I was also able to diagnose this problem

A few airwindows (PocketVerbs, MackEQ) fail when running on Arm under Rosetta

They work perfectly well running on Arm as native code

So if I build surge xt universal and run in hosting AU I can't use Pv or Meq but if I run the same plugin in logic, no problem.

I've upgraded the Surge XT about screen to make it clear when we run in rosetta, but I'm honestly not sure what to do. I started tracking it down, but we just end up having some sort of floating point blowout. Like one line with some fully normal adds takes the CPU up to 100%. I think (think) it is because airwindows uses long doubles (probably uneccesarily tbh) but I didn't try it with those switched. I'll leave this open in case i feel like trying that but I think this issue is resolved by "use an ARM native DAW and use the universal surge".

**Comment by mkruselj** [comment]
Wonder if we switch from long double to double if the issue goes away...

**Comment by mkruselj** [comment]
@baconpaul I guess the answer here is wontfix and "use native not rosetta", then?

**Comment by baconpaul** [comment]
Yeah and if airwindows finds it port his fix in

**Comment by baconpaul** [comment]
Link this to #5932

**Comment by baconpaul** [comment]
I'm going to close this; there's no action we would take in this code.
