### ISSUE TITLE
XT Crash with overlay and FX select

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4541]
1. Load an effect in an FX slot
2. Open MSEG edit view
3. Select an empty FX slot
4. Select the FX slot in which you've loaded an effect
5. Crash!

**Comment by baconpaul** [comment]
So a quicker way to see the bug is
1. init patch
2. mseg and open editor
3. with editor open select an FX in slot 0 - this dismisses the editor overlay
4. change anything and it crashes

so clearly the editor overlay 'memory' code has broken in juce land, or with the introduction of the various new overlays.

**Comment by selenologist** [comment]
Seems another case is
1. Assign some modulation to (Classic) Oscillator Pitch.
2. Right click and edit the modulation w/ a typein
3. Attempt to enter a value out of bounds of modulation, even by a tiny amount (e.g. 14.00001 semitones)
4. Crash

(typeins still seem to work as long as you're in-bounds)

**Comment by mkruselj** [comment]
Yeah I also can't get it to happen with above steps. Seems fixed, so closing the issue!

**Comment by baconpaul** [comment]
The crash is fixed (since I rewrote all the objects) but there’s still a set of bugs on my list for things like “change between two lfos which are mseg with the mseg open and does it work” and all the other stare which used to crash but is still wrong in the sge idle 

the crash was because the ownership was too liberal. It’s now more conservative but the state management may be off.
