### ISSUE TITLE
Have a default configuration.xml bundled for Linux

### ISSUE THREAD

**Issue by jsakkine** [surge-synthesizer/surge#465]
I've been thinking about this a lot, and I am tending to dilate to the same view as @falkTX with the configuration.xml.

What I would propose Linux would be the following:

- Bundle the default version of configuration.xml bundled to the DSO.
- Plugin checks in the initialization if .local/share/configuration.xml exist.
- If yes, do nothing.
- If no, copy the default version there.

This way Surge.so would completely self-contained bundle that would **always** just work, and would be convenient for Linux users.

This does not require any new scripts, just one static configuration.S and configuration.h files to src/linux.

**Comment by jsakkine** [comment]
I misunderstood @falkTX's earlier comment that he would like to bundle presets and wavetable, which would be completely insane, and is not required to run the plugin.

**Comment by baconpaul** [comment]
We actually did this on mac originally

The only reason to not do so is: While the component will run without presets and wavetables, it indicates the user has not done a correct install. In some sense, surge will be very crippled. You can't load any great sounding patches and can't make many (since there's 7 oscillators and 150 wavetables).

So if you do this, which I don't mind, the one thing I would look for is when you do copy the configuration.xml over you also do a Surge::UserInteraction::promptError which tells the user that they are getting a working-but-suboptimal surge and they should install correctly.

See what I mean?

On windows and mac I would be opposed to doing this, since I really want folks there to run the installer. On linux it is more likely people could clean up themselves so I'm more relaxed.

**Comment by jsakkine** [comment]
Actually, not exactly. Anything that goes to the home directory, should not be part of the installation process.  We never can do an installation process for Linux that would copy stuff there. This will mean that the user will be required to do a manual step after installation.

**Comment by jsakkine** [comment]
Even on Windows and macOS all the software that I use create their home directory placed files themselves (i.e. UID specific files). Factory presets and wavetables, on the other hand, are global resources.

**Comment by jsakkine** [comment]
It is analogous if I would be required to create .config/google-chrome content myself manually, instead of just relying Chrome to do it for me.

**Comment by baconpaul** [comment]
Right. So on mac it is different (for all apps not just surge).

The installer installs these extra assets in /Library/Application Support. But the mac convention is you can also read out of ~/Library/Application Support. The mac install experience of "for all users" or "for this user" determines which path.

**Comment by baconpaul** [comment]
But I have no idea how linux desktop or installers work and am happy to follow your lead. I just don't want to break mac and win! :) And also think if you are running surge and can't find wavetables we at least owe you a popup.

**Comment by jsakkine** [comment]
Presets and wavetables are completely different meat. They will be installed either to global /usr/share, and yes, that can be done by the installer or package manager. Or they will be part of the application container if you use these new application packages (e.g. Snap and FlatPak), which are somewhat similar how macOS does apps (or Android).

This really does not cause any distraction to other platforms. Blame me if anyone ever complains :)

**Comment by falkTX** [comment]
There is no reason to install things system-wide on Linux, surge is not reading them anyway (and they would be read-only).
The current way of installing and storing things in ~/.local/ is fine.

**Comment by jsakkine** [comment]
@falkTX, so what is your stand on configuration.xml design that I proposed?

**Comment by falkTX** [comment]
Please do as you proposed, that the plugin copied the xml if not there.
(make sure to create the folder(s) first too)

Storing the assets system-wide requires root/sudo, which some users might not like.

**Comment by jsakkine** [comment]
OK, cool, just wanted to check from both of you that we are in the same line before taking action. Thank you.

**Comment by baconpaul** [comment]
It seems we are at

*  If configuration.xml is in ~/.local or /local or whatever proceed. 
    * aspire to have an 'installer' which makes that happen properly including patches and wavetables
* If it isn't there them do the following
    * make the ~/.local directory or whatever
    * put configuration.xml there from the dll
    * load and start
    * show the user an error that they are missing resources like wavetables and patches, so have an incomplete surge install and experience

I am totally fine with linux behaving that way.

**Comment by baconpaul** [comment]
It is related.

Now the code has evolved, #250 is better written as "Make Linux UserInteractions use something other than std::cerr" since the rest of the problems are addressed.

We may want to close #250 and just open a new issue which is the above title. @jsakkine will figure it out.

Thanks for all your work this morning on the issue list! Appreciated!

**Comment by jsakkine** [comment]
Overridden by #562.
