### ISSUE TITLE
Clickthrough in User Patch Submenu

### ISSUE THREAD

**Issue by ghost** [surge-synthesizer/surge#4681]
Linux 64bit
Standalone only
hash original post ccc1ad5
hash now 04e38b3d

When selecting Patches (in the Patch Selector) that overlay the "Functions" part
of the menu, a click selects both the patch and the layer underneath.

This bug is best exposed in Mint with a Mate Desktop.
I aditionally tried xfce, cinnamon and stock ubuntu and can reproduce it in all of these,
it's just harder because the spots to click are much narrower which can make it seem random.

Example steps for Ubuntu:
- Remove User Patches and Favorites
- Select "Giana Brothers/Chords/5th Element" 
- Click exactly here (very small spot, try a few times):
![click](https://user-images.githubusercontent.com/80534683/145351436-4e946242-5714-4959-9242-2c54846a0241.png)
- This will open a folder.

This is only one example, you can do this for all items in the functions menu.
Likewise in the FX menu.

Possible future bug reports that might be this:
- Chorus Init(Dry) is a deadlink
- Defaultpatch changes all the time
- Selection hands out random patch
- Selecting patch xyz crashes (super hard to reproduce but possible)
- Patch selection opens folder/dialog/etc.
- Selection triggers "initialize"
- etc.

(btw: The license display mentioned below turns out to be a long standing Ubuntu issue, it's what they do)

**Comment by mkruselj** [comment]
I take it this is using LV2, then?

**Comment by mynameismuhl** [comment]
no
standalone

**Comment by baconpaul** [comment]
Oooh that’s interesting
When you use the vst3 which daw are you using?
And what’s your Linux distro / wm if you don’t mind me asking

thank you!

**Comment by mynameismuhl** [comment]
host is reaper
distro is mint 20.1 / mate desktop

**Comment by mkruselj** [comment]
Cannot confirm on Windows.

**Comment by baconpaul** [comment]
I tried ubuntu 20 reaper and also couldn’t confirm. Will need to come back to tbis one to debug this summer

**Comment by mynameismuhl** [comment]
:-)
This issue is about xt-standalone.
It is *not* happening with vst3 in Reaper and I did *not* try lv2.

I have now set up a fresh Ubuntu 20.04 LTS on the side 
and installed the latest xt .deb to make sure it's not distro or build env specific
which by the way shows me this :)
![Screenshot from 2021-07-06 18-25-05](https://user-images.githubusercontent.com/80534683/124641406-f6aa2480-de8e-11eb-9da0-50b289f52bfb.png)


and i can reproduce above described behavior with xt-standalone in ubuntu.

just to make sure we are all seeing the same:
- Remove user patch folder for a second (so it doesn't show up in patch-browser) 
- Zoom 100%
- Click on Third Party Patches/Bluelight/Percussion/Tubular
-> Selects Tubular & opens file browser

I should add that the xt-alpha generally runs super nicely!
and as with all my reported issues, please understand this as:
FYI, look what I found, you might want to know this etc.

**Comment by mkruselj** [comment]
I understood it's about standalone. I tested in XT standalone on Windows - doesn't happen.

**Comment by baconpaul** [comment]
Oh I should fix that license thing

ok when I next have a Linux vm running I will try. Greatly appreciate the clarity thank you

**Comment by mynameismuhl** [comment]
Another idea why you might not be able to see this.
In Ubuntu it is harder to trigger this, the cursor needs to hit exact spots, a few pixels off and it doesn't happen.
Note: I am doing this on a non-HD screen. With a higher pixel density you maybe never run into this.
So I don't know, the only thing that maybe makes this more than a minor inconvenience is that this way
you could set your default patch without knowing it.

**Comment by mynameismuhl** [comment]
I have edited first post with detailed reproduction steps for Ubuntu
(not to boost the importance but to get it out of my head without it getting lost,
 I personally have a workaround)

**Comment by mkruselj** [comment]
@baconpaul It seems JUCE peoples nailed this one, if I understand [the commit log](https://github.com/juce-framework/JUCE/commit/a1a8e1339f0cb28e47812b69cf4b8c3861e2655c) correctly!

**Comment by baconpaul** [comment]
Yes it seems so!
