### ISSUE TITLE
Tune button doesn't toggle loaded tuning on Windows

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4729]
Exactly as subject says.

![tune](https://user-images.githubusercontent.com/2393720/124750722-18a2b600-df26-11eb-8373-5e57b57b757c.gif)

**Comment by baconpaul** [comment]
So here’s how it works on Mac at head

with a tuning loaded the button toggles
If you toggle tuning on and choose standard tuning it is no longer toggleable

so I think what we need to do is - like I did with the rest of the tuning stack in 19 - write the state machine charefulky then see where I introduced the bug in the ui rewrite. Easy but requires a wee bit of caution since we need to deal with the rebuild and the non rebuild state
