### ISSUE TITLE
Offline manual

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#4961]
So we were just spitballing on DIscord about this. An idea popped up: we could ship releases with the latest state of the online manual copied as HTML (+all required assets) into a subfolder of the factory directory. Then the [?] menu option would use the offline manual to open in the browser. If somehow the offline manual is not available, fallback to online manual.

And @baconpaul told me to add these words to the issue: "manual has a version number associated". 🙂

**Comment by mynameismuhl** [comment]
Cool! If that part is touched anyway I would love to add a "context help language selector" to this.

I made a DE version of `paramdocumentation.xml` already 
(and had somewhere in the past built a version that installs and uses the translated links exclusively.)
maybe this could be considered when changing the cmake rules?

the goal would be to use english by default but have a menu option to set the preferred language.

**Comment by baconpaul** [comment]
Connect with #4477 and #4304 then just do them all one day

**Comment by baconpaul** [comment]
So turns out this is really a pain in the neck so I'm going to close the issue as a won't do.

The reason it is hard, in case anyone wants to re-open it, is we need the manual in all our installers of course. So something has to check out the website repo, generate the manual in a readable form (not markdown), put it in the resources directory and do all of that on all three oses in the release pipeline before we make the installer. Or do it at the top of the pipeline and do inter connectivity.

So tagging won't do and closing.

If someone comes along with a credible plan to do it please reopen.
