### ISSUE TITLE
Surge has many possible priority inversions on the audio thread.

### ISSUE THREAD

**Issue by sagantech** [surge-synthesizer/surge#505]
A priority inversion is when a high priority thread is waiting for a low priority thread to finish. This can occur in Surge because of the many memory allocation performed when voices are played. If a memory allocation is performed on a high priority audio thread and the UI thread, or any other thread in the same process, is allocating memory, a priority inversion will occur. Currently the SurgeVoice constructor makes many memory allocations.

**To Reproduce**
Play a note.

**Expected behavior**
No priority inversions.

This may be a difficult problem to fix in Surge.

**Comment by baconpaul** [comment]
Do you have particular tools to show this? That could be useful.

I took a look because of your comment on SurgeVoice with some alacrity.

I'm sure you know this, but the SurgeVoice allocators are in two phases. When the voices_array is constructed the stack is created all at startup. The event that happens at voice play does not allocate the voice, but rather calls the voice constructor again on a pre-created instance. 

So at startup we have about 128 calls to SurgeVoice::SurgeVoice() then at each note we have a call to SurgeVoice::SurgeVoice( arglist ) but that second call isn't on a newly allocated block of memory; rather it gets the startup allocated element from the vector and does `new (element) SurgeVoice` which runs the constructor over the pre-allocated memory. I'm sure you've read the voice management software in SurgeSynthesizer and all but want to make sure you aren't seeing other behavior. 

I didn't trap malloc or anything, but reading the larger constructor it doesn't seem to do much beyond assignments.

Oh and from double checking that code, I bet when I finally fix #339 I will end up fixing it in the "if( !found_one ) block of SurgeSynthesizer around line 458 in the pm_mono_st_fp case block.

**Comment by sagantech** [comment]
I don't want to argue about this. Just put a breakpoint at malloc and set it to break when the threadid is not equal to the UI thread.

**Comment by baconpaul** [comment]
OK, one day I’m sure someone will. Maybe me!

If you have, and are interested, feel free to share any catches you find here too. Especially if you find unexpected new SurgeVoice activity, which we have re-arranged withthe alignment changes, I am sure we would be interested.

Thank you

**Comment by sagantech** [comment]
Sorry but now that debugging is so slow it is unlikely that I will be working with this version.

**Comment by baconpaul** [comment]
Something makes the w32 surge debug dll prohibitiveky slow for @sagantech. We don’t know what. The release dll works fine for him and it does for me also (now that I put in the windows 32 bit fixes)

**Comment by sagantech** [comment]
I hate to admit to debugging it because I said I wouldn't but it is 'delete' that is slow it seems to be doing heap checking on each call under win32 c++17. In TinyXML each compare does a new and a delete (unnecessarily in my opinion since it is like 8 bytes).

**Comment by baconpaul** [comment]
Heya @sagantech I'm sorry you are having these problems. Also let me acknowledge that you and I seem to not have a shared context and resulting communication style which leads to our mutual and easy collaboration. 

Nonetheless, I did a build of surge 32bit debug on windows 10 with the latest vs2017, loaded it into bitwig, and it played notes and started no problem. Takes about 2-3 seconds more than the release version. This is all in a parallels VM with an up to date windows 10. So I can't replicate this extreme debug delay you are seeing.

I did notice, at high voice count, the onset of distortion and crackling. I'm still somewhat unsurprised by this in a debug release. 

The UI was functional in basically every way I tried.

Somewhat concerningly, the new headless code I wrote gave a different result with debug 32 on, but that code is too new for that to be definitive, and I haven't tried it in release 32 either.

I took a look around googling the internet, and it seems some older versions of vs2017 had the super-aggressive debug heap system on by default although it wasn't entirely clear to me.  My version is

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cl /version
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```

I hope you find this helpful.

**Comment by baconpaul** [comment]
OK so I'm going to close this issue, not because it is wrong but because it is not specific enough. With the memory leak I found last night in the voices, I now know where the allocations are mis-happening on the UI thread. I will make a new issue for those.

@sagantech if you are still maintaining your own branch, you may want to look at these two commits

973741c0885254c8025e118dd1b365f9528817db
506ec576ae3020175b0f97b41578790ce177ab8a

and the change to those in PR #804

**Comment by sagantech** [comment]
Allocations on the UI thread is not the problem and not what this thread was referring to.

**Comment by baconpaul** [comment]
Yup - I mistyped my comment. The allocation are in the audio thread
