### ISSUE TITLE
Menu entry to check for updates and sent to download page

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#506]
Some method of checking for Surge updates while in-plugin. I guess some would be against this, but I wouldn't _exactly mind_ this.

@baconpaul thoughts?

I would be against it popping up everytime you load up the plugin, but to have a Menu entry would be pretty useful

**Comment by baconpaul** [comment]
A menu item to open the release page is easy

To check for updates I need to grab a document with a version and compare it to my version. That's more work.

@kzantow can we upload a document to the releases page along with the releases like "build-info.txt" which contains the git head and build date? Then I could URL grab that and have check for updates work.

We should do it on user action, not on surge startup, I think. Mostly because we do an update with every PR so don't want to bug users.

**Comment by mkruselj** [comment]
Waiting on @kzantow reply since Feb 2019... 😛
