### ISSUE TITLE
Old-Surge feature: Folders with .wav -format wavetables used to be shown and were loadable from wavetable-context menu.

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#509]
Here's a screenshot provided by layzer on KVR -- so this is a folder with wavefiles in it, and the wavetable-dropdown menu displays it. in fact, the .wavs can even be loaded.

![surgeppg](https://user-images.githubusercontent.com/4966687/52267657-4f81d580-2942-11e9-89d8-f1046ca0f0b2.JPG)

p.s. and yep i asked him, dragging a .wav from the windows explorer will also load it, so old-surge definitely supported these :)

**Comment by baconpaul** [comment]
Drag a wav on windows today actually works.

#288 would allow this to load from user folders and we need to do that, obviously.

And then have the reader work on mac which is #198 

so linking those up all together.

Can we add a label "path to wav" and tag up all these related issues? I'll take a swing at em when I next have 4 or 5 hours of uninterrupted dev time. (Not today).

Thank you for this information. Super useful..

**Comment by tank-trax** [comment]
I noticed that the .wt files in the wavetables folder are not loaded (at least not on the Linux build)

I had to remove a few of the presets (FXP files) as they caused whatever DAW or host to crash when attempting to load them

**Comment by baconpaul** [comment]
Hi @tank-trax 
That's probably a different issue; can you answer a quick question for me, since there's two code paths.

Is the crash when you take a patch and switch to wavetable then drop one down from the menu?
Or is the crash when you open a preset which uses a wavetable and it loads?

I'll try and fire up a linux vm and give it a try; and will probably move this to a separate issue.

But also: woohoo! We're finally in a state to get linux bug reports :)

**Comment by baconpaul** [comment]
OK just fired up my linux vm with latest build and was able to open patches with embedded waveforms and also open several of the wavetables.

I'm sure there is some codepath that crashes the thing. If you have a bit more info (like host, daw, linux version, build, which wavetables crash) would you mind opening another issue?

Thanks!

**Comment by tank-trax** [comment]
I managed to successfully build the VST2. The VST3 and the standalone build but the VST3 is not recognized by any DAW's or hosts and the standalone does nothing if run from the command line. No errors. Nothing.

The VST2 works well in Reaper, Waveform and Carla but does not load in Bitwig or Renoise. I use Debian Stretch 9.6 with KDE plasma as my DE. 

The crashes happened with one of the FXP files that I have since removed. I removed a few others that were buggy but for the most part almost all the presets load. 

The Wavetable files do not load. The folders show but nothing with a .wt extension is showing up or loading

**Comment by tank-trax** [comment]
There are some graphics issues in Linux where things like buttons and sliders disappear when moved around and the GUI needs to be refreshed for them to show up again. I am not sure where I should post bugs I find.

**Comment by baconpaul** [comment]
Yeah I just opened an issue for the graphics problem. We already have one for bitwig linux. Hold on - let me give you the right locations for these things. It's going to put stuff in this ticket which is separate from this issue.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/issues/513 Linux Drawing Errors
https://github.com/surge-synthesizer/surge/issues/492 Linux host status

and the newly created

https://github.com/surge-synthesizer/surge/issues/514 Linux VST3

The standalone doesn't do anything, yeah. There's a headless coming soon #502 

Thanks!
