### ISSUE TITLE
Notes are playing when typing text

### ISSUE THREAD

**Issue by mynameismuhl** [surge-synthesizer/surge#5123]
6a8c861b2949d52fcf3fe7bcb808af259a015be8 Linux 
Standalone and VST3

Typing text in either the store dialog or the patch db search bar also plays notes,
if the virtual keyboard is shown.

**Comment by baconpaul** [comment]
This doesn't happen on mac
@mkruselj can you confirm windows is ok?
if so i will fire up my linux vm and look!
thanks for the report as always

**Comment by mkruselj** [comment]
It happens on Windows too!

**Comment by baconpaul** [comment]
OK the problem is that some components on lin/win pass some of their state on to the parent but not all of it. Text Editors are like this. And the API makes this very hard to detect

The correct thing is to keep a map of all keypresses i forward and then only forward state changes for forwarded key presses. That's a lot of work though so for now i just disabled it on win/lin to not be annoying for those platform users.

**Comment by baconpaul** [comment]
Alright fixing this is miserable. the way midi keyboard works is if there is a state change it just re-scans the keyboard for presses; rather than accumulating them based on event. Thats smart. but the lin/win text edits don't eat their state change off when you release a paired key. So that release makes the state change get forwarded.

There's all sorts of intricate fixes but the one i'm going with is: I'm going to add an SGE::SupressKeystrokeForwarding type thing and just poll that before i forward. Then the things with typeins (patch browser and save overlay, typeins, and mini edit) will suppress it when shown and unspress it afterwards. The other ways are all hard.
