### ISSUE TITLE
Airwindows Tube DSP not continuous in input parameter

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5126]
Yep.

**Comment by baconpaul** [comment]
Oh right so this is not zippering
This is: The Tube DSP is not continuous smoothly in A.

Here's the code where "A" is the parameter

```
double iterations = 1.0-A;
	int powerfactor = (5.0*iterations)+1;
	double gainscaling = 1.0/(double)(powerfactor+1);
	double outputscaling = 1.0 + (1.0/(double)(powerfactor));
```

So clearly gainscaling is not continuous in A; and moreover

```
double factor = inputSampleL; //Left channel
		
		for (int x = 0; x < powerfactor; x++) factor *= inputSampleL;
		//this applies more and more of a 'curve' to the transfer function
		
		if (powerfactor % 2 == 1) factor = (factor/inputSampleL)*fabs(inputSampleL);
		//if we would've got an asymmetrical effect this undoes the last step, and then
		//redoes it using an absolute value to make the effect symmetrical again
```

so when A changes from 0.799 to 0.801 the algorithm changes discontinuously

Let me tag @airwindows here

I'm not sure if there's anything to be done here other than "don't include tube in surge since its not a robust modulation target". But I haven't looked at Tube2 yet so maybe sub Tube for Tube2 is the answer also.

**Comment by mkruselj** [comment]
Yes I would lean towards replacing Tube with Tube2 if it modulates better. I don't care if it sounds different, modulating targets should never create zipper noises in a synthesizer.

**Comment by baconpaul** [comment]
i agree

**Comment by baconpaul** [comment]
Tube2 has the same code.
I think 'disable the tubes' is alas the answer.
