### ISSUE TITLE
Surge crashe when closing UI (within bitwig)

### ISSUE THREAD

**Issue by pitrackster** [surge-synthesizer/surge#5160]
**Bug Description:**
Opening Surge within Bitwig causes no problems. But when I close Surge UI plugin crashes.

**Surge Version**

* Version: 1.9.0.91069f8
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Add a track with surge
2. Surge UI is opening
3. Close Surge UI

**Expected Behavior:**
Surge UI should disappear without any error message.

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS with 5.4.0-86-lowlatency kernel
 - Host: Bitwig
 - Version: 3.2.8

**Additional Information:**

- Bitwig logs for "add a surge track"

```bash
About to start the following process:  /opt/bitwig-studio/bin/BitwigPluginHost64 host Surge-Synth-Team-Surge-3 48000 256 6984-3 4 not-dpi-aware 5 HDA Intel PCH;ALC236 Analog;HDA:10ec0236,17aa38c9,00100002 HDA:8086280b,80860101,00100000;HDA-Intel;0;0 HDA Intel PCH / ALC236 Analog
Creating plugin audio thread proxy 0
PluginHost: Starting new audio thread for processing plugin 0
Successfully set thread realtime priority to 19
Applying plugin IO state
Applying plugin instance state
IPlugFrame is a runloop 0xc00200
```
- logs added after the "close surge UI action"
```bash
Could not read async reply: End of stream
Killing pluginhost process
Waiting for plugin host process to exit
Plugin host process exited with code: 256
Child process with PID 7204 exited with error code: 1
``

**Comment by baconpaul** [comment]
Hi

yes bitwig In the 3.2 vintages has vst3 support issues. 

**Q: I'm having problems with the VST3 in Bitwig/Linux**
A: Bitwig Linux Surge VST3 requires at least Bitwig 3.2.0. Bitwig versions between 3.2.5 and 3.3 beta 3 have a problem with sub-processes and dynamic libraries which Surge hits, meaning in those versions you must run surge in process (not sandboxed). This issue was partially fixed as of Bitwig 3.3 beta4 and fully fixed in Bitwig 3.3 beta 5, where Surge works properly.

So: 3.2.0 - 3.2.4: fine. 3.2.5 - 3.3 beta 3: only fine if you don't sandbox. 3.3 beta5 and up: fine.

**Comment by pitrackster** [comment]
Oups ... I should have read the FAQ before submitting issue. Thanks for your answer

**Comment by baconpaul** [comment]
No worries! Have fun using surge!
