### ISSUE TITLE
Modulation List Book of Work

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5323]
Replaces #2049 

- [x] Mouse wheel on scroll vs the slider

**Comment by VincyZed** [comment]
In case this might help, I saw that the frame rate also drops in the same way when the formula modulator editor or the MSEG are opened. I also tried in Reaper and it does the same thing too.

**Comment by baconpaul** [comment]
Help me understand how you see a frame rate change? Like what changes? And is it when the overlay is torn out or overplayed?

**Comment by VincyZed** [comment]
New small ones: When modulating for instance the Amplitude of an envelope from another mod source, the modulated envelope will be written as "LFO 4" in the mod list instead of "ENV 4" as an example:
![image](https://user-images.githubusercontent.com/50145178/143289560-bcae8bae-cd9e-4c67-9aa4-7dadaa26bac8.png)

Also, if you change the mod shape from LFO to Envelope on voice modulator 1 while the modlist is opened, it won't update until closed and re-opened
