### ISSUE TITLE
After left-click opening a menu, left-clicking on that menu button again should close it

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#5395]
Title is pretty self-explanatory. 
AFAIK, this happens with all menus (OSC type, Patch browser, "Filter By" in the modulation list, etc. ).

**Comment by baconpaul** [comment]
oh this is supper annoying. 
the mouse event on the button launches the popup
this means i have to keep maintain and not blow all the state for popup open
this is all because the menu doesn't stop the mouse  events on the underlying.
May not make into XT1 

pianoteq 7 on mac does this but gets hover state wrong when you dismiss, i notice.

**Comment by baconpaul** [comment]
OK there's a sort of fix

If for each place in the code we do a showMenuAsync we instead convert

```cpp
foo.showMenuAsync(...)
```

to

```cpp
if (!juce::PopupMenu::dismissAllActiveMenus())
{ 
    foo.showMenuAsync(...)
}
```

then a menu won't pop up if one is showing. 

I did this at the two spots in XMLConfiguredMenu (I skipped the accessibility one since that's a bit different) and then got oscmenu/click loading the menu then click on it again and it closes. But also oscmenu/click - click on FX selector and the oscmenu closes and the fxmenu does not open

this is also what 1.9 does so i think its a reasonable fix.

**Comment by baconpaul** [comment]
Yeah Ok this will work. Will merge it.

**Comment by mkruselj** [comment]
@baconpaul Reopening this issue because the new behavior after #5398 does not match what 1.9 did at all.

What 1.9 did was it closed the popup menu ONLY if the mouse position didn't change at all. So, hold the mouse stationary at main menu or osc menu or FX menu, right-click it, menu opens. Right-click it again, menu closes. BUT if you right-click the menu, menu opens, then you move the mouse slightly and right-click again - menu is reopened at the new position.

**Comment by VincyZed** [comment]
So **right-clicking** somewhere else on a menu button area should move the menu (so keep it opened), but **left-clicking** somewhere on that menu button should close it, even if we moved the mouse.

**Comment by baconpaul** [comment]
this is so miserably difficult
when we open the filter menu we have by then lost the left/right distinction
i just don't know how to do this easily
:(

**Comment by mkruselj** [comment]
I would then suggest reverting #5398 and pushing this to XT2.

**Comment by baconpaul** [comment]
Yeah unfortunately the crash on close with menu item means I can’t auto revert without conflicts so will have to do it by hand. Will do so

**Comment by VincyZed** [comment]
This looks fixed on my end. Anyone could confirm before closing this issue?

**Comment by mkruselj** [comment]
I can confirm it fixed. The only outliers are filter type menus and menu-as-sliders in certain oscs and FX - because they pop the menu up at mouse cursor, instead of below the menu widget.

But yes we can consider this one closed I think!

**Comment by VincyZed** [comment]
Both the filter type menus and menu-as-sliders work fine for me:
you just have to move your mouse pointer a little bit, but clicking on the menu does close it correctly.
