### ISSUE TITLE
Linux: Inactive buttons

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#544]
the KEYTRACK and RETRIGGER buttons in the Oscillator section do not change colours, either to yellow or back to black, if clicked in Linux

they do appear to be active though

same for the red M and S buttons in the Scene section
the green Filter buttons just below however are functional

**Comment by tank-trax** [comment]
![screenshot_20190208_173413](https://user-images.githubusercontent.com/41337033/52510347-a0efc600-2bc9-11e9-9ae3-618bbbf96f43.png)

**Comment by baconpaul** [comment]
Thanks. Very specific and also very odd. Appreciate the detail.

**Comment by rghvdberg** [comment]
confirmed here

**Comment by baconpaul** [comment]
@rghvdberg a few controls (mute, solo, unipolar, relative, and link) use `CSwitchControl` rather than `CHSwitchControl`. The mute control is created in the ct_bool_solo case statement around line 856 of SurgeGUIEditor.coo

Oh and now reading the code, I know the bug.

CSwitchControl draws the background with a command that looks like `pBackground->draw(...,0xff)`

That `0xff` sets the alpha to 255 which you would think is right. And is on mac. But there's a bug in cairo that the bitmap draw explicitly compares with 255. See the comment in line 164 of CScalableBitmap.cpp

So I think the fix for now is in CSwitchControl add

```
   float alpha = 0xff;
#if LINUX
  // FIXME: see comment in cscalablebitmap
   float alpha = 1.0
#endif

  ...
  pBackground->draw( ......, alpha )
```

and update CScalableBitmap comment only to point at the change we made here too.

Good luck!

**Comment by baconpaul** [comment]
oh and I haven't tested this or anything. This is just from looking at the code to write a guide on how it hangs together. So bug may be something else.

**Comment by tank-trax** [comment]
this may or may not be a clue

I ran Waveform9 and Reaper from the shell and when Surge loads in either DAW this error message appears...

```
scalable/bmp00110.png not found
scalable/bmp00110@15x.png not found
scalable/bmp00110@2x.png not found
scalable/bmp00110@3x.png not found
scalable/bmp00110@4x.png not found
scalable/bmp00150.png not found
scalable/bmp00150@15x.png not found
scalable/bmp00150@2x.png not found
scalable/bmp00150@3x.png not found
scalable/bmp00150@4x.png not found
Surge Error
```

could those be the missing images?

**Comment by rghvdberg** [comment]
bmp00110.png = IDB_OSCSWITCH
bmp00150.png = IDB_BUTTON_CHECK
see [resource.h](https://github.com/surge-synthesizer/surge/blob/master/src/common/resource.h)
but I don't see them used in [SurgeGUIEditor.cpp](https://github.com/surge-synthesizer/surge/blob/master/src/common/gui/SurgeGUIEditor.cpp)

**Comment by rghvdberg** [comment]
I think that any bitmap drawn with [CSwitchControl::draw()](https://github.com/surge-synthesizer/surge/blob/b273f9e1c071481c1a34039a5045403507a03402/src/common/gui/CSwitchControl.h#L11) doesn't show up.

**Comment by rghvdberg** [comment]
I've tried this CSwitchControl.cpp
```CRect size = getViewSize();
   printf("get ViewSize() %f, %f\n",size.getHeight(),size.getWidth());
   auto pBackground = getBackground();
   auto testSize = pBackground->getSize();
   printf("pBackground size %f,%f\n",testSize.x,testSize.y);
```
output
```
get ViewSize() 15.000000, 22.000000
pBackground size 0.000000,0.000000
```
am I on to something ?

**Comment by baconpaul** [comment]
OK so crack debugging @rghvdberg the bitmaps have size 0x0 and have size 0x0 only on linux

The reason for this is because CScalableBitmap subclasses VSTGUI::CBitmap. On win and mac the parent constructor `: CBitmap(desc)` at line 41 or so sets up the parent class to load the original 100x asset; on linux it doesn't because resource resolution works differently on linux. As a result the parent class ::getSize() returns 0 on linux and returns the correct size on mac and win. Bummer

The reason anything works though is because CSwitchControl and only CSwitchControl reads the height of an image from the bitmap. Compare CHSwitch2::draw (which uses the member variable heightOfOneImage which is set on construction) to CSwitchControl (which uses pBackground->getHeight() if is_itype is false). And is_itype is always false.

OK so now we know the problem. We either need to

1. Patch CSwitchControl so it doesn't get the height from pBackground->getHeight() or
2. Patch CScalableBitmap so it responds to getHeight properly

The second seemed smart. Just override getHeight in CScalableBitmap and blammo fixxo. But getHeight is not virtual in cbitmap so nope. If we want to make CScableBitmap respond to get height we need to construct the base class properly.

So lets explore #1 a bit. The "is_itype" means it is a two state button and the top half of the image is off and the bottom half of the image is on. This matches what we see in the mute button image.

![bmp00134 4x](https://user-images.githubusercontent.com/13387561/52652055-60d75e80-2ebb-11e9-855d-5a4783af0a57.png)

So that translation is just moving half way down the image when it is on. 

```
         CPoint where(0, (down ? (pBackground->getHeight() / 2) : 0));
         pBackground->draw(dc, size, where, 0xff);
```

But the image takes up the entire rect into which it draws, so our constructor knows how big it is. This leads me to the easiest approach

1. Add a member 'heightOSinglefImage' to CSwitchControl.cpp
2. In the constructor set heightOfSingleImage = size.getHeight()
3. In the draw method replace pBackground->getHeight() with heightOfSIngleImage
4. Test on linux; if it works make a PR and we will test on mac and win and then merge

The other path is harder, which is make CScalableBitmap pass a proper thing to its base class. To do that

1. Factor the code which makes a filename at line 80 into a member function of CScalableBitmap
2. Replace the scamp #if MAC with that function rather than filename.str().c_str()
3. Make the try block in an #if linux into another function which is #if linux, called perhaps "platformBitmapForIDAndScale" which calls the filename function then does that try block. Call it around line 83
4. Once that function is written change the constructor around line 41 so

```
   : CBitmap(desc)
```

becomes

```
#if LINUX
   : CBitmap( makePlatformBitmapForIDAndScale( desc.u.id, 100 ) )
#else
  : CBitmap( desc )
#endif`
```

and test and sweep. That is in some sense "more correct" but it is also a way bigger change. I would approve the first PR with the simpler approach in a heartbeat if it works.

Hope that helps!
