### ISSUE TITLE
J5v reports stale ui with patch swaps

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5470]
(My theory is the refresh patch sets the rebuild sentinel before not after the patch load and so the idle can catch the rebuild before the patch load. That will mean values don’t update but the synth does. Then when the oscillator repaints it uses the synth but the non dybamic@elements like sliders and stuff stay stale. If this is correct a stuck surge would heal if you did something like swap an lfo or load a new fix)

**Comment by j5v** [comment]
Steps to reproduce:
1. Start DAW, load in a project that has an existing Surge XT track set up.
2. View the Surge instance. It views as 'init' as expected.
3. Load a Surge patch from the **Patch Browser** menu (this can be from a user folder, or the factory presets).

Expected result: the patch loads and the display updates.

Actual result: the patch loads, but only the oscillator part of the display updates.
If I play the patch it sounds as expected. However (for example) the **Patch Browser** still shows "init", **Macro** names and values are not displayed, 

Further attempts to load a patch: same behavior; the display fails to update.

Attempts to reproduce in a different session: cannot reproduce. I'll make some attempts now...

**Comment by baconpaul** [comment]
the patch browser menu is the right mouse menu, not the fancy new typeahead thing, right?

**Comment by baconpaul** [comment]
this could also happen if the idle thread crashes. If you capture this again, i'd be interested in knowing if an LFO swap or changing FX bank and FX items does stuff or not.

Thanks!

**Comment by j5v** [comment]
> the patch browser menu is the right mouse menu, not the fancy new typeahead thing, right?
Left-click in the area labelled **Patch Browser** (where the patch name is) - it shows the four-column list.

**Comment by j5v** [comment]
I've found a way to produce _similar_ results, which is a different (less critical) bug, different because for the originally-reported bug, I could audition the patches using the virtual keyboard in Surge, so the audio engine was still running.

The 'different' bug, which is caused by the audio engine not running:
I can switch off the DAW's audio engine, and then quickly change patch in Surge before Surge notices.
I then see "Audio engine not available" in the Output meter of Surge (I cannot be sure that was present in the original occurrence of the problem).
In this state, Surge does not display the modal overlay, and (predictably) the UI does not update. However, I can still select patches, but the display doesn't update.

**Comment by baconpaul** [comment]
I wonder if this is related to the load order fix i fixed in https://github.com/surge-synthesizer/surge/commit/ccf5d842755279c3db0003b674e059c611fd39e5 which means that the DAW load can happen in a way which left the state incorrect on the synth editor in some daw load paths.

Any luck on a more reliably repro with a recent nightly @j5v ?

**Comment by mkruselj** [comment]
@j5v Any new info on this one, perhaps?

**Comment by j5v** [comment]
I cannot reproduce this bug again. Close, given changes in #5547 ?
