### ISSUE TITLE
Name CC's according to GM spec

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#552]
Suggestion, name CC according to GM Spec (Pan, Volume, etc), instead of having `CC # 0`

![fullscreen_09_02_2019__14_02](https://user-images.githubusercontent.com/4966687/52520581-69d5ef00-2c73-11e9-97eb-e5281e4be59f.jpg)

**Comment by baconpaul** [comment]
If we do that mapping we should do it I'm the learn display also
Tagging as good first issue. Not hard once you have the data

**Comment by esaruoho** [comment]
This stuff seems related, too
```
src/common/gui/SurgeGUIEditor.cpp:      sprintf(txt, "CC %i", num);
src/common/gui/SurgeGUIEditor.cpp:                     sprintf( name, "CC %d -> %d", mc, min( mc+10, 127 ));
src/common/gui/SurgeGUIEditor.cpp:                 sprintf( name, "CC # %d", mc );
```
somewhat, at least

Accessed it by typing `git grep "\"CC"`

**Comment by baconpaul** [comment]
yeah that's the code that makes those menus. :)

**Comment by esaruoho** [comment]
> yeah that's the code that makes those menus. :)

i was actually hoping to find a lookup table in regular-strings (human-readable, editable) :) could've started punching in CC7 = volume or pan or whichever it was

**Comment by esaruoho** [comment]
not all of this stuff is going to be valid, but it's a start.
![fullscreen_09_02_2019__14_20](https://user-images.githubusercontent.com/4966687/52520760-ec5fae00-2c75-11e9-8f34-32f280e4aea9.jpg)
![fullscreen_09_02_2019__14_21](https://user-images.githubusercontent.com/4966687/52520765-fc778d80-2c75-11e9-811c-2ddded167a98.jpg)
![fullscreen_09_02_2019__14_21](https://user-images.githubusercontent.com/4966687/52520772-0bf6d680-2c76-11e9-97b2-0304bc6077ce.jpg)

there's probably some site where this stuff can be kicked out as text instead of screenshots :)

**Comment by baconpaul** [comment]
That place is: https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2

**Comment by itsmedavep** [comment]
Just so that Im clear, the desire is:

1) Name the CC's to the GM spec
2) Actually map the CC's to the given parameter

Is that right? Naming them what the spec says they should be when in reality they are not mapped to those CC's is a bit misleading no?

https://user-images.githubusercontent.com/4966687/52520581-69d5ef00-2c73-11e9-97eb-e5281e4be59f.jpg

To use this as an example. If I were to go in and change the label for CC 1

I would go into CC 0 -> 10 menu and find CC 1 change its label to CC 1 = Modulation.

Thats great _if_ CC 1 is mapped to modulation. If its not actually mapped it's a bit disingenuous is it not? 

I want to make sure that the "ask" is clear. Not only is this about updating the strings but its _*also*_  mapping the CC's as well.  

@esaruoho @baconpaul 
Is my understanding correct here?

**Comment by baconpaul** [comment]
I think name them on the menu so they match the spec; remove the ones which are not learnable (that's a separate issue but I think we should at least not have them in the menu - don't disable learning yet but you know) and add a check mark to the one which is currently mapped if it is learned. That's what I think the ask is.

**Comment by itsmedavep** [comment]
Thanks. That helps. Theres a few details in there I missed! 

I can certainly do the rename. 
I haven't looked at the code yet but my hunch is its easy to get the unmappable out of the menu. 
IDK about the check mark. Im willing to give that bit a shot too.

**Comment by baconpaul** [comment]
ill Drop some notes in on checkmark tomorrow

**Comment by itsmedavep** [comment]
Just a heads up to anyone interested. I started to chip away at this one tonight. Havent made much progress yet though. Ill have some more time over the weekend.

**Comment by mkruselj** [comment]
I chipped it away completely. 🔥
