### ISSUE TITLE
Global distorsion effect is not loaded correctly

### ISSUE THREAD

**Issue by hsn10** [surge-synthesizer/surge#5524]
**Bug Description:**
After loading my saved patch there is no sound. It looks like it is caused by global distorsion effect not initializing correctly.

**Surge Version**

* Version: 190
* Plugin Type: VST3
* Bitness: 64-bit

**Reproduction Steps:**
1. Load attached patch
2. There should be sound but I hear only clicking

**Expected Behavior:**
Loading patch should sound the same as patch sounded at the time it got saved.

**Computer Information:**
 - OS: Windows 10
 - Host: Cakewalk

[Distored Guitar.zip](https://github.com/surge-synthesizer/surge/files/7613541/Distored.Guitar.zip)

**Comment by baconpaul** [comment]
There’s a bug in 19 if you use waveshapers other than soft and hard which we fixed in xt. I haven’t looked at patch yet but wonder if that’s the case here

**Comment by hsn10** [comment]
Patch is using _waveshaper hard_. It looks like initialization problem, values for distorsion are loaded back from file correctly.

**Comment by baconpaul** [comment]
The patch you shared has the wave shaper set to "Sine" which was one of the wave shaper setups we fixed

I checked your patch and it loaded in XT (the beta version now ready for release in January). The commit that fixed it was 553e04c4d2b7b1b688e6f6a47a757453209946dc

So I think this is fixed in the new version. Any chance you'd be interested in trying the beta? IF not, changing from 'sine' to 'hard' in the 'model' dropdown, saving, and restarting your daw should fix it with 1.9

**Comment by baconpaul** [comment]
oh and the wavehsaper in question here is the one in the 'model' param of the distortion, not the wave shaper in the filter section, just FYI

**Comment by hsn10** [comment]
You plan to fix 1.9 line? I don't want to install new version to mess up presets.

**Comment by mkruselj** [comment]
We won't be returning to 1.9 anymore. At any rate Surge XT installs side by side so none of your patches will be affected.

**Comment by baconpaul** [comment]
but also you can just change the model from 'sine' to 'hard' in your distortion preset and everything will work.

**Comment by mkruselj** [comment]
Closing as fixed in XT.
