### ISSUE TITLE
No Freerun on LFO - Surge XT

### ISSUE THREAD

**Issue by hellerdejanuar** [surge-synthesizer/surge#5534]
**Bug Description:**
Voice LFO Freerun doesn't behave as (I) expected. It seems to work almost like retrig, making it impossible to keep it phase synched with tempo. 

**Surge Version**
Surge XT 0.9.nightly.7323973

* Version:
* Plugin Type: VST3
* Bitness:  64-bit

**Reproduction Steps:**
1. Simple patch with LFO (not SLFO) to cutoff. Optionally set rate to Sync.
2. Select Freerun
3. Play two notes spaced half a LFO cycle
4. The two notes have now different phase. And none is synched to session BPM

**Expected Behavior:**
In Surge (no XT) it does work as intended.

**Computer Information (please complete the following information):**
 - OS: Macos Mojave
 - Host: Ableton
 - Version: 11.0.2

**Comment by baconpaul** [comment]
Ha so, the freerun works as expected if you run transport, but doesn't if transport is paused. (at least in LPX)

Believe it or not, that's a return of https://github.com/surge-synthesizer/surge/issues/146

Just in JUCE. Note that that bug was one I fixed almost 3 years ago. Funny!

If there's no transport we don't advance ppqpos artificially, and freerun VLFOs use song position.

I'll tag this into the milestone and apply the fix. Thank you for the excellent bug report.

**Comment by hellerdejanuar** [comment]
forgot to mention it also doesn't work with the transport running.

**Comment by baconpaul** [comment]
huh so then live is different than logic, or my test was bad. (Your nightly is also quite a bit older than mine but that's probably OK - I don't think this code has changed much)

I'll dig. Something odd is definitely afoot. Very much appreciate the bug report.

**Comment by baconpaul** [comment]
Anyway I found it! Turns out we had an internal counter update which was placed in a block from when we looped by block, not sample, in juce; so it's just moving one line. The reason transport made it 'better' for me in logic was because my buffer size (64) resets the ppqpos really frequently so the drift was not that bad although now i retest it, not perfect; but with long buffers the result would be worse

PR in and this issue will auto close when we merge it, and an hour or so after that there will e a new nightly with the fix.

Thanks for the bug report. Excellent and long standing bug in XT we hadn't identified. Really appreciated.
