### ISSUE TITLE
Mod list doesn't use proper mod f01 depth

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5562]
![image](https://user-images.githubusercontent.com/2393720/144824153-217acf45-20d6-4d02-94df-821b9efadb4c.png)
![image](https://user-images.githubusercontent.com/2393720/144824155-c94f7951-ba5e-42de-92e8-53517378736f.png)

**Comment by baconpaul** [comment]
Huh tbis should use the exact same code as the infowindow display - interresting

**Comment by baconpaul** [comment]
So this *is* the exact same code as the infowindow
and the info window doesn't show units for the bounds

but the problem isn't units; its that i'm not converting from f01 to native properly so real bug here

Check out the discrepancy between the info window and the moldiest for pitch here.

<img width="1100" alt="Screen Shot 2021-12-06 at 8 00 58 AM" src="https://user-images.githubusercontent.com/13387561/144850652-4fde3504-98d3-4292-8c74-f9738e03a2b1.png">

**Comment by baconpaul** [comment]
<img width="1137" alt="Screen Shot 2021-12-06 at 8 04 31 AM" src="https://user-images.githubusercontent.com/13387561/144850984-7e2455f5-21ab-4140-bc0b-9384fb0f4517.png">

And fixed!
