### ISSUE TITLE
NaN formula values crash Surge XT when a note is played

### ISSUE THREAD

**Issue by xard-dev** [surge-synthesizer/surge#5566]
**Bug Description:**
NaN formula values crash Surge XT when a note is played.

**Surge Version**
Surge XT 0.99.main.007a427

* Version:
* Plugin Type: LV2
* Bitness: 64-bit

**Reproduction Steps:**
1. Open first example preset "01 A Simple Formula".
2. Click on "FORM 1.1".
3. Click on the "Pen icon" to open Formula editor.
4. Change row "pclamp = limit_range(modstate["intphase"], 0, 10) / 10" tail to "... / 0".
5. Play a note.

**Expected Behavior:**
No sound is played and additionally an error message is displayed in some method.

**Screenshots:**
![image](https://user-images.githubusercontent.com/65303522/144840779-6c6934f0-eaea-4a60-9d47-f4a898fac8aa.png)

**Computer Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Host: Carla / Standalone
 - Version: 2.1.0

**Comment by baconpaul** [comment]
Great reports this morning! Thanks so much!!

**Comment by mkruselj** [comment]
Just FYI no need to put XT in the title since we're not going back to fixing 1.9 so everything that is reported already basically pertains to XT. Thanks!

**Comment by xard-dev** [comment]
Alright, I'll drop the prefix then.

**Comment by baconpaul** [comment]
on my mac this doesn't crash but does of course produce garbage
i wonder if you have fpe on in your host
but i can put a `std::is_finite()` check when i pull the values from lua back into c++ world

**Comment by baconpaul** [comment]
but first let me fire up linux and see if it crashes there.

**Comment by xard-dev** [comment]
Confirmed that the crash happens on standalone as well.

**Comment by baconpaul** [comment]
Right so there's a few things happening here

First of all the juce path renderer on linux throws exceptions with nans. Fine.

But more importantly, our limit_range assumes a finite input so with a nan all our checks blow up. The particular stack in this case happens in SurgeVoice where we use the pitch to interpolate across a 2^x interpolation array in the filter blah blah and it would be fine if we were accidentally out of bounds as long as we are finite

I don't want to make limit_range check std::isfinite. We use that everywhere. So the fix I propose - since we have made sure all the rest of the modulators never make nan and we can't guarantee that with lua - is to just check isfinite on the outbound of the formula modulator, set a flag, and voila. 

Will do that now.
