### ISSUE TITLE
Linux LV2 Reaper notes lingering / continuing after event finished 

### ISSUE THREAD

**Issue by jmarcham1983** [surge-synthesizer/surge#5612]
**Bug Description:**
notes continuing after midi event and unable to stop it 

**Surge Version**

* Version: surge XT 0.99 main .8775f73/ build 2021-12-03
* Plugin Type: LV2
* Bitness:  64-bit

**Expected Behavior:**
the note finishes after stop or midi event finishing

**Computer Information (please complete the following information):**
 - OS: MX linux
 - Host: Reaper 
v6.42 - November 16 2021

**Comment by baconpaul** [comment]
Can we get some more information? Which patch? Which midi controller? Do you have a reaper session which shows this reliably? Does it occur with the vst3 (the lv2 uses a community branch of juce not the official distro so has different handling of some things)

**Comment by jmarcham1983** [comment]
the notes appear to be functioning as normal using the vst3, the notes whilst using the LV2 plugin version don't linger whilst using the midi controller just whilst the sequence is playing, it does this using various patches, I will continue to use the vst3 instead, thanks for the advice

**Comment by baconpaul** [comment]
Ok @KottV @falkTX have you seen anything like this with your lv2 fork in Linux reaper?

@jmarcham1983 thank you very much for reporting this!

**Comment by jmarcham1983** [comment]
such a great plugin just thought this might improve it for others and myself, hope my input helps

**Comment by falkTX** [comment]
not really, first time I hear of such a thing. maybe a reaper side issue.

tbh I am not doing anything with the juce lv2 wrapper at the moment since the juce devs are doing their own custom implementation from scratch and not interested on contributors.

**Comment by baconpaul** [comment]
Ok I’ll close this then.
Should we remove the lv2 from our upcoming release?

**Comment by falkTX** [comment]
depends if people still find it useful or not I guess..

note that I will eventually get back to the juce lv2 wrapper, but it is best to wait for the official support first. my idea is to add the necessary backwards compatibility bits to the distrho fork, rather than maintaining a whole alternative wrapper. but if they take too long or give up, I will have to reconsider.

**Comment by baconpaul** [comment]
are there any hosts which run lv2 and not vst3?
we will definitely guide people to the vst3 though.

**Comment by falkTX** [comment]
on linux the vst3 support is still quite new for a few hosts, so it wont be as robust.
it is not an easy call, but if things are not terribly broken the extra format might be nice.

worth noting btw, VST3 SDK might not be compatible with GPL, because of their extra terms.
steinberg is yet to provide an answer https://forums.steinberg.net/t/cannot-use-the-gpl3-option/750876
as of now Fedora and RedHat distributions forbid the use of the VST3 SDK and will strip away or simply not package programs that make use of it, just as a safety concern.

**Comment by baconpaul** [comment]
I guess we’ll guide them to the vst3 and ubuntu then :)

Will leave the lv2 in for now. Thanks for getting back to me!
