### ISSUE TITLE
Make Pitch/Osc Octave/Keytrack/Retrigger semitransparent for Audio In oscillator

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5638]
Since they are inconsequential and do nothing for Audio In, they should be considered disabled. And we already show disabled things as 50% opaque 🙂

**Comment by baconpaul** [comment]
So the reason this is tricky is because we need a dynamic deactivation on something which isn't part of the oscillator. But not the end of the world.

Take a look in SurgePatch around line 500 and you can see we make a bunch of dynamic deactivations for the lfo stuff. What we need to do is

1. Make a similar dynamic deactivation for the oscillator pitch
2. Make the oscillator pitch param type allow user data and set that user data on
3. make the logic something like 'if the oscillator for my control group is audio in return true else return false'

and that will do it. Exact same pattern as the LFO deactivations there.
