### ISSUE TITLE
individual output problems in VST2 and VST3

### ISSUE THREAD

**Issue by K0rrid0r** [surge-synthesizer/surge#5655]
VST2

Version: Surge XT 0.99.main.37f1e40e
Build: 2021-12-21 @ 02:15:17 on 'KORRIDOR/local' with 'MSVC-19.26.28806.0' using JUCE 6.1.2
System: Windows 32-bit VST on Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Host: FruityLoops @ 44.1 kHz

Open up XT

Individual outputs are **on** when they shouldn't be

![image](https://user-images.githubusercontent.com/56724286/146853400-e2fb84d8-4dc9-41e5-9a3d-25884e68290b.png)

the individual outputs **make sounds** and i can turn them **off** and on via the menu.

when **cloning** a surge that had the individual outputs **off** will turn them **on** in the new clone, this is not wanted.

i cant save a state in surge nor a default preset that keep the individual outputs off.

**VST3**

Version: Surge XT 0.99.nightly.37f1e40
Build: 2021-12-19 @ 21:28:14 on 'fv-az102-738/pipeline' with 'MSVC-19.29.30137.0' using JUCE 6.1.2
System: Windows 32-bit VST3 on Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
Host: FruityLoops @ 44.1 kHz

When opening up XT VST3 individual outputs are on but they give **no sound**

![image](https://user-images.githubusercontent.com/56724286/146853776-16b39b53-1af0-4066-95f8-e4943623c752.png)

cloning the VST3 XT also put the individual outputs on again but they actually give no sound.

![image](https://user-images.githubusercontent.com/56724286/146853872-a0a990bc-2932-4003-9b24-dadf4e802e9d.png)

**Comment by baconpaul** [comment]
This is almost definitely due to the fact that no-one ever calls setupActivateExtraOutputs anywhere!!

**Comment by baconpaul** [comment]
@K0rrid0r if you get a chance (if not i can get to it also in the next few days)

in `src/surge-xt/SurgeSynthProcessor.cpp`

Around line 90 are these lines

```
   surge->hostProgram = juce::PluginHostType().getHostDescription();
    surge->juceWrapperType = wrapperTypeString;
```

Immediately after them add `surge->setupActivateExtraOutputs()` so it will look like

```
    surge->hostProgram = juce::PluginHostType().getHostDescription();
    surge->juceWrapperType = wrapperTypeString;
    surge->setupActivateExtraOutputs();
```

and rebuild and see if it fixes the problem you see?

Forever and a day this has been a global not an instance wide property; we should make it instance level in 1.1. But right now the switch isn't ever being called.

My code is sort of apart on the floor right now otherwise i would test. If you don't get to it I can look over the next week but I think that's the fix.

**Comment by K0rrid0r** [comment]
It's a fix! Now it works.

**Comment by baconpaul** [comment]
Great.

**Comment by baconpaul** [comment]
(Obviously we need to merge that fix before closing tbis but thanks for test)
