### ISSUE TITLE
Default skin fully in memory

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5747]
Currently we have all hovers and tempo sync overlays for the default skin installed to the file system, and the rest is being read from the binary. It would be nicer to just have a completely in memory default skin. Steps to do that:

1. Move out all SVGs from resources/data/skins/default.surge-skin to resources/classic-skin-svgs
2. Update resources/surge-xt/memory-skin.xml with tempo sync overlay setup
3. Add a flag to the skin to use hover assets from memory, which is false by default and only true for the in memory skin
4. Modify the hover resolution code to read that flag and use assets from the binary
5. Test all the skins and merge

**Comment by baconpaul** [comment]
So the reason this one is hard is because hovers resolve using `hoverBitmapOverlayForBackgroundBitmap` which uses the string id semantic to load. So what we need to do is have all those hover assets resolve in the getByStringID from memory.

That is this code gets run when resolving a hover

```
  switch (t)
        {
        case HOVER:
            sid << defaultImageIDPrefix << "hover" << std::setw(5) << std::setfill('0')
                << b->resourceID << ".svg";
            break;
        case HOVER_OVER_ON:
            sid << defaultImageIDPrefix << "hoverOn" << std::setw(5) << std::setfill('0')
                << b->resourceID << ".svg";
            break;
        }
        auto bmp = bitmapStore->getImageByStringID(sid.str());
```

There's a couple of ways to do this but since we want these images available as fallbacks I think the way I would do it is as follows

in SurgeImageStore.cpp we call a bunch of calls to addEntry. these calls to addEntry go ahead and add an entry by calling the SurgeImage constructor with this form

```
 resourceID = rid;
    std::string fn = "bmp00" + std::to_string(rid) + "_svg";
    int bds;
    auto bd = SurgeXTBinary::getNamedResource(fn.c_str(), bds);
    if (bd)
    {
        drawable = juce::Drawable::createFromImageData(bd, bds);
        currentDrawable = drawable.get();
    }
```

so cool now the path is clear

Make addEntry still do that. But *ALSO* make it check if there is a hover and hoverOn asset available in the memory database using the above API. If there is, then we can add another entry in this case to the byStringID

That is to SurgeImage add something like

```
static SurgeImage *createFromPrefix( const std:;string &pfx, int id)
{
std::string fn = "bmp00" + std::to_string(rid) + "_svg";
    int bds;
    auto bd = SurgeXTBinary::getNamedResource(fn.c_str(), bds);
    if (bd)
    {
        drawable = juce::Drawable::createFromImageData(bd, bds);
       return new SurgeImage(drawable.get()); // you will need a surge image ctor on a drawable
    } 
   return nullptr;

}
```

then make addEntry in addition to the thing ti does do a

```
if (auto *h = SurgeImage::createImageFor("hover", id))
   bitmap_file_registry["hover" + id as string appropriately] = h
```

and it should all work.

medium difficulty. Requires quite a bit of C++ knowledge and also the image db and skin engine knowledge.
