### ISSUE TITLE
Freerun doesn't freerun if transport stopped and loop mode enabled

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5812]
1. Init Saw
2. Set VLFO1 to Freerun
3. Modulate osc pitch with it
4. Be in Bitwig or Studio One or Maschine or MuLAB or Reason (out of hosts that I have), and enable transport loop mode
5. Play consecutive notes while transport is stopped

Result: notes all sound as if we're in Keytrigger mode for the LFO. Emulated song position pointer doesn't advance. Reaper also has transport loop mode, but for some reason, this doesn't happen in Reaper at all!

**Comment by baconpaul** [comment]
Ahh I bet it is this code

```
 if (cp.isPlaying || cp.isRecording || cp.isLooping)
            surge->time_data.ppqPos = cp.ppqPosition;
```

I thought the 'isLooping' meant 'is playing in a loop' but it seems it means 'isLoopEnabled'. 

That if should just be isPlaying since, according to the juce docs, isRecording is always true if isPlaying is true, and isLooping is transport is set to loop not that it is actually doing a loop.

lemme see if i can repro and if this fixes.

**Comment by baconpaul** [comment]
Yeah could repro in bitwig that's totally it

PR inbound.
