### ISSUE TITLE
Absolute mode for unison detune not working in Modern and Alias (fixed except in non-12-TET at modulation mode)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5898]
Yep!

**Comment by baconpaul** [comment]
Ugh on in the tun-after-modulation mode this turns out to be really really hard. It may ship as a bug still. Gonna tag this edge case as may-bounce.

The problem is these two oscillators work in 'dPhase' space and the unison calculation then needs to solve for the dPhase difference in an untuned way based on the pitch. tricky.

**Comment by baconpaul** [comment]
oh and of course as soon as i wrote this i figured out how to do it.
