### ISSUE TITLE
Z layer issue with overlays and modbutton drag and drop

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#5899]
See GIF!

![overlay z layer issue](https://user-images.githubusercontent.com/2393720/155111217-93cc8496-872b-457e-a10a-771eb55413d4.gif)

**Comment by baconpaul** [comment]
So the toFront happens around line 627 of ModulationSourceButton.cpp
that torrent we need. Especially on this. But we need to do overlays after parent

So what we want to do is

getParent->torrent (line 627)
[new code]
toFront(false) (line 628)

that new code should probably be finding and fronting all the visible overlays. They aren't modal so what you can do is add a new method to SGE like 'frontNonModalOverlays' which looks a lot like line 1950 of SGE but without the modal hook (since we can't initiate a drag with modal on). So just

```
  vector frontThese;
  for (auto c : frame->getChildren())
    {
        if (auto ol = dynamic_cast<Surge::Overlays::OverlayWrapper *>(c))
        {
            if (!ol->getIsModal())
                frontthese.push_back(c);
            }
        }
    }

   for f : frontthese
      f->toFront(true);
```

call that sandwiched in the middle and you should be good
