### ISSUE TITLE
Automation and MIDI CC not working in Surge XT 1.0.1.6

### ISSUE THREAD

**Issue by tegedo** [surge-synthesizer/surge#5974]
I want to use Surge XT 1.0.1.6 with Samplitude Pro X3 on Windows 10 (64); but Automation and Midi CC does not work with Samplitude. With Surge 1.9.0.91 Automation and Midi CC works fine, but the plugin changes pitch, need to transpose it to +2 to match the tune. It also would be great if the Standalone version of Surge XT works with JackRouter on Windows.

**Comment by mkruselj** [comment]
That would probably be a bug in Samplitude, or a bug in JUCE vs Samplitude... Unfortunately none of us use or have Samplitude.

**Comment by baconpaul** [comment]
I believe JUCE Jack support exists only on linux to your second question.

**Comment by mkruselj** [comment]
Well, I got access to Samplitude X4 and tried the current Surge XT nightly in it and after being thoroughly confused in the way Samplitude operates (not unexpected), everything worked just fine - I didn't have to transpose Surge because when creating a new project I made sure that project sample rate matches my audio interface's sample rate. Recording MIDI and wiggling parameters on the GUI recorded host automation just fine and everything played back exactly as I wiggled.

I would say there is no bug in Surge here. Closing the issue!

**Comment by tegedo** [comment]
Thanks for checking, I am using Samplitude X3; obviously X4's updates fixed issues with VST3. Samplitude was known for having problems with VST3.

**Comment by mkruselj** [comment]
Right. I see they're on what, X7 now?

So I hope at some point you will upgrade. Or switch to a more solid DAW 🙂

**Comment by tegedo** [comment]
I am using mostly MOTU's Digital Performer :-)
