### ISSUE TITLE
String oscillator tuning and filters 

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#5992]
Deform mode let’s you choose and calibrate different filter models per convo with jpr mar 24 discord in using surge channel

**Comment by baconpaul** [comment]
OK so the problem with detuning occurs when the LP cutoff is < playing frequency (or HP cutoff > playing frequency) basically surpassing the fundamental. I think the solution is to pitch adjust based on that cutoff relative to the played pitch empirically. Need some noodling. Can definitely do with deform modes

Oh also changing the resonance of the biquad to higher values - especially up to 0.99 - is very interesting

**Comment by mkruselj** [comment]
To be honest, I'm actually a fan of this detuning because it _is_ kinda realistic, when you slacken the string it does go down in pitch 🙂 But I suppose it might also be useful to have an option not to do this - I suppose then Stiffness as the name of the parameter would make more sense, since it would then pertain solely to the timbre of the string (depending on the "stiffness" of the "virtual material" used for it) rather than _also_ affecting the tuning (as if you were tuning a drum skin or something).
