### ISSUE TITLE
Surge Osc update for VCV

### ISSUE THREAD

**Issue by XtremeSounds** [surge-synthesizer/surge#6010]
Hi any way we can get the Surge Osc for VCV Rack  updated with everything in Surge VST?  Just take the whole chunk from the vst and make it for VCV?

**Comment by baconpaul** [comment]
I started this port and ran into trouble. In the surge rack repo there’s an open Pr which works on mac linking rack to the xt codebase rather than 1.7 but it crashes the compiler n windows and doesn’t build on linux. If a dev wanted to help clean that up they would be welcome, then adding the other Osc types is pretty trivial.  But thst infrastructure work has to happen first.

https://github.com/surge-synthesizer/surge-rack/pull/314

Let me close this but happy to discuss over in the rack repo if you want to help!
