### ISSUE TITLE
Features for more advanced a Portamento

### ISSUE THREAD

**Issue by Lo-lo78** [surge-synthesizer/surge#6519]
**Is your feature request related to a problem? Please describe!**

I don't know if it's a dublicate but I think a synth portamento can have more functionality:
auto e legato.
Auto is like what Surge has. Legato activates portamento only when notes are tied.
So if the notes are not related, there is no portamento.
Another feature is the ability to do it exponentially and linearly.
Sorry but I'm very fond of synths!

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by mkruselj** [comment]
Please read the manual in more depth. Surge already does this in "FP" (fingered portamento) play modes.

**Comment by Lo-lo78** [comment]
Excuse me, too much enthusiasm.
I've only recently been using Surge.

**Comment by mkruselj** [comment]
All good, enthusiasm is nice. But I would suggest first exploring Surge in depth and instead of opening an issue, maybe ask a question in #using-surge channel on our Discord? Things that you want to do might already be possible in some way.

**Comment by Lo-lo78** [comment]
@mkruselj 
Scusami ma la funzione che ti descrivevo non c'è.
Ho letto il manuale. Ho provato con il menù contestuale ma non esiste nulla del genere.
Ti descrivevo un portamento che con le note non legate il portamento non ha effetto. Solo con il legato.
Non c'è assolutamente questa funzionalità.

**Comment by baconpaul** [comment]
What does “tied” mean?  You mean like in a mono mode if there is a gap where no note is playing the portamento resets? Or no voice?

(The exponential and so on are there)

**Comment by Andreya-Autumn** [comment]
@Lo-lo78 The Portamento option you're looking for does exist (if I'm understanding you right). It's just not in the portamento context menu where it should be, but in the voice mode. 
Where you select between Poly and Mono modes, you also have the option of Mono, Mono Single Trigger (meaning envelopes don't retrigger for overlapping notes), Mono Fingered Portamento (meaning portamento only happens with overlapping notes, this is what you're looking for), and lastly Mono Single Trigger & Fingered Portamento. The last two of those options should do what you're looking for.

There's also an option in the context menu of the play mode which makes envelopes continue from their current level instead of resetting from 0 when notes overlap in Mono mode. And I just realized this option actually breaks fingered portamento for long release times. If that happens to be the mode you had dialed in, that'll be why you're not getting the results you want. I'll make a separate issue for that though.

**Comment by mkruselj** [comment]
> @mkruselj I'm sorry but the function I was describing is not there. I have read the manual. I have tried with the context menu but there is no such thing. I was describing a portamento that with unbound notes portamento has no effect. Only with the legate. There is absolutely no such feature.

Yes there is, and as I said (and Andreya too) it's the Mono FP and Mono ST+FP play modes. That's what you want - already there.

**Comment by Andreya-Autumn** [comment]
Yes indeed! 

@Lo-lo78 is certainly not alone in the struggle with how Surge describes these features. I found it super confusing at first too. TBH I think these functions can be confusing in many synths. And Surge makes it more confusing by using unique terminology + grouping options into menus weirdly. All will be improved in Surge XT2. :)

**Comment by mkruselj** [comment]
Single trigger and fingered portamento aren't really unique terminology, just the merger of those features into separate play modes is idiosyncratic.

**Comment by baconpaul** [comment]
Yeah expanding 2 switches (st, fp) into four linear modes is a wierd ui decision for sure. And thanks for the new mode bug catch!

**Comment by Lo-lo78** [comment]
@Andreya-Autumn 
Hello,
yes, with the:
Mono (fingered portamento)
It works exactly as I thought it would. Thank you!
I think it is better that I bring issues on accessibility.
(rofl)
Surge is very powerful and often the features are there. A little sparse but wonderfulSurge.
But the arpeggiator is too important!
🙂
