### ISSUE TITLE
Undo doesn't track waveform selection

### ISSUE THREAD

**Issue by treelimbjim** [surge-synthesizer/surge#6581]
Waveform selection isn't tracked by Undo/

**Surge XT Version**
Version: Surge XT 1.0.1.60228e8
Build: 2022-01-31 @ 16:53:52 on 'Mac-1643647381380.local/pipeline' with 'AppleClang-12.0.0.12000032' using JUCE 6.1.2
System: macOS 64-bit AU on Apple M1
Host: Apple Logic @ 96.0 kHz

* Version: Logic Pro 10.7.4 in M1 native mode
* Plugin Type: AU
* Bitness: 64-bit

**Reproduction Steps:**
1. Loaded Bass IV preset
2. Poked around to adjust envelope
3. Got curious about different waveforms. Tried out a few.
4. Hit Undo in LP wrapper. Began unstacking envelope slider positions while waveform stayed in last selection.

**Expected Behavior:**
Please don't tell me to RTFM; that its an expected behavior. 

**Computer Information (please complete the following!):**
 - OS: macOS 12.5.1
 - Host: Logic Pro 
 - Version: 10.7.4 in M1 Native Mode

**Additional Information:**

**Comment by baconpaul** [comment]
Hi

So Logic Pro can only undo parameter changes, and wavetables aren't parameter exposed at the edge. Similarly the LP undo can't undo anything like modulation depths, mseg snap points, formulae so on. This is why many plugins end up having to implement their own internal undo mechanism (especially since Logic is one of the *better* daws in this regard).

But In Surge XT 1.1 we implemented that mechanism, and when I use it, wavetables undo correctly using it.

There's practically no way to express something like a wavetable as a stable AU parameter; the range and value is not stable over sessions. But if you upgrade to 1.1 you will be able to undo all features of the synth whether they are exposed as parameters or not.

So while I guess we are, to your delight, not inviting you to RTFM, we are inviting you to RTFCLAU (read the fine change log and upgrade) so you can get this feature.

Thanks!

**Comment by baconpaul** [comment]
No problem! Hope you enjoy making music with surge, and if there is any missing undo in 1.1.1 its a real bug so please let us know. We think we got it all but it is tricky.
