### ISSUE TITLE
Waveshaper tearout scaling is borked

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6635]
It's fine as long as it stays inside, but torn out it looks like this: 

<img width="502" alt="Waveshaper" src="https://user-images.githubusercontent.com/105538426/192945341-5c1b41e6-cd3d-407f-9c37-0a84e2020d5c.png">

**Comment by baconpaul** [comment]
oh that's the annoying scale-on-resize thing that tarots need. I know the fix. easy to do for 1.1.2. thanks!

**Comment by baconpaul** [comment]
The reason for this is that the window when torn out doesn't quite inherit the parent transform

The fix for this is in the `::resized` method to compensate the width and height.

You can see `FilterAnalysis::resized` does

```cpp
void FilterAnalysis::resized()
{
    auto t = getTransform().inverted();
    auto h = getHeight();
    auto w = getWidth();
    t.transformPoint(w, h);

    f1Button->setBounds(2, 2, 40, 15);
    f2Button->setBounds(w - 42, 2, 40, 15);

    catchUpStore = evaluator->outboundUpdates - 1; // because we need to rebuild the path
}
```

whereas `WaveShaperAnalysis::resized` does

```cpp
void WaveShaperAnalysis::resized() {}
```

so basically take that transform of w and h and use it in the resized method is the answer. Make WaveShaper look like Filter.

**Comment by baconpaul** [comment]
Oh the other trick is in the Filter paint method we don't use `getLocalBounds` but we use a transformed local bounds

So look in `FilterAnalysis::paint` and you see

```
  auto lb = getLocalBounds().transformedBy(getTransform().inverted());
    auto dRect = lb.withTrimmedTop(15).reduced(4);
    auto width = dRect.getWidth();
    auto height = dRect.getHeight();
    
```

will have to do same in waveshaper paint (and that's probably the real fix since waveshaper doesn't currently have any subcomponents to resize)
