### ISSUE TITLE
answer issue

### ISSUE THREAD

**Issue by tranzedude** [surge-synthesizer/surge#6718]
hi

can youi please answer this unresolved CLOSED issue?

https://github.com/surge-synthesizer/surge/issues/6712

**Comment by Andreya-Autumn** [comment]
Hello! I see no one answered properly in the other issue, sorry about that. There's been a lot going on. 

In order to keep the patch library somewhat manageable, we've asked that anyone who wants to contribute to it be willing to submit at least ≈25 patches. That's the minimum effort required to have your patches shipped with the Surge XT install. Even with that being the case, there's *many* patches in there, as you can see. And including single patches by users not only risks blowing that up even further, it would also be lots of extra work for the team.

So no, on its own that supersaw preset won't be shipped with the next release. But if you'd like to make a whole set of patches, we'd be happy to review it! 
If you do go down that route, try to make it so each patch has all the macros assigned. That's going to be a requirement for all patches to ship with the future Surge XT2 release, so it's useful to move in that direction already. ;)

If you have more questions, I recommend joining the Surge Discord channel. That's a better forum for discussion than Github issues.

Thanks!
