### ISSUE TITLE
XY cutoff/res control in filter analysis pane

### ISSUE THREAD

**Issue by PopeKehoeIII** [surge-synthesizer/surge#6747]
as discussed on discord:

Would be in the words of baconpaul a "cute idea" to allow clicking on the filter analysis window to control cutoff on the X axis and resonance on the Y axis.

this lets you tweak both params simultaneously with a mouse, turns a previously display-only part of screen into a control surface, and would provide the pretty satisfying experience of really dragging around the cutoff point and resonance peak directly on the curve.

**Comment by baconpaul** [comment]
Basically 2 steps 

Add an o mouse dragged handler to the preview which shows the cutoff and res line with a ball under the mouse 

Use changes there to send the param changed event probably by just faking the call to surge gui editor value changed with the appropriate tag 

the tricky bit is you want bidirectional either slider or pane to edit both and right now we are one way 

good second issue lemme know if you need help

**Comment by mkruselj** [comment]
Another important thing - cutoff frequency to which Cutoff gets set should absolutely match the markings on the plot, so you will likely need to convert normalized 0...1 range (0 being 10 Hz and 1 being 24kHz) to how the Cutoff parameter is scaled in semitones (-60 to +70, 0 being MIDI note 69 or A440).

In fact, since our Cutoff slider goes to max 25087 Hz, it might be prudent to take this chance and modify L148 of FilterAnalysis.cpp to increase the maximum frequency of the plot to 25k.
