### ISSUE TITLE
Repeatable crash on typein.

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6755]
Open any typein field. 
Type something that starts with a letter.
Hit Enter.
Hard Crash. 
[Typein crash.txt](https://github.com/surge-synthesizer/surge/files/10271917/Typein.crash.txt)

**Comment by baconpaul** [comment]
Oooh ... @mkruselj did you change std::atof(s.c_str()) to std::stof?

If so they have different behaviors. namely `std::atof("Hello")` returns 0 and `std::stof(std::string("yellow"))` throws an exception which if not caught will crash the entire system.

I'm sorry i didn't catch this in review but it very much looks like the problem here.

The solution is either

1: use `std::atof(s.c_str())` or
2: use `auto v = 0.f; try { v = std::stof(s); } catch (const std::invalid_argument &) {}`

**Comment by mkruselj** [comment]
Thanks! That's exactly what happened, I used stof.

**Comment by baconpaul** [comment]
Great. I think solution 1 is the right one.
