### ISSUE TITLE
A new "wide" UI mode that presents all 3 oscillators onscreen simultaneously

### ISSUE THREAD

**Issue by Yzrsah** [surge-synthesizer/surge#6841]
**Is your feature request related to a problem? Please describe!**

My only problem with Surge is being able to only see a single oscillator onscreen at once. Surge is a fabulous synth but I find myself often avoiding using it because of slow access to oscillators. It's not that switching between oscillators is so slow, but I feel like I'm always worried about what's on the other oscillator page. I find it's a kinda "stressful" UI because of the oscillator switching. Surge would be so much cooler if you could relax and just look at one page. I think it's a design priority problem that we have access to 8 macro slots yet access to the oscillators is more limited.

**Describe the solution you'd like:**

It would be really great if there could be a new "wide" UI mode that presents all three oscillators onscreen simultaneously. This could help to make Surge more hands-on friendly. I realize there would be more onscreen but looking at three oscillators instead of 1 is not that difficult, and perhaps a new skin could color code background areas of the different synthesis sections.

**Comment by mkruselj** [comment]
This is not planned, sorry. Especially because in XT2 we are upgrading Surge to have 6 oscillators, not 3.

**Comment by Yzrsah** [comment]
@mkruselj This is a serious design problem. I feel that I'm going to have to fork the synth just to make a version that is not stressful to use. I will be very unhappy pressing keyboard shortcuts to switch between oscillators. The main problem is *seeing* the information. For example I'm making special oscillator chord stacks and I need to see all the pitch/detune values at once. It's just pure stressful being able to only see 1 of them, it makes me switch to a different synth where it's nice and easy and I can see everything.

If you're upgrading to 6 oscillators, how about showing 3 oscillators onscreen and Page 2 with OSC 4-5-6?

**Comment by baconpaul** [comment]
the code is all GPL so you are welcome to fork it! If you get that working I would love to see the code that did it and the design you come up with!

**Comment by mkruselj** [comment]
> If you're upgrading to 6 oscillators, how about showing 3 oscillators onscreen and Page 2 with OSC 4-5-6?

No. The design is already almost locked in, we're not changing it.

**Comment by Yzrsah** [comment]
@mkruselj Nothing was completed, the synth is still almost unusable because access to oscillator UI is so slow.

**Comment by mkruselj** [comment]
@Yzrsah Well, we can see even if you delete your post since GitHub is linked to our Discord server, so every new post that appears here, there. And if you delete it, it's not deleted on Discord. :)

So - not sure what you mean by "nothing was completed". If you meant the Surge XT 2.0 design update - that one is pretty much completed but it is not public yet. And when I say there's no room to show 3 oscillators at the same time - there is no room. You will see why once XT 2.0 is released sometime in 2024, hopefully.

Also, thousands upon thousands of Surge XT users have no problems using it (this also includes blind users), so you saying it's unusable is only subjective from your end, but the evidence of many happy users flies in face of such statement. And that's fine. Not every synth is for everyone, as I said.

**Comment by Yzrsah** [comment]
@mkruselj I deleted my original message because I decided to think longer about how to possibly convince you to make some kind of compromise. Being able to see all the oscillators is an important usability feature and maybe there is some way we can all get what we want...like an alternate layout or a second page that shows all 6 oscillators side by side.

**Comment by mkruselj** [comment]
No alternate layouts are planned for XT2. When you see it in 2024 you will understand why.
