### ISSUE TITLE
LFO display doesn't update when automating LFO controls

### ISSUE THREAD

**Issue by VincyZed** [surge-synthesizer/surge#6849]
The LFO display doesn't update when automating any or multiple LFO controls.

Switching to another LFO and switching back forces it to repaint and it updates to the current state, but still stays static. Moving the sliders manually though updates fine of course.

Paul: "Bet MIDI CC does the same"

**Comment by mkruselj** [comment]
For LFO, I can see this:

![image](https://user-images.githubusercontent.com/2393720/221133023-597cf137-19fb-4ebc-8a3f-3a27be59f337.png)

So there's no attempts to repaint at all when this method is called (and it's called in SGE L927 and L1009 ).

For osc display the similarly named `repaintIfIdIsInRange` actually does something, but apparently doesn't work when CC is sent for whatever reason. And it should be happening, since this is called in `idle()`...
