### ISSUE TITLE
Weird alias when modulating mixer at Block size 8

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6891]
Build Surge at Block_Size=8, 
Make osc1 a Sine osc (makes it easy to hear the issue)
Attach an LFO to osc1 mixer slider
Play a bass note and bring the LFO rate up.
You'll hear an alias-like ringing that gets louder as LFO rate increases.

Curiously, the frequency of the ringing is constant no matter what note you play, and no matter what the LFO rate is; only its amplitude changes. It seems rooted at around 6k.

And also curiously, if you oversample this block size-8 Surge, the frequency changes as expected (goes to ≈12k at 2x OS etc), but if you use the default block size 32, the problem dissappears from consequential ranges. Introducing some totally overkill treble boost CPU, it does seem like a similar ringing might actually be present also at BS=32, but it's much much quieter. I would've never found it if I wasn't trying to. 

Dropping this in XT2 for now.

**Comment by baconpaul** [comment]
I am almost 100% sure this bug is at line 13 of `src/common/dsp/vembertech/lipol.cpp`

that `setBlockSize(64)` should be replaced with a `setBlockSize(BLOCK_SIZE_OS)` 

That requires a `#include "globals.h"` at the top

basically what this does is smooth oscillator changes over the block; but with the block set at 64 vs the oversample of 6 you get a 1/4 height saw and a block size square; that block size square will have frequency 48000 / 4 (error) / 2 (oversampling) = 6k

If you want to try this locally and confirm then perhaps we can get it merged.

**Comment by baconpaul** [comment]
Oh and tbis was bugging me the error is 4 so the pulses happen every 48000/4 = 12k samples but since you need two cycles to make a square the sound sounds as if it is at 6k; the second 2 isn’t oversampling it is just a square wave requires two pulses per cycle not one

**Comment by baconpaul** [comment]
Don’t close it until we merge the fix!!!

**Comment by Andreya-Autumn** [comment]
No stress of course. And thanks for the fix!

**Comment by baconpaul** [comment]
Oh you sent in a pr I see! Merged and closing
