### ISSUE TITLE
An audio in effect

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#6901]
Getting audio in the fx chain is pretty easy - you can see how the vocoder does it - but chatting on discord realized that a utility audio in effect you could put in the fx bank with a mix would be useful

so I guess an fx unit with 3 controls

- channel (l,r,stereo,a(on non-a inserts only)
- Audio level db
- Upstream level db

you get the idea - and make sure it doesn’t show up in the fx plugin

**Comment by Alexander-Zyurkalov** [comment]
Looking

**Comment by Alexander-Zyurkalov** [comment]
@baconpaul, Why audio level and upstream are in DB, why aren't they gains?

**Comment by Alexander-Zyurkalov** [comment]
@baconpaul, what is "a" in the list of possible values for channel?

**Comment by mkruselj** [comment]
Scene A.

**Comment by Andreya-Autumn** [comment]
> 

About the send question. This is supposed to be able to receive audio from the other scene right? If it's in the a send slot, that's a bit redundant, since any transparent effect can fill the same function.

Maybe rather than disallowing it from loading in a certain chain, it could be made aware of what type of chain it's in. Then it could dynamically receive audio from the other scene, whether it's loaded/moved into A or B chain. And the scene input could be disabled entirely when it's in Send or Master chains. How's that?

**Comment by Andreya-Autumn** [comment]
Wait, would it even feedback? For the audio in oscillator, we tap the opposite scene pre-fx. If we do the same here, bringing up same scene audio would just... add same scene audio. Which would be present on what Paul called the "Upstream level dB" slider anyway.

If the host allows feedback, you could do it of course. And then there would be a case for the audio in fx on the Send chain actually. Route Scene A and/or B outputs to an external FX chain, and bring that back into Surge via a send FX slot, to be mixed into the master FX chain. Niche, yes. But you know, sometimes we do niche stuff. ;)

And yeah, you could do other feedback shenanigans with such a setup also. But you still should never need specific A and B sliders. "Upstream", "External" and "Other Scene" (names TBD) should get you everything you need always right? 

Either way, I guess dB sliders are better than a mix control, since we have a tendency to end up with 12dB less than unity here and there. Like in Audio In osc.

**Comment by Alexander-Zyurkalov** [comment]
I meant to show another scene option in the menu of choosing channels if it is an insert slot, or I mean to show nothing but stereo, left and right, but no scene at all if it is a send or a global effect slot.

**Comment by mkruselj** [comment]
I would suggest using the already established parameterization from Audio In oscillator, or something very similar to it. So I guess our parameter set would be:

AUDIO IN (section label)
Channel
Volume

SCENE A (section label)
Channel
Volume

SCENE B (section label)
Channel
Volume

OUTPUT (section label)
Width
Mix

**Comment by Alexander-Zyurkalov** [comment]
For the fx in insert-a chain: 
![image](https://user-images.githubusercontent.com/31346594/233432150-39006b04-adc7-46a8-b624-7161eb86e6ce.png)

For the fx in insert-b chain:
![image](https://user-images.githubusercontent.com/31346594/233432273-5556460c-0300-49ba-b422-297b538fb0f0.png)

For the fx in send chain:
![image](https://user-images.githubusercontent.com/31346594/233432379-004f1554-fa03-47fe-b229-5e4edf0509e7.png)

For the fx in global chain:
![image](https://user-images.githubusercontent.com/31346594/233432459-117ed4af-4481-4976-8fec-3eaeb8da2ab8.png)

**Comment by Alexander-Zyurkalov** [comment]
@mkruselj , something like that?
![image](https://user-images.githubusercontent.com/31346594/233449013-1d52be1c-4f9c-416b-8243-b22b6e51bc49.png)

**Comment by mkruselj** [comment]
Without the menu would be better, I think. It's important to be able to blend between left-right channels (see Audio In oscillator), especially because this can then also be modulated.

**Comment by mkruselj** [comment]
So looking at this the final parameter set should be IMO:

AUDIO IN
Channel (-100% is left only, 0% is left+right, 100% is right only)
Pan
Level

UPSTREAM (should find a better name possibly, maybe EFFECT IN?)
Channel
Pan
Level

SCENE A / SCENE B (only shows SCENE A if loaded in scene B, and vice versa)
Channel
Pan
Level

OUTPUT
Width
Mix

**Comment by Alexander-Zyurkalov** [comment]
@mkruselj This what I made. Correct me again if I understood wrong.
Here I show Scene B Input because the effect in A-chain:
![image](https://user-images.githubusercontent.com/31346594/233712796-c6aa9cf6-c131-4412-94d5-79366046ed82.png)

Here I show Scene A Input because the effect in B-chain:
![image](https://user-images.githubusercontent.com/31346594/233712597-c299c9f2-4979-4b6b-9d3e-9b6cfc6e0561.png)

No scene inputs in send and global chains:
![image](https://user-images.githubusercontent.com/31346594/233712936-be1260fe-1701-470d-8a6a-3392a8fb32fb.png)

**Comment by mkruselj** [comment]
That looks pretty great! Three comments:

1. Channel slider should be bipolar. Use `ct_percent_bipolar_stereo` for this.
2. The Output section should always retain its position even if we don't show Scene A/B section - always on the bottom.
3. Not a huge fan of "Input Blender" name. I'd just call it Audio In, with IN shorthand for the FX grid.


Thanks!

**Comment by Alexander-Zyurkalov** [comment]
@mkruselj , something like that?
![image](https://user-images.githubusercontent.com/31346594/233857207-7b356417-0edd-4ad8-9a9d-62dfb8035cff.png)
![image](https://user-images.githubusercontent.com/31346594/233857308-2d84bf62-b69e-4142-b56f-60981f3c6d93.png)
![image](https://user-images.githubusercontent.com/31346594/233857337-7d99645e-b306-4b96-a086-3a94ac366fee.png)

**Comment by mkruselj** [comment]
Yes, great!

You have a typo there in the menu "Audion Input", also we order effects alphabetically within each section, so Audio In should come right after Airwindows. That's it - PR it!

**Comment by Alexander-Zyurkalov** [comment]
I have almost finished the effect, there are only tests left.

**Comment by Alexander-Zyurkalov** [comment]
The tests are finished. The only thing left is to remove the effect from Surge-FX
