### ISSUE TITLE
the Time Scaling slider on the Oscilloscope is active when opened

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#6927]
happens for all skins

![image](https://user-images.githubusercontent.com/41337033/231269539-09304666-f524-4b0a-a00b-b143ceab80ec.png)
![image](https://user-images.githubusercontent.com/41337033/231269571-3605bdcf-95dc-4e68-b091-a0f5d4c64613.png)

it dismisses only after the slider has been budged or focus changed (for example if any item is pressed/moused down), then it paints mouse overs and gestures as it should

**Comment by mx** [comment]
For some reason, this slider is grabbing the keyboard focus when the window launches. Trying to figure out why...

**Comment by mx** [comment]
The problem stems from this line here: https://github.com/surge-synthesizer/surge/blob/dcda21748f2c1aa00e62f3b802e85724b67214b1/src/surge-xt/gui/SurgeGUIEditorOverlays.cpp#L513

When an overlay is opened, Surge gives it the keyboard focus. This likely ends up giving the keyboard focus to the first child in the overlay that can actually receive it, which in this case is the time scaling slider. Assuming we don't want this behavior, we need to find a way to give away this focus after it receives it (which is annoying, because all the code I've tried so far in the oscilloscope runs before the focus is granted).
