### ISSUE TITLE
MIDI learn: needs better visual feedback

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#693]
When you right-click a slider and go Learn controller, there is no lingering visual feedback to remind you what you're doing - which slider is being MIDI learned, or that you are in MIDI learn mode at all.

I would suggest for the parameter being MIDI learned to either flash on/off with a glow of some sort, or just permanently "light up" somehow, so that we know something is happening there.

**Comment by MachinaeWolf** [comment]
I right click midi learn and never see where it lists the control value. Not sure if that's because I'm using renoise or if there's a bug with surge on linux.

**Comment by baconpaul** [comment]
If you RMB the control after you learn it should show it. Does it not?

**Comment by MachinaeWolf** [comment]
It never does show me, all it shows are the regular options and abort midi learn.

**Comment by baconpaul** [comment]
Did you wiggle a controller to send a midi message? So “RMB/Midi learn” (move a slider on your keyboard) “RMB/See the controller mapping”

If you did that, can you check if your DAW is suppressing midi CC somehow? If the CC get to surge it will learn them.

**Comment by MachinaeWolf** [comment]
Well unfortunately I don't have a midi controller yet but if you know the controller numbers you can still control them on renoise with the instrument automation or midi instrument control meta device.

**Comment by baconpaul** [comment]
Right. So then you need to make sure renoise sends the controller on channel 0 to surge from your automation while learn is active. If you are running recording you see the midi events?

But if that’s what you are doing, you can also just automate all the learnable parameters directly as VST parameters. The MIDI Learn is really intended for physical controllers not DAW control. (Although it should work if the message gets to surge)

**Comment by MachinaeWolf** [comment]
Oh ok, yeah I see the instrument automation meta device is picking up the parameters. I've seen that most plugins that I have you have to try midi learn as it doesn't pick them up right purely by the instrument automation meta device. I was a bit confused because a couple plugins I have when you use midi learn it lists them in the right click menu after a bit.

**Comment by baconpaul** [comment]
In surge you can assign the 8 control modulators to any CC you want (default is 40-48 or 41-49 - I forget) and they dump the CC into the modulation matrix. You can direct learn a param if you want too, but it’s not saved in patch. But yeah the VST properly exposes all the DAW modulatable parameters to the DAW so that’s definitely the way to go.

I suppose we could add a “learn forced to controller” menu item in the future. But seems your immediate problem is solved with DAW automation.

best

**Comment by mkruselj** [comment]
Path to making this one happen:

1. In the menu where you start MIDI learn, snap the control->getViewSize() into a CRect which is a member of SurgeGUIEditor.
2. Then in (some component to be determined) which is an overlay component, draw that rectangle in red (add skin color too while at it) if `synth->learn_param` is set in `idle()`. Basically add something like the info window which draws MIDI learn rectangle based on that CRect member instead.
3. ????
4. Profit!

**Comment by baconpaul** [comment]
OK so I implemented exactly that approach. You can see it on branch `baconpaul/19-midi-learn-overlay-693`

The problem is that painting the bounds of the control 'looks' unnatural. I just used an alpha 100/255 red rectangle on the bounds of the learned control:

<img width="427" alt="Screen Shot 2021-01-24 at 9 34 28 PM" src="https://user-images.githubusercontent.com/13387561/105654713-94370c00-5e8c-11eb-9b5d-3dbb48cbb594.png">
<img width="164" alt="Screen Shot 2021-01-24 at 9 37 42 PM" src="https://user-images.githubusercontent.com/13387561/105654721-9731fc80-5e8c-11eb-9148-9a04464de5c5.png">

now that branch has some bugs to work out (like if you switch scenes the thing stays up etc....) but I didn't push on them since I am actually not sure what visual we want to indicate 'being learned'.

It's easy to show something.

I think maybe we want the slider to have trays for learn mode. But that's a lot of assets.

So the hard part here isn't the code. The code was easy. It's the 'what should the code show on screen'.

Will leave that branch around tho.

**Comment by mkruselj** [comment]
Maybe we could just have a skin color that changes the text color below the slider to something else?

**Comment by baconpaul** [comment]
Yeah good idea and same code just draw a bmp rather than a rect
