### ISSUE TITLE
Latching scene B plays a voice on Scene A

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6963]
Scene A has a sine osc and is monophonic
Scene B has an audio in osc from Scene A
Latching scene B should be silent, but here, it latches both scenes for some reason.

**Comment by Andreya-Autumn** [comment]
Simpler repro: 
Load a fresh Surge.
Set it to Dual scene mode.
In one of the scenes, turn latch on and off again.

If I latch scene A, the voice counter reads 2. Turning latch off again it does down to 1, and indeed it still makes sound. Each time I turn latch on/off, another extra voice lingers. Switching off dual doesn't end them, but switching to scene B and turning latch on/off there does. 

If I latch scene B, the behavior is the same, except it doesn't stack extra voices. Each time you latch on it goes to 2, then back to 1. Switching off dual does stop them from sounding.

**Comment by baconpaul** [comment]
tagging into 1.3

i bet the latch-end-voice-reaper isn't properly scene aware

**Comment by Andreya-Autumn** [comment]
An afternoon of casually building Surge from different commits I think I've found it. It appears at #6606, and only happens with the added MIDI channel-to-Scene option *not* engaged. I guess something about the scene channel mask code is a bit borky...

**Comment by baconpaul** [comment]
My guess is this state https://github.com/surge-synthesizer/surge/blob/3c4c9fc3b4ea8ea8ce9ad96a3d01d110ad169df9/src/common/SurgeSynthesizer.cpp#L4023 is getting set improperly in that case (that is play a or b is wrong) and I would start with a print there

**Comment by Andreya-Autumn** [comment]
I tried looking at it, but I'm in a bit over my head as you might expect. 😅 I messed around with XCode breakpoints a little, and I think you're right PlayB stays true in some cases where it shouldn't, but discerning why is where I'm lost. Wish I could be of more help. 🙃

**Comment by baconpaul** [comment]
We have confirmed the diff that breaks it and the line that’s wrong. That’s 90% of the fix. I’m sure this one will now be easy to do the last 10%. Awesome bug hunting!

**Comment by baconpaul** [comment]
Oh also do you know about git bisect?

**Comment by Andreya-Autumn** [comment]
No! Lemme guess, it helps find a breaking commit? I should read up on that probably. :)

**Comment by baconpaul** [comment]
Right. The problem is entirely with the ch23 turn off thing. That basically breaks latch.

It breaks latch for an annoying reason though. 

https://github.com/surge-synthesizer/surge/blob/8d791a18b7153b249ab819e2aa805f1451ce50c0/src/common/SurgeSynthesizer.cpp#L4094

there's the code which plays in latch mode. As you can see it uses 'channel 1' to mean scene A and 'channel 2' to mean scene b.

So it turns out this is *also* broken in 1.2.3 in MPE mode, where latch does the exact same thing.

The answer here is to add an argument to playNote for 'ignore scene' which ands onto the channel mask then pass it form that latch initiation point.

**Comment by baconpaul** [comment]
Ahh great and i can grab it in a regtest now. Will have this soon.

**Comment by baconpaul** [comment]
yup got it.
