### ISSUE TITLE
] key and new vkb

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7069]
With the new vkb we bind `]` to extended keyboard but that key is also accessible key for menu open so right now any action with accessible on that opens a menu also plays a key. So

1. why? Why doesn’t the event get eaten and why does it go to the vkb. Is it keypress vs scan keybed
2. If we can’t answer that de extend the keyboard if the key edits are on and
3. If we can’t do a that make a narrow vkb binding which activates when key edits are on 

or some such. But gotta sort it out!

**Comment by mkruselj** [comment]
It only happens when vkb is visible and focused. I don't think it's a big deal since if you have vkb focused you want to play It, and expanding the available number of notes is not a bad thing.

I was also thinking we could provide two row vkb layouts perhaps, although unsure if ] would end up being used again even in that scenario (don't have a US Qwerty layout in front of me atm).

**Comment by baconpaul** [comment]
Well except it does t! That’s bscross bug report. It happens when he presses [ on a slider with accesibility keybindings on

**Comment by baconpaul** [comment]
oh this is a massive pain in the ass to fix

we interact with the vkb in two places

1) where we send key events and
2) in the scan method

but in the scan method we don't get a juce::KeyPress event just a keyboard state changed

so we can't ask if the key state change is an accessible key

I think we really just have to revert right bracket being a virtual keyboard playing note.

**Comment by baconpaul** [comment]
have done it a far less satisfactory way which works.

**Comment by baconpaul** [comment]
Confirmed fixed
