### ISSUE TITLE
Audio/MIDI Settings window doesn't show on Ubuntu 23.04

### ISSUE THREAD

**Issue by wupeka** [surge-synthesizer/surge#7071]
**Bug Description:**
Unable to open Audio/MIDI Settings window in standalone app (JUCE issue?)

**Surge XT Version**
1.0.0 -> 1.2.3

* Version:
Standalone

**Reproduction Steps:**
1. Click "Options"
2. Click "Audio/MIDI Settings..."
3. The Settings window doesn't show up.

**Expected Behavior:**
Settings window shows up

**Computer Information (please complete the following!):**
 - OS: Ubuntu 23.04
 - Host: Standalone

**Additional Information:**
The setting window shows up when the app is launched in XNest without any WM.

**Comment by baconpaul** [comment]
A couple of questions if you don't mind

1. Do any of the surge tear out window gestures work (like open the MSEG Editor and make it an independent window with the green icon)
2. Are you able to run the code at head? There we use JUCE 7 and I wonder if this problem is remediated
3. The it works with a different WM makes me think this is indeed JUCE and the WM interacting. Do other JUCE standalone (vital, dexed, odin) show the same?

I run 22 not 23 when I use linux and it works there so a bit of collaborative debugging is probably gonna be needed.

Thanks for the report and look forward to hearing more!

**Comment by wupeka** [comment]
1. MSEG editor as an independent window works
2. I checked with main and with main + JUCE from devel branch (needed some minor fixes in the code), still no cigar
3. I've checked dexed - the settings window either shows up for a split second and disappears, or it doesn't show up at all

**Comment by mkruselj** [comment]
So this seems to point to an issue between JUCE and Ubuntu 23 then.

**Comment by wupeka** [comment]
Created an issue there https://github.com/juce-framework/JUCE/issues/1242

**Comment by mkruselj** [comment]
Great!

If you don't mind we'd then close this issue here. If JUCE folks say it's not on their end, feel free to reopen it!
