### ISSUE TITLE
CSnapshotMenu gets Checkmarks (FX Preset and OSC type menus)

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge#726]
would be cool to show a checkmark when something is selected in fx preset folder world
<img width="361" alt="image" src="https://user-images.githubusercontent.com/4966687/53795567-edb18d00-3f3a-11e9-84b6-4fd59c3ac2c5.png">

**Comment by sense-amr** [comment]
yes because absense of display in the Insert Pull down of the effect.. for the preset you have chosen AND .. absense of a checkmark next to it when going back to check which youve selected..! .. oh ill just go get my notepad :)

**Comment by sense-amr** [comment]
yeah !

**Comment by baconpaul** [comment]
This and #705 are the same bit of code (CSnapshotLoader.cpp) so fix one and you fix both.

**Comment by esaruoho** [comment]
> This and #705 are the same bit of code (CSnapshotLoader.cpp) so fix one and you fix both.

i tried looking for `CSnapshotLoader.cpp` but can't find it in the repo.
i was, however, able to find `src/common/gui/CSnapshotMenu.cpp`.

**Comment by baconpaul** [comment]
Yeah that’s it

**Comment by baconpaul** [comment]
Populatesubmenu in there and populate builds the menu

**Comment by baconpaul** [comment]
Oh these are mildly and irritatingly tricky. I'll take care of them but they aren't as easy as I thought.

**Comment by baconpaul** [comment]
<img src="https://user-images.githubusercontent.com/13387561/53687509-56aec000-3d03-11e9-8945-d882d0c2bb4c.png">

**Comment by baconpaul** [comment]
So this is all one issue but it is a bit tricky since these two menus are different; they are populated at construction time not at popup time but they are the same class. So my plan of attack is move them to populate at popup time instead (the time taken should be trivial) so we can know our current state and add a check mark.

We also have to know our current state though which requires the callbacks updating the state on the object

So alas this one is a teensy bit tricky so I'm removing the "good first issue" tag.

**Comment by baconpaul** [comment]
Turns out this is actually a massive pain in the neck. I know it's out there but it is a lot of really annoying and tedious work to get right, I'm sorry!

**Comment by baconpaul** [comment]
This issue continues to be a huge PITA. Pushing out of 1.7.0

**Comment by mkruselj** [comment]
@baconpaul I assume #3111 is the path to solve this one more easily?

**Comment by baconpaul** [comment]
100%
