### ISSUE TITLE
FX Group Labels Accessible

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#7283]
Making the group titles accessible would probably be the right move then. It would also help in other areas. The distortion effect, for instance. The thing that makes it less confusing is that the drive and feedback separates the pre-clip from the clip stage.

**Comment by mkruselj** [comment]
From bscross: "If adding the groups means making the focusable, I'd probably change my recommendation to the concat just because adding more focusable elements will screw with people's muscle memory of where stuff is"

I also agree it's better to concatenate group label name with parameter name. See #1559.

**Comment by baconpaul** [comment]
7284 closed this but tagged the wrong issue
