### ISSUE TITLE
Modulating Sine Feedback through 0 causes clicks. 

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#7353]
Load Init Sine
Take an LFO, bring its rate up to like 10hz, and assign it to the sine feedback +/- 25% or so.
You get a bunch of discontinuity clicks. Which are not there if you move the feedback slider up to say +30 or so. 

Something borked seems to be happening there.

**Comment by baconpaul** [comment]
OK @Andreya-Autumn I see why this could happen although I couldn't quite make my 32-block-size version click just be a bit noisy, and was able to improve it.

There was a case where we evaluated the fact of FB being negative every block rather than every sample. (The feedback depth is d for fb > 0 and d*2 for fb < 0) so I moved it to per sample in #7439 (it was just moving one SIMD operation from outside the block to inside - no big deal). 

Once that's merged I would appreciate you testing again and seeing if it breaks. If not, sharing a patch which still makes an audible click for you would be appreciated.

**Comment by Andreya-Autumn** [comment]
Great, thanks! Will build and try. :)

**Comment by Andreya-Autumn** [comment]
Good news and not such good news! 
Good: the clicks are gone. 
Less good: So is the difference between positive and negative feedback. 😅

**Comment by baconpaul** [comment]
Ha hoops! Lemme look.

**Comment by baconpaul** [comment]
OK #7441 will fix that and will now put the abs in the right place and voice the modulation problem I think.

Will merge it tonight when CI finishes.

Sorry about that!

**Comment by Andreya-Autumn** [comment]
No worries at all! Going to bed now but will test tomorrow.

**Comment by Andreya-Autumn** [comment]
Good news only this time! Negative feedback is back and the clicks remain absent. :) Closing.

**Comment by baconpaul** [comment]
Wonderful. Great find.
