### ISSUE TITLE
Reaper preset library

### ISSUE THREAD

**Issue by jjYBdx4IL** [surge-synthesizer/surge#7356]
I have exported factory presets to Reaper preset library files. That allows simple import and MIDI program assignment. I can share the files and the export automation script if so desired.

**Comment by mkruselj** [comment]
Feel free to share the file on our Discord server in #surge-content-sharing channel. Considering this sort of thing is highly DAW specific, I don't think it belongs in our installer. I can also very easily become out of date because we add new patches often, this would then require an additional maintenance step, which we'd like to avoid.

Thanks though!
