### ISSUE TITLE
Add notification for Parameter valiue changes due to 'undo'

### ISSUE THREAD

**Issue by pkstone** [surge-synthesizer/surge#7476]
Please add a notification for Parameter value changes caused by 'undo', to be used for firing a 'paramChangeListener'.

**Comment by baconpaul** [comment]
So I'm not sure what the problem is here

begin param edit and end param edit are called when I do an undo at head.

Here's exactly what I did

Open surge standalone in the debugger
move pitch from 0 ->4
activate a breakpoint at `void SurgeSynthEditor::endParameterEdit(Parameter *p)`
press undo

and i hit the breakpoint

![Screenshot 2024-01-23 at 9 41 34 AM](https://github.com/surge-synthesizer/surge/assets/13387561/6b3fa2d5-81b3-4cf5-b0a1-911b922a3eb9)

that's the stack I see and if you look at SGE::setParamFromUndo you clearly see its calling begin and end edit

So: what's the problem you are seeing? I'm not sure what it is you are missing that needs a callback. I'm sure its something but I'm not sure what it is :)

**Comment by pkstone** [comment]
Mistake on my part. It now seems to be working fine.
