### ISSUE TITLE
https://surge-synthesizer.github.io/ DL, a bug?

### ISSUE THREAD

**Issue by StallmanSlave** [surge-synthesizer/surge#7525]
Tried DL the Windows release. Hit's 123-125MB then hits flat zero download speed. Fairly certain everything is fine on my end, must be sonething with the file or server or something. 
The download link on that site links here. 
https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.1/surge-xt-win64-1.3.1-setup.exe

**Comment by mkruselj** [comment]
We don't control downloads in any way and cannot do anything about it. Try to download again later, try a different browser, etc. Nothing else we can suggest.

**Comment by StallmanSlave** [comment]
I tried downloading on different network about 16 hours later and it happened to go through, same file, same browser, same OS. The network switched from Verizon cellphone hotspot to verizon jetpack. If everything is fine on your end and nothing changed it must be the cellphone hotspot. Warning to readers, your ISP may be screwing up the connection for unkown reasons.

**Comment by baconpaul** [comment]
Thanks!

"Our end" is microsoft azure underneath GitHub provided for free to open source projects. Microsoft generously provides, basically, free storage and free compute and free network to open source projects like ours! Which means we don't have the pain of debugging a server.

But since we don't run any servers, we can't see really what happened with your DL. I think the cell phone network glitching in the bigger download is likely. But MSFT does post their server status https://www.githubstatus.com there if you have a problem again too!

Thanks, glad the DL worked, and enjoy surge!
