### ISSUE TITLE
audio channel mixing behaves differently as CLAPi vs VST3i

### ISSUE THREAD

**Issue by jjYBdx4IL** [surge-synthesizer/surge#7584]
**Bug Description:**
I'm trying to use the CLAPi version of v1.3.1 as a vocoder under Win11/amd64 in Reaper 7.11. I noticed that the audio input gets mixed with the audio output. That does NOT happen when loading the plugin as VST3i. Is that a plugin or a Reaper issue?

**Surge XT Version**
1.3.1

* Version:
* Plugin Type: VST3i vs CLAPi
* Bitness: 64

**Computer Information (please complete the following!):**
 - OS: Win11/amd64
 - Host: Reaper
 - Version: 7.11

**Comment by baconpaul** [comment]
My guess is this is reaper clap implementation passing the input through to the output. Have you looked at the pin diagram?

getting reaper working with instrument sidechains in vst3 took a fix - wonder if same happened in their clap

https://youtu.be/OKR0x_dneYI?si=DzfQ4DV00VfQpHJj

Here’s how we worked around before reaper fixed the instrument side chain in vst3 - if same works here we can follow up with reaper devs.

thanks

**Comment by jjYBdx4IL** [comment]
Ah yeah, that way it works. I put the CLAPi version on master and set the master track to use channels 3/4 for output. Then I set up the plugin to use channels 1/2 as inputs and 3/4 as outputs.

**Comment by baconpaul** [comment]
Oh that means reaper ignores the is main flag on inputs just like it used to in vst3 or surge isn’t reporting them properly. Useful!

**Comment by Andreya-Autumn** [comment]
This is Reaper's behavior with Instrument plugins generally! I'm not completely sure, it's been a while since I checked, but I think it happens with AUi, VST3i, VSTi and CLAPi all - if you patch audio to an instruments input the output will be the sum of the in and out. Purportedly it's intentional (so you can stack multiple instances on one track and get a sum), but I find this behavior frustrating personally. 

The only solution I know is the one shown in that video, make sure the external audio isn't on the same channels as the output of the instrument.

**Comment by jjYBdx4IL** [comment]
it's not happening for VST3i, at least not any more

**Comment by baconpaul** [comment]
No that’s not quite right @Andreya-Autumn - the vst3 and clap api can indicate that there’s no main input and then instruments can get set up properly. This is a thing we fixed with reaper 5.75 or some such when a vst3 has only non main ins. The video above isn’t how it works in reaper 6 with vst3. 

my guess here is either surge clap doesnt advertise it’s input as not main or the reaper clap implementation doesn’t have the same fix as their vst3 implementation

**Comment by Andreya-Autumn** [comment]
Right, I stand corrected! The only other VST3i's with audio inputs that I have here are Pianoteq and VCV, and they both have this same problem, Surge XT is the only one that gets this right apparently. I've been using the CLAP lately so I didn't realize.

**Comment by mkruselj** [comment]
Actually haven't talked to either of them in a while... Remember Timo tried to contact them too regarding some other issue and they weren't exactly responsive. Weird folks.

**Comment by mkruselj** [comment]
Looks like Cockos will implement this after 7.12 release. Closing this issue then!
