### ISSUE TITLE
UI doesn't update when using wine

### ISSUE THREAD

**Issue by bauhaushousedog** [surge-synthesizer/surge#7636]
**Bug Description:**
UI doesn't update when ran using wine (version 9.6-1), the standalone doesn't play sound using the virtual keyboard for some reason, the vst does play sound on fl studio with wine though.

The standalone native linux version works perfectly.

**Surge XT Version**
1.3.makepkg.20a8e16ab, installed on pacman as the `extra/surge-xt` package

* Version:
* Plugin Type: the ones I tested where the VST3 and standalone
* Bitness: 64-bit as far as im aware

**Reproduction Steps:**
1. Open surgext (either the standalone over wine or on a daw like fl studio over wine)
2. click anything
3. UI does not update for itself
4. on a daw i could update the UI if i opened and closed the window

**Expected Behavior:**
UI updates

**Screenshots:**

https://github.com/surge-synthesizer/surge/assets/165673081/fa7363b9-c51d-4dce-9ae8-e7cde8bef7f3

(my screen recorder did not capture audio for some reason but the test beep is playing when clicked)

**Computer Information (please complete the following!):**
 - OS: Linux (endeavour os ((arch based distro))), 
 - Host: Standalone and Fl Studio (both under wine)
 - Version: [e.g. 2.4]

![image](https://github.com/surge-synthesizer/surge/assets/165673081/ca7d8e62-6104-434a-b00c-9beecd70e51b)

**Comment by baconpaul** [comment]
Hi.

We don't support running in the WINE environment, so no-one on the team here is going to look at this, but would be happy for members of the community who want to look to do so.

the standalone making sound is, my guess, that it is defaulting to wasapi or direct sound, and wine only support the other. Did you try the options screen?

The UI - no clue. JUCE is pretty standard GDI and we use JUCE 7.0.5.

**Comment by bauhaushousedog** [comment]
sure thanks for the response

**Comment by LazerVV** [comment]
Tried DXVK and vkd3d Proton, only makes Surge crash. Various options in FL studio don't show effect, such as detach window, make bridged, update when hidden, etc. and debugging stuff.

Surge seems to work perfectly in Wine, except for the UI which does not update, so it is unusable.

Buttons like "Zoom" and Menu work. 

Toggling the Window open/closed updates the UI, as well as setting "Zoom".

**Comment by baconpaul** [comment]
Hi.

We support a native linux version for linux users. We can't provide support for wine. 

Depending on your version, the UI is just built with JUCE 7 or JUCE 8. Nothing special. Perhaps look what it takes to get juce sis working in wine?

**Comment by LazerVV** [comment]
I am making a PR that does a simple wine-detection and then hack to update the UI with polls.

However JUCE 8 no longer really works with Wine, unless you switch the rendering Engine to 0 (not D2D), so I also added that in case Wine is detected.

Update: Got it to render once, but get "Expression: can't decrement value-initialized vector iterator" errors randomly. When I switched to more cautious approach, it was somehow back to being broken entirely. Not sure how much longer I will try this tomorrow. At least it doesn't compile from scratch now anymore each time after deleting and re-cloning repo and ChatGPT tweaks.

Unfortunately for most Linux users VST plugins can only be run with Wine (which works very well in general), just because their DAW is Windows-only and then all the good VSTs are also Windows-only. So you have no choice but to not use native Linux and a Windows environment instead. But virtualization creates too much delays and issues versus WINEASIO, and Linux DAW spawning Wine has even more issues than just delays. So you pretty much have to use Wine in the end for the whole DAW.

**Comment by mkruselj** [comment]
I would not claim that "most" Linux users are using virtualized Windows for their DAW. Doubt there are any actual metrics available, but we have a lot more pure Linux users using pure Linux apps (including DAWs) contacting us, rather than WINE users, so at least from our perspective this situation seems completely turned on its head.

**Comment by baconpaul** [comment]
@mkruselj since surge doesn't work with wine we certainly have a good idea on number of wine users we have. But I agree that the characterization of 'most' linux audio users use windows software in wine doesn't match my experience.

bitwig and reaper native and yabridge works well for our users who have an odd windows-only vst or two they have purchased though. Perhaps thats a configuration that would work here?

or if you want to run windows software, run windows! That also works well.

**Comment by baconpaul** [comment]
But if theres a PR to make it work happy to review and merge it of course. Appreciate the effort.

**Comment by mkruselj** [comment]
@baconpaul I think Surge worked fine with WINE (would you look at that rhyme) while we were on JUCE 7 or older.


But yes, for OP I would suggest checking out yabridge if WINE is crapping out.

**Comment by baconpaul** [comment]
Right it didn't work with vstgui; maybe it did with juce 7
but in that case, trying 1.3.4 rather than 1.4 would help
but also if juce 8 generally doesn't work with wine then the wine-for-windows-strategy is going to start failing pretty darn soon

https://github.com/surge-synthesizer/surge/issues/7981

we do have that option to turn of the software renderer. The problem is that the JCUE implementation of no software renderer is not complete (sub-windows and menus can skip it) with juce 8.0.x and you need some way to set that. and we need to code that

but adding an option to not software render like i did for six sines and setting it in the xml might help here?

**Comment by mkruselj** [comment]
I kinda feel we should default to software renderer, because then there is more guarantee that the plugin will show its UI, and then users could use an option to switch to another renderer.

This is common in many other plugins. It's a better UX than requiring people to chase and edit XML files.

**Comment by baconpaul** [comment]
Software renderer means old font rendering on windows. you would immediately ask me to revert it.

**Comment by LazerVV** [comment]
There is a discussion in Juce 8 to detect Wine like described and switch to software renderer. So detection in Surge would be superfluous.

But the issue is apparently more complicated, because if I understand it correctly native dxgi lacks features and it was suggested to switch to DXVK. However in my experience DXVK tends to crash a lot of VSTs (including Surge) and generally is more of a bad idea for DAWs.

So not sure if this can be fixed. My attempts didn't really yield usable results. Perhaps it is best to wait for Juce or Wine to fix it.

Kind of a pickle though because I prefer to use an older Wine version that has proven to be less bugged than recent Wine.

Good news though! In Wine 10.8 Surge 1.3.4 the UI is not frozen! But only if you set WINEDLLOVERRIDES="d3dcompiler_47=n;dxgi=n,b" and you DON'T use winetricks to install d3dcompiler_47.

The recent builds with Juice 8 on the other hand still crash.

So all the fuzz for nothing. Sorry.

**Comment by baconpaul** [comment]
Yeah the software renderer fix to be complete needs to be pretty invasive too since it needs to apply to sub windows including menus - it’s a bit ugly 

Surge at head probably still builds with juce 7 or could with a macro or two. And 134 is all juce 7. That may be a better approach if bitwig and yabridge for win vst and native isn’t an option 

From chatting to other audio devs I’m not sure wine support will ever be a high priority though. Folks shipping Linux will just say use Linux. Folks not shipping Linux also won’t be able to debug wine. Especially with juce 8 rolling out more broadly I do worry a bit about the reliability of windows except not windows over the next few years

**Comment by mkruselj** [comment]
> Software renderer means old font rendering on windows. you would immediately ask me to revert it.

Nah. This is also the case with other plugins. I would just change the setting on my end.

**Comment by LazerVV** [comment]
**Steps to fix UI not responding in Wine:**

* use WINEDLLOVERRIDES="d3dcompiler_47=n;dxgi=n,b"
* **don't** use winetricks to install d3dcompiler_47 / dxgi
* **don't** use DXVK
* use Wine 10.8 and Surge 1.3.4

Seems to work flawlessly!

**Comment by baconpaul** [comment]
Right so that's basically "JUCE 7" or "software renderer everywhere"

Maybe we should just do a parallel Juce 7 / Juce 8 build of surge at head like I do for air win consolidated and elfin. Then you could do those tricks and use the juce 7 version. I'll open an issue to make that part of the pipeline.

**Comment by baconpaul** [comment]
Tracking parallel build in https://github.com/surge-synthesizer/surge/issues/8045

**Comment by mkruselj** [comment]
Frankly I think the option with default to sw renderer is better than yet another build...

**Comment by LazerVV** [comment]
Don't do parallel build, 1.3.4 works! I figured out how: https://github.com/surge-synthesizer/surge/issues/7636#issuecomment-3015376240

Just wait for Juice 8 to fix their Wine issues, or Wine to fix it.

**Comment by LazerVV** [comment]
@baconpaul 

Did build latest git Surge with your code fixes for Juce 7 just now. Using my solution https://github.com/surge-synthesizer/surge/issues/7636#issuecomment-3015376240 , everything works perfectly in Wine just like before.

https://github.com/user-attachments/assets/e1b77ff4-a940-4c2c-83a6-c81fdc1e8923


Thanks!

**Comment by baconpaul** [comment]
Great!

There's also a binary staged in the nightly with a name like win-juce7-pluginsonly.zip or some such.

But good. this is a problem which seems solved.

Thanks for flagging it.

**Comment by bauhaushousedog** [comment]
hi! thank you all for taking interest in this issue!!, ill test the windows binary with my fl studio with wine later

**Comment by KayDox64** [comment]
> [@baconpaul](https://github.com/baconpaul)
> 
> Did build latest git Surge with your code fixes for Juce 7 just now. Using my solution [#7636 (comment)](https://github.com/surge-synthesizer/surge/issues/7636#issuecomment-3015376240) , everything works perfectly in Wine just like before.
> 2025-06-28_22-28-34.out2.mp4
> 
> Thanks!

So i did all of this and now the plug in wont even open, just gives me an error (the error is also blank)

<img width="607" height="137" alt="Image" src="https://github.com/user-attachments/assets/55f44cf6-a4c8-4dfa-93cc-b49532c6d8e6" />
