### ISSUE TITLE
Surge UI redesign concept

### ISSUE THREAD

**Issue by trynsta** [surge-synthesizer/surge#7661]
Hello. I made an UI redesign in Inkscape. Maybe you find it useful for future UI changes.
![surge_redesing_final](https://github.com/surge-synthesizer/surge/assets/131924349/322b9240-485c-43ca-9111-5de8c18de612)

**Comment by baconpaul** [comment]
Thank you for sharing!

we have a redesign we are kicking around and I’m glad to see it fixes many of the problems you also fixed - especially the signal path is laid out more clearly on the ui.


we are focused mostly on short circuit, our new sampler project, as our major lift this year but I’ll keep this issue open for us to consult when we revamp surge. Also happy to chat about ideas here or on discord!

**Comment by mkruselj** [comment]
Thanks for this, hope you had fun in figuring things out. Surge redesign has been on my desk for almost two years at this point, we've had a lot of good input and it's looking pretty great. You can get a glimpse of some small parts of this redesign [here](https://github.com/surge-synthesizer/surge/issues/4355#issuecomment-1512085654) but it's not yet been made fully public, since as Paul said we want to focus on Shortcircuit XT this year, instead of building up hype for a whole new major Surge release.
