### ISSUE TITLE
surge-xt-cli segmentation fault

### ISSUE THREAD

**Issue by botoxparty** [surge-synthesizer/surge#7737]
Hi,

I'm running surge-xt-cli on linux and everything seems to be working well, i can produce sounds, change patches via. OSC commands, etc. however i encounter segmentation faults very frequently (about after 30 seconds of use).

How would I go about debugging this issue? Any ideas?

It usually occurs when sending the OSC message `/mnote`

**Comment by baconpaul** [comment]
Well first things first make sure you are using the nightky - we have had a few fixes since the 1.3.2 which we are planning on rolling into a release 1.3.3 towards the end of the summer. 

But the way to debug which would be best would be to build the code in debug mode (with a cmake build type) and run it under debugger 

an alternate approach would be to make it so we can run your setup with the patch osc generator etc 

it’s interesting it is in osc mnote. Wonder if we have a thread issue in the in osc mode. That would be my first guess 

can you share your os and environment details a bit?

**Comment by botoxparty** [comment]
The environment is RPi 4, using the latest OS. Tried the nightly build.

I also discovered that this would happen any time i try to change the patch with `/patch/incr` or `/patch/decr`

I may move to the python bindings as it seems I may have a more responsive application that way, and more tightly integrated. Just need to figure out quite a lot of things about python.

Is the API documented anywhere for the surge instance in python?

**Comment by baconpaul** [comment]
Do you have patches installed? Wonder if we fail the no patch case

there’s a repo here https://github.com/surge-synthesizer/surge-python with examples and it has doc strings et.

**Comment by botoxparty** [comment]
I do have patches installed, the thing is i remember this working a when i first set it up in my project.

Unfortunately i've abandoned the OSC approach for now and am going to continue with Python as I think it will provide a tighter integration with my project. Will close for now.
