### ISSUE TITLE
FX parameter labels way too thin

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#779]
Windows 10 64-bit, VST2 or 3

Load any effect.

See the result:

![image](https://user-images.githubusercontent.com/2393720/54359014-02400480-4662-11e9-90f2-28e57e245ee2.png)

Effect labels for sections (upper left) are way too thin.

**Comment by baconpaul** [comment]
So we had the black font as Lato-SemiBold because windows looked a bit thin and that was too bold for the black, so we made Windows use Lato like everywhere else. But that gray font is now too thin sure.

So the fix here is

1. In installer_win/surge.iss and surge-x86.iss install both "Lato-Regular" and "Lato-SemiBold"
2. add a new global font "effectLabelFont" and on linux and mac set it to displayFont but on windows set it to lato-semibold in the runtime font loader
3. in src/common/gui/CEffectLabel.h change dc->setFont(displayFont) to be the right thing
4. Test - especially test that the font is installed on a machine by the installer and addressable

An alternate fix is change the color from gray to a darker color.

**Comment by itsmedavep** [comment]
Bleck. I see this on Mac in the osc display too!

<img width="147" alt="Screen Shot 2019-03-18 at 7 15 10 PM" src="https://user-images.githubusercontent.com/11078351/54571767-2e38ee00-49b2-11e9-946e-3b82dfd67453.png">

Gotta be in wavetable or window mode to see.

**Comment by baconpaul** [comment]
try setting the antialias mode before the font draws there, dave. I noticed the oscillator display doesn't set antialias. the VUMeter shows how to do it.

**Comment by baconpaul** [comment]
Oh also the oscillator display is weird. It paints to a backing buffer for that part of the display so there may be other vstgui gnarly bits in there. Before I left I actually got pretty far on the 'draw waveforms with lines' plan.

**Comment by baconpaul** [comment]
Huh so i thought this was a font problem but it isn't. For some reason that control was drawing with antialiasing off which means on windows the problem will be more pronounced.

I'm also going to change the color to black. The gray is too washed out. Fix forthcoming.
