### ISSUE TITLE
Delay on raspberry

### ISSUE THREAD

**Issue by grbfst** [surge-synthesizer/surge#7867]
Running Surge-XT-CLI on a Raspberry 4 and some patches have an echo way after I release a key compared to a Windows version of Surge.
I.e. when I use \patches_factory\Winds\Fake Ethno.fxp on the Raspberry I can hear its echo a good 4 seconds later, not so on a Windows machine. When I release a key on patches_factory\Pads\Assymetry.fxp I can hear it echoing 4 times.
 Is there some sort of algorithm that is slow on a Raspberry?

**Comment by baconpaul** [comment]
First of all, are you using the latest version of surge-xt-cli? There was a problem we fixed with tempo setting in the cli and the delay in Fake Ethno is tempo synced, and this fix fixed exactly that problem. If you are using a version earlier than 1.3.4 then this would indeed explain that. 

There are also things which are way slower on a raspberry pi. I mean it's 10-20x less compute power. But this really sounds like you are running a cli version without the tempo fix.

**Comment by baconpaul** [comment]
If you self build, you want to make sure you include https://github.com/surge-synthesizer/surge/blame/c5d87b91c71859c92f2ee259f28e20b34286c760/src/surge-xt/cli/cli-main.cpp#L172 that revision

**Comment by baconpaul** [comment]
Ahh that’s a year old and we moved the build once we got it working

here’s the nightky https://software.opensuse.org//download.html?project=home%3Asurge-synth-team&package=surge-xt-nightly

which has the fix in it

**Comment by grbfst** [comment]
Yay!, That fixed it. Couldn't compile so this is great!
