### ISSUE TITLE
discord link is broken

### ISSUE THREAD

**Issue by shih1** [surge-synthesizer/surge#7877]
hi i have some casual questions that I want to ask the surge team. specifically related to their build and distribution pipeline. 

I found it surprising that there are no juce macros in the root CMake txt file and the lack of any explicity AAX build commands in the cmake. 

i've used many of the files in this repo as references so I would like to contribute a bit as well, both to learn and to help. 

i tried to join the discord but the links seem to be broken

ty in advance.

**Comment by mkruselj** [comment]
Hmmm pretty sure the Discord invite link is working just fine, we get new users signing up all the time.

We don't support AAX because the SDK for it was not open source for the longest time. AVID recently made it dual licensed, but we did not investigate it yet. Also we didn't even get a lot of requests to support AAX, so it's far from a priority to do so.

**Comment by baconpaul** [comment]
The reason for a lack of JUCE macros in the root file is because the root can actually build just fine without JUCE. the package `surge-common` is used in contexts outside of juce plugins. 

AAX is indeed dual licensed but still requires a signing step which none of us can do and a testing environment none of us have; and even thought AAX is dual licensed, it seems Avid has not yet released the code, weirdly, unless you sign up for their dev program. A dev collaborating with us has asked them about this.

Happy to have more devs! If the discord link doesn't work let us know.

**Comment by shih1** [comment]
hm ok potato airbnb wifi took over a minute to load my bad on that. 

appreciate the responses i'll ask more beginner questions in the discord.
