### ISSUE TITLE
UI Knobs respond awkwardly in Bitwig / Linux

### ISSUE THREAD

**Issue by fonkle** [surge-synthesizer/surge#793]
**Describe the bug**
If I move any knob, it 'lags behind' the mouse cursor. The distance it moves is significantly less than the distance I move the mouse, causing extreme input lag. It seems the UI is not updated frequently enough.

**To Reproduce**
1. Open Surge inside Bitwig
2. Move a knob
3. Knob stays behind the mouse cursor

**Expected behavior**
Smooth operation / updates when moving any UI knob

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.10 (lowlatency) x64
 - Desktop: KDE Plasma 5.13.5
 - Driver: NVidia proprietary (X11) version 390.116
 - Host: Bitwig
 - Version: 2.5

**Comment by fonkle** [comment]
Here is a screen capture:

![Surge_knob_lag](https://user-images.githubusercontent.com/47926665/55293899-d2cc1e80-53fb-11e9-83b2-985b897873c8.gif)

**Comment by baconpaul** [comment]
Are you zoomed?

I've also noticed the linux knobs feel funky when zoomed. Wonder if vstgui is not scaling a drag distance somewhere. Do you get the same result at 100% zoom?

Thanks for the complete bug report.

**Comment by fonkle** [comment]
Yes, this behavior is present at 100% as well as 125% and 150%. It does not seem to get worse when zoomed in.

**Comment by fonkle** [comment]
It's also present in Linux Mint 19 (Cinnamon) and Ubuntu 18.10 (Gnome).

**Comment by baconpaul** [comment]
Thanks.

**Comment by baconpaul** [comment]
OK so here's what's happening. There's two things

1: Each parameter has a "move rate" which scales the mouse. This means some things are more "sensitive"

2: On top of that, the CSurgeSlider drops that move rate by 0.3 which means that even at a moderate of 1.0 3 pixels of drag are required for one pixel of move (all x zoom of course)

This makes everything feel really "laggy". @fonkle if you can build yourself, change like 367 of CSurgeSlider to say `double rate = 1.0` rather than `double rate = 0.3 * moderate` and you should see things act more like you expect.

I'm not quite sure what to do here though. @esaruoho would like your opinion. We can make it an option (like have a menu/mouse/exact drag and menu/mouse/faster drag and menu/mouse/default drag menu option). We can speed it up on linux where it feels a bit more unnatural than mac.

Thoughts welcome. The menu items are super easy to add of course.

**Comment by itsmedavep** [comment]
I totally agree with this report. Its something that I've been noticing for a while now. 

Basically, my expectation would be that if I click and drag on a slider I can freely move it to the extents of the slider track without my mouse cursor getting _too_ far away.  

BUT the devil is in that little bit of the _too_ far away detail.  After playing around with Logic's faders and then comparing to Surge I think Surge is somewhat exaggerated whereas Logic's seem about correct. 

SO Ill give your suggestion a shot and report back later. I have a feeling your proposed fix is probably good just by your description.

**Comment by baconpaul** [comment]
We can also change the 0.3 * moverate to 0.7*moverate in CSurgeSlider and just “turn it down” a bit. I agree they seem a bit underdraggy.

**Comment by fonkle** [comment]
rate = 1.0 (without _moverate_ multiplier) works great while at 100%:
![Surge_knob_100pct_10](https://user-images.githubusercontent.com/47926665/55409494-6d467200-5562-11e9-88a9-1e7f1dda62b1.gif)

but not at 150% zoom:
![Surge_knob_150pct_10](https://user-images.githubusercontent.com/47926665/55409547-83543280-5562-11e9-879f-d4a6ce4f3d40.gif)

and _0.7 * moverate_ at 100% zoom does not work well either:
![Surge_knob_100pct_07moverate](https://user-images.githubusercontent.com/47926665/55409643-ac74c300-5562-11e9-86a7-71fb14506058.gif)

**Comment by fonkle** [comment]
However with _**rate = 2.0 * moverate**_ the knob seems to follow the mouse at all zoom levels:
![Surge_knob_100pct_20moverate](https://user-images.githubusercontent.com/47926665/55410309-ee523900-5563-11e9-80e6-8ea56af13546.gif)100%
![Surge_knob_150pct_20moverate](https://user-images.githubusercontent.com/47926665/55410347-01fd9f80-5564-11e9-9e95-0c77ff49fdd3.gif)150%
![Surge_knob_200pct_20moverate](https://user-images.githubusercontent.com/47926665/55410355-05912680-5564-11e9-952b-51a884527108.gif)200%

The framerate is rather low at higher zoom levels (I even have to keep moving the mouse to trigger ui updates), and the knob stops following the mouse at both ends of the slider, yet usability would already be a lot better like this!

I have no idea where moverate is defined, so I cannot predict any implications for other platforms :).

**Comment by fonkle** [comment]
Moverates are defined in _/src/common/Parameter.cpp_ (lines 209, 227, 248 and 328) and they indeed differ per type:

ct_fmratio = 0.25
ct_pitch_semi7bp = 0.5
ct_freq_mod = 0.5
ct_lforate = 0.33

If I set these to _1.0f_ and set _double rate = 1.0 * moverate;_ in line 367 of _CSurgeSlider.cpp_, all horizontal and vertical sliders seem well at all zoom levels.

I have no idea why they are set to different moverates though...?

**Comment by baconpaul** [comment]
Yeah setting to 1.0 not 1.0*moverate is what I had meant and your change does that

I presume they are set differently because these rates set a minimum resolution change for the value. But this is code which has been there since open source epoch so I wouldn’t say we thought about it closely. And with shift drag also working I’m not sure the differences are all that accretive 

1.0 is the wrong setting though I think. 

But sounds like make this a user option with a straight 1.0 is a good idea.

**Comment by fonkle** [comment]
Usability improves a lot setting all to 1.0f.

I was just watching this video about the Windows version and I noticed that the mouse cursor disappears while sliding the sliders. On my Linux systems the mouse cursor stays visible, which is an important difference imo. If it disappears, it won't matter if it sticks to the cursor or not.

Maybe hiding (and showing) the cursor in Linux would be a better first step...?

**Comment by baconpaul** [comment]
Yeah I have no idea how to do that in vstgui!

I think these are all things where people have strong opinions so really kinda think we should make them options. That’s pretty easy code. Since you’re in the code @fonkle would you like me to write up some notes on how I would implement it (saving you a couple of hours of sortnof code orientation) and you could take a shot at it? Would welcome the contribution!

**Comment by fonkle** [comment]
Although I have no experience with the VSTGUI toolkit I would like to make the changes to the moverate-multipliers of the sliders optional using some setting (in the UI?). I would probably have to do some (surge, code and toolkit) orientation but I would like to give it a shot.

It could improve the usability in Linux in the short term and possibly lead to an even better solution by hiding the mouse cursor when sliding, like in Windows (and OSX?) in the long term.

Any notes on code structure / UI settings implementation would be most welcome for that :).

**Comment by baconpaul** [comment]
Yeah almost none of it requires VSTGUI deep knowledge (except the mouse cursor bit...)

Here's how I would do it

My design goal is to have a menu under "Zoom" and "MPE" which says "Mouse Behavior" and inside there have four options: "Classic", "Slow", "Medium", "Exact". 

"Classic" does exactly what the code does now. "Slow" does the equivalent of moverate = 0.3; Medium does moverate = 0.7 and exact does 1.0.

OK so here's I would implement this, in pseudo-code

First: To CSurgeSlider.h add two things. A new enum

```
   typedef enum MoveRateState {
      kUnInitialized=0,
      kClassic,
      kSlow, 
      kMedium,
      kExact
   } MoveRateState;
```

and a public member static. Has to be public because we will edit it from elsewhere

```
   static MoveRateState sliderMoveRateState
```

In CSurgeSlider.cpp declare it

```
static CSurgeSlider::MoveRateState CSurgeSlider::sliderMoveRateState=kUnInitialized;
```

Great. Now in getDeltaMouseScaling you can do a switch statement

```
   switch sliderMoveRateState
   {
     case statements are pretty obvious;
   }
```

So now we are third of the way there. You can test by just setting the static by hand to the other modes and checking it out.

OK so next step is how do you make the initialization of the thing based on user preferences. Luckily we added an entire UserPreferences API to Surge recently! You need to do all of this in SurgeGUIEditor which has a reference to a SurgeStorage*, but that's OK. You can get a fully worked example of this by looking at the "defaultZoom" and "mpePitchBend" implementations.

But I would put somewhere appropriate in `openOrRecreateEditor` code that looks like this

```
    if (CSurgeSlider::sliderMoveRateState==CSurgeSlider::kUnInitialized)
       CSurgeSlider::sliderMoveRateState = Surge::Storage::getUserDefaultValue(
           &(synth->storage), "sliderMoveRateState", (int)kClassic);
```

Cool. Now you are 2/3 of the way done. Now just the menu. That's easy peasy. Take a look in the same file at `SurgeGUIEditor::showSettingsMenu`. You can see where we make the Zoom menu and you can do the same thing to make a sub-menu. As to setting a default, take a look at where the defaultZoom is set. You would do this for each of the enums. We should probably also have them be checked - which is "setChecked(true)" for the one which is selected when you build the menu.

Anyway that's most of the guide. Think from that should be figurable-outable but if you get stuck just drop a question here.

And thanks for volunteering to write some code! I'll look at cursor suppression in vstgui while I'm waiting for this build and if I find anything I'll add it here.

**Comment by baconpaul** [comment]
OK on the cursor thing the answer is surprisingly simple to see, but not clear how to fix.

There's `src/common/gui/CCursorHidingControl.cpp`. The slider isa CCursorHidingControl and calls detachCursor and attachCursor in various spots.

So why isn't the cursor hidden on linux and mac I wonder?

Well here's a hint:

```
void CCursorHidingControl::doDetach(CPoint& where)
{
   _isDetatched = true;
   _detachPos = where;

#if WINDOWS
   ShowCursor(false);

   POINT p;
   if (GetCursorPos(&p))
   {
      _hideX = p.x;
      _hideY = p.y;
   }
#endif
}
```

Ha! So "We do nothing on mac or windows".

Clearly implementing that class for the other OSes would be smart. I don't even have an idea what the linux API would be but can figure out the mac one I bet.

**Comment by baconpaul** [comment]
On Mac the implementation will be `CGDisplayHideCursor` and it's friends.

If you just do Linux that's fine. I can get mac later.

**Comment by baconpaul** [comment]
So branch `bacon paul/mac-cursor-793` hides the cursor on mac like on windows. 

@esaruoho and @itsmedavep curious what you think about this. I'm not sure. Easy to merge though.

@fonkle shows you the code I had to write to get another platform working.

On also @fonkle before you start writing code, look in the "docs" directory at the Developer Guide and (if you are newer to git) the git-howto. Should have mentioned that earlier.

**Comment by itsmedavep** [comment]
Im a bit uncertain about disappearing the cursor.  When I was playing around with the sliders in Logic last night I noticed that they basically did the same thing. 

The leave behind a tiny (1px tall?!) indicator. It seemed odd to me. Like if you're gonna go that far why not just do the thing entirely. 

My expectation is really to have the cursor be visible TBH. So Ill take a look at your branch when I can.

**Comment by fonkle** [comment]
Thanks, I have read the docs and created a fork with branch _fonkle/linux-mousebehavior-793_ to change the mouse behavior for Linux. I will report asap, hopefully with a pull request :).

**Comment by baconpaul** [comment]
Yay that would be great!

Oh don’t know if you saw it but the git clang-format step in the developer doc has really helped me get my pull requests neat and tidy. And don’t know what your commit habits are but I generally commit a bunch on my branch then rebase down to one commit before a PR. 

Happy to help with any part of the process. Eager to have more devs in the surge soup!

**Comment by fonkle** [comment]
Yeah, I have clang-format-7 working with git (I think). I will squash commits if needed.

The code is already working however the current MoveRateState is not (yet?) saved with the project (Bitwig Studio). The same applies to the zoom and MPE states. I will try to fix that so it will save state.

It would be even better if the zoom and mouse behavior settings could be set system-wide, but there is no such mechanism in Surge yet as far as I can tell?

**Comment by baconpaul** [comment]
The system wide settings is exactly what the UserDefaults::save and UserDefaults::get mechanism does. Should create ~/Documents/Surge/SurgeDefaults.xml with everything in there. Are you sure you are calling set? 

Streaming onto the DAW is something I would like to do but I’m worried about patch format versions so have held off.

**Comment by baconpaul** [comment]
Actually: To set zoom system wide, zoom to 150 then do menu / zoom / set 150 as default zoom. That should write your SurgeDefaults.xml in your documents folder and next time you make a new surge set it at 150. If that doesn’t work linux it’s a bug!

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/master/src/common/UserDefaults.h Is the api

**Comment by itsmedavep** [comment]
@baconpaul I had a chance to try out your branch with the disappearing cursor.

So, I ran into a usability issue when testing things out. Here is a .gif of that.

![No_Cursor](https://user-images.githubusercontent.com/11078351/55453268-c8975500-55a0-11e9-826d-1732765bd2ae.gif)

Im not sure how obvious it is in the video but here is the deal:

I'm dragging the morph slider (wt osc) to the left
My Surge instance is close to being on the edge of my monitor
I start to drag but can't. Its like I get stuck about 50% of the way across the slider (AKA in the middle)

Now there may be a bug in there. It felt like I got stuck somehow.
It may be that since the affordance is gone I cant see that I'm hitting the edge of my monitor with the mouse cursor. 

The sliders never got stuck before trying out this branch. Soooo Im assuming that I was hitting the bounds of my monitor. All of that is to say, I now understand why Logic left a minimal affordance of a little 1px (approx) cursor for when dragging sliders. 

Inevitably, someone will position the GUI right next to the edge of a monitor. Without _any_ affordance its *very* easy to not understand what is happening if your not particularly focused on your mouse cursor. 

So, if I had to vote I would say leave the cursor as is. Fix the drag behavior (which sounds like has been done). Or at least thats my .02. 

@fonkle Welcome into the fold! But also (and much more importantly) thanks for pitching in and both reporting and fixing up some GUI issues. I really appreciate it and I know Paul does as well.

**Comment by fonkle** [comment]
Thanks, it helps me get some practical experience in os dev using Github :).

@baconpaul so I could add a menu item called _Set as default_ and write the current value to _SurgeDefaults.xml_? Or should I do that in a separate pull request?

**Comment by fonkle** [comment]
All is working fine now: _sliderMoveRateState_ is written to _~/Documents/Surge/SurgeDefaults.xml_ when the _`Set (...) as default`_ menuitem is activated. It is being used when Surge (re)opens.

However, changing the static _CSurgeSlider::sliderMoveRateState_ while playing sound crashes Surge sometimes :(. Is there a way to stop the sound engine while changing the static variable?

p.s. _Zoom->Set % as default_ works fine on Linux. The zoom level is not saved as state, as expected.

**Comment by baconpaul** [comment]
Right and I realized last night MPE won’t work on linux because the mini edit control doesn’t exist on linux (same reason the rename function doesn’t work). So yes include that all in one pull request. And saving zoom state is a separate issue which requires us to visit each plugin type. I’m still pondering how to do that cleanly and safely. Separate issue I need to open.

The fact that it crashes surge is both surprising and baffling. Did you get a stack trace for why it crashed? You are just setting it from UI action right? I suppose you could change it to a `std::atomic<int>` but that variable should only be read and written from the UI thread so don’t see what could cause that. Just to be sure: did you clean build?

If you want me to take a look at a branch before you do a PR just let me know a branch name and I can offer a quick scan. Or put in a PR and I can do a review. Have a small amount of time today but can look.

Thanks for jumping in. Very excited to have more devs here!

**Comment by baconpaul** [comment]
Oh and my thinking was you would have 5 mouse menu items and each one does the set; you basically always do a set to that as system default. It’s not like zoom where you want to mix and match in many situations. So the menu callback does the updateDefault() call (like MPE and the zoom set) at the same time it writes the static.

**Comment by baconpaul** [comment]
Yeah I agree with you @itsmedavep - lets not hide the slider but lets add menus for the sensitivities. It freaks me out also to have them gone.

**Comment by fonkle** [comment]
Hehe I figured that out too; I was going to suggest that next. I'll implement it in this PR.

About the crash:
1. I added a `this->synth->allNotesOff();` at the beginning of each callback menu. That worked yet the occasional crash persisted.
2. Then I removed all functionality from the callback menus whatsoever, so each menu item would essentially do nothing. Cleaned the project yet the occasional crash still persisted.

So I think the crashes might be unrelated to the new code. I'll do some more testing and then create a PR for review.

**Comment by baconpaul** [comment]
Yeah does sound unrelated. Bit concerning though. We haven't seen a crash in forever! If you get a stack please do open a new issue. We definitely don't want to do allNotesOff in the menu items though.

Look forward to the PR.

**Comment by fonkle** [comment]
Ok so I committed the clang-formatted changes to the _fonkle/linux-mousebehavior-793_ branch in my forked repo. Can I simply create a pull-request from that branch for review?

**Comment by baconpaul** [comment]
Yup - and I see your pr is in. You’ll see it built automatically all platforms andnsucceeded too a good first step. I’ll review next 24 hours and merge or comment!
