### ISSUE TITLE
Fix misdraw in zoom

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#907]
![](https://i.imgur.com/TlsjIuk.png)

As reported on kvr at 150% we mis fill the fx box with the svg renderer

**Comment by VincyZed** [comment]
Some more potential examples of this issue:
![Untitled](https://user-images.githubusercontent.com/50145178/62502528-ef1f0400-b7bd-11e9-95bb-4fe9406e59b5.png)

100% scale for reference:
![image](https://user-images.githubusercontent.com/50145178/62502541-0100a700-b7be-11e9-9a6a-9438b6a164b4.png)

**Comment by baconpaul** [comment]
@itsmedavep small chance this is my fault but I think you may have exported off by 1/2 px or something when you made the new high contrast SVGs? The LFO one is nothing to do with SVG that's just me not scaling line thickness properly in zoom mode.

**Comment by itsmedavep** [comment]
I just walked back through commits that were made with the usability updates for text. There are several graphics here displaying issue at 125% zoom that I haven't touched in quite a while. I had touched some in the update for text usability as well. 

So it seems a mixed bag somewhat. For example, I have not touched the scene buttons since July.

<img width="538" alt="Screen Shot 2019-08-10 at 8 13 13 PM" src="https://user-images.githubusercontent.com/11078351/62828407-54eb0180-bbab-11e9-9d34-ebdb474c47ff.png">

Im about to knock off for the night but will continue to investigate tomorrow.

**Comment by baconpaul** [comment]
OK! This might indeed be unrelated to your changes.  @VincyZed which host and OS here? Looks like FL Windows but just want to be sure

**Comment by itsmedavep** [comment]
This may actually be my fault. Let me try something out before you go spelunking!

I have a sinking suspicion that somewhere in the process of updates the stroke on the borders may have changed from being center aligned to being aligned inside. Presumably, this may have caused the issue BUT, I dont see it and cant recreate it. Im also not sure why moving the stroke alignment to be further inside would cause the issue since it seems to be somewhat the inverse.


Regardless, what I will do today is open up a branch where I will ensure all strokes on things are center aligned and then export graphics again. 

@VincyZed could I get you to test out the "fix" for me when I have a branch with the changes on?

**Comment by itsmedavep** [comment]
Alas, I was wrong about this. 

So I went back to commit : cedba0d978e03e1619a593bd53f22bec8d51c11f

The border strokes were inside aligned. The dimensions have not changed. My above "sinking suspicion" was wrong. 

I didn't capture all of the screenshots but suffice it to say I cant see anything causing this in the skin file.

<img width="326" alt="Screen Shot 2019-08-11 at 1 55 53 PM" src="https://user-images.githubusercontent.com/11078351/62838364-8f52ae00-bc40-11e9-8a58-5ec53595f475.png">
<img width="397" alt="Screen Shot 2019-08-11 at 1 54 27 PM" src="https://user-images.githubusercontent.com/11078351/62838365-8feb4480-bc40-11e9-90b9-a05082178c98.png">
<img width="678" alt="Screen Shot 2019-08-11 at 1 52 57 PM" src="https://user-images.githubusercontent.com/11078351/62838366-8feb4480-bc40-11e9-9e5b-00f559864513.png">

**Comment by baconpaul** [comment]
OK thanks; and sorry for the wild goose chase.

I wonder if I have an off-by-one error somewhere in the scalable bitmap code. Let me see if I can reproduce first by turning mac non-retina and setting 125 zoom.

Thanks @itsmedavep

**Comment by baconpaul** [comment]
So I'm leaving this open to figure out why https://github.com/surge-synthesizer/surge/commit/d55563bfe4d43cae65d75684b3a9377cdb488f7e blew up windows and needed a revert.

**Comment by baconpaul** [comment]
Alright this is "way better" with integralization but I'm going to bump the resolution of that blowup to 1.6.3 for now.

**Comment by baconpaul** [comment]
@VincyZed reports that on Windows 126% is fine and 125% is off; so I’m gonna do an if windows 125 -> 126 hack in 1.6.3

**Comment by baconpaul** [comment]
The hardcode 126 has a couple of things I don't like about it so Im going to push this issue again for now.
