### ISSUE TITLE
Touch automation not working in LogicX

### ISSUE THREAD

**Issue by eoj31** [surge-synthesizer/surge#929]
Touch automation not working in LogicX, when i move something from surge for example when i move the pitch while in touch mode its supposed to record my automation this is it not working i only see that it recognized the parameters but did not record the automation. Im using version 1.6.1.1 and been unsing surge for years this never happened to me with the older versions. can someone help ?

**Comment by baconpaul** [comment]
Hi

I moved the text of your subject into your comment. I’m travelling for 2 weeks without a laptop but can look when I’m back. If one of our other logic users (@itsmedavep or @esaruoho maybe?) could look we can see if they can reproduce.

Thanks for the report. We will look and try and fix!

One thing to try: do the “smart controls” learn parameters and record them properly for you? I had tested that in 1.6.1.1 so I am wondering if it is something about touch mode recording (which I have not tested myself and like I said, can’t test now since I’m on an ipad only until mid july)

**Comment by itsmedavep** [comment]
Im just verifying the report. I cant seem to record MIDI automation at all in my latest build. It registers the parameter changed does not record/update values. AKA creates the first point at default value. Then records no other changes.

<img width="495" alt="Screen Shot 2019-06-25 at 4 39 52 PM" src="https://user-images.githubusercontent.com/11078351/60135685-e7545480-9767-11e9-9497-ac62d591eb46.png">

**Comment by itsmedavep** [comment]
<img width="718" alt="Screen Shot 2019-06-25 at 4 40 30 PM" src="https://user-images.githubusercontent.com/11078351/60135704-f804ca80-9767-11e9-9e89-115980245781.png">
 Logic X

**Comment by baconpaul** [comment]
Gotcha; so it is basically “mouse up sends the event out the AU pipe but mouse drag does not”?

I haven’t touched the code since I got it working. I wonder if this ever worked? You don’t happen to have like 1.6.beta7 around or something like that do you just to compare.

But easy enough to debug once I’m back. I’ve tagged this one as 1.6.2 and will get to it when I’m developing again. I am pretty sure I can imagine I know what code path is missing (since I had to fix it in the VST2 and VST3 also; but I guess I just never fixed it in the AU!!)

**Comment by baconpaul** [comment]
Oh and thanks @itsmedavep!!

**Comment by itsmedavep** [comment]
I just check in beta 9. It was an issue there too. 

Ill go back to beta 7 and check now.

**Comment by baconpaul** [comment]
Yup “never working”. Cool. OK so at least we didn’t break anything recently :)

@eoj31 thanks for letting us know. I should be able to fix this in July. I’ll update this issue when I get a fix into the nightly builds.

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/750066437eaf8886eb205acdd6d99f6408f412d3/src/common/gui/SurgeGUIEditor.cpp#L2399 That’s where to start

**Comment by eoj31** [comment]
thanks guys it's a pleasure for me to inform you about this, surge has always been my favorite vst around. i tried installing V1.5.3 and this problem did not occur automation seems to work properly, except every time i try to open the wavetables Logic crashes although i managed to fix this problem in the past but i don't remember exactly what did i do i think i moved the wavetables files to a different folder. anyways let's focus on the main issue here :) .. again thank you guys for your work

**Comment by baconpaul** [comment]
OK that wasn't it but that was close to it. I have a fix together which I'm pushing through the CI process now.

It would be great if you could try a nightly to confirm it fixes the problem for you reliably. It will take about 1 hour for the new nightly to appear on the website.

**Comment by eoj31** [comment]
YES. touch automation is working with the new version Nightly builds Updated on 2019-07-11. thank you guys

**Comment by baconpaul** [comment]
Great; thanks for both reporting it and confirming the fix!

**Comment by eoj31** [comment]
my pleasure
