### ISSUE TITLE
Settings on linux saved in non-hidden directory, created without user input

### ISSUE THREAD

**Issue by elcalenx** [surge-synthesizer/surge#930]
**Describe the bug**

I know you probably won't consider this a very important issue, but it's kinda been bugging me (no pun intended)...

Surge on Linux creates the directory ~/Documents, and within it a Surge directory containing SurgeUserDefaults.xml. I personally feel this is bad form and deviates from typical Linux practise, which is to store configuration in hidden files or directories in the user's home directory. Creating new non-hidden directories and files without user input feels wrong and creates unnecessary clutter in my home directory.

(And while some desktop environments may assume the existence of a ~/Documents directory, that isn't necessarily universally true. It didn't exist on my hard drive before running Surge...)

**Please let us know your surge version**

* Surge Version: 1.6.1.1
* Plugin type (VST2, 3 or AU): VST2
* Bits (32/64): 64

**Expected behavior**

Settings stored in a hidden file or directory under the user's home directory.

**Desktop (please complete the following information):**
 
- OS: Debian Buster
 - Host: Ardour 5.12

**Comment by baconpaul** [comment]
userDataPath = std::string(homePath) + "/Documents/Surge";

That’s the line in src/common/surgestorage.vpp

Happy to review and merge a or which uses an env vst and then defaults to that if one isn’t set!

**Comment by baconpaul** [comment]
From looking around it seems a better convention is to use “~/.Surge/“ rather than “~/Documents/Surge” but our users already have all those saved patches. So we can do any one of these three things

1. Nothing. Leave it as is

2. If ~/.Surge exists use that; otherwise use ~/.Surge; have the default created be ~/Documents/Surge. When we create ~/Documents/Surge add a README.txt which says “you can rename this directory to ~/.Surge if you want and everything will work”. Or other variations on that. Update the manual

3. Use ~/.Surge and auto-migrate ~/Documents/Surge. Update the manual

The fourth thing (of make it a user preference) is not available to us alas since this is the directory that stores the user preferences

I gotta say I’m kind of partial to #1 but I don’t use linux for music. I’d be happy if you and @tank-trax agreed on a semantic other than #1 to review a Pull Request before we ship 1.6.2 (my guess is push out 1.6.2 in September or so).

**Comment by tank-trax** [comment]
Interesting. I use Mint, Debian and Ubuntu and they all have the following User folders by default:

```
Documents
Downloads
Music
Pictures
Videos
```

as far as preset locations are concerned, some Instruments/VST's use the ~/Documents folder for presets or sessions like:

```
~/Documents/discoDSP
~/Documents/DrumGizmo
~/Documents/Inear_Display
~/Documents/Loomer (factory presets)
~/Documents/Monoplugs

```
others use a hidden folder such as:

```
~/.6pm
~/.add64
~/.helm
~/.Loomer (user presets)
~/.hydrogen
~/.Rack
~/.u-he

```
=================

in reference to discussions we had on Slack, EvilDragon has mentioned u-he's folder structure

in Linux, under `~/.u-he` are sub-folders for each synth; ACE, Bazille, Diva, etc.
these folders each have all the data, presets (user and factory), VST, manuals, Tunefiles and everything else either in the folder or in sub-folders

under `~/.vst `and `~/.vst3` are links to the VST files which are in synth sub-folders under the ~/.u-he folder

here is a visual representation to hopefully help clarify

![u-he](https://user-images.githubusercontent.com/41337033/60751272-cd451e00-9f80-11e9-8ee2-90dd6d3573ff.png)


=========

I am not partial to any location although option 1 works for me, that being said the other option I would think could be interesting (perhaps not from a developer stand point) would be to use the folder structure that u-he synths use, but that could entail moving the contents of `~/.local/share/Surge` to `~/.Surge` as well

**Comment by elcalenx** [comment]
> Interesting. I use Mint, Debian and Ubuntu and they all have the following User folders by default:
> 
> ```
> Documents
> Downloads
> Music
> Pictures
> Videos
> ```
> 

Yeah, these do commonly exist on a lot of linux computers, but I don't think they're part of the core OS installation itself, but rather created by whichever desktop environment you use. Which, even though these big distros default to particular desktop environments, is not a universal factor. I should emphasize though that I'm hardly an expert on the subject, but talking only from personal experience. I personally don't use any of the big desktop environments (I use fluxbox on one computer, compiz on another), and I don't have any of those folders by default. In fact, I'm used to creating my own equivalent folders, and I'm also used to naming all my folders in lower case, which makes it even more annoying when a brand new 'Documents' folder pops up beside my existing 'documents' folder...

I guess maybe I'm just an old curmudgeon set in my old ways and at some point the desktop community decided that it's OK to create those folders without my explicit permission? I dunno, the whole concept just really bugs me, for some reason. The home folder should be for the user to set up, not for software... But that's not really a Surge problem, but rather an issue with newer desktop-oriented linux software in general...


As far as Surge goes, I'm not much of a coder, but I feel like it should be fairly trivial to check for the existence of both ~/.Surge and ~/Documents/Surge. Checking for both folders should be easier than actually migrating existing data, too, right? The big question I guess is which should be considered the default location. I think I've made my personal opinion on that topic fairly clear...

**Comment by baconpaul** [comment]
Well i will re-iterate my comment that I sure wish Linux was a desktop operating system.

Checking is super easy. And since we have an “open user folder” menu option browsing too it is easy too.

From reading both your comments (and thanks for the research!) I think the thing to do is

1. Open a separate issue for the u-he style folders and tag that 1.6.n milestone
2. Make surge do the following in exactly this order
    1. If ~/.Surge exists use that
    2. If ~/Documents/Surge exists use that
    3. If ~/Documents exists, use ~/Documents/Surge as the default
    4. Use ~/.Surge as the default

And modify the manual

That seems most likely to match the various flavors of the “documents folder” problem we are facing and is a reasonable semantic.

Comments?

**Comment by baconpaul** [comment]
Just a quick ping: Does the above proposal seem reasonable to you both?

**Comment by tank-trax** [comment]
Your proposals are always reasonable. My only concern is the extra work that it would require you to do to implement them.

The Manual may need an update to reflect these modifications.

**Comment by baconpaul** [comment]
Very considerate. This is an easy change I can get to when I next have a bit of time and my linux vm up and running. Can definitely do it for a 1.6.2 type release. Users who ran 1.6.1 will need to manually rename the directory to .Surge if they want that but otherwise should be OK.

And yeah definitely will need to update the manual as part of this change.

**Comment by baconpaul** [comment]
This change is now in master. @elcalenx if you move your ~/Documents/Surge to ~/.Surge everything should just work if you are running the latest code.

If you build yourself, you may want to wait another 30 minutes from this note since I have another linux fix inbound to some recent changes I made.
