### ISSUE TITLE
add exclude "src/linux/LinuxVST3Helpers.cpp" to vst2 section in premake.lua

### ISSUE THREAD

**Issue by mickski56** [surge-synthesizer/surge#980]
As title.
All files in src/linux are added to vst2 build in function plugincommon() in premake.lua
so add
excludes {
	      "src/linux/LinuxVST3Helpers.cpp"
        }

somewhere in the vst2 section to allow the vst2 plugin to build without error

The error was in the link stage.
Linking surge-vst2
obj/x64/Release/surge-vst2/LinuxVST3Helpers.o: In function `_GLOBAL__sub_I_LinuxVST3Helpers.cpp':
LinuxVST3Helpers.cpp:(.text.startup._GLOBAL__sub_I_LinuxVST3Helpers.cpp+0x3b): undefined reference to `Steinberg::Singleton::isTerminated()'
LinuxVST3Helpers.cpp:(.text.startup._GLOBAL__sub_I_LinuxVST3Helpers.cpp+0x44): undefined reference to `Steinberg::Singleton::lockRegister()'
LinuxVST3Helpers.cpp:(.text.startup._GLOBAL__sub_I_LinuxVST3Helpers.cpp+0x6b): undefined reference to `Steinberg::UpdateHandler::UpdateHandler()'
LinuxVST3Helpers.cpp:(.text.startup._GLOBAL__sub_I_LinuxVST3Helpers.cpp+0x7e): undefined reference to `Steinberg::Singleton::registerInstance(Steinberg::FObject**)'
LinuxVST3Helpers.cpp:(.text.startup._GLOBAL__sub_I_LinuxVST3Helpers.cpp+0x56): undefined reference to `Steinberg::Singleton::unlockRegister()'
collect2: error: ld returned 1 exit status

**Comment by baconpaul** [comment]
Oh thanks!

**Comment by baconpaul** [comment]
I chose a slightly different fix - use a `#if TARGET_VST3` around the whole file - since that is symmetric with how linux-aeffguieditor conditionally compiles for VST2. PR in. This ticket will close when it is merged to master.

Thank you very much for the clear and quick report! This had only been merged for about 4 hours when you found it! Appreciate it.
